var eikenpre2plus_batch1 = [
  {
    "title": "1. Yuki's Scholarship Application",
    "content": "✏️ Yuki had been working on her scholarship essays since last month.\nユキは先月から奨学金エッセイに取り組んできました。\n📚 She knew that the competition would be very tough this year.\n今年の競争は激しいと彼女は分かっていました。\n🙏 Her teacher encouraged her to submit the application before the deadline.\n締め切り前に申請書を出すよう先生は励ましました。\n😰 Yuki felt nervous because many students wanted this award.\n多くの学生がこの賞を目指していて、ユキは緊張しました。\n💪 She had practiced writing essays for two hours every evening.\n彼女は毎晩2時間、エッセイを書く練習をしていました。\n📝 Her essays were reviewed by her English teacher last week.\ エッセイは先週、英語の先生に見直してもらいました。\n📧 The letter of recommendation had been written by her principal.\n推薦状は校長が書いてくれました。\n✅ All documents had been submitted before the deadline finally.\nすべての書類が締め切り前に提出されました。\n🎉 Yuki received an email that she had been selected for the award.\nユキは自分が選ばれたというメールを受け取りました。\n😊 She felt proud that her hard work had been recognized.\n努力が認められて、彼女は誇らしく思いました。\n\n✏️ Have you ever applied for a scholarship?\n奨学金を申請したことはありますか？\n📚 Do you enjoy writing essays for your classes?\nクラスのためにエッセイを書くのは好きですか？\n🙏 Has a teacher encouraged you to do something difficult?\n先生に難しいことをするよう励まされたことはありますか？\n😰 Do you feel nervous before important competitions or tests?\n重要な試験の前に緊張しますか？\n💪 Do you practice something every day to improve?\n毎日何かを練習して上達していますか？\n📝 Do you write in English regularly?\n定期的に英語で書きますか？\n📧 Have you ever received a letter of recommendation?\n推薦状をもらったことはありますか？\n✅ Are you good at meeting deadlines?\n締め切りに間に合うのは得意ですか？\n🎉 How do you feel when you receive good news?\n良い知らせを受け取るとどう感じますか？\n😊 What makes you feel proud of yourself?\n自分の何に誇りを持っていますか？"
  },
  {
    "title": "2. Ken's Volunteer Work",
    "content": "🌳 Ken had been volunteering at the local animal shelter since spring.\nケンは春から地元の動物保護施設でボランティアをしていました。\n🐕 He had been feeding the dogs every weekend for six months.\n6ヶ月間、毎週末犬に餌をあげていました。\n🧹 The shelter manager thanked him for his hard work regularly.\nシェルターマネージャーは定期的に彼に感謝していました。\n😊 Ken loved helping animals that needed homes and care.\n家と世話が必要な動物を助けるのが大好きでした。\n👀 He noticed that some animals had been waiting for adoption.\nいくつかの動物が里親待ちであることに気がつきました。\n💡 Ken decided to create posters to help find them homes.\n家を見つけるのを手伝うポスターを作ることにしました。\n🖌️ The posters were designed by him using bright colorful pictures.\n明るくカラフルな写真を使ってポスターをデザインしました。\n📋 He posted the posters around the neighborhood last Saturday.\n先週の土曜日、近所にポスターを貼りました。\n📞 A kind person called because they wanted to adopt a dog.\n犬を飼いたいという親切な人が電話をかけてきました。\n🎉 Ken felt happy when the dog found a loving home.\n犬が愛ある家を見つけた時、ケンは嬉しかったです。\n\n🌳 Have you ever done volunteer work?\nボランティア活動をしたことはありますか？\n🐕 Do you like animals?\n動物は好きですか？\n🧹 Have you ever been thanked for helping someone?\n誰かを手伝って感謝されたことはありますか？\n😊 Do you enjoy helping others in need?\n困っている人を助けるのは好きですか？\n👀 Have you noticed something that needed improvement?\n改善が必要なことに気づいたことはありますか？\n💡 Do you have any good ideas for helping your community?\nコミュニティを助ける良いアイデアはありますか？\n🖌️ Are you good at designing or making posters?\nポスターをデザインしたり作ったりするのは得意ですか？\n📋 Do you share information with neighbors?\n近所の人と情報を共有しますか？\n📞 Do you talk on the phone often?\nよく電話をしますか？\n🎉 How do you feel when you help someone achieve something?\n誰かが何かを達成するのを手伝った時どう感じますか？"
  },
  {
    "title": "3. Maya's Music Competition",
    "content": "🎹 Maya had been practicing the piano for three hours daily since January.\nマヤは1月から毎日3時間ピアノを練習していました。\n🎼 Her teacher had told her that she should enter a competition.\n先生はコンテストに出場するべきだと言いました。\n😰 She felt nervous because she had never performed in public before.\n人前で演奏したことがないので緊張しました。\n📅 The competition had been announced by the music school last month.\n音楽学校は先月コンテストを発表しました。\n👨‍🏫 Her parents encouraged her to practice even more before the event.\n両親はイベントの前にもっと練習するよう励ましました。\n🎵 Maya chose a beautiful piece that she had been learning for months.\nマヤは数ヶ月間習っている美しい曲を選びました。\n👗 She had bought a nice dress to wear at the performance.\n演奏で着るための素敵なドレスを買っていました。\n🎤 On the day, Maya walked onto the stage and took a deep breath.\n当日、マヤはステージに上がって深呼吸をしました。\n✨ She played beautifully and impressed all the judges and audience.\n美しく演奏して、審査員と聴衆を感動させました。\n🏆 Maya was announced as the winner of the junior category.\nマヤはジュニア部門の優勝者として発表されました。\n\n🎹 Do you play a musical instrument?\n何か楽器を演奏しますか？\n🎼 Do you enjoy listening to music?\n音楽を聴くのは好きですか？\n😰 Do you get nervous before performing or speaking in public?\n公の場で演奏やスピーチをする前に緊張しますか？\n📅 Do you prepare for important events or competitions?\n重要なイベントやコンテストの準備をしますか？\n👨‍🏫 Do your parents encourage you in your activities?\n両親はあなたの活動を応援していますか？\n🎵 What kind of music do you like listening to?\nどんな音楽を聴くのが好きですか？\n👗 Do you like dressing up for special occasions?\n特別な機会にきれいに着飾りますか？\n🎤 Have you ever given a performance or speech on stage?\nステージで演奏やスピーチをしたことはありますか？\n🏆 Have you ever won a competition or prize?\nコンテストや賞に勝ったことはありますか？\n✨ How do you feel when you do something very well?\n何かとても良くできた時どう感じますか？"
  },
  {
    "title": "4. Satoshi's Science Project",
    "content": "🔬 Satoshi had been interested in renewable energy since he watched a documentary.\nサトシはドキュメンタリーを見てから、再生可能エネルギーに興味を持っていました。\n💡 He decided to make a science project about solar power for school.\n学校で太陽光発電についての科学プロジェクトを作ることにしました。\n📚 He had been reading books about energy sources at the library.\n図書館でエネルギー源についての本を読んでいました。\n🛠️ The materials for his project had been purchased by his father.\nプロジェクトの材料は父が買ってくれました。\n😰 Satoshi was worried because he had never built anything by himself before.\n今まで一人で何も作ったことがなかったので心配でした。\n👨‍🏫 His science teacher helped him understand how the solar panel worked.\n科学の先生が太陽光パネルの仕組みを理解するのを助けてくれました。\n⚡ The project had been completed after two weeks of hard work.\n2週間の努力の後、プロジェクトが完成しました。\n🎨 He had painted the model solar panel and labeled it clearly.\n模型の太陽光パネルにペンキを塗り、ラベルを貼りました。\n📊 The science fair had been organized by the school last week.\ 先週、学校で科学フェアが開催されました。\n🏅 Satoshi was awarded second prize for his interesting and informative project.\n興味深く情報豊富なプロジェクトでサトシは2位になりました。\n😊 He felt proud that his hard work had been recognized.\n努力が認められて、彼は誇らしく思いました。\n\n🔬 Do you enjoy science experiments?\n科学実験は好きですか？\n💡 Do you like learning about the environment or energy?\n環境やエネルギーについて学ぶのは好きですか？\n📚 Do you often go to the library to study?\n勉強のためによく図書館に行きますか？\n🛠️ Do you like building things with your hands?\n自分の手で物を作るのは好きですか？\n😰 Have you ever worried about doing something difficult for the first time?\n初めて難しいことをする時、心配したことはありますか？\n👨‍🏫 Do your teachers help you when you need assistance?\n助けが必要な時、先生たちは手伝ってくれますか？\n🎨 Do you like art or creative projects?\nアートや創造的なプロジェクトは好きですか？\n📊 Have you ever displayed your work at a school fair or exhibition?\n学校のフェアや展示会で作品を展示したことはありますか？\n😊 How do you feel when your hard work is appreciated?\n努力が認められた時どう感じますか？"
  },
  {
    "title": "5. Emi's Study Abroad Dream",
    "content": "✈️ Emi had been dreaming about studying abroad since she was young.\nエミは小さい頃から留学を夢見ていました。\n🇺🇸 She wanted to improve her English in an English-speaking country.\n英語圏の国で英語を上達させたかったです。\n📚 Emi had been studying English very hard for three years.\nエミは3年間、一生懸命英語を勉強してきました。\n💰 Her parents had saved money to support her dream to study abroad.\n両親は留学の夢を支援するためにお金を貯めていました。\n📝 The application form had been completed by Emi last month.\n申請書は先月エミによって書き上げられました。\n📧 She received an acceptance letter from a university in Canada that week.\nその週、カナダの大学から合格通知が届きました。\n😊 Emi was excited because she had never traveled abroad before.\n海外旅行が初めてだったので、エミは興奮しました。\n🏠 A host family had been chosen for her by the program coordinator.\nプログラムコーディネーターがホストファミリーを選んでくれました。\n🎒 She had packed her bags with clothes and personal items carefully.\n服と個人の荷物を注意深く荷物を詰めました。\n👋 Her friends said goodbye to her at the airport and wished her luck.\n空港で友達がさよならを言って、幸運を祈ってくれました。\n🌟 Emi felt ready for this new adventure in her life.\n新しい冒険への準備ができていると感じました。\n\n✈️ Would you like to study in another country?\n他の国で勉強したいですか？\n🇺🇸 Do you want to improve your English language skills?\n英語力を上げたいですか？\n💰 Have your parents supported your dreams or goals?\n両親はあなたの夢や目標を支援していますか？\n📝 Have you ever filled out a long application form?\n長い申請書を書き込んだことはありますか？\n📧 How do you feel when you receive good news?\n良い知らせを受け取るとどう感じますか？\n😊 Do you like traveling to new places?\n新しい場所に旅行するのは好きですか？\n🏠 Have you ever stayed with a host family or friend?\nホストファミリーや友達と泊まったことはありますか？\n🎒 Do you like packing for a trip?\n旅行のために荷造りするのは好きですか？\n👋 How do you say goodbye to friends when you leave?\n去る時、友達にどうさよならを言いますか？"
  },
  {
    "title": "6. Ryu's Sports Challenge",
    "content": "⚽ Ryu had been practicing soccer with his team every day since last season.\n昨シーズンから、リョウは毎日チームとサッカーの練習をしていました。\n🏆 His team had won all their games and reached the regional finals.\nチームはすべての試合に勝って、地域決勝に進みました。\n😰 Ryu felt nervous because this match was very important for them.\nこの試合はとても重要だったので、リョウは緊張しました。\n👨‍🏫 The coach told them that they should play their very best.\nコーチは全力でプレイするように言いました。\n🥅 He had been chosen as the team captain because he was a good leader.\n良いリーダーだったので、リョウはチームのキャプテンに選ばれました。\n💪 His teammates respected him and followed his strategies during the game.\nチームメイトは彼を尊敬し、試合中に彼の戦略に従いました。\n⚡ Ryu ran quickly across the field and controlled the ball well.\nリョウは素早くフィールドを走り、ボールをよくコントロールしました。\n🎯 He scored an amazing goal early in the second half of the game.\n後半の早い段階で素晴らしいゴールを決めました。\n🎉 The crowd cheered loudly when they saw him score the goal.\nゴールを見た時、観客は大きな声で歓声を上げました。\n🏅 Ryu's team won the championship trophy after an exciting match.\   リョウのチームはエキサイティングな試合の後、優勝トロフィーを獲得しました。\n😊 He felt proud that his team had worked together to achieve victory.\nチームが一丸となって勝利を得たことに誇りを感じました。\n\n⚽ Do you play any team sports?\nチームスポーツをしていますか？\n🏆 Have you ever won a championship or tournament?\n優勝チャンピオンシップやトーナメントに勝ったことはありますか？\n😰 Do you feel nervous before important games or competitions?\n重要な試合や競技会の前に緊張しますか？\n👨‍🏫 Has a coach or teacher ever encouraged you to do your best?\nコーチや先生にベストを尽くすよう励まされたことはありますか？\n🥅 Are you a good leader when you work in a group?\nグループで働く時、良いリーダーですか？\n👥 Do your teammates or classmates respect your ideas?\nチームメイトやクラスメイトはあなたのアイデアを尊重してくれますか？\n🎉 Do you like cheering for your favorite team or player?\nお気に入りのチームや選手を応援するのは好きですか？\n😊 How does it feel when you achieve something as a team?\nチームで何かを達成した時どう感じますか？\n🏅 What is your favorite sport to play or watch?\nプレイしたり観たりする一番好きなスポーツは何ですか？"
  },
  {
    "title": "7. Aiko's Art Exhibition",
    "content": "🎨 Aiko had been drawing beautiful pictures since she was a small child.\nアイ子は小さい頃から、美しい絵を描いてきました。\n🖼️ Her art teacher noticed that she had a special talent for painting.\n美術の先生は、彼女に絵画の才能があることに気づきました。\n🎨 The teacher encouraged her to enter a local youth art exhibition.\n先生は地元の若者アート展覧会に出展するよう励ましました。\n💡 Aiko decided to paint a picture of the ocean and sky.\nアイ子は海と空の絵を描くことにしました。\n🌊 She worked on her painting for two weeks in the art room.\n2週間、美術室で絵に取り組みました。\n😰 Aiko worried that her painting might not be good enough.\n絵が十分良くないかもしれないと心配しました。\n👨‍🏫 Her teacher helped her improve the colors and details.\n先生は色とディテールを改善するのを助けてくれました。\n📋 The application had been submitted before the exhibition deadline.\  展覧会の締め切り前に申請書を提出しました。\n🎭 The exhibition was held last weekend at the city museum.\ 先週末、市美術館で展覧会が開催されました。\n👀 Many people visited the exhibition and admired all the artworks.\n多くの人が展覧会を訪れて、すべての作品を称賛しました。\n🎉 Aiko was surprised when she won first prize for her painting.\n絵で1位になった時、アイ子は驚きました。\n😊 She felt happy that her artistic skills had been recognized.\n芸術的な才能が認められて、幸せでした。\n\n🎨 Do you like drawing or painting pictures?\n絵を描いたり絵を描くのは好きですか？\n🖼️ Have you ever displayed your artwork to others?\n自分のアート作品を他の人に見せたことはありますか？\n💡 Do you have a special talent or skill?\n特別な才能やスキルはありますか？\n😰 Have you ever worried about whether your work was good enough?\n自分の仕事や作品が十分良くないか心配したことはありますか？\n👨‍🏫 Do you have a teacher who encourages your talents?\n才能を励ましてくれる先生はいますか？\n📋 Have you ever entered a competition or contest?\nコンテストや競技会に参加したことはありますか？\n👀 Do you like visiting art museums or galleries?\n美術館やギャラリーを訪れるのは好きですか？\n😊 How do you feel when someone recognizes your abilities?\n誰かがあなたの能力を認めてくれた時どう感じますか？
\ntalent?\n特別な才能を発揮したことはありますか？"
  },
  {
    "title": "8. The School Recycling Project",
    "content": "♻️ The school recycling project had been started by the student council last month.\   リサイクルプロジェクトは先月、生徒会によって始まりました。\n🤝 All students had been asked to bring recyclable materials to school.\  すべての生徒にリサイクル可能な物資を学校に持ってくるよう依頼されました。\n📦 Paper, plastic bottles, and cans had been collected in special bins.\   紙、プラスチックボトル、缶が特別なゴミ箱に集められました。\n👨‍🏫 The homeroom teachers had encouraged students to participate actively.\  担任の先生は生徒に積極的に参加するよう励ましました。\n😊 The students were enthusiastic about helping the environment and community.\  環境とコミュニティを助けることに生徒たちは熱心でした。\n📊 After four weeks, the amount of recycled materials had been counted by the committee.\  4週間後、リサイクル資材の量が委員会によって集計されました。\n🌱 The money earned from recycling was used to plant trees in the school garden.\  リサイクルで稼いだお金は学校の庭に植樹するために使われました。\n🌿 The new trees were planted by students and teachers together last Friday.\  先週金曜日、新しい木は生徒と先生によって一緒に植えられました。\n☀️ The sunlight had been shining brightly when they planted the young trees.\  若木を植えた時、太陽が明るく輝いていました。\n💧 The students watered the trees and promised to care for them daily.\  生徒たちは木に水をやり、毎日世話をすると約束しました。\n🌟 Everyone felt proud that they had created a greener school environment.\  より緑豊かな学校環境を作ったことにみんな誇りを感じました。\n\n♻️ Do you recycle at home or at school?\n家や学校でリサイクルをしますか？\n🤝 Do you participate in community or school projects?\nコミュニティや学校のプロジェクトに参加しますか？\n📦 Do you sort your trash into different bins?\nゴミを別々のゴミ箱に分けますか？\n😊 Do you want to help protect the environment?\n環境を保護するために役立ちたいですか？\n📊 Are you good at counting or organizing things?\n数えたり整理したりするのは得意ですか？\n🌱 Have you ever planted a tree or flowers?\n木や花を植えたことはありますか？\n🌿 Do you enjoy working in a garden or outdoor space?\n庭や屋外スペースで働くのは好きですか？\n💧 Do you like watering plants or taking care of them?\n植物に水をやったり世話をしたりするのは好きですか？\n😊 How do you feel when you contribute to something good for others?\n他人のために良いことに貢献した時どう感じますか？"
  },
  {
    "title": "9. The New Library Books",
    "content": "📚 The school library had purchased many new books with the budget money.\  学校図書館は予算で新しい本をたくさん購入しました。\n📋 The English department had been asked to recommend good books for students.\  英語科は学生に良い本を推薦するよう依頼されました。\n📖 The librarian had been organizing the new books on the shelves carefully.\  司書は新しい本を棚に注意深く整理していました。\n😰 There had been concern that students might not read enough books this year.\  今年、学生は十分な本を読まないかもしれないという懸念がありました。\n👨‍🏫 The teachers encouraged students to borrow books from the library regularly.\  先生は定期的に図書館から本を借りるよう励ましました。\n📚 Students were excited to see the new collection of storybooks and novels.\  物語や小説の新しいコレクションを見て学生は興奮しました。\n👀 Many students had been browsing the new books during lunch break.\  昼休みに多くの学生が新しい本を見ていました。\n📝 Emma decided to borrow a mystery novel that she had been wanting to read.\  エマは読みたがっていたミステリー小説を借りることにしました。\n😊 She was happy that the library had books that interested her very much.\  非常に興味のある本が図書館にあることにエマは幸せでした。\n📖 Emma spent that evening reading the interesting mystery story at home.\  エマはその夜、家で面白いミステリー物語を読んで過ごしました。\n🌟 She promised to return the book to the library within two weeks.\  2週間以内に本を図書館に返すと約束しました。\n\n📚 Do you like reading books in your free time?\n自由な時間に本を読むのは好きですか？\n📖 Do you visit your school library often?\n学校の図書館によく行きますか？\n😊 Do you have books that you enjoy reading again and again?\n何度も読みたい好きな本はありますか？\n👨‍🏫 Who encouraged you to read when you were young?\n若い時、誰が読むことを励ましてくれましたか？\n📝 Have you ever borrowed a book from a library?\n図書館から本を借りたことはありますか？\n👀 What kind of books or stories do you like reading most?\nどんな種類の本や物語が一番好きですか？\n💡 Have you ever found a book that really interested you?\n本当に興味のある本を見つけたことはありますか？\n🌟 Do you usually return borrowed things on time?\n借りた物を時間通りに返しますか？"
  },
  {
    "title": "10. Haruka's Cooking Challenge",
    "content": "🍳 Haruka had wanted to learn cooking since she started high school last year.\  ハルカは去年高校に入学してから料理を習いたいと思っていました。\n📚 She had been watching cooking shows on television every weekend for inspiration.\  週末にテレビで料理番組を見てインスピレーションを得ていました。\n🧑‍🍳 Her mother taught her how to cook basic dishes like curry and soup.\  母はカレーやスープのような基本的な料理の作り方を教えてくれました。\n😰 Haruka worried that she might burn the food or make mistakes.\  料理を焦がしたり間違えたりするかもしれないと心配しました。\n💪 She decided to cook a special dinner for her family's celebration.\  家族の祝い事のために特別な夕食を料理することにしました。\n🍝 Haruka made pasta with tomato sauce and fresh vegetables carefully.\  ハルカはトマトソースと新鮮な野菜のパスタを注意深く作りました。\n👨‍👩‍👧 Her family had been invited to the dinner and they arrived at seven o'clock.\  家族は夕食に招待され、7時に到着しました。\n😊 Everyone was surprised that the food tasted delicious and looked beautiful.\  料理が美味しくて見た目も美しいことに皆は驚きました。\n🌟 Her parents praised her for her hard work and wonderful cooking skills.\   両親は彼女の努力と素晴らしい料理スキルを褒めました。\n😊 Haruka felt proud that she had successfully cooked a meal for her family.\   家族のために食事を料理できたことに誇りを感じました。\n🍳 She decided that she would practice cooking more often in the future.\  今後もっと頻繁に料理の練習をしようと決めました。\n\n🍳 Do you like cooking or helping in the kitchen?\n料理をしたり台所を手伝ったりするのは好きですか？\n📚 Have you learned cooking from anyone?\n誰かから料理を学んだことはありますか？\n😰 Have you ever been worried about making mistakes in cooking?\n料理で間違えることを心配したことはありますか？\n💪 Do you like doing nice things for your family?\n家族のために良いことをするのは好きですか？\n😊 Do you try new recipes or foods when you can?\nできる時、新しいレシピや食べ物を試しますか？\n👨‍👩‍👧 Do you enjoy cooking dinner for your family?\n家族のために夕食を料理するのは好きですか？
\n🍳 Have you ever been praised by your family?\n家族に褒められたことはありますか？"
  },
  {
    "title": "11. The Science Club Experiment",
    "content": "🔬 The science club had been planning an exciting experiment for the school fair.\   科学クラブは学校祭りのためにエキサイティングな実験を計画していました。\n💡 They decided to show how volcanoes erupt to the students and teachers.\   火山が噴火する様子を生徒や先生に見せることにしました。\n🧪 The materials had been collected by club members during the previous week.\   材料は前週にクラブメンバーによって集められました。\n😰 Some members were nervous because they had never done this experiment before.\   いくつかのメンバーは、この実験をしたことがないので緊張していました。\n👨‍🏫 The science teacher had been supervising their preparations to ensure safety.\   安全を確保するために、科学の先生が準備を監督していました。\n⚗️ The experiment was performed in the school courtyard where everyone could see.\   実験は誰も見れる学校の中庭で行われました。\n🌋 The model volcano had erupted suddenly with bright red lava flowing down.\   模型の火山が突然噴火し、鮮やかな赤い溶岩が流れました。\n😲 The students and parents were amazed when they saw the spectacular eruption.\   壮観な噴火を見た時、生徒と親は驚きました。\n📚 The club members explained the science behind the volcanic eruption clearly.\   クラブメンバーは火山噴火の背後にある科学を明確に説明しました。\n👏 The audience applauded loudly for their impressive and educational demonstration.\   聴衆は印象的で教育的な実演に大きな拍手を送りました。\n😊 The science club felt proud that they had taught everyone something new.\   新しいことをみんなに教えられたことに科学クラブは誇りを感じました。\n\n🔬 Do you like science or have you joined a science club?\n科学は好きですか、それとも科学クラブに所属していますか？\n💡 Do you enjoy learning interesting and new things?\n興味深い新しいことを学ぶのは好きですか？\n😰 Have you ever been nervous before doing something new?\n新しいことをする前に緊張したことはありますか？\n👨‍🏫 Do your teachers supervise your work or activities at school?\n先生は学校でのあなたの仕事や活動を監督していますか？\n😲 Have you ever seen something amazing or spectacular?\n何か素晴らしいものや壮観なものを見たことはありますか？\n👏 Do you like observing or watching interesting demonstrations or shows?\n興味深い実演やショーを見るのは好きですか？\n😊 How do you feel when you explain something to others?\n他人に何かを説明する時どう感じますか？"
  },
  {
    "title": "12. The Sports Day Challenge",
    "content": "🏃‍♂️ The school sports day had been organized by the physical education department.\   運動会は体育科によって組織されました。\n📅 All students had been practicing for their events since last month.\   生徒全員が前月から自分の種目の練習をしてきました。\n😰 Mai was nervous because she had been chosen for the relay race team.\   リレーチームに選ばれたので、マイは緊張していました。\n💪 She had been training very hard to run as fast as possible.\   早く走れるように一生懸命トレーニングしていました。\n👨‍🏫 Her coach encouraged her by saying she could win the race for her class.\  コーチはクラスのためにレースに勝てると励ましてくれました。\n🎽️ Mai wore her sports uniform and running shoes that had been bought recently.\   マイは最近買ったスポーツユニフォームとランニングシューズを履きました。\n🏁 The starting gun was fired and all the runners began their race quickly.\   発砲銃が鳴り、すべてのランナーが素早くレースを開始しました。\n💨 Mai ran faster than she had ever run before in the final stretch.\   マイは最後の直線で今までより速く走りました。\n🥇 She crossed the finish line and realized she had won first place!\n ゴールラインを越えて、自分が1位になったことに気づきました！\n🎉 Her classmates and friends cheered loudly when they saw her victory.\   勝利を見た時、クラスメイトや友達は大きな声で歓声を上げました。\n😊 Mai felt proud that her training and effort had led to her success.\   トレーニングと努力が成功につながったことに誇りを感じました。\n🌟 She thanked her coach and team for their support and encouragement.\  コーチとチームの支援と励ましに感謝しました。\n\n🏃‍♂️ Do you enjoy sports or physical activities at school?\n学校でのスポーツや身体活動は好きですか？\n😊 Have you ever participated in a relay race or running race?\nリレーやレースに参加したことはありますか？\n😰 Do you get nervous before important competitions or events?\n重要な競技会やイベントの前に緊張しますか？\n💪 Do you train or practice regularly to improve your skills?\nスキルを向上させるために定期的にトレーニングや練習をしますか？"
};
module.exports = eikenpre2plus_batch1;
