// Eiken Pre-2 Plus - 48 Stories (Natural TPRS Style)
// CEFR: A2 (higher score range: 1829-2500)
// Target: 8-10 words, natural storytelling
// Grammar: Past perfect, reported speech, 2nd conditionals, perfect passive

var eikenpre2plus = [
{ "title": "1. The Missed Bus", "content": "🛻 Yuki had woken up late that morning. 由紀はその朝、起きたのが遅かったです。 🏃 She ran to the bus stop quickly. 彼女は急いでバス停に走りました。 😱 But the bus had already left without her. しかしバスはもう彼女なしで出発していました。 📱 Her friend texted that class had already started. 友達は授業がもう始まったとテキストしました。 😰 Yuki had never missed the bus before. 由紀は以前バスに乗り遅れたことがありませんでした。 🚶 She decided to walk to school instead. 彼女は代わりに学校まで歩くことにしました。 ⏰ The walk had taken about thirty minutes. 歩くのに約30分かかりました。 🏫 By the time she arrived, she was exhausted. 到着したとき、彼女は疲れ果てていました。 📝 The teacher said that she could make up the test. 先生はテストを受け直せると言いました。 🙏 Yuki had learned her lesson about waking up early. 由紀は早起きの教訓を学びました。

🚌 Have you ever missed a bus or train? ⏰ What had happened on your busiest morning? 😓 How had you felt when you were late? 📱 Who had you texted about being late? 🚶 How long had you walked to school? 🏫 Had your teacher ever given you another chance? ⏱️ How long does it take you to get to school? 📝 What had you learned from being late? 🎯 Do you usually wake up on time? 🙏 Had this experience changed your habits?" },
{ "title": "2. The Found Wallet", "content": "👛 Ken found a wallet on the ground. ケンは地面に財布を見つけました。 🤔 He told his mother what he had found. 彼はお母さんに見つけたものを伝えました。 💭 She asked him what he would do. 彼女は彼にどうするつもりかと尋ねました。 📝 Ken said that he would try to find the owner. ケンは持ち主を探してみると言いました。 🔍 They had looked inside for a name or ID. 彼らは中から名前やIDを探しました。 📞 His mother suggested that they call the police. 彼のお母さんは警察に電話することを提案しました。 🚔 A police officer had thanked them for their honesty. 警察官は彼らの正直さに感謝しました。 👧 The wallet had belonged to a girl named Yui. 財布はユイという名前の女の子のものでした。 💌 Yui's mother had written them a thank-you note. ユイのお母さんから感謝の手紙が届きました。 😊 Ken had felt proud of doing the right thing. ケンは正しいことをしたと誇りに思いました。

👛 Have you ever found something on the ground? 🤔 What would you do if you found a wallet? 📞 Had your parents ever suggested calling someone? 🔍 Where do you usually look for lost things? 🙏 Have you ever returned something to someone? 👮 Had a police officer ever helped you? 💌 Had you ever received a thank-you note? 😊 How did you feel when you helped someone? 👥 Do you know your neighbors' names? 💭 What would you do if you lost something?" },
{ "title": "3. The School Festival Planning", "content": "🎪 The class had decided to hold a festival. クラスはお祭りを開くことを決めました。 💬 Everyone suggested different ideas for activities. みんなが活動のための違うアイデアを提案しました。 🎨 Mio said that she could draw the posters. ミオはポスターを描けると言いました。 🍰 Taka suggested that they sell homemade sweets. タカは手作りのお菓子を売ることを提案しました。 🎭 If they practiced more, the play would be better. もっと練習すれば、劇はもっと良くなるだろう。 ⏰ They had been preparing for two weeks already. 彼らはもう2週間準備し続けていました。 📋 The teacher asked if they needed more time. 先生はもっと時間が必要かと尋ねました。 😓 Mio had felt nervous about performing on stage. ミオはステージで演奏することに緊張していました。 🎉 If the weather was nice, they could hold it outside. 天気がよければ外で開催できる。 🌟 Everyone hoped that the festival would be a success. みんなはお祭りが成功することを願いました。

🎪 Has your class ever planned a festival? 💬 What activities would you suggest for a festival? 🎨 Have you ever drawn posters for school? 🍰 What food would you sell at a festival? 🎭 If you could perform anything, what would you do? ⏰ How long had your class been preparing? 📋 What would you do if you needed more help? 😓 Had you ever been nervous about performing? 🌤️ If the weather was perfect, where would you hold it? 🎉 What made a school event successful?" },
{ "title": "4. The Wrong Lunch Box", "content": "🍱 Riku had opened his lunch box at noon. リクはお昼に弁当箱を開けました。 😲 But the food inside was not his! しかし中の食べ物は彼のものではありませんでした！ 🤔 He had accidentally taken his sister's lunch. 彼は間違えて妹の弁当を持ってきていました。 🍱 His sister liked vegetables, but Riku hated them. 妹は野菜が好きでしたが、リクは嫌いでした。 😂 His friends laughed when they saw the salad. 友達はサラダを見て笑いました。 📱 Riku texted his sister that he had made a mistake. リクは妹に間違えたとテキストしました。 🏃 His sister said that she had already eaten his lunch. 妹は彼の弁当をもう食べてしまったと言いました。 😰 Riku had to eat the vegetables he disliked. リクは嫌いな野菜を食べなければなりませんでした。 😋 Surprisingly, the vegetables had tasted pretty good. 驚いたことに、野菜はとても美味しかったでした。 🙏 From that day, Riku had started eating more vegetables. その日以来、リクは野菜をもっと食べ始めました。

🍱 Have you ever brought the wrong thing to school? 😲 What would you do if you got someone else's lunch? 🤔 Have you ever mixed up something with a sibling? 😂 Do your friends ever laugh at your mistakes? 📱 What would you text if you made a mistake? 🏃 What had your family member eaten by mistake? 😋 Have you ever tried food you thought you hated? 🥕 What vegetables do you like or dislike? 🙏 Had an accident ever changed your habits? 🍱 What is your favorite lunch to bring?" },
{ "title": "5. The Late Night Homework", "content": "📚 Hana had forgotten about the big report. ハナは大きなレポートのことを忘れていました。 😱 It was due tomorrow morning at eight. 提出は明日の朝8時でした。 🌙 She had stayed up very late working on it. 彼女はそれを完成させるために夜遅くまで起きていました。 ☕ Her mother had brought her hot chocolate. お母さんは彼女にホットチョコレートを持ってきてくれました。 ✍️ By midnight, she had written five pages. 真夜中までに、彼女は5ページ書きました。 😴 She had been feeling sleepy since eleven. 彼女は11時から眠くなっていました。 📱 Her friend texted that he had finished already. 友達はもう終わったとテキストしました。 😓 Hana wished that she had started earlier. ハナはもっと早く始めればよかったと思いました。 ⏰ If she had planned better, she would have slept more. もっと計画していれば、もっと寝られたのに。 ✅ She had finally finished at two in the morning. 彼女はついに午前2時に終わりました。

📚 Have you ever forgotten about homework? 😱 What would you do if homework was due tomorrow? 🌙 How late have you stayed up for homework? ☕ What do you drink when you study late? ✍️ How many pages had you written for a report? 😴 What had you been doing when you felt sleepy? 📱 What would you say if a friend finished early? 😓 Have you ever wished you started earlier? ⏰ If you could plan better, what would you change? 🌟 What time had you finished your hardest project?" },
{ "title": "6. The Surprise Gift", "content": "🎁 Saki's birthday had been last month. サキの誕生日は先月でした。 🤫 Her family had planned a surprise for her. 彼女の家族はサプライズを計画していました。 🛒 They had bought a bicycle she had wanted. 彼女が欲しがっていた自転車を買っていました。 😮 If Saki had known, she would have been excited. サキが知っていたら、興奮していただろう。 🎨 Her brother had decorated the living room. 彼女の弟がリビングを飾りました。 🎂 They had ordered her favorite strawberry cake. 彼らは彼女のお気いちごケーキを注文していました。 📸 When Saki came home, everyone shouted surprise! サキが家に帰ったとき、みんなが「びっくり！」と叫びました。 😭 She had been so happy that she cried. 彼女はとても嬉しくて泣いてしまいました。 🚲 Her father said that she had deserved this gift. 彼女のお父さんはこの贈り物に値すると言いました。 💕 Saki had never forgotten that wonderful birthday. サキはあの素晴らしい誕生日を決して忘れませんでした。

🎁 Have you ever received a surprise gift? 🤫 Have you ever kept a secret from someone? 🚲 What had you wanted for your birthday? 😮 If you knew a surprise, would you tell? 🎂 What cake would you order for a birthday? 📸 How had you felt when surprised? 😭 Have you ever been so happy you cried? 👨‍👩‍👧 Who had planned something special for you? 💕 What birthday had been the most memorable? 🎉 If you could surprise someone, how would you do it?" }
];
