var eiken7full = [
  {
    "title": "1. My Family",
    "content": "👨 This is my father.\nこれは私の父です。\n\n👩 This is my mother.\nこれは私の母です。\n\n👶 This is my sister.\nこれは私の妹です。\n\n👧 This is my brother.\nこれは私の弟です。\n\n👴 We are a family.\n私たちは家族です。\n\n🏠 We live in a home.\n私たちは家に住んでいます。\n\n❤️ I love my family.\n私は家族を愛しています。\n\n👨 My father is tall.\n私の父は背が高いです。\n\n👩 My mother is kind.\n私の母は優しいです。\n\n👶 My family is happy.\n私の家族は幸せです。\n\n👶 Do you have a sister?\nあなたは妹がいますか？\n\n👧 Do you have a brother?\nあなたは弟がいますか？\n\n🏠 Do you live with your family?\nあなたは家族と住んでいますか？\n\n❤️ Do you love your family?\nあなたは家族を愛していますか？\n\n👨 Is your father tall?\nあなたの父は背が高いですか？\n\n👩 Is your mother kind?\nあなたの母は優しいですか？\n\n👶 Is your family big?\nあなたの家族は大きいですか？\n\n👶 Is your family happy?\nあなたの家族は幸せですか？\n\n🏠 Is your home big?\nあなたの家は大きいですか？"
  },
  {
    "title": "2. My Home",
    "content": "🏠 This is my house.\nこれは私の家です。\n\n🚪 This is the door.\nこれはドアです。\n\n🪟 This is a window.\nこれは窓です。\n\n🛏️ This is a bed.\nこれはベッドです。\n\n🪑 This is a chair.\nこれは椅子です。\n\n🚿 This is a bath.\nこれはお風これはお風呂です。\n\n👨 I sleep in my room.\n私は自分の部屋で寝ます。\n\n👩 I eat at the table.\n私はテーブルで食べます。\n\n👶 I play in the house.\n私は家で遊びます。\n\n👧 My home is warm.\n私の家は暖かいです。\n\n🏠 Do you have a house?\nあなたは家がありますか？\n\n🚪 Do you have a door?\nあなたはドアがありますか？\n\n🪟 Do you have windows?\nあなたは窓がありますか？\n\n🛏️ Do you have a bed?\nあなたはベッドがありますか？\n\n🪑 Do you sit here?\nあなたはここに座りますか？\n\n🚿 Do you take a bath?\nあなたはお風呂に入りますか？\n\n👨 Do you sleep at home?\nあなたは家で寝ますか？\n\n👩 Do you eat at home?\nあなたは家で食べますか？\n\n👶 Do you play in your room?\nあなたは自分の部屋で遊びますか？\n\n👧 Is your home warm?\nあなたの家は暖かいですか？"
  },
  {
    "title": "3. Family Time",
    "content": "🍽️ We eat dinner together.\n私たちは一緒に夕食を食べます。\n\n🛏️ We sleep at night.\n私たちは夜に寝ます。\n\n🎮 We play games.\n私たちはゲームをします。\n\n💬 We talk every day.\n私たちは毎日話します。\n\n👨 My father reads a book.\n私の父は本を読みます。\n\n👩 My mother cooks food.\n私の母は料理を作ります。\n\n👶 My sister helps me.\n私の妹は私を助けます。\n\n👧 My brother runs fast.\n私の弟は速く走ります。\n\n👴 We watch TV together.\n私たちは一緒にテレビを見ます。\n\n❤️ We are a happy family.\n私たちは幸せな家族です。\n\n🍽️ Do you eat dinner?\nあなたは夕食を食べますか？\n\n🛏️ Do you sleep at night?\nあなたは夜に寝ますか？\n\n🎮 Do you play games?\nあなたはゲームをしますか？\n\n💬 Do you talk every day?\nあなたは毎日話しますか？\n\n👨 Does he read books?\n彼は本を読みますか？\n\n👩 Does she cook food?\n彼女は料理をしますか？\n\n👶 Does she help you?\n彼女はあなたを助けてくれますか？\n\n👧 Does he run fast?\n彼は速く走りますか？\n\n👴 Do you watch TV?\nあなたはテレビを見ますか？\n\n❤️ Is your family happy?\nあなたの家族は幸せですか？"
  },
  {
    "title": "4. Family Feelings",
    "content": "😊 I am happy today.\n私は今日幸せです。\n\n👨 My father is strong.\n私の父は強いです。\n\n👩 My mother is nice.\n私の母はいい人です。\n\n👶 My sister is small.\n私の妹は小さいです。\n\n👧 My brother is big.\n私の弟は大きいです。\n\n❤️ We love each other.\n私たちはお互いを愛しています。\n\n😢 I am sad sometimes.\n私は時々悲しいです。\n\n😊 I am happy again.\n私はまた幸せです。\n\n👨 My family loves me.\n私の家族は私を愛しています。\n\n👩 I love my family too.\n私も家族を愛しています。\n\n😊 Are you happy today?\nあなたは今日幸せですか？\n\n👨 Is your father strong?\nあなたの父は強いですか？\n\n👩 Is your mother nice?\nあなたの母はいい人ですか？\n\n👶 Is your sister small?\nあなたの妹は小さいですか？\n\n👧 Is your brother big?\nあなたの弟は大きいですか？\n\n❤️ Do you love your family?\nあなたは家族を愛していますか？\n\n😢 Do you feel sad?\nあなたは悲しい気分ですか？\n\n😊 Do you feel happy?\nあなたは幸せですか？\n\n👨 Do they love you?\n彼らはあなたを愛していますか？\n\n👩 Do you love your family?\nあなたは家族を愛していますか？"
  },
  {
    "title": "5. Pets I Like",
    "content": "🐱 This is a cat.\nこれは猫です。\n\n🐱 The cat is small.\n猫は小さいです。\n\n🐱 It likes to play.\n猫は遊ぶのが好きです。\n\n🐱 The cat sleeps a lot.\n猫はよく寝ます。\n\n🐶 This is a dog.\nこれは犬です。\n\n🐶 The dog is big.\n犬は大きいです。\n\n🐶 The dog runs fast.\n犬は速く走ります。\n\n🐶 It likes to jump.\n犬は跳ぶのが好きです。\n\n❤️ I love my pets.\n私はペットを愛しています。\n\n🏠 Pets are good friends.\nペットは良い友達です。\n\n🐱 Do you have a cat?\nあなたは猫を飼っていますか？\n\n🐱 Is it a small cat?\nそれは小さい猫ですか？\n\n🐶 Do you like dogs?\nあなたは犬が好きですか？\n\n🐶 Is the dog big?\n犬は大きいですか？\n\n❤️ Do you love pets?\nあなたはペットを愛していますか？\n\n🏠 Are pets good friends?\nペットは良い友達ですか？\n\n🐱 Do cats sleep?\n猫は寝ますか？\n\n🐱 Do cats like to play?\n猫は遊ぶのが好きですか？\n\n🐶 Do dogs run?\n犬は走りますか？"
  },
  {
    "title": "6. Farm Animals",
    "content": "🐮 This is a cow.\nこれは牛です。\n\n🐮 The cow is big.\n牛は大きいです。\n\n🐮 It eats grass.\n牛は草を食べます。\n\n🐮 The cow walks slowly.\n牛はゆっくり歩きます。\n\n🐷 This is a pig.\nこれは豚です。\n\n🐷 The pig is fat.\n豚は太っています。\n\n🐷 It likes mud.\n豚は泥が好きです。\n\n🐷 The pig sleeps a lot.\n豚はよく寝ます。\n\n🐴 This is a horse.\nこれは馬です。\n\n🐴 The horse runs very fast.\n馬はとても速く走ります。\n\n🐮 Do you see a cow?\nあなたは牛を見ますか？\n\n🐮 Is the cow big?\n牛は大きいですか？\n\n🐷 Do you like pigs?\nあなたは豚が好きですか？\n\n🐷 Is the pig fat?\n豚は太っていますか？\n\n🐴 Do you like horses?\nあなたは馬が好きですか？\n\n🐴 Does the horse run?\n馬は走りますか？\n\n🐮 Do cows eat grass?\n牛は草を食べますか？\n\n🐷 Do pigs like mud?\n豚は泥が好きですか？\n\n🐴 Is the horse fast?\n馬は速いですか？"
  },
  {
    "title": "7. Zoo Animals",
    "content": "🦁 This is a lion.\nこれはライオンです。\n\n🦁 The lion is very big.\nライオンはとても大きいです。\n\n🦁 It has a mane.\nライオンにはたてがみがあります。\n\n🦁 The lion walks slowly.\nライオンはゆっくり歩きます。\n\n🐯 This is a tiger.\nこれはトラです。\n\n🐯 The tiger has stripes.\nトラにはしま模様があります。\n\n🐯 It is orange and black.\nトラはオレンジと黒です。\n\n🐯 The tiger runs very fast.\nトラはとても速く走ります。\n\n🐘 This is an elephant.\nこれはゾウです。\n\n🐘 The elephant is very big.\nゾウはとても大きいです。\n\n🦁 Do you like lions?\nあなたはライオンが好きですか？\n\n🦁 Is the lion big?\nライオンは大きいですか？\n\n🐯 Do you see tigers?\nあなたはトラを見ますか？\n\n🐯 Is the tiger orange?\nトラはオレンジですか？\n\n🐘 Do you like elephants?\nあなたはゾウが好きですか？\n\n🐘 Is the elephant big?\nゾウは大きいですか？\n\n🦁 Do lions walk?\nライオンは歩きますか？\n\n🐯 Do tigers have stripes?\nトラにはしま模様がありますか？\n\n🐘 Are elephants very big?\nゾウはとても大きいですか？"
  },
  {
    "title": "8. Small Animals",
    "content": "🐝 This is a bee.\nこれはハチです。\n\n🐝 The bee is very small.\nハチはとても小さいです。\n\n🐝 It likes flowers.\nハチは花が好きです。\n\n🐝 The bee flies.\nハチは飛びます。\n\n🦋 This is a butterfly.\nこれはチョウです。\n\n🦋 The butterfly is beautiful.\nチョウは美しいです。\n\n🦋 It has many colors.\nチョウはたくさんの色を持っています。\n\n🦋 The butterfly flies in the sky.\nチョウは空を飛びます。\n\n🐜 This is an ant.\nこれはアリです。\n\n🐜 The ant is very small.\nアリはとても小さいです。\n\n🐝 Do you see bees?\nあなたはハチを見ますか？\n\n🐝 Is the bee small?\nハチは小さいですか？\n\n🦋 Do you like butterflies?\nあなたはチョウが好きですか？\n\n🦋 Is it beautiful?\nそれは美しいですか？\n\n🐜 Do you see ants?\nあなたはアリを見ますか？\n\n🐜 Is the ant small?\nアリは小さいですか？\n\n🐝 Do bees fly?\nハチは飛びますか？\n\n🦋 Do butterflies have colors?\nチョウは色を持っていますか？\n\n🐜 Are ants very small?\nアリはとても小さいですか？"
  },
  {
    "title": "9. Hello",
    "content": "Hello.\nこんにちは。\n\nI am Ken.\n私はケンです。\n\nI am a student.\n私は学生です。\n\nI am happy.\n私は幸せです。\n\nNice to meet you.\nはじめまして。\n\nThis is my friend.\nこれは私の友達です。\n\nWe are friends.\n私たちは友達です。\n\nHow are you？\n元気ですか？\n\nI am fine.\n私は元気です。\n\nThank you.\nありがとう。\n\nHello.\nこんにちは。\n\nHow are you？\n元気ですか？\n\nAre you happy？\n幸せですか？\n\nWhat is your name？\n名前は何ですか？\n\nAre you a student？\n学生ですか？\n\nDo you have friends？\n友達はいますか？\n\nWho is your friend？\n友達は誰ですか？\n\nAre you fine today？\n今日は元気ですか？\n\nThank you.\nありがとう。\n\nGoodbye.\nさようなら。\n"
  },
  {
    "title": "10. My Things",
    "content": "I have a bag.\n私はカバンを持っています。\n\nThe bag is blue.\nカバンは青いです。\n\nI have a pencil.\n私は鉛筆を持っています。\n\nI have a book.\n私は本を持っています。\n\nI have a pen.\n私はペンを持っています。\n\nThe book is red.\n本は赤いです。\n\nThe pen is black.\nペンは黒いです。\n\nThese are my things.\nこれらは私のものです。\n\nI like my things.\n私は自分のものが好きです。\n\nThings are good.\nものは良いです。\n\nDo you have a bag？\nカバンを持っていますか？\n\nWhat color is your bag？\nあなたのカバンは何色ですか？\n\nDo you have a book？\n本を持っていますか？\n\nDo you have a pen？\nペンを持っていますか？\n\nWhat color is your pen？\nあなたのペンは何色ですか？\n\nWhat things do you have？\nどのようなものを持っていますか？\n\nDo you like your things？\nあなたのものは好きですか？\n\nIs your book red？\nあなたの本は赤いですか？\n\nIs your pen black？\nあなたのペンは黒いですか？\n\nWhat is your favorite color？\n一番好きな色は何ですか？\n"
  },
  {
    "title": "11. Food",
    "content": "I like food.\n私は食べ物が好きです。\n\nI like rice.\n米が好きです。\n\nI like bread.\nパンが好きです。\n\nI like apples.\nりんごが好きです。\n\nI drink water.\n私は水を飲みます。\n\nI drink tea.\n私はお茶を飲みます。\n\nThe food is good.\n食べ物は美味しいです。\n\nThe water is cold.\n水は冷たいです。\n\nThe tea is hot.\nお茶は熱いです。\n\nI eat lunch every day.\n私は毎日昼食を食べます。\n\nDo you like food？\n食べ物は好きですか？\n\nDo you like rice？\n米は好きですか？\n\nDo you like bread？\nパンは好きですか？\n\nWhat fruit do you like？\nどの果物が好きですか？\n\nDo you drink water？\n水を飲みますか？\n\nDo you drink tea？\nお茶を飲みますか？\n\nDo you eat lunch？\n昼食を食べますか？\n\nWhat do you eat？\n何を食べますか？\n\nAre you hungry？\nお腹が空いていますか？\n\nWhat food do you like？\nどの食べ物が好きですか？\n"
  },
  {
    "title": "12. At Home",
    "content": "This is my home.\nこれは私の家です。\n\nMy home is big.\n私の家は大きいです。\n\nI have a room.\n私は部屋を持っています。\n\nThe room is nice.\n部屋はいいです。\n\nI have a bed.\n私はベッドを持っています。\n\nI sleep in the bed.\nベッドで寝ます。\n\nI have a desk.\n私は机を持っています。\n\nI study at the desk.\n机で勉強します。\n\nI love my home.\n私は私の家を愛しています。\n\nHome is sweet.\n家はすてきです。\n\nDo you have a home？\n家はありますか？\n\nIs your home big？\nあなたの家は大きいですか？\n\nDo you have a room？\n部屋がありますか？\n\nIs your room nice？\nあなたの部屋はいいですか？\n\nDo you have a bed？\nベッドがありますか？\n\nDo you have a desk？\n机がありますか？\n\nDo you study at home？\n家で勉強しますか？\n\nDo you sleep well？\nよく眠れますか？\n\nDo you love your home？\nあなたの家を愛していますか？\n\nIs home sweet？\n家はすてきですか？\n"
  },
  {
    "title": "13. Numbers One to Three",
    "content": "1️⃣ One.\nいち。\n\n2️⃣ Two.\nに。\n\n3️⃣ Three.\nさん。\n\n🌸 One flower.\n一つの花。\n\n🐦 Two birds.\n二羽の鳥。\n\n🌳 Three trees.\n三本の木。\n\n1️⃣, 2️⃣, 3️⃣.\nいち、に、さん。\n\n👀 I see one flower.\n私は一つ花を見ます。\n\nWhat is one?\nいちは何ですか？\n\nWhat is two?\nには何ですか？\n\nWhat is three?\nさんは何ですか？\n\nDo you see one flower?\n一つ花を見ますか？\n\nHow many birds?\n鳥は何羽ですか？\n\nHow many trees?\n木は何本ですか？\n\nCan you count to three?\nさんまで数えられますか？\n\nIs it one?\nいちですか？\n\nIs it two?\nにですか？\n\nIs it three?\nさんですか？\n"
  },
  {
    "title": "14. Numbers Four to Six",
    "content": "4️⃣ Four.\nよん。\n\n5️⃣ Five.\nご。\n\n6️⃣ Six.\nろく。\n\n🍎 Four apples.\n四個のリンゴ。\n\n🍊 Five oranges.\n五個のオレンジ。\n\n🍌 Six bananas.\n六本のバナナ。\n\n4️⃣, 5️⃣, 6️⃣.\nよん、ご、ろく。\n\n👋 I have four apples.\n私は四個のリンゴを持っています。\n\nWhat is four?\nよんは何ですか？\n\nWhat is five?\nごは何ですか？\n\nWhat is six?\nろくは何ですか？\n\nDo you have four apples?\n四個のリンゴを持っていますか？\n\nHow many oranges?\nオレンジはいくつですか？\n\nIs it five?\nごですか？\n\nCan you count to six?\nろくまで数えられますか？\n\nHow many bananas?\nバナナは何本ですか？\n\nDo you like apples?\nリンゴが好きですか？\n\nDo you like oranges?\nオレンジが好きですか？\n"
  },
  {
    "title": "15. Numbers Seven to Ten",
    "content": "7️⃣ Seven.\nなな。\n\n8️⃣ Eight.\nはち。\n\n9️⃣ Nine.\nきゅう。\n\n1️⃣0️⃣ Ten.\nじゅう。\n\n📖 Seven books.\n七冊の本。\n\n✏️ Eight pencils.\n八本の鉛筆。\n\n🌳 Nine trees.\n九本の木。\n\n🌸 Ten flowers.\n十本の花。\n\n1️⃣ to 1️⃣0️⃣.\nいちからじゅう。\n\n📖 I have seven books.\n私は七冊の本を持っています。\n\nWhat is seven?\nななは何ですか？\n\nWhat is eight?\nはちは何ですか？\n\nWhat is nine?\nきゅうは何ですか？\n\nWhat is ten?\nじゅうは何ですか？\n\nDo you have ten flowers?\n十本の花を持っていますか？\n\nHow many books do you have?\n本は何冊持っていますか？\n\nCan you count to ten?\nじゅうまで数えられますか？\n\nIs it nine?\nきゅうですか？\n\nIs it seven?\nななですか？\n\nHow many pencils?\n鉛筆は何本ですか？\n"
  },
  {
    "title": "16. Big and Small",
    "content": "⚽️ One big ball.\n一個の大きいボール。\n\n⚽️ Two small balls.\n二個の小さいボール。\n\n🔢 Big and small.\n大きいと小さい。\n\n⚽️ The ball is big.\nボールは大きいです。\n\n🍎 The apple is small.\nリンゴは小さいです。\n\n1️⃣, 2️⃣, 3️⃣ numbers.\nいち、に、さんの数字。\n\n4️⃣, 5️⃣, 6️⃣ numbers.\nよん、ご、ろくの数字。\n\n🔢 Big numbers.\n大きい数字。\n\n🔢 Small numbers.\n小さい数字。\n\n⚽️ One is small.\nいちは小さいです。\n\n1️⃣0️⃣ Ten is big.\nじゅうは大きいです。\n\nWhat is big?\n何が大きいですか？\n\nWhat is small?\n何が小さいですか？\n\nIs the ball big?\nボールは大きいですか？\n\nIs the apple small?\nリンゴは小さいですか？\n\nHow many big numbers?\n大きい数字はいくつですか？\n\nHow many small numbers?\n小さい数字はいくつですか？\n\nIs ten big?\nじゅうは大きいですか？\n\nIs one small?\nいちは小さいですか？\n\nCan you see big and small?\n大きいと小さいが見えますか？\n\nDo you like big balls?\n大きいボールが好きですか？\n"
  },
  {
    "title": "17. Numbers in Spring",
    "content": "🌸 I see one flower.\n私は一つの花を見る.\n\n🌸 I see two flowers.\n私は二つの花を見る.\n\n🌸 I see three birds.\n私は三羽の鳥を見る.\n\n🌸 I see four trees.\n私は四本の木を見る.\n\n🌸 I see five children.\n私は五人の子供を見る.\n\n🌸 I see six dogs.\n私は六匹の犬を見る.\n\n🌸 I see seven cars.\n私は七台の車を見る.\n\n🌸 I see eight books.\n私は八冊の本を見る.\n\n🌸 I see nine chairs.\n私は九つの椅子を見る.\n\n🌸 I see ten friends.\n私は十人の友達を見る.\n\n❓ How many flowers do you see？\nあなたは何個の花を見ますか？\n\n🌸 What color is a flower？\n花は何色ですか？\n\n❓ How many birds are there？\nそこには何羽の鳥がいますか？\n\n❓ Do you like flowers？\nあなたは花が好きですか？\n\n❓ How many dogs do you have？\nあなたは何匹の犬を持っていますか？\n\n❓ Can you count to ten？\nあなたは十まで数えることができますか？\n\n❓ How many friends are here？\nここには何人の友達がいますか？\n\n❓ What number comes after five？\n五の後は何の数字ですか？\n\n❓ How many books do you read？\nあなたは何冊の本を読みますか？\n\n❓ What is your favorite number？\nあなたの好きな数字は何ですか？"
  },
  {
    "title": "18.colors in Spring",
    "content": "🔴 I like red.\n私は赤が好きです.\n\n🟠 I see orange.\n私はオレンジを見る.\n\n🟡 The sun is yellow.\n太陽は黄色いです.\n\n🟢 The grass is green.\n草は緑色です.\n\n🔵 The sky is blue.\n空は青いです.\n\n🟣 I wear purple clothes.\n私は紫色の服を着る.\n\n⚫ My cat is black.\n私の猫は黒いです.\n\n⚪ My dog is white.\n私の犬は白いです.\n\n🟤 The tree is brown.\n木は茶色です.\n\n🌸 The flower is pink.\n花はピンク色です.\n\n❓ What color do you like？\nあなたはどの色が好きですか？\n\n🔴 What color is an apple？\nりんごは何色ですか？\n\n🔵 Is the sky blue？\n空は青色ですか？\n\n🟢 What color is the grass？\n草は何色ですか？\n\n⚫ What color is your school bag？\nあなたのランドセルは何色ですか？\n\n⚪ What color are clouds？\n雲は何色ですか？\n\n🟣 Is purple a nice color？\n紫色は素敵な色ですか？\n\n🟡 What fruit is yellow？\nどの果物は黄色ですか？\n\n🟤 What color are dogs' eyes？\n犬の目は何色ですか？\n\n🌸 What is your favorite color？\nあなたの好きな色は何ですか？"
  },
  {
    "title": "19. Greetings",
    "content": "👋 Hello.\nこんにちは.\n\n👋 Good morning.\nおはようございます.\n\n👋 Good afternoon.\nこんにちは.\n\n👋 Good evening.\nこんばんは.\n\n😊 I am fine, thank you.\n私は元気です、ありがとう.\n\n👋 Goodbye.\nさようなら.\n\n👋 See you later.\nまた会いましょう.\n\n👋 Nice to meet you.\nはじめまして.\n\n👋 How are you？\nお元気ですか？\n\n😊 Thank you very much.\nどうもありがとうございます.\n\n❓ How do you say hello in English？\n英語でこんにちはと言うにはどうしますか？\n\n👋 What do you say in the morning？\n朝には何と言いますか？\n\n👋 What do you say at night？\n夜には何と言いますか？\n\n😊 How are you today？\n今日はお元気ですか？\n\n👋 When do you say goodbye？\nさようならと言うのはいつですか？\n\n👋 What do you say to a new friend？\n新しい友達に何と言いますか？\n\n😊 Do you say thank you？\nあなたはありがとうと言いますか？\n\n👋 What do you say in the afternoon？\n午後に何と言いますか？\n\n👋 How do you greet your teacher？\nあなたは先生にどのように挨拶しますか？\n\n😊 Are you happy today？\n今日は幸せですか？"
  },
  {
    "title": "20. My Family",
    "content": "👨 This is my father.\nこれは私の父です.\n\n👩 This is my mother.\nこれは私の母です.\n\n👦 This is my brother.\nこれは私の弟です.\n\n👧 This is my sister.\nこれは私の妹です.\n\n👴 This is my grandfather.\nこれは私の祖父です.\n\n👵 This is my grandmother.\nこれは私の祖母です.\n\n🐱 This is my cat.\nこれは私の猫です.\n\n🐶 This is my dog.\nこれは私の犬です.\n\n👨‍👩‍👦 This is my family.\nこれは私の家族です.\n\n🏠 This is my home.\nこれは私の家です.\n\n❓ Who is this？\nこれは誰ですか？\n\n👨 Who is your father？\nあなたの父は誰ですか？\n\n👩 Who is your mother？\nあなたの母は誰ですか？\n\n🐱 Do you have a cat？\nあなたは猫を持っていますか？\n\n🐶 Do you have a dog？\nあなたは犬を持っていますか？\n\n👴 How many grandparents do you have？\nあなたは何人の祖父母を持っていますか？\n\n👧 Is she your sister？\n彼女はあなたの妹ですか？\n\n👦 Is he your brother？\n彼はあなたの弟ですか？\n\n🏠 Where is your home？\nあなたの家はどこですか？\n\n👨‍👩‍👦 How many people are in your family？\nあなたの家族には何人がいますか？"
  },
  {
    "title": "21. Rainy Day Phrases",
    "content": "🌧️ It is rainy.\n雨です.\n\n☔ I have an umbrella.\n私は傘を持っています.\n\n🧥 I wear a coat.\n私はコートを着ています.\n\n☕ I drink tea.\n私はお茶を飲みます.\n\n📖 I read a book.\n私は本を読みます.\n\n🏠 I stay at home.\n私は家に留まります.\n\n😊 I am happy.\n私は幸せです.\n\n📺 I watch TV.\n私はテレビを見ます.\n\n🕐 It is eight o'clock.\n八時です.\n\n🌙 Good night.\nおやすみなさい.\n\n❓ What is the weather today？\n今日の天気は何ですか？\n\n🌧️ Do you like rain？\nあなたは雨が好きですか？\n\n☔ What do you use in the rain？\n雨の中で何を使いますか？\n\n☕ What do you drink？\n何を飲みますか？\n\n📖 Do you like reading？\nあなたは読むのが好きですか？\n\n🏠 Where do you stay？\nどこに留まりますか？\n\n📺 What do you watch？\n何を見ますか？\n\n😊 Are you happy？\nあなたは幸せですか？\n\n🕐 What time is it？\n今は何時ですか？\n\n🌙 When do you sleep？\nいつ寝ますか？"
  },
  {
    "title": "22. Things at Home",
    "content": "🪑 This is a chair.\nこれは椅子です.\n\n🪑 I sit on a chair.\n私は椅子に座ります.\n\n🛋️ This is a sofa.\nこれはソファーです.\n\n🛋️ I sit on a sofa.\n私はソファーに座ります.\n\n🖼️ This is a picture.\nこれは絵です.\n\n🖼️ I look at the picture.\n私は絵を見る.\n\n🪴 This is a plant.\nこれは植物です.\n\n🪴 The plant is green.\n植物は緑色です.\n\n💡 I turn on the light.\n私は点灯をつける.\n\n🚪 I open the door.\n私はドアを開ける.\n\n❓ What is this？\nこれは何ですか？\n\n🪑 Where do you sit？\nどこに座りますか？\n\n🛋️ Do you like sofas？\nあなたはソファーが好きですか？\n\n🖼️ What picture do you like？\nどの絵が好きですか？\n\n🪴 What color is the plant？\n植物は何色ですか？\n\n💡 Can you turn on the light？\nあなたは電気をつけることができますか？\n\n🚪 Where is the door？\nドアはどこですか？\n\n🪑 How many chairs are there？\n椅子はいくつありますか？\n\n🖼️ Do you have pictures at home？\n家には絵がありますか？\n\n🪴 Do you like plants？\nあなたは植物が好きですか？"
  },
  {
    "title": "23. Food and Drink",
    "content": "🍎 I eat an apple.\n私はりんごを食べる.\n\n🍌 I eat a banana.\n私はバナナを食べる.\n\n🍊 I eat an orange.\n私はオレンジを食べる.\n\n🍓 I eat a strawberry.\n私はイチゴを食べる.\n\n🍵 I drink tea.\n私はお茶を飲む.\n\n☕ I drink coffee.\n私はコーヒーを飲む.\n\n🥛 I drink milk.\n私は牛乳を飲む.\n\n💧 I drink water.\n私は水を飲む.\n\n🍞 I eat bread.\n私はパンを食べる.\n\n🍚 I eat rice.\n私はご飯を食べる.\n\n❓ What do you eat？\nあなたは何を食べますか？\n\n🍎 Do you like apples？\nあなたはりんごが好きですか？\n\n☕ What do you drink？\nあなたは何を飲みますか？\n\n🍌 What fruit is yellow？\nどの果物は黄色ですか？\n\n🍓 What fruit is red？\nどの果物は赤色ですか？\n\n🥛 What do you drink in the morning？\n朝には何を飲みますか？\n\n🍞 What do you eat for breakfast？\n朝食には何を食べますか？\n\n🍚 Do you like rice？\nあなたはご飯が好きですか？\n\n💧 Do you drink water every day？\nあなたは毎日水を飲みますか？\n\n🍊 What fruit do you like？\nどの果物が好きですか？"
  },
  {
    "title": "24. Simple Actions",
    "content": "🚶 I walk.\n私は歩く.\n\n🏃 I run.\n私は走る.\n\n🧘 I sit.\n私は座る.\n\n🛏️ I sleep.\n私は眠る.\n\n🤗 I stand.\n私は立つ.\n\n😊 I smile.\n私は微笑む.\n\n🗣️ I speak.\n私は話す.\n\n👂 I listen.\n私は聞く.\n\n👁️ I look.\n私は見る.\n\n🙋 I raise my hand.\n私は手を挙げる.\n\n❓ What do you do？\nあなたは何をしますか？\n\n🚶 Do you walk to school？\nあなたは学校へ歩いて行きますか？\n\n🏃 Can you run fast？\nあなたは速く走ることができますか？\n\n😊 Do you smile every day？\nあなたは毎日微笑みますか？\n\n🗣️ What language do you speak？\nあなたはどの言語を話しますか？\n\n👂 Do you listen to music？\nあなたは音楽を聴きますか？\n\n👁️ What do you look at？\nあなたは何を見ますか？\n\n🧘 Where do you sit？\nどこに座りますか？\n\n🛏️ Do you sleep well？\nあなたはよく眠れますか？\n\n🙋 When do you raise your hand？\nいつ手を挙げますか？"
  },
  {
    "title": "25. Counting Summer Things (Numbers)",
    "content": "🌅 One sun.\n太陽が一つ.\n✈️ Two planes.\n飛行機が二機.\n🏨 Three hotels.\nホテルが三つ.\n🌴 Four beaches.\nビーチが四つ.\n📸 Five photos.\n写真が五枚.\n🍦 Six ice creams.\nアイスクリームが六つ.\n🎫 Seven tickets.\nチケットが七枚.\n🥾 Eight shoes.\n靴が八足.\n🗺️ Nine maps.\n地図が九枚.\n😊 Ten friends.\n友だちが十人.\n🌅 How many suns？\n太陽はいくつ？\n✈️ How many planes？\n飛行機は何機？\n🏨 How many hotels？\nホテルはいくつ？\n🌴 How many beaches？\nビーチはいくつ？\n📸 How many photos？\n写真は何枚？\n🍦 How many ice creams？\nアイスクリームは何個？\n🎫 How many tickets？\nチケットは何枚？\n🥾 How many shoes？\n靴は何足？\n🗺️ How many maps？\n地図は何枚？\n😊 How many friends？\n友だちは何人？"
  },
  {
    "title": "26. At the Beach (Basic Phrases)",
    "content": "🌊 Look at the water.\nお水を見てください.\n🏖️ The sand is hot.\n砂は熱い.\n☀️ The sun is big.\n太陽は大きい.\n🏊 I swim.\n私は泳ぎます.\n🍦 I eat ice cream.\n私はアイスクリームを食べます.\n🚗 I go by car.\n私は車で行きます.\n⛱️ I sit under the umbrella.\n私は傘の下に座ります.\n🥪 I eat lunch.\n私は昼食を食べます.\n🏩 The restaurant is here.\nレストランはここです.\n🌅 Good night.\nおやすみなさい.\n🌊 Is this water？\nこれは水ですか？\n🏖️ Is it hot？\n暑いですか？\n☀️ Is it big？\n大きいですか？\n🏊 Can you swim？\nあなたは泳げますか？\n🍦 Do you eat？\nあなたは食べますか？\n🚗 Can you go？\nあなたは行けますか？\n⛱️ Is it an umbrella？\nそれは傘ですか？\n🥪 Is it lunch？\n昼食ですか？\n🏩 Where is it？\nそれはどこですか？\n🌅 Is it night？\n夜ですか？"
  },
  {
    "title": "27. In the Mountains (Numbers / Phrases)",
    "content": "🏔️ One mountain.\n山が一座.\n🥾 Two boots.\nブーツが二足.\n🗺️ Three maps.\n地図が三枚.\n⛈️ Four clouds.\n雲が四つ.\n🏕️ Five tents.\nテントが五つ.\n🌲 Six trees.\n木が六本.\n🎒 Seven bags.\nバッグが七つ.\n🥶 Eight jackets.\nジャケットが八着.\n🦅 Nine birds.\n鳥が九羽.\n🌟 Ten flowers.\n花が十本.\n🏔️ How many mountains？\n山はいくつ？\n🥾 How many boots？\nブーツは何足？\n🗺️ How many maps？\n地図は何枚？\n⛈️ How many clouds？\n雲はいくつ？\n🏕️ How many tents？\nテントはいくつ？\n🌲 How many trees？\n木は何本？\n🎒 How many bags？\nバッグはいくつ？\n🥶 How many jackets？\nジャケットは何着？\n🦅 How many birds？\n鳥は何羽？\n🌟 How many flowers？\n花は何本？"
  },
  {
    "title": "28. At the Festival (Basic Phrases)",
    "content": "🎏 The festival is fun.\nお祭りは楽しい.\n🍜 I eat food.\n私は食べ物を食べます.\n🎶 I listen to music.\n私は音楽を聞きます.\n🎎 I dance.\n私は踊ります.\n🏮 It is pretty.\nそれはきれいです.\n🎉 I am happy!\n嬉しい！\n🎫 I buy a ticket.\n私はチケットを買います.\n🚮 I see a bin.\n私はゴミ箱を見ます.\n🎇 Wow!\nすごい！\n📸 The photo is nice.\n写真はいい。\n🎏 Is it fun？\n楽しいですか？\n🍜 Do you eat？\nあなたは食べますか？\n🎶 Do you listen？\nあなたは聞きますか？\n🎎 Do you dance？\nあなたは踊りますか？\n🏮 Is it pretty？\nそれはきれいですか？\n🎉 Are you happy？\nあなたは幸せですか？\n🎫 Do you buy？\nあなたは買いますか？\n🚮 Do you see？\nあなたは見ますか？\n🎇 Wow!\nすごい！\n📸 Is it nice？\nそれはいいですか？"
  },
  {
    "title": "29. Obon Numbers (Numbers)",
    "content": "👻 One family.\n家族が一.\n🕯️ Two lanterns.\n灯篭が二つ.\n🎶 Three songs.\n歌が三曲.\n🍚 Four dishes.\n料理が四品.\n🚢 Five boats.\n船が五艘.\n🎭 Six dancers.\n踊り子が六人.\n🏮 Seven lights.\n明かりが七つ.\n🌙 Eight stars.\n星が八つ.\n✨ Nine fireworks.\n花火が九発.\n💖 Ten hearts.\n心が十個.\n👻 How many families？\n家族はいくつ？\n🕯️ How many lanterns？\n灯篭はいくつ？\n🎶 How many songs？\n歌は何曲？\n🍚 How many dishes？\n料理は何品？\n🚢 How many boats？\n船は何艘？\n🎭 How many dancers？\n踊り子は何人？\n🏮 How many lights？\n明かりはいくつ？\n🌙 How many stars？\n星はいくつ？\n✨ How many fireworks？\n花火は何発？\n💖 How many hearts？\n心はいくつ？"
  },
  {
    "title": "30. Fireworks! (Basic Phrases)",
    "content": "🎆 Look up!\n見上げてください！\n💥 Boom!\nドーン！\n👶 Children smile.\n子供たちは笑います.\n🌃 The sky is bright.\n空は明るい.\n💔 The dog runs.\n犬は走ります.\n🎇 See colors.\n色を見てください.\n🎉 I am happy!\n嬉しい！\n🏙️ Big city!\n大きな都市.\n✨ Beautiful!\n綺麗！\n🎆 I see fire.\n私は火を見ます.\n🎆 Look!\n見て！\n💥 What noise？\nどんな音？\n👶 Are they happy？\n彼らは幸せですか？\n🌃 Is it bright？\n明るいですか？\n💔 Does it run？\nそれは走りますか？\n🎇 What color？\n何色？\n🎉 Are you happy？\nあなたは幸せですか？\n🏙️ Is it big？\nそれは大きいですか？\n✨ Is it beautiful？\nそれは綺麗ですか？\n🎆 Do you see？\nあなたは見ますか？"
  },
  {
    "title": "31. Hot Summer (Basic / Be-Verb)",
    "content": "🌡️ It is hot.\n暑い.\n☀️ The sun is hot.\n太陽は熱い.\n🏙️ I walk.\n私は歩きます.\n💧 Water is good.\n水は良い.\n🌲 It is cool.\n涼しい.\n💷 I sit inside.\n私は中に座ります.\n🚿 I wash.\n私は洗います.\n🌅 The sun sets.\n太陽が沈む.\n🍶 I eat.\n私は食べます.\n🌡️ It is very hot.\nとても暑い。\n🌡️ Is it hot？\n暑いですか？\n☀️ Is it sunny？\n晴れていますか？\n🏙️ Do you walk？\nあなたは歩きますか？\n💧 Is water good？\n水は良いですか？\n🌲 Is it cool？\n涼しいですか？\n💷 Is it inside？\nそれは中ですか？\n🚿 Do you wash？\nあなたは洗いますか？\n🌅 Is it sunset？\n日没ですか？\n🍶 Do you eat？\nあなたは食べますか？\n🌡️ Is it very hot？\nとても暑いですか？"
  },
  {
    "title": "32. School Things (Basic Phrases)",
    "content": "📚 This is a book.\nこれは本です.\n🎒 I have a bag.\n私はバッグを持っています.\n📏 This is a ruler.\nこれは定規です.\n🚌 The bus comes.\nバスが来ます.\n📖 I read.\n私は読みます.\n🌟 I see friends.\n私は友達を見ます.\n📝 I write.\n私は書きます.\n🏫 This is school.\nこれは学校です.\n😊 I smile.\n私は笑います.\n🎨 I draw.\n私は描きます.\n📚 Is it a book？\nそれは本ですか？\n🎒 Do you have it？\nあなたはそれを持っていますか？\n📏 Is it long？\nそれは長いですか？\n🚌 Does it come？\nそれは来ますか？\n📖 Do you read？\nあなたは読みますか？\n🌟 Do you see？\nあなたは見ますか？\n📝 Do you write？\nあなたは書きますか？\n🏫 Is it school？\nそれは学校ですか？\n😊 Are you happy？\nあなたは幸せですか？\n🎨 Do you draw？\nあなたは描きますか？"
  },
  {
    "title": "33. Autumn Begins (Absolute beginners / Simple)",
    "content": "🍂 I see red leaves.\\n赤い葉を見ます。\\n🍂 The wind blows.\\n風が吹きます。\\n🍂 It is cool.\\n涼しいです。\\n🍂 I like autumn.\\n秋が好きです。\\n🍂 Fall is nice.\\n秋はいいです。\\n🍂 Do you like autumn?\\n秋が好きですか？\\n🍂 Is it cool today?\\n今日は涼しいですか？\\n🍂 What color are the leaves?\\n葉は何色ですか？\\n🍂 Do you see red trees?\\n赤い木が見えますか？\\n🍂 Is autumn good?\\n秋はいいですか？"
  },
  {
    "title": "34. Typhoon Season (Absolute beginners / Simple)",
    "content": "🌀 Rain falls.\\n雨が降ります。\\n🌀 The wind blows.\\n風が吹きます。\\n🌀 I stay home.\\n家にいます。\\n🌀 Typhoons are strong.\\n台風は強いです。\\n🌀 I am safe.\\n安全です。\\n🌀 Do you like rain?\\n雨は好きですか？\\n🌀 Are typhoons scary?\\n台風は怖いですか？\\n🌀 Do you stay inside?\\n中にいますか？\\n🌀 Is the wind strong?\\n風は強いですか？\\n🌀 Are you safe?\\n安全ですか？"
  },
  {
    "title": "35. Back to School (Absolute beginners / Simple)",
    "content": "📚 I go to school.\\n学校に行きます。\\n📚 I have a teacher.\\n先生がいます。\\n📚 I see friends.\\n友達に会います。\\n📚 School starts today.\\n学校は今日始まります。\\n📚 I am happy。\\n嬉しいです。\\n📚 Is school fun?\\n学校は楽しいですか？\\n📚 Do you have a teacher?\\n先生がいますか？\\n📚 Do you see friends?\\n友達に会いますか？\\n📚 Is today Monday?\\n今日は月曜日ですか？\\n📚 Are you happy?\\n嬉しいですか？"
  },
  {
    "title": "36. Harvest Festivals (Absolute beginners / Simple)",
    "content": "🎃 We eat food.\\n食べ物を食べます。\\n🎃 Farmers work.\\n農家が働きます。\\n🎃 We are happy。\\n嬉しいです。\\n🎃 Food is good.\\n食べ物はいいです。\\n🎃 We sing songs.\\n歌を歌います。\\n🎃 Do you like festivals?\\n祭りは好きですか？\\n🎃 Do farmers work hard?\\n農家は一生懸命働きますか？\\n🎃 Are you happy?\\n嬉しいですか？\\n🎃 Is the food good?\\n食べ物はいいですか？\\n🎃 Do you sing?\\n歌いますか？"
  },
  {
    "title": "37. Halloween (Absolute beginners / Simple)",
    "content": "👻 I see ghosts.\\nお化けを見ます。\\n👻 It is fun。\\n楽しいです。\\n👻 I eat candy.\\nお菓子を食べます。\\n👻 We dress up.\\n仮装します。\\n👻 Halloween is here.\\nハロウィンが来ました。\\n👻 Do you like ghosts?\\nお化けは好きですか？\\n👻 Is it fun today?\\n今日は楽しいですか？\\n👻 Do you eat candy?\\nお菓子を食べますか？\\n👻 Do you dress up?\\n仮装しますか？\\n👻 Is Halloween fun?\\nハロウィンは楽しいですか？"
  },
  {
    "title": "38. Autumn Leaves (Koyo) (Absolute beginners / Simple)",
    "content": "🍁 Leaves are red.\\n葉は赤いです。\\n🍁 They are yellow.\\n黄色です。\\n🍁 I go to the park.\\n公園に行きます。\\n🍁 They are pretty.\\nきれいです。\\n🍁 I take photos.\\n写真を撮ります。\\n🍁 Are the leaves red?\\n葉は赤いですか？\\n🍁 Are they yellow?\\n黄色ですか？\\n🍁 Do you go to the park?\\n公園に行きますか？\\n🍁 Are they pretty?\\nきれいですか？\\n🍁 Do you take photos?\\n写真を撮りますか？"
  },
  {
    "title": "39. Moon Viewing (Absolute beginners / Simple)",
    "content": "🌕 The moon is round.\\n月は丸いです。\\n🌕 It is bright.\\n明るいです。\\n🌕 We sit outside.\\n外に座っています。\\n🌕 The night is dark.\\n夜は暗いです。\\n🌕 I see stars.\\n星が見えます。\\n🌕 Is the moon round?\\n月は丸いですか？\\n🌕 Is it bright?\\n明るいですか？\\n🌕 Do you sit outside?\\n外に座りますか？\\n🌕 Is the night dark?\\n夜は暗いですか？\\n🌕 Do you see stars?\\n星が見えますか？"
  },
  {
    "title": "40. Cooler Temperatures (Absolute beginners / Simple)",
    "content": "❄️ It is cold.\\n寒いです。\\n❄️ I wear a coat.\\nコートを着ます。\\n❄️ The wind blows.\\n風が吹きます。\\n❄️ I drink tea.\\nお茶を飲みます。\\n❄️ Winter is near.\\n冬が近いです。\\n❄️ Is it cold today?\\n今日は寒いですか？\\n❄️ Do you wear a coat?\\nコートを着ますか？\\n❄️ Does the wind blow?\\n風が吹きますか？\\n❄️ Do you drink tea?\\nお茶を飲みますか？\\n❄️ Is winter near?\\n冬は近いですか？"
  },
  {
    "title": "41. Numbers 1-10",
    "content": "1️⃣ One apple. りんご二つ.\n2️⃣ Two books. 本二冊.\n3️⃣ Three cats. 猫三匹.\n4️⃣ Four dogs. 犬四匹.\n5️⃣ Five pens. ペン五本.\n6️⃣ Six stars. 星六つ.\n7️⃣ Seven days. 七日間.\n8️⃣ Eight cars. 車八台.\n9️⃣ Nine birds. 鳥九羽.\n🔟 Ten trees. 木十本.\n1️⃣ How many apples？ 何個のりんご？\n2️⃣ How many books？ 何冊の本？\n3️⃣ Do you like cats？ 猫は好きですか？\n4️⃣ Do you have dogs？ 犬はいますか？\n5️⃣ Do you use pens? ペンを使いますか？\n6️⃣ Can you see stars？ 星が見えますか？\n7️⃣ How many days？ 何日間？\n8️⃣ Do you have a car？ 車はありますか？\n9️⃣ Do you like birds？ 鳥は好きですか？\n🔟 How many trees？ 何本の木？"
  },
  {
    "title": "42. Colors and Weather",
    "content": "🔴 Red is my favorite color. 赤は私のお気に入りの色です.\n🟡 Yellow is the sun. 黄色は太陽です.\n🟢 Green is the grass. 緑は草です.\n🔵 Blue is the sky. 青は空です.\n🟠 Orange is a pumpkin. オレンジはカボチャです.\n🟣 Purple is nice. 紫は綺麗です.\n⚫ Black is night. 黒は夜です.\n⚪ White is snow. 白は雪です.\n🟤 Brown is the earth. 茶色は大地です.\n🌤️ Sunny is nice. 晴れは良いです.\n🔴 Do you like red？ 赤は好きですか？\n🟡 What is yellow？ 黄色は何ですか？\n🟢 Is grass green？ 草は緑ですか？\n🔵 What color is the sky？ 空は何色ですか？\n🟠 Do you like orange？ オレンジは好きですか？\n🟣 What color is this？ これは何色ですか？\n⚫ Do you like night？ 夜は好きですか？\n⚪ Do you like snow？ 雪は好きですか？\n🟤 What is brown？ 茶色は何ですか？\n🌤️ Is it sunny？ 晴れですか？"
  },
  {
    "title": "43. Basic Greetings",
    "content": "👋 Hello! How are you？ こんにちは！お元気ですか？\n👋 Good morning! おはようございます！\n👋 Good afternoon! こんにちは！\n👋 Good evening! こんばんは！\n👋 Good night! おやすみなさい！\n😊 I am fine, thank you. 私は元気です、ありがとう.\n😊 Nice to meet you. お会いできて嬉しいです.\n👋 Goodbye! さようなら！\n👋 See you later! また後で！\n❤️ Thank you very much. どうもありがとうございます.\n👋 How do you say hello？ こんにちはとどう言いますか？\n😊 Are you fine today？ 今日は元気ですか？\n😊 What do you say when meeting？ 会ったとき何と言いますか？\n👋 What do you say at night？ 夜に何と言いますか？\n😊 How are you today？ 今日お元気ですか？\n❤️ Do you say thank you？ ありがとうと言いますか？\n👋 How do you say goodbye？ さようならとどう言いますか？\n😊 Is it morning or afternoon？ 朝ですか、それとも午後ですか？\n👋 What do you say before sleep？ 寝る前に何と言いますか？\n❤️ How do you feel？ 気分はどうですか？"
  },
  {
    "title": "44. My Day",
    "content": "🌅 I wake up in the morning. 私は朝に起きます.\n🥣 I eat breakfast in the morning. 朝に朝食を食べます.\n🏫 I go to school. 私は学校に行きます.\n📚 I study at school. 私は学校で勉強します.\n🍎 I eat lunch. 私は昼食を食べます.\n🏠 I go home. 私は家に帰ります.\n🎾 I play in the afternoon. 午後に遊びます.\n🥗 I eat dinner at home. 家で夕食を食べます.\n📖 I read a book. 私は本を読みます.\n😴 I go to sleep at night. 夜に私は寝ます.\n🌅 When do you wake up？ いつ起きますか？\n🥣 What do you eat for breakfast？ 朝食に何を食べますか？\n🏫 Where do you go？ どこに行きますか？\n📚 Do you study hard？ 一生懸命勉強しますか？\n🍎 When do you eat lunch？ いつ昼食を食べますか？\n🏠 Where is your home？ あなたの家はどこですか？\n🎾 What do you play？ 何で遊びますか？\n🥗 Do you eat dinner？ 夕食を食べますか？\n📖 Do you like reading books？ 本を読むのは好きですか？\n😴 When do you sleep？ いつ寝ますか？"
  },
  {
    "title": "45. Winter Words",
    "content": "❄️ Snow is white. 雪は白い.\n☃️ A snowman is fun. 雪だるまは楽しい.\n🧣 A scarf is warm. マフラーは暖かい.\n🧤 Gloves are warm. 手袋は暖かい.\n🏠 Home is warm. 家は暖かい.\n☕ Tea is hot. お茶は熱い.\n🍪 Cookies are sweet. クッキーは甘い.\n🎄 A tree is green and tall. 木は緑で背が高い.\n🎁 A gift is nice. プレゼントは良い.\n🌟 A star is bright. 星は明るい.\n❄️ Do you like snow？ 雪は好きですか？\n☃️ Do you make snowmen？ 雪だるまを作りますか？\n🧣 Do you wear a scarf？ マフラーを着ますか？\n🧤 Are your hands cold？ 手は寒いですか？\n🏠 Is your home warm？ あなたの家は暖かいですか？\n☕ Do you drink tea？ お茶を飲みますか？\n🍪 Do you like cookies？ クッキーは好きですか？\n🎄 Do you have a tree？ 木はありますか？\n🎁 Do you give gifts？ ギフトをあげますか？\n🌟 Do you see stars？ 星が見えますか？"
  },
  {
    "title": "46. Counting Winter Things",
    "content": "1️⃣ One snowman. 雪だるま一つ.\n2️⃣ Two snowflakes. 雪の結晶二つ.\n3️⃣ Three gifts. プレゼント三つ.\n4️⃣ Four candles. ろうそく四本.\n5️⃣ Five cookies. クッキー五個.\n6️⃣ Six stars. 星六つ.\n7️⃣ Seven bells. 鐘七つ.\n8️⃣ Eight trees. 木八本.\n9️⃣ Nine snowballs. 雪玉九個.\n🔟 Ten lights. ライト十個.\n1️⃣ How many snowmen？ 何個の雪だるま？\n2️⃣ Do you see snowflakes？ 雪の結晶が見えますか？\n3️⃣ What gifts do you like？ どんなプレゼントが好きですか？\n4️⃣ Do you light candles？ ろうそくを灯しますか？\n5️⃣ How many cookies do you eat？ 何個のクッキーを食べますか？\n6️⃣ Can you see stars？ 星が見えますか？\n7️⃣ Do you hear bells？ 鐘の音が聞こえますか？\n8️⃣ How many trees？ 何本の木？\n9️⃣ Do you play with snow？ 雪で遊びますか？\n🔟 How many lights？ 何個のライト？"
  },
  {
    "title": "47. Family and Christmas",
    "content": "👩 This is my mother. これは私の母です.\n👨 This is my father. これは私の父です.\n👧 This is my sister. これは私の姉です.\n👦 This is my brother. これは私の兄です.\n👴 This is my grandfather. これは私の祖父です.\n👵 This is my grandmother. これは私の祖母です.\n❤️ I love my family. 私は私の家族が好きです.\n🎄 We have a Christmas tree. 私たちはクリスマスツリーを持っています.\n🎁 We give gifts. 私たちはギフトをあげます.\n👨‍👩‍👧‍👦 We are happy together. 私たちは一緒で幸せです.\n👩 Do you have a mother？ 母はいますか？\n👨 Who is your father？ あなたの父は誰ですか？\n👧 Do you have a sister？ 姉はいますか？\n👦 Do you have a brother？ 兄はいますか？\n👴 Is your grandfather kind？ 祖父は優しいですか？\n👵 Is your grandmother nice？ 祖母は良いですか？\n❤️ Do you love your family？ 家族は好きですか？\n🎄 Do you like Christmas？ クリスマスは好きですか？\n🎁 What gifts do you give？ どんなギフトをあげますか？\n👨‍👩‍👧‍👦 Is your family happy？ あなたの家族は幸せですか？"
  },
  {
    "title": "48. Feelings and Likes",
    "content": "😊 I am happy. 私は幸せです.\n😢 I am sad sometimes. 時々悲しいです.\n😠 I am angry sometimes. 時々怒っています.\n😰 I am scared sometimes. 時々怖いです.\n😴 I am tired at night. 夜は疲れています.\n❤️ I like December. 私は12月が好きです.\n❤️ I like winter. 私は冬が好きです.\n❤️ I like snow. 私は雪が好きです.\n❤️ I like holidays. 私は祝日が好きです.\n❤️ I like my family. 私は私の家族が好きです.\n😊 How do you feel today？ 今日は気分はどうですか？\n😢 Are you sad or happy？ 悲しいですか、それとも幸せですか？\n😠 Do you get angry often？ よく怒りますか？\n😰 Are you scared of snow？ 雪が怖いですか？\n😴 Do you sleep well？ よく眠れますか？\n❤️ What do you like？ 何が好きですか？\n❤️ Do you like December？ 12月は好きですか？\n❤️ Do you like winter？ 冬は好きですか？\n❤️ What holidays do you like？ どんな祝日が好きですか？\n❤️ Do you like your family？ 家族は好きですか？"
  }
];
