// Eiken Pre-2 - Complete (48 Stories)
// TPRS Narrative Style
// Sentence length: 10-12 words
// Grammar: All Pre-2 patterns covered
// Status: Production Ready with all fixes

var eikenpre2 = [
  {
    "title": "1. Emma's New Routine (Present Perfect / Comparatives)",
    "content": "🏡 Emma wants to become healthier this year.\nエマは今年、より健康になりたいです。\n🏃‍♀️ She decides to start jogging every morning.\n彼女は毎朝ジョギングを始めることにします。\n⏰ But waking up at 6 AM is very hard.\nしかし、朝6時に起きるのはとても大変です。\n😴 For three days, she feels too tired to continue.\n3日間、彼女は疲れすぎて続けられません。\n💪 However, Emma remembers her goal to be healthy.\nしかし、エマは健康になるという目標を思い出します。\n🌳 She starts jogging slowly in the park nearby.\n彼女は近くの公園でゆっくりジョギングを始めます。\n🥤 After running, she drinks water and feels better.\n走った後、彼女は水を飲んで元気になります。\n😊 Now Emma is stronger than she was last month.\n今、エマは先月よりも強くなりました。\n🌟 She has become a morning person finally!\nついに彼女は朝型人間になりました！\n\n🏡 Do you want to become healthier this year?\n今年はもっと健康になりたいですか？\n🏃‍♀️ Have you ever tried jogging in the morning?\n朝ジョギングをしたことがありますか？\n⏰ Is it difficult for you to wake up early?\n早起きすることは難しいですか？\n😴 What do you do when you feel tired?\n疲れた時何をしますか？\n💪 Do you have a goal this year?\n今年目標がありますか？\n🌳 Do you like exercising in parks?\n公園で運動するのは好きですか？\n🥤 How much water do you drink daily?\n毎日水をどれくらい飲みますか？\n😊 Do you feel happy when you achieve goals?\n目標を達成すると幸せですか？\n🌟 Are you a morning person or night person?\n朝型ですか夜型ですか？\n🏡 What healthy habit do you want to start?\nどんな健康習慣を始めたいですか？"
  },
  {
    "title": "2. Kenta's Helpful Weekend (Passive Voice / Adverbs)",
    "content": "🧹 Kenta wants to help his busy parents this weekend.\nケンタは今週末、忙しい両親を手伝いたいです。\n🍽️ He decides to wash the dishes after dinner.\n彼は夕食後に皿を洗うことにします。\n😱 But he drops his mother's favorite plate!\nしかし、彼は母のお気に入りの皿を落としてしまいます！\n💔 The plate is broken into many pieces.\n皿は多くの破片に割れてしまいました。\n😰 Kenta feels terrible and thinks his mom will be angry.\nケンタは最悪な気分になり、母が怒ると思います。\n🙏 However, his mother says, \"Thank you for trying to help.\"\nしかし、母は「手伝ってくれてありがとう」と言います。\n😊 She teaches him how to wash dishes carefully.\n彼女は彼に丁寧に皿を洗う方法を教えます。\n🧺 Now Kenta helps with laundry every weekend.\n今、ケンタは毎週末洗濯を手伝います。\n❤️ He feels proud when his parents thank him.\n両親がありがとうと言ってくれると彼は誇らしく思います。\n\n🧹 Do you help your parents at home?\n家で両親を手伝いますか？\n🍽️ Have you ever broken a dish?\n皿を割ったことがありますか？\n😱 How did you feel when you made a mistake?\nミスをした時どう感じましたか？\n🙏 Do your parents get angry easily?\nあなたの両親は簡単に怒りますか？\n😊 Who teaches you new things at home?\n家で新しいことを誰が教えてくれますか？\n🧺 What chores do you like doing?\nどんな家事が好きですか？\n❤️ How do you feel when someone thanks you?\n誰かにありがとうと言われるとどう感じますか？\n💪 What can you do to help your family?\n家族を助けるために何ができますか？\n🏠 Is your room usually clean or messy?\nあなたの部屋はいつもきれいですか、それとも散らかっていますか？\n🌟 What chore do you want to learn?\nどんな家事を学びたいですか？"
  },
  {
    "title": "3. Yui's Music Challenge (Gerunds / Infinitive)",
    "content": "🎵 Yui wants to join the school music club.\nユイは学校の音楽部に入りたいです。\n🎸 She is interested in playing the guitar.\n彼女はギターを弾くことに興味があります。\n😰 But learning guitar is harder than she expected.\nしかし、ギターを学ぶことは思っていたより難しいです。\n🖐️ Her fingers hurt from pressing the strings.\n弦を押さえるので彼女の指が痛くなります。\n😔 After one week, Yui thinks about quitting.\n1週間後、ユイは辞めることを考えます。\n👩‍🏫 However, her teacher says, \"Keep trying. You will improve.\"\nしかし、先生は「続けなさい。上手になるよ」と言います。\n📚 Yui practices the same song every day.\nユイは毎日同じ曲を練習します。\n🎶 After one month, she can play the song perfectly!\n1ヶ月後、彼女はその曲を完璧に弾けるようになります！\n🎉 Yui performs at the school festival with her club.\nユイはクラブの仲間と学校祭で演奏します。\n🌟 She is happy she didn't give up.\n彼女は諦めなかったことを嬉しく思います。\n\n🎵 Do you play any musical instruments?\n何か楽器を演奏しますか？\n🎸 Have you ever wanted to learn guitar?\nギターを習いたいと思ったことがありますか？\n😰 What is something difficult you have learned?\nあなたが学んだ難しいことは何ですか？\n🖐️ Have you ever wanted to quit something?\n何かを辞めたいと思ったことがありますか？\n👩‍🏫 Does a teacher encourage you sometimes?\n先生は時々あなたを励ましてくれますか？\n📚 Do you practice something every day?\n毎日何かを練習しますか？\n🎶 What song do you like listening to?\nどんな曲を聴くのが好きですか？\n🎉 Have you ever performed in front of people?\n人の前で演奏したことがありますか？\n🌟 What do you want to learn this year?\n今年何を学びたいですか？\n🎵 Which instrument do you think is hardest?\nどの楽器が一番難しいと思いますか？"
  },
  {
    "title": "4. Daiki's Speech Challenge (Superlative / Adjectives)",
    "content": "🗣️ Daiki has to give a speech tomorrow in English class.\nダイキは明日の英語クラスでスピーチをします。\n📝 He wants to give the best speech in his class.\n彼はクラスでいちばん良いスピーチをしたいです。\n😰 But he is very nervous about speaking in public.\nしかし、人前で話すことがとても緊張します。\n📖 He practices his speech in front of the mirror every night.\n毎晩、彼は鏡の前で練習します。\n⏰ The speech must be exactly three minutes long.\nスピーチはちょうど3分である必要があります。\n💪 His teacher tells him to speak slowly and clearly.\n先生はゆっくりとはっきり話すように言います。\n🎤 On the big day, Daiki takes a deep breath.\n当日、ダイキは深呼吸をします。\n🗣️ He speaks clearly and finishes his speech perfectly!\n彼ははっきり話して完璧に終わります！\n🎉 Everyone claps and says, \"That was the best speech!\"\n全員が拍手して「いちばん良いスピーチでした」と言います！\n🌟 Daiki feels proud and learns to face his fears.\nダイキは誇らしく感じ、恐怖に立ち向かうことを学びます。\n\n🗣️ Do you like speaking in front of people?\n人前で話すのは好きですか？\n📝 Have you ever given a speech?\nスピーチをしたことがありますか？\n😰 What makes you feel nervous?\n何があなたを緊張させますか？\n📖 Do you practice in front of a mirror?\n鏡の前で練習しますか？\n⏰ Can you speak for one minute without stopping?\n1分間止まらずに話せますか？\n💪 Has a teacher given you good advice?\n先生は良いアドバイスをくれたことがありますか？\n🎤 Do you take deep breaths when you are nervous?\n緊張する時、深呼吸をしますか？\n🗣️ What topic would you choose for a speech?\nスピーチのトピックに何を選びますか？\n🎉 Have you ever received applause for something?\n何かで拍手されたことがありますか？\n🌟 What fear do you want to overcome?\nどんな恐怖を乗り越えたいですか？"
  },
  {
    "title": "5. Haruka's Part-Time Job (Relative Clause / SVOO)",
    "content": "☕ Haruka needs money to buy a new smartphone.\nハルカは新しいスマホを買うためにお金が必要です。\n📅 She finds a part-time job at a cafe near the station.\n彼女は駅の近くのカフェでアルバイトを見つけます。\n😰 But working on weekends is very tiring.\nしかし、週末に働くことはとても疲れます。\n👔 She must be polite to every customer.\n彼女はお客様全員に親切でなければなりません。\n💪 However, she works hard and saves money.\nしかし、彼女は一生懸命働いてお金を貯めます。\n😊 The manager gives her free coffee after work.\n店長は仕事の後に無料のコーヒーをくれます。\n🤝 Haruka makes friends with her co-workers.\nハルカは同僚と友達になります。\n🌟 She learns the value of hard work.\n彼女は一生懸命働くことの価値を学びます。\n\n☕ Do you want a part-time job?\nアルバイトをしたいですか？\n📅 How do you spend your weekends?\n週末をどう過ごしますか？\n😰 What is the most tiring thing for you?\nあなたにとって一番疲れることは何ですか？\n👔 Do you think being polite is important?\n親切であることは重要だと思いますか？\n💪 Do you save money for something special?\n何か特別なもののためにお金を貯めていますか？\n😊 Who gives you free things sometimes?\n誰が時々無料のことをくれますか？\n🤝 Is it easy to make new friends?\n新しい友達を作るのは簡単ですか？\n🌟 What have you learned from working?\n働いて何を学びましたか？\n☕ Do you prefer coffee or tea?\nコーヒーと紅茶、どちらが好きですか？\n💰 What do you want to buy with your own money?\n自分のお金で何を買いたいですか？"
  },
  {
    "title": "6. Satoshi's Grandparents Visit (Be going to / When clause)",
    "content": "🚅 Satoshi is going to visit his grandparents next week.\nサトシは来週、祖父母を訪ねる予定です。\n🏡 They live in a small village in the mountains.\n彼らは山の小さな村に住んでいます。\n👴 His grandfather grows vegetables in the garden.\n彼の祖父は庭で野菜を育てています。\n😰 But Satoshi has not seen them for one year.\nしかし、サトシは1年間会っていません。\n🍅 When Satoshi arrives, his grandmother will cook dinner.\nサトシが到着すると、祖母が夕食を作ります。\n🌟 The family eats together and talks about old times.\n家族が一緒に食べて昔話をします。\n😊 Satoshi feels happy to see his grandparents again.\nサトシは祖父母にまた会えて嬉しくなります。\n📸 He takes many photos to remember the day.\n彼はたくさんの写真を撮ります。\n\n🚅 How often do you visit your relatives?\nどのくらいの頻度で親戚を訪ねますか？\n🏡 Do your grandparents live near you?\n祖父母は近くに住んでいますか？\n👴 What does your grandfather do?\nお祖父さんは何をしますか？\n😰 Have you not seen someone for a long time?\n久しぶりに誰かに会っていませんか？\n🍅 What is your favorite vegetable?\n一番好きな野菜は何ですか？\n🌟 Do you like eating with your family?\n家族と一緒に食べるのは好きですか？\n😊 Who are you happy to see?\n会えて嬉しい人は誰ですか？\n📸 Do you like taking photos?\n写真を撮るのは好きですか？\n🏞️ Do you prefer the city or the countryside?\n都会と田舎、どちらが好きですか？\n🌙 What did you do on your last visit?\n前の訪問で何をしたか教えてください。"
  },
  {
    "title": "7. Mei's Study Abroad Dream (If clause / Auxiliaries)",
    "content": "✈️ Mei dreams of studying in Canada one day.\nメイはいずれカナダで勉強する夢があります。\n📚 To achieve her dream, she must study English hard.\n夢を達成するために、彼は英語を勉強する必要があります。\n😰 But English is very difficult for her.\nしかし、英語は彼女にとってとても難しいです。\n📺 She watches English movies to improve her listening.\n彼女はリスニング向上のため英語映画を見ます。\n💰 However, studying abroad costs a lot of money.\nしかし、留学はお金がとてもかかります。\n🗣️ If she studies hard, she will get a scholarship.\n一所懸命勉強したら、奨学金をもらえるでしょう。\n🤝 She wants to make friends from different countries.\n彼女はさまざまな国の友達を作りたいです。\n🌟 Mei believes her dream will come true.\nメイは夢が叶うと信じています。\n\n✈️ Do you want to study abroad?\n留学をしたいですか？\n📚 Why do you study English?\nなぜ英語を勉強しますか？\n😰 What is difficult for you in English?\n英語の中で難しいことは何ですか？\n📺 What English movies have you watched?\nどんな英語映画を見ましたか？\n💰 Is it important to save money for the future?\n将来のためにお金を貯めることは重要ですか？\n🗣️ Would you like to stay with a host family?\nホストファミリーと一緒に泊まりたいですか？\n🤝 Do you have friends from other countries?\n他の国の友達がいますか？\n🌟 What is your biggest dream?\n一番大きな夢は何ですか？\n🗺️ What country do you want to visit?\nどの国を訪れたいですか？\n📖 Do you read books in English?\n英語をんで本を読みますか？"
  },
  {
    "title": "8. Ryo's New Blog (Present Perfect Continuous / Adjectives)",
    "content": "💻 Ryo has been writing a blog for three months.\nリョウは3ヶ月間ブログを書いています。\n📝 He writes about his daily life and hobbies.\n彼は日常生活と趣味について書きます。\n😰 But nobody reads his blog at first.\nしかし最初は誰もブログを読みません。\n🌐 He feels sad and thinks about stopping.\n彼は悲しく、止めるを考えます。\n📈 After one month, people start leaving comments.\n1ヶ月後、人々はコメントを残すようになります。\n😊 Ryo is happy when people say his blog is funny.\n人々がブログ面白いというとリョウは嬉しいです。\n🚀 He wants to become a famous blogger someday.\nいつか有名なブロガーになりたいです。\n\n💻 Do you read blogs or websites often?\nよくブログやウェブサイトを読みますか？\n📝 Do you keep a diary?\n日記をつけていますか？\n😰 What do you do when nobody notices your work?\n誰も気づいてくれなかった時どうしますか？\n🌐 Have you ever written a comment on a video?\n動画にコメントを書いたことがありますか？\n📈 How do you feel when people like your work?\n人々があなたの作品を好きだとどう感じますか？\n😊 What makes you feel excited?\n何興奮させますか？\n🚀 Do you want to be famous?\n有名になりたいですか？\n📱 What kind of things do you post online?\nオンラインでどんなことを投稿しますか？\n👀 How much time do you spend on the internet?\nインターネットに费等時間を過ごしますか？"
  },
  {
    "title": "9. Koki's Sports Day Training (Because / Comparative)",
    "content": "🏃‍♂️ Koki trains hard because Sports Day is coming.\n運動会が近づいたので、コウキはハードにトレーニングします。\n🥇 He wants to win the 100-meter race.\n彼は100メートル走で勝ちたいです。\n😰 But he is not the fastest runner in his class.\nしかし、彼はクラスでいちばん速くないです。\n💪 He practices running every morning instead of sleeping.\n彼は寝る代わり每天朝練習します。\n👟 He buys new running shoes to run faster.\n彼は速く走るために新しい靴を買います。\n🎉 On Sports Day, Koki runs very fast!\n運動会当日、コウキはとても速く走ります！\n🏅 He wins second place and feels proud!\n彼は2位になって自豪感を持ちます！\n\n🏃‍♂️ Do you like Sports Day?\n運動会が好きですか？\n🥇 Have you ever won a prize or medal?\n賞やメダルを取得したことがありますか？\n😰 What do you do when you are not good at something?\n何かすることに詳しくない時どうしますか？\n💪 Do you practice something every day?\n毎日何かを練習しますか？\n👟 What sports do you like?\nどんなスポーツが好きですか？\n🎉 Do your friends cheer for you?\n友達が応援してくれますか？\n🏅 Do you feel proud when you win?\n勝つと自豪感を持ちますか？\n💪 Do you do any muscle training?\n筋力トレーニングをしますか？\n🌟 Do you think winning is the most important thing?\n勝つのが一番大事だと思いますか？\n👟 What brand of shoes do you like?\nどのブランドの靴が好きですか？"
  },
  {
    "title": "10. Hana's Group Project (Make + Object + Adjective)",
    "content": "🧪 Hana works on a science project with her group.\nハナはグループで科学プロジェクトに取り組みます。\n🎨 They decide to make a poster about space.\n彼らは宇宙についてのポスターを作ることにします。\n✂️ Hana is good at drawing, so she draws the pictures.\nハナは絵が得意なので、彼女が絵を描きます。\n😠 However, one boy does not do his work.\nしかし、男子一人が仕事をしません。\n🤔 The other group members get angry and frustrated.\n他のメンバーが怒って困ります。\n🗣️ They talk to the boy and ask for help.\n彼らは男子に話して助けてもらいます。\n📄 Together, they finish the poster in time.\n一緒に、時間通りにポスターを仕上げます。\n👩‍🏫 The teacher praises their teamwork.\n先生は彼らのチームワークを褒めます。\n🌟 Hana learns that communication solves problems.\nハナはコミュニケーションが問題を解決することを知ります。\n\n🧪 Do you like science class?\n理科の授業は好きですか？\n🎨 Are you good at drawing?\n絵を描くのは得意ですか？\n✂️ Have you ever made a poster?\nポスターを作ったことがありますか？\n😠 What makes you angry?\n何怒させますか？\n🤔 How do you solve problems with friends?\n友達とどう問題を解決しますか？\n🗣️ Do you talk to people when you have problems?\n問題がある時、人と話しますか？\n📄 Do you finish your work on time?\n時間通りに仕上げられますか？\n👩‍🏫 Do you like working in groups?\nグループで作業するのは好きですか？\n🌟 What have you learned from group work?\nグループ作業から何を学びましたか？\n🤝 Is teamwork important?\nチームワークは重要ですか？"
  },
  {
    "title": "11. Yuna's School Festival Preparation (Passive Voice / Be covered with)",
    "content": "🎪 Yuna helps prepare for the school festival.\nユナは学園祭の準備を手伝います。\n🎨 Her class decides to make an art gallery.\n彼女のクラスはアートギャラリーを作ることにします。\n🖼️ They cover the walls with colorful papers.\n彼らは壁をカラフルな紙で覆います。\n😰 But they only have two hours to finish.\nしかし、仕上げるのに2時間しかないので大変です。\n🧹 Everyone works together to clean and decorate.\nみんなが一緒に掃除して飾ります。\n😊 Yuna paints beautiful pictures with her friends.\nユナは友達と、美しい絵を描きます。\n📸 Many photos are taken during the festival.\n学園祭の間、多くの写真が撮られます。\n🌟 Everyone enjoys the art gallery and compliments Yuna.\nみんながアートギャラリーを楽しんでユナを褒めます。\n\n🎪 Do you like school festivals?\n学園祭が好きですか？\n🎨 What did your class do for the festival?\nあなたのクラスは学園祭で何をしましたか？\n🖼️ Are you good at decorating?\n飾るのが得意ですか？\n😰 Do you work well under pressure?\n压力下で仕事ができますか？\n🧹 Do you help clean your classroom?\n教室の掃除を手伝いますか？\n😊 What do you paint?\n何を描きますか？\n📸 Do you take photos at school events?\n学校のイベントで写真を撮りますか？\n🌟 Do you feel proud of your work?\n自分の作业に自豪感を持ちますか？\n🎭 Do you prefer watching shows or doing them?\nを見ると好むか、するの好む？\n🏫 What is your favorite school event?\n一番好きな学校イベントは何ですか？"
  },
  {
    "title": "12. Takumi's Aquarium Trip (Look + Adjective / Interested in)",
    "content": "🐟 Takumi visits an aquarium with his family.\nタクミは家族と水族館を訪れます。\n🦈 He is surprised to see huge sharks swimming.\n彼は巨大なサメが泳ぐのを見て驚きます。\n🐬 The dolphin show is the most exciting part.\nイルカショー刺激的です。\n😰 But Takumi cannot see the dolphins clearly.\nしかしタクミはイルカ見えづらい。\n📷 He takes photos but they are blurry.\n彼は写真を撮りますがぼやけます。\n😊 After the show, he gets to touch the dolphins!\nショーの後、イルカに触れます！\n🐠 Takumi learns about many different sea animals.\nタクミは多くの異なる海の動物について学びます。\n🌟 He wants to become a marine biologist.\n彼は海洋生物学者になりたいです。\n\n🐟 Do you like aquariums?\n水族館が好きですか？\n🦈 Which sea animal do you like best?\n一番好きな海の動物は何ですか？\n🐬 Have you ever seen a dolphin show?\nイルカショーを見たことがありますか？\n😰 What do you do when you cannot see well?\n見えらい時どうしますか？\n📷 Do you like taking photos?\n写真を撮るのは好きですか？\n😊 Have you ever touched an animal?\n動物を触ったことがありますか？\n🐠 What have you learned from visiting aquariums?\n水族館訪問から何を学びましたか？\n🌟 What do you want to be in the future?\n将来何になりたいですか？\n🏊 Can you swim?\n泳げますか？\n🌊 Do you like the ocean or mountains more?\n海と山どちらが好きですか？"
  },
  {
    "title": "13. Miki's Cooking Challenge (How to... / Give + Person + Thing)",
    "content": "🍳 Miki wants to learn how to cook.\nミキは料理を習いたいです。\n👩‍🍳 Her mother teaches her how to make miso soup.\n母は彼女に味噌汁の作り方を教えます。\n🔪 But cutting vegetables is harder than she thought.\nでも、野菜を切ることは思ったより難しいです。\n😰 She cuts her finger and feels scared.\n彼女は指を切って怖くなります。\n🩹 Her mother gives her a bandage and says it is okay.\n母は絆創膏をくれて、大丈夫だと言います。\n💪 Miki tries again and cooks curry for her family.\nミキはもう一度挑戦して、家族のためにカレーを作ります。\n😊 Her father says it is delicious!\n父は美味しいと言います！\n🌟 Miki feels proud of her first dish.\nミキは初めての料理を誇らしく思います。\n\n🍳 Do you cook at home?\n家で料理をしますか？\n👩‍🍳 Who teaches you how to cook?\n誰が料理を教えてくれますか？\n🔪 Have you ever cut your finger?\n指を切ったことがありますか？\n😰 What do you do when you feel scared?\n怖い時何をしますか？\n🩹 Do you have a bandage at home?\n家に絆創膏はありますか？\n💪 Do you try again when you fail?\n失敗した時、もう一度挑戦しますか？\n😊 What is your favorite dish?\n一番好きな料理は何ですか？\n🌟 Do you feel proud when you cook?\n料理をすると誇らしく感じますか？\n🍛 Can you make curry?\nカレーを作れますか？\n👨‍👩‍👧 Who cooks dinner in your family?\n家族では誰が夕食を作りますか？"
  },
  {
    "title": "14. Ayaka's Rainy Day (Present Perfect Continuous / Stop -ing)",
    "content": "🌧️ It has been raining since this morning.\n今朝から雨が降り続いています。\n🏠 Ayaka wanted to go shopping.\nアヤカは買い物に行きたかったです。\n😔 But she stopped thinking about going out.\nでも、外出することを諦めました。\n📚 She started reading a new book instead.\nその代わり、新しい本を読み始めました。\n☕ Drinking hot tea makes her feel warm.\n温かいお茶を飲むと、温かい気分になります。\n🎧 She enjoys listening to quiet music.\n静かな音楽を聴くのを楽しんでいます。\n😴 The sound of rain makes her sleepy.\n雨の音で眠くなります。\n📞 She talked with her friend for an hour.\n友達と1時間電話をしました。\n🌈 Tomorrow, the weather will be sunny.\n明日は晴れるでしょう。\n\n🌧️ Do you like rainy days?\n雨の日は好きですか？\n🏠 What do you do on rainy days?\n雨の日は何をしますか？\n📚 Do you read books at home?\n家で本を読みますか？\n☕ What is your favorite hot drink?\n一番好きな温かい飲み物は何ですか？\n🎧 Do you listen to music when you study?\n勉強する時、音楽を聴きますか？\n😴 Do you take naps on weekends?\n週末に昼寝をしますか？\n📞 Who do you talk to on the phone?\n誰と電話で話しますか？\n🌈 Which season do you like best?\nどの季節が一番好きですか？\n☔ Do you carry an umbrella?\n傘を持ち歩きますか？\n😊 Do you feel happy when you stay home?\n家にいると幸せですか？"
  },
  {
    "title": "15. Shun's Violin Challenge (Comparative / Want to be)",
    "content": "🎻 Shun practices violin every day after school.\nシュンは放課後毎日バイオリンを練習します。\n🏠 He practices in his room for two hours daily.\n彼は毎日自分の部屋で2時間練習します。\n😰 Playing violin is harder than playing the piano.\nバイオリンを弾くのはピアノより難しい。\n🌈 However, he loves the beautiful violin sound.\nでも、バイオリンの美しい音が大好き。\n👨‍👩‍👦 His parents always encourage him.\n両親はいつも彼を励ましてくれます。\n🏆 Shun wants to be a professional musician.\nシュンはプロの音楽家になりたい。\n📅 Next month, he has an important concert.\n来月、大事なコンサートがあります。\n🎵 He has memorized all the notes for the song.\nその曲の音符を全部暗記しました。\n😊 After the concert, Shun feels very happy.\nコンサート後、シュンはとても幸せです。\n\n🎻 Have you ever played violin?\nバイオリンを弾いたことは？\n🎶 Is it difficult to read music?\n楽譜を読むのは難しいか？\n🎼 Do you prefer classical or pop music?\nクラシックとポップ、どちら？\n👨‍👩‍👦 Do your parents support you?\n両親は後押ししてくれるか？\n🏆 What do you want to be in the future?\n将来何になりたいですか？\n📅 Do you get nervous before concerts?\nコンサート前緊張するか？\n🎵 Can you sing a song in English?\n英語で歌えますか？\n🏠 Where do you study or practice?\nどこで練習しますか？\n😊 What makes you feel proud?\n誇らしく思うのは何か？\n🌟 What is your favorite musician?\n好きな音楽家は？"
  },
  {
    "title": "16. Riku's Park Cleanup (Passive Voice / Be glad to)",
    "content": "🌳 Riku joined a volunteer group last Saturday.\nリクは先週土曜にボランティアに参加した。\n🧤 They went to the local park to clean up trash.\n近くの公園をゴミ拾いに行った。\n😱 Many plastic bottles were found under benches.\nベンチの下にペットボトルが大量発見。\n😰 Riku thought it would take too much time.\n時間がかかるとリクは思った。\n💪 However, everyone worked together efficiently.\nでも、みんなが効率的に作業した。\n👴 An old man said, 'Thank you for your hard work.'\nお年寄りが「ありがとう」と言ってくれた。\n😊 Riku was glad to hear kind words.\n親切な言葉を聞けて嬉しかった。\n🌿 Now the park looks very clean.\n今、公園はとてもきれいに見える。\n🌟 Riku decided to join again next month.\nリクは来月も参加することに決めた。\n\n🌳 Have you done volunteer work?\nボランティア活動したことある？\n😱 Have you ever seen too much trash?\nゴミが多すぎる場面を見たことが？\n💪 Do you like working with a team?\nチームで働くのは好きか？\n👴 Did someone thank you recently?\n最近誰かに「ありがとう」と言われた？\n🧤 Do you mind getting dirty?\n汚れるのを気にする？\n🌿 Do you like clean environments?\nきれいな環境は好きですか？\n🗑️ Do you separate trash correctly?\nゴミを正しく分別する？\n😊 When did someone help you?\n誰かに助けられたのはいつ？\n🌟 Would you volunteer again?\nまたボランティア活動に興味ある？"
  },
  {
    "title": "17. Saki's Long Phone Call (Enjoy -ing / Adverbial clauses)",
    "content": "📱 Saki called her cousin in Tokyo last night.\n昨夜、Sakiは東京のいとこに電話した。\n🏙️ She talked about her new high school life.\n新しい高校生活について話した。\n😱 Saki was surprised Tokyo is so crowded.\n東京がこんなに混んでると驚いた。\n⌛ They talked for more than two hours!\n2時間以上も話した！\n😢 It was already midnight when they finished.\n終わった時は真夜中になっていた。\n😌 Saki felt time flies when enjoying conversation.\n楽しく話すと時間経つのが早いと感じた。\n📧 They promised to message each other often.\n頻繁にメッセージを送り合うことにした。\n😴 The next morning, Saki was a little sleepy.\n翌朝、Sakiは少し眠かった。\n🌟 Keeping in touch with family is important to her.\n家族と連絡を取り合うことは彼女にとって大事。\n\n📱 Who do you like talking to most?\n誰と一番話すのが好き？\n🏙️ Do you want to live in a big city?\n大都市に住みたいですか？\n⌛ What's your longest phone call?\n一番長い電話はどれくらい？\n😱 Have you been surprised by something?\n何かに驚いたことがある？\n😌 Does time fly when you study?\n勉強する時、早く経つか？\n😴 Do you usually wake up early?\n普段は早起きする？\n😢 Are you sleepy right now?\n今眠いですか？\n📧 Do you use messaging apps daily?\n毎日メッセージアプリを使う？\n😌 Do you enjoy long conversations?\n長い話を楽しむか？\n😴 How do you feel when you don't sleep enough?\n眠り不足の時どう感じる？"
  },
  {
    "title": "18. Haru's Museum Visit (Be interested in / Passive)",
    "content": "🏛️ Haru visited the history museum with his class.\nハルはクラスで歴史博物館を訪問した。\n📖 He is interested in Japanese culture.\n彼は日本文化に興味がある。\n🏺 But the museum was built 100 years ago.\nでも、博物館は100年前に建てられた。\n👀 They looked at old tools and clothes.\n古い道具と服を見た。\n😰 Haru wondered how people lived long ago.\n昔の人々がどう暮らしていたか不思議に思った。\n📸 Taking photos was allowed in some rooms.\nいくつかの部屋では写真が許可されていた。\n😊 Haru learned many new things about his city.\n彼は自分の街について新しいことを学んだ。\n🌟 Haru wants to visit again with his family.\nハルは家族とまた訪れたいと思った。\n\n🏛️ Do you like history?\n歴史は好きですか？\n🏺 Do you like visiting museums?\n博物館を訪問するのは好き？\n📖 What old things do you have at home?\n家に古いものはある？\n👀 What do you like looking at most?\n何を一番見るのが好き？\n😰 What do you wonder about?\n何について不思議に思う？\n📸 Do you follow rules in public places?\n公共の場でルールを守る？\n😊 Have you been surprised by something lately?\n最近何かに驚いたことはある？\n🌟 What museums have you visited before?\n前に訪問した博物館はどこ？\n🏯 Do you like visiting old temples or shrines?\n古い寺や神社を訪問するのは好き？\n📚 What do you learn from school trips?\n学校訪問から何を学ぶか？"
  },
  {
    "title": "19. Aya's New Writing Club (Relative pronoun / Try to)",
    "content": "📝 Aya loves writing stories and poems.\nアヤは物語や詩を書くのが大好き。\n🏫 She decided to start a Creative Writing Club.\n創作ライティング部を始めることにした。\n😰 She needed five members to start the club.\n部を始めるには5人必要だった。\n🗣️ She talked to friends who like reading.\n本を読むのが好きな友達に話した。\n📄 They made posters to advertise their club.\n彼らは部を宣伝するポスターを作った。\n😊 Luckily, six students joined the club!\n運良く、6人生徒が入部した！\n✍️ Now they try to write a short story weekly.\n今、彼らは毎週短い物語を書いている。\n📚 They read each other's stories and share comments.\n互いの物語を読んでコメントを共有する。\n🌟 Aya is happy she has friends with same hobby.\nアヤは同じ趣味の友達がいて幸せ。\n\n📝 Do you like writing?\n書くのは好き？\n🏫 Does your school have many clubs?\n学校にクラブはいくつある？\n👥 If you started a club, what kind?\nクラブを作るならどんなの？\n🗣️ Are you good at asking for help?\n助けを求めるのは得意？\n📄 Do you know how to make posters?\nポスターの作り方知ってる？\n✍️ Have you ever written a story?\n物語を書いたことある？\n📚 What is your favorite book genre?\n好きな本のジャンルは？\n🌟 Do you share hobbies with friends?\n友達と趣味を共有してる？\n🚀 What is your dream job?\n夢の仕事は何？\n😊 Are you a leader or follower?\nリーダーとフォロワーどっち？"
  },
  {
    "title": "20. Ken's Busy Morning (Too... to... / Be late for)",
    "content": "⏰ Ken overslept this morning because alarm didn't ring.\n今朝、ケンが目覚ましが鳴らず寝坊した。\n😱 He was too shocked to move for a moment.\nショックで少しの間動けなかった。\n🍞 He didn't have time to eat breakfast.\n朝食を食べる時間がなかった。\n🏃‍♂️ He ran to station as fast as he could.\nできるだけ速く駅まで走った。\n🚋 However, he missed the train he usually takes.\nでも、いつもの電車を逃した。\n😰 He was worried about being late for school.\n学校に遅刻するか心配だった。\n📱 He sent a message saying he might be late.\n遅れるかもしれないとメッセージした。\n🏫 Luckily, he arrived at school gate just in time.\n運良く、学校の門にギリギリ着いた。\n💨 He was very tired and out of breath.\n彼はとても疲れて息切れしていた。\n🌟 Ken decided to go to bed earlier tonight.\nケンは今夜もっと早く寝ると決めた。\n\n⏰ Do you use an alarm clock?\n目覚まし時計を使う？\n😱 Have you ever overslept on important day?\n大事な日に寝坊したことは？\n🍞 Do you eat breakfast every day?\n毎日朝食を食べる？\n🏃‍♂️ Are you a fast runner?\n速く走れる？\n🚋 How do you go to school?\n学校にどうやって行く？\n😰 What do you do when late?\n遅刻した時どうする？\n📱 Do you text friends often?\nよく友達にメッセージする？\n🏫 What time does first class start?\n最初の授業は何時から？\n💨 Do you get tired easily?\n疲れやすい？\n🌟 What time do you usually sleep?\n普段何時に寝る？"
  },
  {
    "title": "21. Haruka's Library Visit (Present Perfect / Recommend)",
    "content": "📚 Haruka has visited school library many times this month.\nハルカは今月何度も学校図書館を訪問した。\n📖 She likes reading mystery novels very much.\n彼女はミステリー小説がとても好き。\n👩‍🏫 The librarian recommended a famous book to her.\n司書が彼女に有名な本を勧めてくれた。\n🔍 The story is about a detective solving cases.\nその話は事件を解決する探偵の話。\n🤔 Reading books makes her think deeply.\n本を読むことは彼女に深く考えさせる。\n📝 She has written a book report for Japanese class.\n彼女は国語のために読書感想文を書いた。\n🤫 You must be quiet when in the library.\n図書館にいる時は静かにしなければならない。\n🤝 Haruka often borrows books friends like.\nハルカはよく友達が好きな本を借りる。\n🌟 She thinks libraries are wonderful places.\n彼女は図書館は素晴らしい場所だと思う。\n📅 She plans to read ten books during summer vacation.\n夏休みに10冊読む計画。\n\n📚 Do you go to library often?\n図書館によく行く？\n📖 What was last book you read?\n最後に読んだ本は？\n👩‍🏫 Do you ask teachers for advice?\n先生にアドバイスを求める？\n🔍 Do you like mystery movies or books?\nミステリー映画か本は好き？\n🤔 Do you like thinking about puzzles?\nパズルを考えるのは好き？\n📝 Have you written book report recently?\n最近読書感想文を書いた？\n🤫 Can you stay quiet for long time?\n長い間静かにしていられる？\n🤝 Do you lend books to friends?\n友達に本を貸す？\n🌟 What is favorite place in school?\n学校でお気に入りの場所は？\n📅 How many books do you read in a year?\n1年に何冊本を読む？"
  },
  {
    "title": "22. Yui's New Pet (Take care of / Adjective)",
    "content": "🐱 Yui's family got a new kitten yesterday.\nユイの家族は昨日新しい子猫を飼った。\n😊 The kitten is very cute and playful.\nその子猫はとても可愛くて遊び好き。\n😰 But taking care of it is hard work.\nでも、世話をするのは大変。\n🍚 Yui must feed it every morning and night.\nユイは毎朝と夜に餌をあげなければならない。\n🧹 She must clean the litter box daily.\n彼女は毎日猫砂を掃除しなければならない。\n😴 Sometimes the kitten wakes her up early.\n時々、子猫が彼女を早くに起こす。\n💪 However, Yui loves her new pet very much.\nでも、ユイは新しいペットが大好き。\n🐾 The kitten follows her everywhere she goes.\n子猫は彼女の行く所どこでもついてくる。\n🌟 Yui learned responsibility from this experience.\nユイはこの経験から責任を学んだ。\n\n🐱 Do you have a pet at home?\n家にペットはいる？\n😊 What pet do you like best?\nどのペットが一番好き？\n😰 Is it hard to take care of pets?\nペットの世話は大変？\n🍚 What do pets need every day?\nペットは毎日何が必要？\n🧹 Do you clean up after your pet?\nペットの後片付けをする？\n😴 Does your pet wake you up early?\nペットは早くに起こす？\n💪 Do you like animals?\n動物は好き？\n🐾 Do you want to have a pet?\nペットを飼いたい？\n🌟 What have you learned from pets?\nペットから何を学んだ？\n🏠 Is your house good for pets?\n家はペットに向いてる？"
  },
  {
    "title": "23. Kenji's Class Debate (Agree/Disagree with / Opinion)",
    "content": "🗣️ Kenji's class had a debate today.\n今日のケンジのクラスで討論があった。\n📚 The topic was about school uniforms.\nトピックは学校の制服について。\n😰 Kenji was nervous to speak in front.\nケンジは前で話すのが緊張した。\n💭 He disagreed with wearing uniforms daily.\n彼は毎日制服を着るのに反対した。\n🗣️ However, his friend agreed with uniforms.\nでも、彼の友達は制服に賛成した。\n🤝 They listened to each other's opinions carefully.\n彼らは互いの意見に注意深く耳を傾けた。\n😊 The teacher said both sides had good points.\n先生は両方の意見に良い点があると言った。\n🌟 Kenji learned it's okay to disagree politely.\nケンジは礼儀正しく反対しても良いと学んだ。\n\n🗣️ Do you like speaking in front of class?\nクラスの前で話すの好き？\n📚 What topic would you debate?\nどんなトピックを討論する？\n😰 What makes you nervous?\n何が緊張させる？\n💭 Do you agree with school uniforms?\n学校の制服に賛成？\n🤝 Do you listen to others' opinions?\n他人の意見に耳を傾ける？\n😊 Is it okay to disagree?\n反対してもいい？\n📚 What is your opinion on homework?\n宿題についての意見は？\n🌟 Have you ever changed your opinion?\n意見を変えたことは？\n🗣️ Do you like debates?\n討論は好き？\n💭 What is your strongest opinion?\n一番強い意見は？"
  },
  {
    "title": "24. Rina's Snowy Day (So... that... / It is [adjective] to...)",
    "content": "❄️ It snowed heavily last night.\n昨夜大雪が降った。\n🌨️ The garden was covered with white snow.\n庭は白い雪に覆われた。\n😰 It was so cold that Rina stayed inside.\nとても寒かったのでリナは中にいた。\n☕ She drank hot chocolate to feel warm.\n温かく感じるためホットチョコを飲んだ。\n🧤 Her mother made her wear thick clothes.\n母は彼女に厚着をさせた。\n⛄ Rina wanted to make a snowman outside.\nリナは外で雪だるまを作りたかった。\n😊 After an hour, the sun came out.\n1時間後、太陽が出てきた。\n🌟 It is fun to play in the snow.\n雪の中で遊ぶのは楽しい。\n⭐ Rina went outside and made a big snowman!\nリナは外に出て大きな雪だるまを作った！\n\n❄️ Do you like snowy days?\n雪の日は好き？\n🌨️ Have you ever made a snowman?\n雪だるまを作ったことは？\n😰 Are you afraid of cold weather?\n寒い天気は怖い？\n☕ What is your favorite hot drink?\n好きな温かい飲み物は？\n🧤 Do you wear gloves in winter?\n冬は手袋をする？\n⛄ Do you like winter sports?\n冬のスポーツは好き？\n😊 Do you play in the snow?\n雪で遊ぶ？\n🌟 What is your favorite season?\n好きな季節は？\n❄️ Is it fun to play outside in snow?\n雪で外で遊ぶのは楽しい？\n☕ Do you prefer hot or cold drinks?\n温かいか冷たい飲み物どっちが好き？"
  },
  {
    "title": "25. Toms Test Challenge (Help + Person + Verb)",
    "content": "📝 Tom's big math test is next week.\nトムの大きな数学のテストは来週。\n😰 But Tom struggles with algebra problems.\nでも、トムは代数問題に苦戦しています。\n👨 His older sister helps him understand.\n彼の姉が理解できるよう助けてくれます。\n📚 Tom studies as hard as he can.\nトムはできる限り一生懸命勉強します。\n🎯 On the test day Tom feels nervous.\nテストの当日、トムは緊張します。\n😊 However he remembers what his sister taught.\nでも、姉が教えてくれたことを思い出します。\n📊 Tom solves the problems correctly.\nトムは問題を正しく解きます。\n🏆 He gets a good score on his test!\nテストで良い点数を取ります！\n\n📝 Do you have big tests at school?\n学校で大きなテストはありますか？\n😰 What subject is hardest for you?\n一番難しい科目は何ですか？\n👨 Does anyone help you study?\n誰かが勉強を手伝ってくれますか？\n📚 Do you study hard every night?\n毎晩一生懸命勉強しますか？\n🎯 Do you feel nervous before tests?\nテストの前に緊張しますか？\n😊 Who encourages you?\n誰が励ましてくれますか？\n📊 Are you good at solving problems?\n問題を解くのは得意ですか？\n🏆 Have you gotten a good score recently?\n最近良い点数を取りましたか？\n🌟 What helps you study?\n何が勉強の助けになりますか？"
  },
  {
    "title": "26. Ryos Beach Day (Look/Sound/Feel + Adjective)",
    "content": "🏖️ Ryo visits the beach on a sunny day.\nリョウは晴れた日に海を訪れます。\n🌊 The water looks very blue and beautiful.\n海水はとても青くて美しいです。\n🎵 Ryo loves the sound of ocean waves.\nリョウは波の音が大好きです。\n😰 But the sun is very hot today.\nでも、今日は太陽がとても暑いです。\n🧢 Ryo wears a hat to protect himself.\nリョウは身を守るために帽子をかぶります。\n😊 He feels much better in the shade.\n彼は日陰でもっと気分が良くなります。\n🏖️ Ryo plays in the sand all day.\nリョウは一日中砂で遊びます。\n🌟 The day at the beach is wonderful!\n海での日は素晴らしいです！\n\n🏖️ Do you like going to the beach?\n海に行くのは好きですか？\n🌊 What does the ocean look like near you?\n近くの海はどんな様子ですか？\n🎵 Do you like the sound of waves?\n波の音は好きですか？\n😰 What do you do when it is hot?\n暑い時何をしますか？\n🧢 Do you wear a hat outside?\n外で帽子をかぶりますか？\n😊 What makes you feel better?\n何が気分を良くしてくれますか？\n🏖️ Do you play in the sand?\n砂で遊びますか？\n🌟 What is your favorite beach activity?\n好きな海での活動は何ですか？"
  },
  {
    "title": "27. Mios Birthday Gift (Give + Person + Thing)",
    "content": "🎁 Mios grandmothers birthday is soon.\nミオの祖母の誕生日がすぐです。\n🧥 Mio chooses a red scarf for her.\nミオは赤いマフラーを選びました。\n😊 Grandmother looks happy when she opens it.\n祖母は受け取ると嬉しそうです。\n🌟 Mio feels proud to give a gift.\nミオは贈り物をあげられて誇らしく思います。\n\n🎁 When is your grandmothers birthday?\n祖母の誕生日はいつですか？\n😢 What gifts do you give to grandmothers?\n祖母にどんな贈り物をあげますか？\n👨 Does your grandmother live near you?\n祖母は近くに住んでいますか？\n🧥 Does your grandmother like warm clothes?\n祖母は暖かい服が好きですか？\n😊 Does your grandmother smile easily?\n祖母はよく笑いますか？\n❤️ Do you feel happy when you give gifts?\n贈り物をあげると幸せですか？"
  },
  {
    "title": "28. Takumis Basketball Challenge (Be good at)",
    "content": "⛹️ Takumi wants to try basketball.\nタクミはバスケボールを試したいです。\n🏀 But he is not good at shooting.\nでもシュートが得意ではありません。\n😰 He misses many shots at first.\n最初は多くのシュートを外します。\n💪 His coach says to practice.\nコーチは練習しなさいと言います。\n📅 Takumi practices every weekend.\nタクミは毎週末練習します。\n😊 After two months he improves.\n2ヶ月後に上達しました。\n🌟 Takumi learns practice is important.\nタクミは練習が大切だと学びました。\n\n⛹️ Do you like basketball?\nバスケボールは好きですか？\n🏀 What sport do you want to try?\nどんなスポーツを試してみたいですか？\n😰 Are you good at shooting?\nシュートは得意ですか？\n💪 Does your coach help you?\nコーチは手伝ってくれますか？\n📅 Do you practice every weekend?\n毎週末練習しますか？\n😊 Have you improved lately?\n最近上達しましたか？\n🌟 What did you learn from practice?\n練習から何を学びましたか？"
  },
  {
    "title": "29. Emi Helps Neighbor (Ask + Person + To)",
    "content": "🤝 Emi wants to help her neighbor.\nエミは隣人を助けたいです。\n😰 Her neighbor is elderly.\n隣人は年配です。\n📦 Emi carries heavy shopping bags.\nエミは重い買い物袋を運びます。\n😊 The neighbor says thank you.\n隣人はありがとうと言います。\n😢 However the neighbors garden needs care.\nでも隣人の庭に手入れが必要です。\n😊 Emi and friends clean the leaves.\nエミは友達と落ち葉を片付ける。\n🌟 Emi feels happy to help.\nエミは手伝えて幸せです。\n\n🤝 Do you help your neighbors?\n隣人を助けますか？\n😰 Do you have elderly neighbors?\n年配の隣人はいますか？\n📦 Do you carry heavy things?\n重いものを運びますか？\n😲 Do you say thank you often?\nありがとうはよく言いますか？\n😢 Does your garden need care?\n庭の手入れは必要ですか？\n🍂 Do you like autumn?\n秋は好きですか？\n😊 Does helping make you happy?\n手伝うと幸せですか？"
  },
  {
    "title": "30. Hanas Cultural Experience (Passive Voice)",
    "content": "🎎 Hanas class visits a crafts festival.\nハナのクラスは工芸祭を訪問します。\n😰 Hana does not know about crafts much.\nハナは工芸について詳しくありません。\n🖌️ She watches traditional paper folding.\n彼女は伝統的な折り紙を見ます。\n😲 She is surprised the paper makes shapes.\n紙が形を作ることに驚きます。\n🙋 A craftsman teaches her how to fold.\n職人が折り方を教えてくれます。\n😊 Hana makes a nice origami.\nハナはきれいな折り紙を作ります。\n🌟 Hana becomes interested in culture.\nハナは文化に興味を持ちます。\n\n🎎 Have you visited crafts festivals?\n工芸祭を訪問したことはありますか？\n🖌️ Have you tried origami?\n折り紙を試したことはありますか？\n😲 What surprised you recently?\n最近何かに驚きましたか？\n😊 Are you good at making things?\n物を作るのは得意ですか？\n🌟 Are you interested in your culture?\nあなたの文化に興味がありますか？\n📚 What Japanese art do you know?\nどんな日本芸術を知っていますか？"
  },
  {
    "title": "31. Kenjis Camping Trip (Past Continuous)",
    "content": "?? Kenji goes camping in mountains.\nケンジは山でキャンプします。\n?? But it starts raining at night.\nでも夜に雨が降りました。\n?? Everyone feels very tired.\nみんなとても疲れています。\n?? However water leaks into tent.\nしかしテントに水が入ります。\n?? They fix the tent quickly.\n彼らはテントをすぐに直します。\n?? The sun comes out next morning.\n翌朝太陽が出ます。\n?? The trip is still fun with friends.\n友達との旅行は楽しいです。\n\n?? Have you been camping?\nキャンプの経験がありますか？\n?? Have you experienced raining while camping?\nキャンプ中の雨の経験はありますか？\n?? Did your tent ever leak?\nテントが漏ったことはありますか？\n?? Did you fix the problem quickly?\n問題を早く治しましたか？\n?? Did the sun come out?\n太陽が出ましたか？\n?? Do friends make trips better?\n友達が旅行をより良くしますか？"
  },
  {
    "title": "32. Yumes Online Lessons (Present Perfect Cont)",
    "content": "?? Yume takes online English lessons.\nユメはオンライン英語レッスンを受けています。\n?? But her internet is sometimes slow.\nでもインターネットが時々遅いです。\n?? Her webcam freezes during lessons.\nレッスン中ウェブカメラがフリーズします。\n?? Yume feels frustrated.\nユメはイライラします。\n?? But her teacher is very patient.\nでも先生はとても忍耐強いです。\n?? Yume looks forward to learning.\nユメは学ぶのを楽しみにしています。\n?? After one month she improves.\n1ヶ月後に上達しました。\n\n?? Do you have online classes?\nオンラインクラスはありますか？\n?? Is your internet fast or slow?\nインターネットは速いですか、遅いですか？\n?? Does your webcam work well?\nウェブカメラは良く働きますか？\n?? Do you feel frustrated sometimes?\n時々イライラしますか？\n?? Is your teacher patient?\n先生は忍耐強いですか？\n?? Have you improved recently?\n最近上達しましたか？"
  },
  {
    "title": "33. Rens Recycling Project (Passive Voice)",
    "content": "?? Rens class decides to recycle.\nレンのクラスはリサイクルすることにしました。\n?? But not all students participate.\nでも全員ではありません。\n?? However Ren and friends are enthusiastic.\nでもレンと友達は熱心です。\n?? They collect bottles from classrooms.\n教室からボトルを集めます。\n?? The trash is sorted for recycling.\nゴミはリサイクルのために分別されます。\n?? The teacher praises Rens group.\n先生はレンのグループを褒めます。\n?? Ren feels proud to help.\nレンは役立って誇らしく思います。\n\n?? Do you recycle at school?\n学校でリサイクルをしていますか？\n?? Does your class collect bottles?\nクラスでボトルを集めますか？\n?? Do you sort trash into different bags?\nゴミを別々の袋に分別しますか？\n?? Does your teacher praise you?\n先生は褒めてくれますか？\n?? Do you feel proud when you help?\n助けると誇らしく思いますか？\n?? Is recycling important for everyone?\n全員にとってリサイクルは重要ですか？"
  },
  {
    "title": "34. Kais Bike Ride Plan (Conditionals)",
    "content": "?? Kai wants to ride his bike to park.\nカイは自転車で公園に行きたいです。\n?? But the weather is very hot.\nでも天気はとても暑いです。\n?? Kai feels tired after riding.\n自転車に乗って疲れます。\n?? He decides to rest under a tree.\n彼は木の下で休むことにします。\n?? He sees ice cream being sold.\nアイスを売っているのを見ます。\n?? Kai buys vanilla ice cream.\nカイはバニラアイスを買います。\n?? It tastes sweet and cold.\n甘くて冷たくて美味しいです。\n\n?? Do you have a bike?\n自転車はありますか？\n?? What do you do when tired?\n疲れたら何をしますか？\n?? Do you like ice cream?\nアイスは好きですか？\n?? How do you feel when you eat?\n食べるとどんな気分になりますか？\n?? Do you rest under trees?\n木の下で休みますか？"
  },
  {
    "title": "35. Ayas Science Fair Experiment (Passive)",
    "content": "?? Aya does a volcano experiment.\nアヤは火山実験をします。\n?? She mixes baking soda and vinegar.\n彼女は重曹とお酢を混ぜます。\n?? The mixture bubbles up immediately.\n混合物はすぐに泡立ちます。\n?? Aya shouts Its erupting!\n「噴火だ！」と叫びます。\n?? Her parents take photos.\n両親は写真を撮ります。\n?? She explains how it erupted.\nどうして噴火したかを説明します。\n?? Her project wins first prize.\nプロジェクトが1位になります。\n\n?? Have you done science experiments?\n科学実験をしたことはありますか？\n?? Have you seen something bubble up?\n泡立つものを見たことはありますか？\n?? Did your parents watch you work?\n両親は作業を見てくれましたか？\n?? Can you explain to others?\n他人に説明できますか？\n?? Have you won a prize?\n賞を取ったことはありますか？\n?? Do you want to become a scientist?\n科学者になりたいですか？"
  },
  {
    "title": "36. Harukas Class Election (Relative Pronoun)",
    "content": "?? Harukas class needs a representative.\nハルカのクラスは代表が必要です。\n?? Students give speeches to become rep.\n代表になるためにスピーチします。\n?? Haruka is nervous but wants to help.\nハルカは緊張しますが手伝いたいです。\n?? She speaks about making the class better.\nクラスを良くすることについて話します。\n?? Classmates listen with respect.\nクラスメートは尊敬して聞きます。\n?? They vote for Haruka.\n彼女に投票します。\n?? Haruka will help everyone in class.\nハルカはクラスのみんなを助けます。\n\n?? Does your class have a representative?\nクラスに代表はいますか？\n?? Have you given a speech to class?\nクラスでスピーチをしたことはありますか？\n?? Are you nervous when you speak?\n話す時緊張しますか？\n?? Can you express your ideas clearly?\nアイデアを明確に伝えられますか？\n?? Do others respect your ideas?\n他人はあなたのアイデアを尊重しますか？\n?? Did you get voted for something?\n投票されたことはありますか？\n?? Do you want to help your class?\nクラスを助けたいですか？\n🌟 What ideas do you have?\nどんなアイデアがありますか？"
  },
  {
    "title": "37. Autumn Preparation",
    "content": "🍂 Yuki prepares for autumn weather.\nユキは秋の天気に備えます。\n😰 But she has many things to organize.\nでも整理很多东西。\n🧥 She packs summer clothes in boxes.\n彼女は夏の服を箱にしまいます。\n🍂 She cleans the garden of fallen leaves.\n彼女は庭の落ち葉を掃きます。\n😊 Her mother helps organize the house.\n母が家の整理を手伝います。\n🍵 They drink hot tea after finishing.\n仕事の後、温かいお茶を飲む。\n🌟 Yuki feels ready for the cold season.\nユキは寒い季節の準備ができたと感じます。\n\n🍂 Do you prepare for autumn?\n秋の準備をしますか？\n🧥 Do you pack summer clothes?\n夏の服をしまいますか？\n😰 What do you organize at home?\n家で何を整理しますか？\n🍂 Do you like autumn?\n秋は好きですか？\n🍵 What hot drink do you like?\nどんな温かい飲み物がか好きですか？\n😊 Does your mother help you?\n母は手伝いしてくれますか？\n🌟 Do you feel ready for winter?\n冬の準備はできましたか？"
  },
  {
    "title": "38. Autumn Health Habits",
    "content": "🍎 Ken starts eating healthier food.\nケンはもっと健康的な吃的开始。\n🥗 He eats more fruits and vegetables.\n彼は更多的果物を食べます蔬菜。\n😰 But he misses junk food.\nでもジャンクフードが恋しい。\n🏃 Ken exercises to stay healthy.\nケンは健康のために運動します。\n😊 He feels more energetic.\n彼はもっと元气感觉。\n🍂 The autumn weather is perfect for exercise.\n秋の天气は運動に最適。\n🌟 Ken learns healthy habits take time.\nケンは健康的习惯需要时间。\n\n🍎 Do you eat healthy food?\n健康的食物を食べますか？\n🥗 What fruits do you like?\nどんな果物が好きですか？\n😰 What food do you miss most?\n一番恋しい食べ物は何ですか？\n🏃 Do you exercise outdoors?\n外で運動しますか？\n😊 Do you feel energetic after exercise?\n運動後元气になりますか？\n🌟 What healthy habit do you want?\nどんな健康的习惯を始めたいですか？"
  },
  {
    "title": "39. November Family Budget",
    "content": "💰 The family decides to make a budget for November.\n家族は11月の予算を作ることにします。\n😰 But they always spend too much money.\nでもお金の使いすぎ。\n📝 They write down all their expenses.\nすべての出費を書き出します。\n🎁 They plan Christmas gift buying early.\nクリスマスギフトの-buyingをの计划提前。\n😊 They find ways to save money.\n節約法を見つけます。\n💳 They decide to use cash instead of cards.\nカード 대신現金を決める。\n🌟 The family works together to save.\n家族は一緒に節約の努力します。\n\n💰 Do you have a budget?\n予算はある？\n😰 Do you spend too much money?\nお金の使いすぎ？\n📝 Do you track your spending?\n出費を記録？\n🎁 When do you buy Christmas gifts?\nクリスマスギフトいつ買う？\n😊 Do you save money for gifts?\nギフトのため貯金？\n💳 Do you use cash or cards more?\n現金とカードどちらを 많이 使？\n🌟 Does your family work on budgets together?\n家族が一緒に予算に取り組む？"
  },
  {
    "title": "40. Autumn Community Events",
    "content": "🎪 The town holds an autumn festival.\n町は秋祭りを開催します。\n😊 Yuki and her family attend the festival.\nユキと家族は祭りに出席します。\n🎭 There are many traditional performances.\n多くの伝統のなパフォーマンスがあります。\n😰 The festival is very crowded.\n人どちらも是とても多。\n🍡 They eat festival food like takoyaki.\nたこ焼きなどの祭りFoodを食べます。\n😊 They watch a beautiful fireworks show.\n好看の花火を見る。\n🌟 Yuki feels connected to her community.\nユキは地域に_CONNECTEDの感觉。\n\n🎪 Do you go to autumn festivals?\n秋祭りに行く？\n😊 What do you do at festivals?\n祭りですることは何？\n🎭 What traditional performances do you like?\nどんな伝統のなパフォーマンスが好き？\n😰 Is it crowded at events?\nイベントで込みます？\n🍡 What festival food do you like?\nどんな祭りFoodが好き？\n😊 Do you watch fireworks?\n花火見る？\n🌟 Do you feel connected to your community?\n地域に 연결되어 있다고 느끼？"
  },
  {
    "title": "41. Preparing for Winter",
    "content": "❄️ The first cold day arrives in December.\n12月に最初の寒い日が訪れます。\n😰 Haruka is not ready for the cold.\nハルカはまだ寒さに備えていない。\n🧥 She buys a warm winter coat.\n彼女は暖かい冬コートを買う。\n🧤 She also buys gloves and a scarf.\n手套とマフラーも買う。\n😊 Now she is ready for winter.\n今、冬の準備ができた。\n🌟 Haruka feels confident about the cold.\nハルカは寒さに自信を持っている。\n\n❄️ Do you like winter?\n冬が好き？\n😰 Are you ready for cold weather?\n寒さに備えてる？\n🧥 What coat do you wear in winter?\n冬どんなコート着る？\n🧤 Do you have gloves and scarf?\n手套マフラーある？\n😊 Do you like warm clothes?\n暖かい服好き？\n🌟 Do you feel confident in winter?\n冬に自信持てる？"
  },
  {
    "title": "42. Winter Holiday Travel",
    "content": "✈️ Kenji plans to travel during winter vacation.\nケンジは冬休みに旅行を計画します。\n😰 But plane tickets are very expensive.\nでもチケットとても高い。\n💰 He decides to take a bus instead.\n 대신バスで行くことに。\n😊 He saves a lot of money.\nお金を節約。\n🗺️ He visits his grandparents in the countryside.\n祖父母のるところ行く。\n🌟 Kenji feels happy to see his family.\n家族にできるえて幸せ。\n\n✈️ Do you travel during winter break?\n冬休みに旅行する？\n😰 Are tickets expensive in winter?\n冬のチケット高い？\n💰 Do you save money for trips?\n旅行のため貯金？\n🗺️ Where do you want to travel?\nどこに行きたい？\n😊 Do you like visiting family?\n家族にできるうのは好き？\n🌟 What makes you happy during holidays?\n休みに何を幸せにする？"
  },
  {
    "title": "43. New Years Celebration",
    "content": "🎉 The new year is coming soon.\n新年すぐ来る。\n😰 Emi doesn't know how to celebrate.\nエミはどう祝うか知らない。\n🍜 She cooks traditional New Year food.\n伝統の新年料理作る。\n😊 Her family eats together at midnight.\n家族は一緒に年夜飯食べる。\n🎊 They watch the sunrise on January first.\n元旦日の出を見る。\n🌟 Emi starts the year with her family.\n家族と新年始める。\n\n🎉 How do you celebrate New Year?\n新年どう祝う？\n😰 What is difficult about New Year?\n新年難しいことは何？\n🍜 What traditional food do you eat?\nどんな伝統の食物食べる？\n😊 Do you eat with family on New Year?\n新年に家族と食べる？\n🎊 Do you watch the sunrise?\n日の出見る？\n🌟 How do you start your new year?\n新年どう始める？"
  },
  {
    "title": "44. Winter Indoor Activities",
    "content": "❄️ It is too cold to go outside today.\n今日外出る、寒すぎて。\n😊 Hana decides to stay home.\nハナは家にいればの决定。\n📚 She reads books all afternoon.\n午後も読書。\n🎮 She plays video games with her brother.\n弟とビデオゲーム。\n☕ They drink hot chocolate together.\n一緒に温かいチョコレ飲み。\n🌟 Hana enjoys her cozy winter day.\nハナは冬の可爱のの一日を享受。\n\n❄️ Do you stay home in cold weather?\n寒い日 家にいる？\n😊 What do you do at home?\n家で何する？\n📚 What books do you like reading?\nどんな読書好き？\n🎮 Do you play video games?\nゲームする？\n☕ What hot drink do you like?\nどんな温かい飲み物好き？\n🌟 Do you enjoy cozy winter days?\n冬の可爱のの日 Enjoy?"
  },
  {
    "title": "45. Holiday Shopping",
    "content": "🛍️ The holiday season is here.\nHolidayシーズン来到これ里。\n😰 Maya doesn't know what gifts to buy.\nマヤどのGift買えばいいかわからない。\n💡 She makes a list of people and ideas.\n人とアイデアのリスト作る。\n😊 She finds perfect gifts for everyone.\nみんなに完美のGift見つける。\n🎁 She wraps all the gifts beautifully.\nきれいに包む。\n🌟 Maya feels ready for Christmas.\nクリスマス準備できた感じる。\n\n🛍️ Do you go holiday shopping?\nHoliday買い物行く？\n😰 What gifts do you buy?\nどんなGift買う？\n💡 Do you make a gift list?\nGiftリスト作る？\n😊 Do you enjoy finding gifts?\nGift見つける의乐趣?\n🎁 Do you wrap gifts yourself?\nGift自分で包む？\n🌟 Do you feel ready for holidays?\nHoliday 준비 됐어?"
  },
  {
    "title": "46. New Years Eve",
    "content": "🥂 December 31st is New Year's Eve.\n大晦日。\n😊 Ryo celebrates with his family.\nリョウは家族と祝う。\n🕐 They stay up until midnight.\n午夜まで起きてる。\n🎆 They watch fireworks at midnight.\n午夜、花火見る。\n🌟 Ryo makes a New Year's resolution.\nリョウは新年决意作る。\n💪 He promises to study harder this year.\n今年もっと勉强发誓。\n\n🥂 Do you celebrate New Year's Eve?\n大晦日祝う？\n😊 Who do you celebrate with?\n誰と祝う？\n🕐 Do you stay up until midnight?\n午夜まで起きてる？\n🎆 Do you watch fireworks?\n花火見る？\n🌟 Do you make New Year's resolutions?\n新年决意作る？\n💪 What is your resolution?\nあなたの决意は？"
  },
  {
    "title": "47. January Goals",
    "content": "📅 January is the start of a new year.\n1月は新しい年の始まり。\n🎯 Yuki makes goals for the new year.\nユキは今年の目標作る。\n📚 She wants to improve her English.\n英語を向上させたい。\n🏃 She wants to exercise more.\nもっと運動したい。\n😊 She writes her goals on paper.\n紙に目标書く。\n🌟 Yuki feels motivated for the new year.\nユキは新しい年に Motivation 感じる。\n\n📅 What do you want to do in January?\n1月に何をしたい？\n🎯 What are your goals this year?\n今年の目標は？\n📚 Do you want to improve English?\n英語を向上させたい？\n🏃 Do you want to exercise more?\nもっと運動したい？\n😊 Do you write your goals?\n目标を書く？\n🌟 Do you feel motivated in January?\n1月に動機 느끼?"
  },
  {
    "title": "48. Winter Memories",
    "content": "❄️ Winter vacation is almost over.\n冬休みすぐ終わる。\n😊 Kenji enjoyed his winter break.\nケンジは冬休みを楽しんだ。\n📸 He took many photos with his family.\n家族写真を撮った。\n🎮 He played games and read books.\nゲームして読書した。\n🌟 He feels ready for school again.\n学校に戻る準備できた感じる。\n🏫 Kenji starts the new term happily.\nケンジは新しい学期を幸せ始める。\n\n❄️ What did you do during winter break?\n冬休みにしたことは何？\n😊 Did you enjoy your break?\n休みを楽しんだ？\n📸 Did you take many photos?\n写真を撮った？\n🎮 What games did you play?\nどんなゲームした？\n🌟 Do you feel ready for school?\n学校準備できた？\n🏫 Are you happy to start school?\n学校が始まる幸せ？"
  }
];
