var eikenpre2plus = [
{ "title": "1. The Wrong Backpack", "content": "🎒 Miko grabbed her backpack and ran to school. ミコはリュックをつかんで学校に走りました。 😱 When she opened it, the books weren't hers! 彼女が開けたら、本が自分のものではありませんでした！ 🤔 She must have taken her brother's backpack by mistake. 間違えて弟のリュックを持ってきたに違いありません。 📚 His books were about science and math. 彼の本は科学と数学についてでした。 😂 Her friends laughed because the backpack was tiny. 友達は笑いました。リュックがとても小さかったから。 📱 Miko texted her brother during lunch break. ミコは昼休みに弟にテキストしました。 😓 Her brother said he had already left for school. 弟はもう学校に出発したと言いました。 🏃 They had to meet after school to switch. 放課後に会って交換することになりました。 ✅ By the end of the day, everything was fixed. 一日の終わりには、すべてが解決しました。 😊 Miko now always checks her bag before leaving. ミコは今、出かける前にいつもリュックを確認します。

🎒 Have you ever grabbed the wrong bag? 😱 What would you do if you had the wrong books? 🤔 Have you ever mixed up things with a sibling? 📚 What subjects does your brother or sister study? 😂 Do your friends ever laugh at your mistakes? 📱 How do you contact someone when there's a problem? 😓 What would you do if you couldn't swap back? 🏃 Where is a good place to meet after school? ✅ How do you fix mistakes when they happen? 😊 What do you always check before leaving home?" },
{ "title": "2. The Festival Surprise", "content": "🎪 Yuna's town held a big festival every autumn. ユナの町では毎年秋にお祭りがありました。 🎨 She had wanted to try the goldfish scooping. 彼女は金魚すくいを試してみたかったです。 😢 But by the time she arrived, the fish were gone. しかし着いたとき、魚はもういなくなっていました。 🍡 Her grandmother bought her some delicious dango instead. おばあちゃんが代わりにおいしい団子を買ってくださいました。 🎆 They watched fireworks together after eating. 食べた後、二人で花火を見ました。 😲 Yuna had never seen such big fireworks before. ユナはそんな大きな花火を見たことがありませんでした。 📸 She took lots of photos with her grandmother. 彼女はおばあちゃんと一緒にたくさんの写真を撮りました。 💕 Her grandmother told her stories about old festivals. おばあちゃんは昔のお祭りの話をしてくれました。 🌙 They stayed until the festival ended late at night. 彼らはお祭りが夜遅く終わるまでいました。 😊 It had been the best festival Yuna could remember. ユナが覚えている中で最高のお祭りでした。

🎪 Does your town have a festival every year? 🎨 What festival activity would you most like to try? 😢 Have you ever arrived too late for something? 🍡 What festival food do you like the most? 🎆 Do you enjoy watching fireworks? 😲 What is the most amazing thing you have ever seen? 📸 Do you like taking photos at events? 💕 Has a grandparent ever told you stories? 🌙 How late do you stay at festivals? 😊 What is your best festival memory?" },
{ "title": "3. The New Club", "content": "🏀 Kenji wanted to join the basketball club. ケンジはバスケットボール部に入りたいと思っていました。 😰 But the club had already started practice two weeks ago. しかし部活はもう2週間前に始まっていました。 📝 The captain told him he could still join. キャプテンはまだ入れるよと教えてくれました。 💪 Kenji practiced every day after school. ケンジは毎日放課後に練習しました。 😓 He was not as good as the others yet. 彼はまだ他の人ほど上手ではありませんでした。 🤝 The older students helped him learn new moves. 先輩たちが新しい動きを教えてくれました。 🏆 By the end of the month, he had improved a lot. 月末までに、彼はかなり上達しました。 🎉 His team won their first game together. 彼のチームは初めて一緒に試合に勝ちました。 😊 Kenji had made many new friends in the club. ケンジは部活でたくさんの新しい友達ができました。 🌟 He was glad that he had joined even though he was late. 遅かったけれど入ってよかったと思いました。

🏀 Have you ever wanted to join a club? 😰 What would you do if you missed the start? 📝 Has a captain or leader ever welcomed you? 💪 How often do you practice something after school? 😓 Have you ever been the worst at something? 🤝 Who has helped you learn something new? 🏆 How long did it take you to get better? 🎉 Have you ever won something as a team? 😊 Have you made friends through a club? 🌟 What are you glad you tried even though you were nervous?" },
{ "title": "4. The Broken Phone", "content": "📱 Sora accidentally dropped her phone in water. ソラは間違えてスマホを水に落としてしまいました。 😱 The screen went black immediately. 画面がすぐに真っ暗になりました。 😭 She had saved all her photos on that phone. 彼女はそのスマホにすべての写真を保存していました。 💭 Her mother said they could take it to a shop. お母さんは修理屋に持っていけるよと言いました。 🔧 The shop worker told them the phone might be fixed. 店員さんはスマホは修理できるかもしれないと言いました。 ⏰ They had to wait three days for the result. 結果まで3日待たなければなりませんでした。 📞 Sora borrowed an old phone from her father for school. ソラは学校用にお父さんから古いスマホを借りました。 😊 Luckily, the photos had been backed up online. 幸い、写真はオンラインでバックアップされていました。 🙏 Sora learned to always back up her data. ソラはデータをいつもバックアップすることを学びました。 ✅ Her phone had been fixed by the next week. 彼女のスマホは翌週修理されました。

📱 Have you ever broken something important? 😱 What would you do if your screen went black? 😭 Do you keep important photos on your phone? 🔧 Have you ever taken something to be repaired? ⏰ What is the longest you have waited for something? 📞 Have you ever borrowed something from a parent? 😊 Do you back up your photos or data? 🙏 What lesson have you learned from a mistake? ✅ Has something broken ever been fixed for you? 💭 What would you do without your phone for a week?" },
{ "title": "5. The Cooking Disaster", "content": "🍳 Hana decided to make breakfast for her family. ハナは家族のために朝ごはんを作ることにしました。 📖 She followed a recipe she found online. 彼女はオンラインで見つけたレシピに従いました。 😱 But she had forgotten to set the timer! しかしタイマーをセットするのを忘れていました！ 🔥 The eggs burned and the kitchen filled with smoke. 卵が焦げて、台所が煙でいっぱいになりました。 😭 Hana felt terrible about the ruined breakfast. ハナはダメになった朝ごはんのことでひどい気持ちでした。 👨 Her father came to help open the windows. お父さんが窓を開けるのを手伝いに来ました。 😂 Everyone laughed and they ate cereal instead. みんな笑って、代わりにシリアルを食べました。 💪 Hana tried again the next morning. ハナは翌朝もう一度挑戦しました。 ✅ This time she had set the timer perfectly. 今度はタイマーを完璧にセットしました。 😋 The family loved her second attempt at breakfast. 家族は彼女の2回目の朝ごはんを気に入りました。

🍳 Have you ever cooked something for your family? 📖 Do you use recipes when you cook? 😱 Have you ever forgotten an important step? 🔥 What would you do if something burned? 😭 How do you feel when something goes wrong? 👨 Who helps you when there is a problem in the kitchen? 😂 Have you ever had to eat something else instead? 💪 Do you try again after failing? ✅ What is the best meal you have ever made? 😋 What food does your family love the most?" },
{ "title": "6. The Camping Trip", "content": "⛺ Taro's class went camping in the mountains. タロウのクラスは山でキャンプに行きました。 🎒 They had packed everything the night before. 彼らは前夜にすべての荷物をまとめました。 🌧️ When they arrived, it started raining heavily. 着いたとき、激しい雨が降り始めました。 😓 The teacher said they should wait inside the bus. 先生はバスの中で待つべきだと言いました。 ⏰ After an hour, the rain had finally stopped. 1時間後、雨がついに止みました。 🏕️ They quickly set up their tents in the mud. 泥の中で急いでテントを設置しました。 🔥 Making a campfire was harder than they expected. キャンプファイヤーを作るのは思ったより難しかったです。 🌟 But the stars that night were amazing. しかし、その夜の星は素晴らしかったです。 📖 They told scary stories before sleeping. 寝る前に怖い話をしました。 😊 Everyone agreed it had been an unforgettable trip. みんな、忘れられない旅行だったと同意しました。

⛺ Have you ever been camping with your class? 🎒 What do you pack for a trip? 🌧️ What would you do if it rained on your trip? 😓 Have you ever had to wait because of bad weather? ⏰ What is the longest you have waited for rain to stop? 🏕️ Have you ever set up a tent? 🔥 What is harder than people expect? 🌟 Do you enjoy looking at stars? 📖 What kind of stories do you like to tell? 😊 What trip has been unforgettable for you?" }
];
