var eiken7fun = [
  {
    "title": "25. Week 7 - Rainbow After Rain",
    "content": "🌧️ It stops raining. 雨が止みます。\n\n☀️ The sun comes out. 太陽が出ます。\n\n🌈 A rainbow appears! 虹が見えます！\n\n🎨 It has many colors. たくさんの色があります。\n\n❤️ I like red. 私は赤が好きです。\n\n💚 My friend likes green. 友達は緑が好きです。\n\n💙 We look at the rainbow. 私たちは虹を見ます。\n\n📸 Dad takes a photo. お父さんが写真を撮ります。\n\n😌 The rainbow is beautiful! 虹は美しいです！\n\n🌈 Do you like rainbows? 虹は好きですか？\n\nWhat is your favorite color? 一番好きな色は何ですか？\n\nDo you like sunny days? 晴れた日は好きですか？\n\nDo you like storms? 嵐は好きですか？\n\nDo you take photos? 写真を撮りますか？\n\nDoes your dad take photos too? お父さんも写真を撮りますか？\n\nDo you like beautiful things? 美しいものは好きですか？\n\nDo you like the sky? 空は好きですか？\n\nDo you see rainbows often? よく虹を見ますか？\n\nDo you have a favorite color preference? 色の好みはありますか？\n\nDo you like weather like this? こんな天気は好きですか？"
  },
  {
    "title": "26. Week 8 - Butterfly",
    "content": "🦋 I see a butterfly. 私は蝶を見ます。\n\n🌸 It flies to a flower. 花に飛びます。\n\n🌺 The flower is pink. 花はピンクです。\n\n😊 I watch it fly. 蝶が飛びます。\n\n🐦 A bird flies by too. 鳥も飛びます。\n\n🐌 A snail walks slowly. カタツムリはゆっくり歩きます。\n\n🐜 An ant walks too. アリも歩きます。\n\n💦 I water the plants. 私は植物に水をやります。\n\n🌻 The flowers grow. 花は育ちます。\n\n😊 Butterflies are beautiful! 蝶は美しいです！\n\nDo you like insects? 昆虫は好きですか？\n\nDo you like flowers? 花は好きですか？\n\nWhat color do you like? どんな色が好きですか？\n\nDo birds fly near you? 鳥はあなたのそばで飛びますか？\n\nDo snails walk fast or slowly? カタツムリは速く歩きますか、それともゆっくり？\n\nDo you water plants? 植物に水をやりますか？\n\nDo things grow where you live? あなたの住んでいる場所で物は育ちますか？\n\nDo you like beautiful insects? 美しい昆虫は好きですか？\n\nDo you watch animals closely? 動物をよく観察しますか？\n\nDo you help nature? 自然を助けることはありますか？\n\nDo you like gardens? 庭は好きですか？"
  },
  {
    "title": "27. Week 8 - Baby Bird",
    "content": "🐦 I see a baby bird. 私はひな鳥を見ます。\n\n🌳 It is in a tree. 木の中にいます。\n\n🥚 It cannot fly. 飛ぶことができません。\n\n😔 The bird looks hungry. 鳥はお腹が空いてそうです。\n\n🍎 I find some bread. パンを見つけました。\n\n🥖 I put the bread near the tree. 木のそばにパンを置きます。\n\n🐦 The big bird comes. 親鳥が来ます。\n\n🍴 The baby bird eats. ひな鳥が食べます。\n\n🕊 Now the bird is happy! 今、鳥は幸せです！\n\n🤪 Can the bird fly now? 今、鳥は飛べますか？\n\nDo you help baby animals? 子供の動物を助けますか？\n\nDo you give food to animals? 動物に食べ物を与えますか？\n\nDo you have bread at home? 家にはパンはありますか？\n\nDo baby animals need you? 子供の動物はあなたを必要としていますか？\n\nDo you like birds? 鳥は好きですか？\n\nDo you have trees near you? あなたのそばに木はありますか？\n\nDo you watch birds? 鳥を見ますか？\n\nDo you feed birds often? よく鳥に餌をやりますか？\n\nDo you feel happy when you help? 助けるとき幸せですか？\n\nDo you like small animals? 小さな動物は好きですか？"
  },
  {
    "title": "28. Week 8 - Star",
    "content": "🌙 I look at the night sky. 夜空を見ます。\n\n⭐ I see a bright star. 明るい星が見えます。\n\n✨ It shines very bright! とても明るく輝いています！\n\n✈️ A plane flies by. 飛行機が飛びます。\n\n🤔 Is it a UFO? UFOかな？」\n\n🚀 No, it is just a plane. いや、ただの飛行機です。\n\n🌠 I make a wish. 願い事をします。\n\n💫 I wish to be happy. 幸せになりたいと願います。\n\n😊 The night sky is amazing! 夜空は素晴らしいです！\n\nDo you look at the stars? 星を見ますか？\n\nDo you like the night? 夜は好きですか？\n\nDo you see planes often? よく飛行機を見ますか？\n\nDo you like space? 宇宙は好きですか？\n\nDo you make wishes often? よく願い事をしますか？\n\nDo you hope to be happy? 幸せになりたいと思いますか？\n\nDo you like flying in planes? 飛行機で空を飛ぶのは好きですか？\n\nDo you believe in UFOs? UFOを信じますか？\n\nDo you like amazing things? 驚きは好きですか？\n\nDo you watch the sky at night? 夜空を見ますか？\n\nDo you want to travel? 旅行に行きたいですか？"
  },
  {
    "title": "29. Week 9 - Christmas",
    "content": "🎄 It is Christmas day. クリスマスです。\n\n❄️ Snow falls today. 今日は雪が降ります。\n\n🎅 Santa Claus is coming! サンタクロースが来ます！\n\n🎁 We put gifts under the tree. 木の下にプレゼントを置きます。\n\n🎼 We sing Christmas songs. クリスマスソングを歌います。\n\n🥶 We drink hot cocoa. ホットココアを飲みます。\n\n🍪 We eat Christmas cookies. クリスマスクッキーを食べます。\n\n🎉 We open gifts together. 一緒にプレゼントを開けます。\n\n😊 Christmas is my favorite day! クリスマスは私の一番好きな日です！\n\nDo you like Christmas? クリスマスは好きですか？\n\nDoes it snow where you live? あなたが住んでいる場所では雪が降りますか？\n\nDo you have a tree at home? 家にはツリーはありますか？\n\nDo you like presents? プレゼントは好きですか？\n\nDo you sing songs? 歌を歌いますか？\n\nDo you like hot drinks? 温かい飲み物は好きですか？\n\nDo you like cookies? クッキーは好きですか？\n\nDoes your family celebrate together? 家族は一緒にお祝いしますか？\n\nIs Christmas important to you? クリスマスは重要ですか？\n\nDo you get gifts on this day? この日にはプレゼントをもらいますか？\n\nDo you like to give presents? プレゼントをあげるのは好きですか？"
  },
  {
    "title": "30. Week 9 - Carnival",
    "content": "🎪 We go to the carnival. 私たちはカーニバルに行きます。\n\n🎡 Many people are there! たくさんの人がいます！\n\n🎠 We ride the merry-go-round. メリーゴーラウンドに乗ります。\n\n🎢 It goes round and round! くるくると回ります！\n\n🎈 I want balloons. 風船が欲しいです。\n\n🍿 We eat popcorn. ポップコーンを食べます。\n\n🎭 We see a clown. ピエロがいます。\n\n🤡 He is very funny! 彼はとても面白いです！\n\n😂 We laugh so much! 私たちはたくさん笑います！\n🎪 Do you like carnivals? カーニバルは好きですか？\n\nDo you like people? 人々は好きですか？\n\nDo you ride rides often? 乗り物によく乗りますか？\n\nDo things spin where you live? 回転するものはありますか？\n\nDo you like balloons? 風船は好きですか？\n\nDo you like popcorn? ポップコーンは好きですか？\n\nDo clowns make you laugh? ピエロはあなたを笑わせますか？\n\nDo you laugh a lot? よく笑いますか？\n\nDo you like entertainment shows? エンターテインメントは好きですか？\n\nDo you have fun with people? 人々と楽しみますか？"
  },
  {
    "title": "31. Week 10 - Swimming",
    "content": "🏊 I go swimming. 私は水泳に行きます。\n\n🌊 The pool is big. プールは大きいです。\n\n💧 The water is blue. 水は青いです。\n\n🥶 It is cold! 冷たいです！\n\n🏃 I jump into the water. 水に飛び込みます！\n\n🏊 I swim fast! 速く泳ぎます！\n\n👧 My friend swims too. 友達も泳ぎます。\n\n🚣 My friend swims past me. 友達が追い越しさます！\n\n🤩 We have a race. レースをします。\n\n😁 Swimming is so fun! 水泳はとても楽しい！\n\nDo you like swimming? 水泳は好きですか？\n\nDo you have a pool? プールはありますか？\n\nDo you like cold water? 冷たい水は好きですか？\n\nDo you jump into water? 水に飛び込みますか？\n\nDo you swim fast? 速く泳げますか？\n\nDo friends swim with you? 友達はあなたと泳ぎますか？\n\nDo you like races? レースは好きですか？\n\nDo you win sometimes? 時々勝つことはありますか？\n\nDo you like water sports? 水上スポーツは好きですか？\n\nDo you feel good in water? 水の中で気分は良いですか？"
  },
  {
    "title": "32. Week 10 - Flute",
    "content": "🎷 I play the flute. 私はフルートを演奏します。\n\n🎶 It is a small instrument. 小さな楽器です。\n\n🎵 I play a song. 歌を演奏します。\n\n😊 My song is nice. 私の歌は良いです。\n\n👯 My friends listen. 友達が耳を傾けます。\n\n👏 They clap their hands. 彼らは拍手します。\n\n🎭 I feel happy. 幸せを感じます。\n\n📢 Tomorrow I play trumpet. 明日はトランペットを演奏します。\n\n🎤 I can sing too！ 歌うこともできます！\n\n😊 I love music！ 音楽は大好きです！\n\nDo you play an instrument? 楽器を演奏しますか？\n\nDo you like small instruments? 小さな楽器は好きですか？\n\nDo you like music? 音楽は好きですか？\n\nDo your friends like your songs? 友達はあなたの歌が好きですか？\n\nDo people clap for you? 人々はあなたのために拍手しますか？\n\nDo you like different instruments? いろんな楽器は好きですか？\n\nDo you feel happy often? よく幸せですか？\n\nDo you try new things often? よく新しいことを試しますか？\n\nDo you like singing? 歌うのは好きですか？\n\nDo you love music? 音楽は大好きですか？\n\nDo your friends think you play well? 友達はあなたがよく演奏すると思いますか？"
  },
  {
    "title": "33. Week 10 - Roller Coaster",
    "content": "🎢 We go to the amusement park. 遊園地に行きます。\n\n🎡 There are many rides! たくさんの乗り物があります！\n\n🏎️ I want the roller coaster! ローラーコースターに乗りたい！\n\n😨 It goes very high! とても高いところへ！\n\n📉 Then it goes down fast! そして速く下がります！\n\n😱 I yell \"Ahhh!\" 私は「アーッ！」と叫びます！\n\n😂 My friends laugh too! 友達も笑います！\n\n🎉 We ride again! もう一度乗ります！\n\n😊 The roller coaster is thrilling！ ローラーコースターはスリル満点です！\n\nDo you like amusement parks? 遊園地は好きですか？\n\nDo you like rides? 乗り物は好きですか？\n\nDo you like high places? 高いところは好きですか？\n\nDo you like going down? 下がるのは好きですか？\n\nDo you yell when scared? 怖いときは叫びますか？\n\nDo you laugh with friends? 友達と笑いますか？\n\nHave you gone on rides again? もう一度乗りましたか？\n\nDo you like thrilling things? スリルがあるものは好きですか？\n\nDo you like fast rides? 速い乗り物は好きですか？\n\nDo your friends like exciting things? 友達は盛り上がるのが好きですか？\n\nDo you feel brave? 勇敢であると感じますか？\n\nDo you like to scream sometimes? 時々叫びたくなりますか？"
  },
  {
    "title": "34. Week 11 - My Teacher",
    "content": "👩‍🏫 I have a nice teacher. 私は良い先生を持っています。\n\n📚 Her name is Ms. Tanaka. 先生の名前は田中先生です。\n\n😊 She smiles a lot. 彼女はよく笑います。\n\n📝 She teaches us math. 私たちに数学を教えてくれます。\n\n🔢 I learn numbers. 数字を学びます。\n\n📖 She reads stories too. 物語も読んでくれます。\n\n🎨 I draw pictures in her class. 彼女のクラスで絵を描きます。\n\n🌟 She is kind and smart. 彼女は親切で聡明です。\n\n❤️ I love my teacher! 私は先生が大好きです！\n\nIs your teacher nice? あなたの先生は良い人ですか？\n\nWhat is your teacher's name? 先生の名前は何ですか？\n\nDo you learn math at school? 学校では数学を学びますか？\n\nDo you like numbers? 数字は好きですか？\n\nDoes your teacher read stories? 先生は物語を読んでくれますか？\n\nDo you draw pictures often? 絵をよく描きますか？\n\nAre teachers smart? 先生は聡明ですか？\n\nDo you like school? 学校は好きですか？\n\nDoes your teacher smile at you? 先生はあなたに微笑みますか？\n\nIs your teacher kind? 先生は親切ですか？\n\nDo you help your teacher? 先生を助けますか？"
  },
  {
    "title": "35. Week 11 - Windy Day",
    "content": "🍃 Today is a windy day. 今日は風が強い日です。\n\n🌳 The trees sway. 木が揺れます。\n\n🍂 Leaves fly in the air! 葉っぱが飛びます！\n\n🎪 My kite flies high! 私の凧が高く飛びます！\n\n💨 I run very fast! 私は速く走ります！\n\n😆 The kite goes up! 凧が上がります！\n\n⛅️ It touches a cloud! 雲に触れました！\n\n🏃 The kite flies down! 凧が下がります！\n\n😂 Flying a kite is fun! 凧揚げは楽しいです！\n\nDo you like windy days? 風が強い日は好きですか？\n\nDo you like trees? 木は好きですか？\n\nDo leaves fall in autumn? 秋には葉っぱが落ちますか？\n\nDo you like kites? 凧は好きですか？\n\nDo you have a kite? 凧を持っていますか？\n\nDo you run fast? 速く走れますか？\n\nDo you look at the sky often? よく空を見ますか？\n\nDo clouds look near? 雲は近くに見えますか？\n\nDo things fly near you? 飛んでいくものがありますか？\n\nDo you have fun with wind? 風と楽しみますか？\n\nDo you look up at the sky? 空を見上げますか？"
  },
  {
    "title": "36. Week 11 - Parrot",
    "content": "🦜 I see a parrot. 私はオウムを見ます。\n\n🐦 It is colorful. カラフルです。\n\n💚 It has green feathers. 緑の羽があります。\n\n❤️ It has red feathers too. 赤い羽もあります。\n\n🗣️ The parrot talks! オウムが話します！\n\n💬 It can say hello! 「こんにちは！」と言えます！\n\n🍎 It eats an apple. りんごを食べます。\n\n🥜 It eats nuts too. ナ�も食べます。\n\n😊 The parrot is clever! オウムは賢いです！\n\nDo you like colorful birds? カラフルな鳥は好きですか？\n\nWhat color do you like best? どんな色が一番好きですか？\n\nDo you have green things? 緑色のものはありますか？\n\nDo you like red things? 赤いものは好きですか？\n\nDo parrots really talk? オウムは本当に話しますか？\n\nHave you heard a parrot? オウムの声を聞いたことがありますか？\n\nDo you like apples? りんごは好きですか？\n\nDo you eat fruit? 果物を食べますか？\n\nDo you like smart animals? 賢い動物は好きですか？\n\nDo you like birds that talk? 話せる鳥は好きですか？\n\nDo you like learning from animals? 動物から学ぶのは好きですか？\n\nDo you have a clever pet? 賢いペットはいますか？"
  }
];
