var eiken5story = [
  {
    "title": "1. My Winter Day (Mixed Grammar)",
    "content": "⛄ It is snowing very heavily outside my window today.\n外では今、窓のそばで雪が激しく降っています。\n\n🏠 I am looking out the window from my warm and cosy room.\n暖かくて居心地のいい部屋から窓の外を見ています。\n\n❄️ My friends are playing happily in the deep white snow now.\n友達は今、深い白い雪の中で楽しく遊んでいます。\n\n☕ My mother is making delicious hot chocolate for all of us right now.\n母は今、私たち全員のために美味しいホットチョコレートを作っています。\n\n🎩 We are wearing our warm hats and thick winter coats outside.\n私たちは外で暖かい帽子と厚い冬のコートを着ています。\n\n🎵 I am very happy on this beautiful snowy winter day.\nこの美しい雪の冬の日はとても嬉しいです。\n\n🌟 Winter days are always fun and beautiful for my family.\n冬の日は私の家族にとっていつも楽しくて美しいです。\n\n🌨️ More snow is falling slowly in the cold afternoon today.\n今日の寒い午後には、さらに雪がゆっくりと降っています。\n\n🌨️ Snow days are myfavorite time of the whole year.\n雪の日は一年の中で私のお気に入りの時間です。\n\n🏂 The children are running and playing in the garden now.\n子供たちは今、庭で走ったり遊んだりしています。\n\n🏠 What do you usually like doing on cold winter days?\n寒い冬の日に普段は何をするのが好きですか？\n\n⛄ Where do you like to go when it snows very much?\nたくさん雪が降るときはどこへ行きたいですか？\n\n👫 Do you enjoy playing outside with your friends in winter?\n冬のとき、友達と外で遊ぶのは好きですか？\n\n❄️ Which season do you like the most and why?\nどの季節が一番好きですか、そしてそれはなぜですか？\n\n🎿 What do you wear on very cold and snowy days?\nとても寒くて雪の日は何を着ていますか？\n\n🏠 Is your house warm when it is cold outside?\n外が寒いとき、あなたの家は暖かいですか？\n\n👨 What does your father do in the evenings at home?\n父は家で夜は何をしていますか？\n\n👩 What does your mother like to cook for the family?\n母はご家族のためにどんな料理をするのが好きですか？\n\n🌨️ Do you prefer staying inside or playing outside in winter?\n冬のときは家の中にいるのが好きですか、外で遊ぶのが好きですか？\n\n🌟 What makes you feel very happy on winter days?\n冬の日にどんな時、とても幸せな気持ちになりますか？"
  },
  {
    "title": "2. Playing in Snow (Present Continuous Focus)",
    "content": "⛄ I am running very fast in the white and cold snow now.\n私は今、白くて冷たい雪の中をとても速く走っています。\n\n🎿 My friends are playing happily outside in the cold weather today.\n友達は今日、寒い天気の中で楽しく外で遊んでいます。\n\n☕ My brother is making a big and round snowball in the garden.\n兄は庭で大きくて丸い雪玉を作っています。\n\n🎶 We are laughing and having great fun together in the snow.\n私たちは雪の中でいっしょに笑ってとても楽しく過ごしています。\n\n🎁 My sister is making a tall and beautiful snowman near the house.\n妹は家の近くで背の高くて美しい雪だるまを作っています。\n\n🎨 She is putting a long orange carrot on the snowman's face.\n彼女は雪だるまの顔に長いオレンジ色のニンジンを載せています。\n\n🔴 The children are throwing many white snowballs at each other.\n子供たちはお互いにたくさんの白い雪玉を投げ合っています。\n\n🎉 Everyone is playing very happily in the fresh winter air.\nみんなは新鮮な冬の空気の中でとても楽しく遊んでいます。\n\n❄️ The sun is shining brightly on the beautiful white snow.\n太陽は美しい白い雪の上を明るく輝いています。\n\n🌨️ The snow is falling very slowly from the grey sky now.\n雪は今、灰色の空からとてもゆっくりと降っています。\n\n🎒 What are you doing right now in your warm house?\nあなたは今、暖かい家の中で何をしていますか？\n\n🏃 Are you playing outside with your friends in the snow?\nあなたは友達と雪の中で外で遊んでいますか？\n\n❄️ Is it snowing where your house is right now?\nあなたの家のある場所では今、雪が降っていますか？\n\n👫 Who are you playing with outside on this cold day?\nこの寒い日は外で誰と遊んでいますか？\n\n🎉 Are you having a good time playing in the snow today?\n今日は雪の中で遊ぶのを楽しんでいますか？\n\n🏠 Where are you now with your family on this day?\nこの日は今、家族とどこにいますか？\n\n🌨️ What is happening right now outside your window today?\n今日は今、あなたの窓の外で何が起きていますか？\n\n👕 What warm clothes are you wearing right now?\n今はどんな暖かい服を着ていますか？\n\n❄️ Is it very cold where you are staying now?\nあなたが今いる場所はとても寒いですか？\n\n👨 What is your father doing in the house right now?\nあなたの父は今、家の中で何をしていますか？"
  },
  {
    "title": "3. My Family (Mixed Grammar)",
    "content": "👨 My father is reading an interesting newspaper in the living room.\n父はリビングルームで面白い新聞を読んでいます。\n\n👩 My mother is cooking a delicious dinner in the kitchen now.\n母は今、キッチンで美味しい夕食を作っています。\n\n👧 My sister is doing her homework quietly at her desk.\n妹は自分の机で静かに宿題をしています。\n\n👦 My brother is playing a fun video game in his bedroom.\n兄は自分の寝室で楽しいビデオゲームをしています。\n\n🐶 Our little dog is sleeping quietly under the big table.\n私たちの小さな犬は大きなテーブルの下で静かに寝ています。\n\n🏠 I am helping my mother prepare dinner in the kitchen.\n私はキッチンで母と一緒に夕食の準備を手伝っています。\n\n👨‍👩‍👧‍👦 My family lives in a small and comfortable house.\n私の家族は小さくて居心地のいい家に住んでいます。\n\n❤️ We are a very happy and friendly family.\n私たちはとても幸せで友好的な家族です。\n\n🎵 My father likes listening to music on Sunday mornings.\n父は日曜日の朝に音楽を聴くのが好きです。\n\n🎁 My mother is very kind and always helps us.\n母はとても親切で、いつも私たちを助けてくれます。\n\n👨 Who is reading in your house right now?\nあなたの家では今、誰が読書をしていますか？\n\n👩 Who is cooking in your kitchen this evening?\n今夜はあなたのキッチンで誰が料理をしていますか？\n\n👧 Is your sister doing her homework right now?\nあなたの妹は今、宿題をしていますか？\n\n👦 Who is playing video games in your family?\nあなたの家族の中でビデオゲームをしているのは誰ですか？\n\n🐶 Is your pet sleeping somewhere in the house now?\nあなたのペットは今、家のどこかで寝ていますか？\n\n🍽️ What is your family eating together right now?\nあなたの家族は今、いっしょに何を食べていますか？\n\n❤️ Is your family big or small in number?\nあなたの家族は人的には大きいですか、それとも小さいですか？\n\n🏠 Does your family live in a house or flat?\nあなたの家族は家に住んでいますか、それともアパートですか？\n\n👨‍👩‍👧‍👦 What are your family members doing now?\nあなたの家族の皆さんは今、何をしていますか？"
  },
  {
    "title": "4. Family Photos (Wh-Questions Focus)",
    "content": "📷 We are looking at beautiful old family photos together today.\n私たちは今日、いっしょに美しい古い家族の写真を見ています。\n\n👴 This is my kind grandfather in that old black and white picture.\nその古い白黒写真の中にいるのは優しい私の祖父です。\n\n👵 My grandmother is standing next to him in the photo.\n祖母は写真の中で彼の隣に立っています。\n\n👨 My father is happily playing with a big ball outside.\n父は外で大きなボールで楽しく遊んでいます。\n\n👩 My mother is holding my small sister in her arms.\n母は小さな妹を腕に抱いています。\n\n👧 I am a cute baby in this lovely family photo.\nこの素敵な家族写真の中で私は可愛い赤ちゃんです。\n\n🏠 We lived in a different house many years ago.\n私たちは昔、別の家に住んでいました。\n\n❤️ My family looks very happy in these pictures.\nこれらの写真の中、私の家族はとても幸せそうです。\n\n📷 The old photos are beautiful and very interesting.\n古い写真は美しくてとても興味深いです。\n\n🌟 I love looking at old and new family pictures.\n古い家族の写真も新しい家族の写真も見るのが大好きです。\n\n👨 Who is the young man in this family picture?\nこの家族写真の中の若い男性は誰ですか？\n\n👨‍👩‍👧‍👦 Who are these people in the family photo?\nこの家族写真の中の人たちは誰ですか？\n\n📱 What are the people holding in the photo?\n写真の中の人たちは何を持っていますか？\n\n🏠 Where was the photo with the family taken?\n家族が写っているこの写真はどこで撮られましたか？\n\n🎉 Why are the people smiling in the picture?\n写真の中の人たちはなぜ笑っているのですか？\n\n❄️ When was the photo taken by your family?\nあなたの家族によってこの写真はいつ撮られましたか？\n\n🏠 Where is your family living in this season?\nこの季節、あなたの家族はどこに住んでいますか？\n\n👨 Who is yourfavorite person in your big family?\nあなたの大きな家族の中で誰がお気に入りですか？\n\n📷 Do you like seeing old photos of your grandparents?\nあなたの祖父母の古い写真を見るのは好きですか？\n\n📸 What kind of family photos do you like most?\nあなたはどんな家族の写真が一番好きですか？"
  },
  {
    "title": "5. Playing at School with Friends 🏫",
    "content": "🎒 Ken goes to school every morning with his school bag.\nケンは毎朝学校のカバンを持って学校へ行きます.\n\n👫 He meets his friends Tom and Yuki at the school gate.\nケンは学校の門で友達のトムとユキに会います.\n\n😊 They are playing football in the playground now happily.\n彼らは今、校庭で楽しくサッカーをしています.\n\n⚽ Ken is running with the ball very fast currently.\nケンは現在、ボールを持ってとても速く走っています.\n\n👦 Tom is trying to catch Ken near the goal enthusiastically.\nトムはゴール近くで熱心にケンを捕まえようとしています.\n\n👧 Yuki is laughing and watching them play joyfully.\nユキは笑って彼らが遊ぶのを楽しく見ています.\n\n🏆 Ken is the best football player in his class proudly.\nケンはクラスで一番のサッカー選手だと誇りに思っています.\n\n👍 His friends think he is very good at football clearly.\n友達は彼がサッカーがとても上手だとはっきり思っています.\n\n📚 After playing, they go back to the classroom together.\n遊んだ後、彼らは一緒に教室に戻ります.\n\n🏫 Ken loves playing with his friends at school greatly.\nケンは友達と学校で遊ぶのが大好きです.\n\n🏫 Do you like your school and your classroom?\nあなたはあなたの学校と教室は好きですか？\n\n👫 Who are your best friends at school happily?\n学校での楽しい一番の親友は誰ですか？\n\n⚽ What games do you play at school often?\n学校ではどのようなゲームをよくしますか？\n\n👨‍🏫 Who is yourfavorite teacher at school?\n学校での一番の先生は誰ですか？\n\n📚 What subject do you like the most really?\n本当に一番好きな教科は何ですか？\n\n🍱 What do you eat for lunch at school usually?\n通常学校で昼食に何を食べますか？\n\n😊 Are you happy when you are at school always?\n学校にいるときいつも幸せですか？\n\n🎒 What do you bring to school every day?\n毎日学校に何を持って行きますか？\n\n👨‍👩‍👧‍👦 Do you go to school with your friends often?\n頻繁に友達と一緒に学校へ行きますか？\n\n🎨 What do you do during break time happily?\n休み時間には何を楽しくしますか？"
  },
  {
    "title": "6. A School Day with Friends 💕",
    "content": "☀️ Ken wakes up at seven o'clock in the morning daily.\nケンは毎朝7時に起きます.\n\n🍞 He eats breakfast with his family before school hurriedly.\nケンは学校に行く前に家族と朝食を急いで食べます.\n\n👋 He says goodbye to his mother at the door politely.\n彼はドアで母に優しくさようならと言います.\n\n🚶 He walks to school with his bag happily.\n彼はカバンを持って幸せに学校へ歩いていきます.\n\n👋 He says hello to his teacher, Mr Tanaka kindly.\n彼は田中先生に親切にこんにちはと言います.\n\n📚 He sits at his desk in the classroom attentively.\n彼は注意深く教室の自分の机に座っています.\n\n✏️ Ken writes English words in his notebook carefully.\nケンはノートに英単語を注意深く書いています.\n\n👩‍🏫 The teacher is kind and helpful to everyone naturally.\n先生は自然にみんなに親切で役に立ちます.\n\n👫 Ken studies with his friend Yuki now collaboratively.\nケンは今、友達のユキと協力的に勉強しています.\n\n😊 He is happy to learn many things at school enthusiastically.\nケンは熱心に学校でたくさんのことを学べるのが幸せです.\n\n☀️ What time do you get up in the morning regularly?\n毎朝何時に起きますか？\n\n🍞 What do you eat for breakfast happily?\n幸せに朝食には何を食べますか？\n\n🚶 How do you go to school normally?\n普通はどうやって学校へ行きますか？\n\n🏫 Is your school near your house or far away?\nあなたの学校は家の近くですか、それとも遠くですか？\n\n👨‍🏫 Do you have a kind teacher at school?\n学校には親切な先生がいますか？\n\n📚 What is yourfavorite subject at school?\n学校で一番好きな教科は何ですか？\n\n😊 Are you happy at school generally?\n学校には一般的に幸せですか？\n\n👫 Do you study with your friends sometimes?\n時々友達と勉強しますか？\n\n✏️ What are you good at doing at school?\n学校で何をするのが得意ですか？\n\n🎉 What do you like about school really?\n学校のどんなところが本当に好きですか？"
  },
  {
    "title": "7. School Activities and Learning 📚",
    "content": "🎨 Tom draws a picture in art class today beautifully.\nトムは今日、美術の授業で美しい絵を描きます.\n\n🖍️ He uses colored pencils for his drawing carefully.\n彼は絵を描くのに色鉛筆を注意深く使います.\n\n👩‍🏫 The teacher helps him draw a cat kindly.\n先生は彼が猫の絵を描くのを親切に助けます.\n\n😊 Tom thinks art class is very fun really.\nトムは美術の授業が本当にとても楽しいと思っています.\n\n📖 After art class, they have English class next.\n美術の授業の後、彼らには次に英語の授業があります.\n\n🗣️ The students practise new English words aloud.\n生徒たちは新しい英単語を練習します.\n\n📝 Aiko writes sentences in her notebook thoughtfully.\nアイコはノートに文章を思慮深く書いています.\n\n👍 She is good at English and likes reading much.\n彼女は英語が得意で、読書が大好きです.\n\n📚 Learning new things makes the students happy often.\n新しいことを学ぶと生徒たちは頻繁に幸せになります.\n\n🏫 School activities help students learn every day well.\n学校の活動は生徒たちが毎日よく学ぶのを助けます.\n\n🎨 Do you like art class in school?\n学校の美術の授業は好きですか？\n\n🖼️ What do you like to draw in art class?\n美術の授業では何を描くのが好きですか？\n\n🖍️ Do you use colored pencils or paints for art?\n美術のために色鉛筆と絵の具、どっちを使いますか？\n\n👩‍🏫 Who is yourfavorite teacher really?\n本当にあなたの一番の先生は誰ですか？\n\n📚 What subject do you like best actually?\n実際一番好きな教科は何ですか？\n\n📖 Do you like reading books at home often?\n家では頻繁に本を読みますか？\n\n✏️ Are you good at writing properly?\n適切に文章を書くのは得意ですか？\n\n😊 What makes you happy at school truly?\n学校で何があなたを本当に幸せにしますか？\n\n🎯 What do you want to learn at school next?\n学校で次に何を学びたいですか？\n\n📝 Do you like studying new things always?\n常に新しいことを学ぶのは好きですか？"
  },
  {
    "title": "8. Helping Friends at School 🤝",
    "content": "👧 Aiko studies maths in the classroom seriously.\nアイコは教室で数学を真剣に勉強しています.\n\n❓ She looks at the maths problems carefully now.\n彼女は今、数学の問題を注意深く見ています.\n\n😕 The questions are difficult for her today unfortunately.\n残念ながら、今日の問題は彼女にとって難しいです.\n\n🤝 Ken sees that Aiko needs some help kindly.\nケンはアイコが少し助けが必要だと気づきます。\n\n😊 He walks to her desk now immediately.\n彼女は今すぐ彼女の机へ歩いていきます.\n\n👨‍🏫 Ken explains the problem to Aiko clearly.\nケンはアイコに問題を明確に説明します.\n\n📝 Aiko understands the maths answer now happily.\nアイコは今、数学の答えを幸せに理解しています.\n\n😊 She thanks Ken for his help gratefully.\n彼女は助けてくれたことにケンに感謝しています.\n\n👫 They are friends and help each other every day always.\n彼らは友達で、毎日いつもお互いに助け合っています.\n\n❤️ Helping friends is important and kind clearly.\n友達を助けることは明確に大切で優しいことです.\n\n🤝 Do you help your friends at school often?\n学校では頻繁に友達を助けますか？\n\n👫 Who do you help at school most?\n学校では最も誰を助けますか？\n\n❓ Is it good to help your friends really?\n本当に友達を助けるのはいいことですか？\n\n😊 How do you feel when you help someone happily?\n誰かを助けると、幸せにどう感じますか？\n\n👨‍🏫 Does your teacher help you with problems sometimes?\n時々、先生は問題の助けをしてくれますか？\n\n📚 When do you ask for help at school properly?\n学校では適切にいつ助けを求めますか？\n\n🤝 Have you helped a friend recently lately?\n最近、友達を助けましたか？\n\n😕 When you need help, who do you ask nicely.\n助けが必要なとき、誰に優しく頼みますか？\n\n💕 Are your friends kind to you generally?\n一般的にあなたの友達は親切ですか？\n\n👨‍👩‍👧‍👦 Do your parents help you with homework often?\n両親は宿題を頻繁に手伝ってくれますか？"
  },
  {
    "title": "9. Playing at School",
    "content": "I am playing football with my friends at school now.\n私は今友達と学校でサッカーをしています.\n\nTom is running very fast with the ball in the playground.\nトムは校庭でボールを持ってとても速く走っています.\n\nYuki is watching us and cheering loudly for our team.\nユキは私たちを見て、チームのために大声で応援しています.\n\nI am kicking the ball towards the goal happily now.\n私は今幸せにゴールに向かってボールを蹴っています.\n\nMy friends are laughing and having fun together today.\n友達は今日一緒に笑って楽しんでいます.\n\nThe sun is shining brightly in the blue sky today.\n今日は青い空の中で太陽が明るく輝いています.\n\nWe are drinking water and taking a short break now.\n私たちは今水を飲んで短い休憩をとっています.\n\nThe football game is very exciting for everyone here.\nサッカーゲームはここにいる全員にとってとてもエキサイティングです.\n\nI am feeling energetic and happy today.\n私は今日活力があり、幸せな気持ちです.\n\nWe are going back to our classroom after playing.\n遊んだ後、私たちは教室に戻っています.\n\nDo you like playing sports at school everyday？\n毎日学校でスポーツをするのは好きですか？\n\nWhat games are you playing with your friends now？\n今友達と何のゲームをしていますか？\n\nAre you enjoying your school day today？\n今日は学校生活を楽しんでいますか？\n\nWho is helping you learn new things at school？\n学校で新しいことを学ぶのを誰が助けてくれていますか？\n\nIs your teacher kind and friendly to you？\nあなたの先生は優しくてフレンドリーですか？\n\nWhat subjects are you studying this semester？\n今学期何の科目を勉強していますか？\n\nAre you making many new friends at school？\n学校で多くの新しい友達を作っていますか？\n\nDo you go home alone or with friends after school？\n放課後一人で帰りますか、それとも友達と帰りますか？\n\nWhat time do you usually have lunch at school？\n学校で通常何時に昼食をとりますか？\n\nAre you feeling happy or tired right now？\n今は幸せな気持ちですか、それとも疲れていますか？\n"
  },
  {
    "title": "10. My Weekend",
    "content": "I am visiting my grandmother's house this Saturday.\n今週の土曜日に祖母の家を訪れています.\n\nI am taking the train with my mum in the morning.\n朝母と電車に乗っています.\n\nMy grandmother is making delicious cookies for us now.\n祖母が今私たちのために美味しいクッキーを作っています.\n\nI am helping her in the kitchen happily.\n私は幸せにキッチンで彼女を手伝っています.\n\nWe are eating cookies and drinking tea together now.\n私たちは今一緒にクッキーを食べてお茶を飲んでいます.\n\nMy grandmother is telling interesting stories to me now.\n祖母が今私に面白い話をしています.\n\nShe is showing me old photos of my family.\n彼女は私の家族の古い写真を見せています.\n\nI am looking at the photos and asking questions.\n私は写真を見て質問をしています.\n\nWe are having a wonderful weekend together.\n私たちは一緒に素晴らしい週末を過ごしています.\n\nI am loving spending time with my grandmother.\n祖母と時間を過ごすのが大好きです.\n\nDo you visit your grandparents often？\n祖父母を頻繁に訪れますか？\n\nWhat are you doing on weekends usually？\n通常週末に何をしていますか？\n\nIs your family big or small？\nあなたの家族は大家族ですか、それとも小家族ですか？\n\nWho is yourfavorite family member？\n一番好きな家族メンバーは誰ですか？\n\nWhat food does your grandmother cook for you？\nあなたの祖母はあなたにどんな料理を作りますか？\n\nAre you close to your grandparents？\n祖父母と親しいですか？\n\nWhat stories does your family tell you？\nあなたの家族はあなたにどんな話をしますか？\n\nDo you like going to other people's houses？\n他の人の家に行くのは好きですか？\n\nWhat makes you happy when visiting family？\n家族を訪れるとき何があなたを幸せにしますか？\n\nAre you writing a letter or email to anyone？\n誰かに手紙やメールを書いていますか？\n"
  },
  {
    "title": "11. Spring Picnic",
    "content": "My class is having a picnic in the park today.\n私のクラスは今日公園でピクニックをしています.\n\nWe are sitting on a big blue sheet together.\n私たちは一緒に大きな青いシートの上に座っています.\n\nI am eating myfavorite sandwich now.\n私は今一番好きなサンドイッチを食べています.\n\nMy friends are sharing their food with me.\n友達は私と食べ物を分け合っています.\n\nWe are talking and laughing together happily.\n私たちは幸せに一緒に話して笑っています.\n\nThe teacher is taking photos of our class now.\n先生が今私たちのクラスの写真を撮っています.\n\nSome students are playing games in the grass.\n一部の学生は芝生でゲームをしています.\n\nI am drinking orange juice from a small bottle.\n私は小さなボトルからオレンジジュースを飲んでいます.\n\nThe weather is warm and sunny today.\n今日は天気が暖かく晴れています.\n\nWe are enjoying our spring picnic very much.\n私たちは春のピクニックをとても楽しんでいます.\n\nDo you like having picnics with your friends？\n友達とピクニックをするのは好きですか？\n\nWhat food are you eating for lunch today？\n今日昼食に何を食べていますか？\n\nIs the weather sunny or cloudy today？\n今日は天気は晴れですか、それともくもりですか？\n\nWhat are your friends doing at lunchtime？\n昼食時に友達たちは何をしていますか？\n\nWhere are you sitting right now？\n今どこに座っていますか？\n\nAre you feeling hungry or full right now？\n今お腹が空いていますか、それとも満腹ですか？\n\nWhat games do you play during free time？\n自由時間に何のゲームをしますか？\n\nDo you help organize snacks for class parties？\nクラスパーティーのお菓子を整理するのを手伝いますか？\n\nWho are you sitting with in lunch？\n昼食時に誰と一緒に座っていますか？\n\nWhat is the best thing about school picnics？\n学校のピクニックで最高なことは何ですか？\n"
  },
  {
    "title": "12. English Class",
    "content": "I am studying English in my classroom now.\n私は今教室で英語を勉強しています.\n\nMy English teacher is teaching us new words today.\n今日英語の先生が私たちに新しい単語を教えています.\n\nWe are practising the pronunciation together now.\n私たちは今一緒に発音を練習しています.\n\nI am repeating after the teacher carefully now.\n私は今先生の後に注意深く繰り返しています.\n\nMy classmates are listening and speaking English now.\n同級生たちは今英語を聴いて話しています.\n\nThe teacher is writing the words on the board now.\n先生が今黒板に単語を書いています.\n\nWe are writing the new words in our notebooks.\n私たちはノートに新しい単語を書いています.\n\nI am checking my spelling with a dictionary now.\n私は今辞書でスペルをチェックしています.\n\nEveryone is working hard in English class today.\nみんな今日英語のクラスで一生懸働いています.\n\nI am enjoying learning English very much today.\n私は 今日英語を学ぶのをとても楽しんでいます.\n\nDo you like English classes at school？\n学校の英語の授業は好きですか？\n\nHow many new words are you learning this week？\n今週何個の新しい単語を学んでいますか？\n\nIs your English teacher strict or kind？\n英語の先生は厳しいですか、それとも優しいですか？\n\nWhat are you writing in your notebook now？\n今ノートに何を書いていますか？\n\nAre you speaking English in class often？\nクラスでよく英語を話していますか？\n\nIs English easy or difficult for you？\n英語はあなたにとって簡単ですか、それとも難しいですか？\n\nDo you practise English after school at home？\n放課後家で英語を練習しますか？\n\nWhat English words do you know well？\nどの英単語をよく知っていますか？\n\nAre you doing homework or studying now？\n今宿題をしていますか、勉強していますか？\n\nWhat would you like to learn in English next？\n次は英語で何を学びたいですか？\n"
  },
  {
    "title": "13. My New Teacher",
    "content": "👩 My new teacher is very kind.\n新しい先生はとても優しいです。\n\n📚 She is teaching us English now.\n彼女は今英語を教えています。\n\n👗 The teacher is wearing a blue dress today.\n先生は今日青いワンピースを着ています。\n\n😊 She is smiling at us in the classroom.\n彼女は教室で私たちに微笑んでいます.\n\n📝 I am sitting in the front row.\n私は前列に座っています.\n\n🧑‍🤝‍🧑 My friends are listening carefully.\n友達も注意深く聞いています。\n\n📝 The teacher is writing on the board.\n先生は黒板に書いています。\n\n📖 We are learning new words today.\n私たちは新しい単語を習っています。\n\n😊 Everyone is happy in the class.\nクラスの皆は幸せです。\n\n📚 The lesson is very interesting.\nその授業はとても面白いです。\n\nWho is your new teacher?\nあなたの新しい先生は誰ですか？\n\nWhat is she teaching now?\n彼女は今何を教えていますか？\n\nIs your teacher kind?\nあなたの先生は優しいですか？\n\nWhere are you sitting in class?\nクラスでどこに座っていますか？\n\nAre your friends listening carefully?\n友達も注意深く聞いていますか？\n\nWhat is the teacher wearing?\n先生は何を着ていますか？\n\nIs the lesson interesting?\n授業は面白いですか？\n\nHow are you feeling in class?\nクラスでどんな気持ちですか？\n\nWhen is your English class?\n英語の授業はいつですか？\n\nWhy are you learning English？\nなぜ英語を勉強していますか？\n"
  },
  {
    "title": "14. My Classroom",
    "content": "🏫 I am in my classroom now.\n私は今教室にいます.\n\n🏢 The classroom is big and clean.\n教室は大きできれいです。\n\n🪑 There are many desks in the room.\n部屋の中にたくさんの机があります。\n\n🌞 The windows are open now.\n今窓が開いています.\n\n🧹 Some students are cleaning the room.\n何人かの学生が部屋を掃除しています。\n\n✏ I am writing on my notebook.\n私はノートに書いています.\n\n👨‍🏫 My teacher is standing near the board.\n先生は黒板の近くに立っています。\n\n⏰ The clock is showing three o'clock.\n時計は3時を指しています。\n\n🔢 We are having a math lesson.\n私たちは算数の授業をしています.\n\n📖 Everyone is working hard.\nみんな頑張っています。\n\nWhere is your classroom?\nあなたの教室はどこにありますか？\n\nIs your classroom big?\nあなたの教室は大きいですか？\n\nWhat is in your classroom?\n教室の中に何がありますか？\n\nAre the windows open now?\n今窓が開いていますか？\n\nWho is cleaning the room?\n部屋を掃除しているのは誰ですか？\n\nWhat are you writing now?\n今何を書いていますか？\n\nIs your teacher in the classroom?\n先生は教室にいますか？\n\nWhat time is it now?\n今何時ですか？\n\nAre you having a lesson now?\n今授業をしていますか？\n\nHow are you feeling in class?\nクラスでどんな気持ちですか？\n"
  },
  {
    "title": "15. School Subjects",
    "content": "📖 I am studying many subjects at school.\n私は学校でたくさんの科目を勉強しています。\n\n🔢 Math is myfavorite subject.\n算数が一番好きな科目です。\n\n🇬🇧 English is very interesting too.\n英語もとても面白いです。\n\n📊 I am learning about numbers in math.\n算数で数字について習っています。\n\n👨‍🏫 My teacher is explaining the lesson.\n先生が授業を説明しています。\n\n📖 We are reading a story in English.\n英語で物語を読んでいます.\n\n🔬 Science is also fun for me.\n理科も私にとっては面白いです.\n\n🎨 Art class is very creative.\n図工の授業はとても創造的です。\n\n🎨 I am drawing a picture now.\n私は今絵を描いています.\n\n😊 Everyone is enjoying the lesson.\nみんな授業を楽しんでいます。\n\nWhat is yourfavorite subject?\n一番好きな科目は何ですか？\n\nWhy do you like math?\nなぜ算数が好きですか？\n\nAre you studying English now?\n今英語を勉強していますか？\n\nWhat are you learning in science?\n理科で何を習っていますか？\n\nIs art class fun for you?\n図工は楽しいですか？\n\nWho is teaching your class?\nあなたのクラスを誰が教えていますか？\n\nWhere are you sitting now?\n今どこに座っていますか？\n\nWhen is your math class?\n算数の授業はいつですか？\n\nHow many subjects do you have?\n科目はいくつありますか？\n\nDo you like school subjects?\n学校の科目は好きですか？\n"
  },
  {
    "title": "16. My Classmates",
    "content": "🧑‍🤝‍🧑 I have many friends in my class.\nクラスの中にたくさん友達がいます。\n\n👦 Tom is sitting next to me.\nトムが私の隣に座っています.\n\n👧 Yuki is my best friend.\nユキは親友です。\n\n😊 She is smiling at me now.\n彼女は今私に微笑んでいます。\n\n💬 We are talking during the break.\n休憩時間に話しています.\n\n🏃‍♂️ Some students are playing outside.\n何人かの学生が外で遊んでいます。\n\n📖 Others are reading books.\n他の人たちは本を読んでいます.\n\n🔊 The classroom is noisy now.\n今教室はうるさいです。\n\n😊 Everyone is happy and relaxed.\nみんな幸せでリラックスしています.\n\n⏰ We are waiting for the next lesson.\n私たちは次の授業を待っています。\n\nWho is your best friend?\n親友は誰ですか？\n\nWhere is Tom sitting?\nトムはどこに座っていますか？\n\nWhat is Yuki doing now?\nユキは今何をしていますか？\n\nAre you talking with friends?\n友達と話していますか？\n\nWhere are some students playing?\n何人かの学生はどこで遊んでいますか？\n\nIs the classroom noisy now?\n今教室はうるさいですか？\n\nHow are you feeling now?\n今どんな気持ちですか？\n\nWhen is the next lesson?\n次の授業はいつですか？\n\nWhat are you doing during the break?\n休憩時間に何をしていますか？\n\nDo you have many friends in class?\nクラスにたくさん友達がいる？\n"
  },
  {
    "title": "17. Golden Week Holiday",
    "content": "🌸 I am enjoying Golden Week with my family this week.\n今週は家族とゴールデンウィークを楽しんでいます.\n\n🏯 We are visiting beautiful temples in Kyoto now.\n私たちは今京都の美しい寺社を訪れています.\n\n📸 My sister is taking many photos of cherry blossoms.\n姉は桜の写真をたくさん撮っています.\n\n👨‍👩‍👧 My parents are walking very slowly in the garden.\n両親は庭で非常にゆっくり歩いています.\n\n🚄 We are travelling by bullet train to Osaka today.\n私たちは今日新幹線で大阪へ旅行しています.\n\n🍜 My friend is eating delicious ramen at a restaurant.\n友達はレストランで美味しいラーメンを食べています.\n\n💰 I am buying some souvenirs for my classmates.\nクラスメートのためにお土産をいくつか買っています.\n\n🌟 The weather is becoming warmer every day this week.\n天気は今週毎日より暖かくなっています.\n\n😄 Everyone is smiling and having fun together.\n全員が笑って一緒に楽しんでいます.\n\n🎉 We are creating wonderful memories on this trip.\n私たちはこの旅行で素晴らしい思い出を作っています.\n\n❓ How are you spending your Golden Week holiday？\nあなたはゴールデンウィーク休暇をどのように過ごしていますか？\n\n🏯 What places are you visiting during your spring break？\n春の休暇中にどのような場所を訪れていますか？\n\n📸 Why is your sister taking so many photos now？\nなぜあなたの姉は今そんなに多くの写真を撮っているのですか？\n\n🍜 What food is your friend eating at the restaurant？\nあなたの友達はレストランでどのような食べ物を食べていますか？\n\n🌸 What are you doing with your family this week？\n今週家族と何をしていますか？\n\n💰 Where are you buying souvenirs for your friends？\n友達のためにどこでお土産を買っていますか？\n\n🌟 How is the weather during your vacation？\nあなたの休暇中の天気はどうですか？\n\n😄 Why is everyone smiling in the photographs？\nなぜ写真の中で全員が笑っていますか？\n\n🚄 What are you doing for transportation this trip？\nこの旅行のためにどのような交通手段をしていますか？\n\n🎉 What memories are you making during Golden Week？\nゴールデンウィーク中にどのような思い出を作っていますか？"
  },
  {
    "title": "18. Spring School Activities",
    "content": "📚 I am studying English very hard this semester.\n今学期英語をとても一生懸命勉強しています.\n\n📝 My teacher is explaining a new grammar point now.\n先生は今新しい文法ポイントを説明しています.\n\n👥 My classmates are listening to the teacher carefully.\nクラスメートたちは先生を注意深く聞いています.\n\n✏️ I am writing answers in my notebook quickly.\n私はノートに答えを素早く書いています.\n\n📖 We are reading an interesting story about spring.\n私たちは春についての興味深い物語を読んでいます.\n\n💻 My partner is using the computer for research today.\nパートナーは今日研究のためにコンピュータを使用しています.\n\n🗣️ I am practising speaking with my friend now.\n私は今友達と話す練習をしています.\n\n✨ Our progress is becoming clear every week.\n私たちの進歩は毎週明確になっています.\n\n🎯 The teacher is giving us helpful advice every day.\n先生は毎日私たちに役立つアドバイスを与えています.\n\n📅 We are preparing for the final exam next month.\n来月の期末試験の準備をしています.\n\n❓ What are you studying at school this semester？\n今学期学校で何を勉強していますか？\n\n📝 How is your teacher explaining today's lesson？\n先生は今日のレッスンをどのように説明していますか？\n\n👥 What are your classmates doing during the lesson？\nレッスン中にあなたのクラスメートたちは何をしていますか？\n\n📖 What story is the class reading together now？\nクラスは今一緒にどのような物語を読んでいますか？\n\n💻 Who is sitting next to the computer in the classroom？\n教室でコンピュータの隣に座っているのは誰ですか？\n\n🗣️ Why are you practising English speaking now？\nなぜ今英語のスピーキングを練習していますか？\n\n✨ How is your English improving this semester？\n今学期あなたの英語はどのように改善していますか？\n\n🎯 What is the most helpful thing your teacher does？\n先生がする最も役立つことは何ですか？\n\n📅 When are you taking your next school exam？\n次の学校の試験をいつ受けていますか？\n\n🎯 Why are exam preparations important for students？\nなぜ試験の準備は学生にとって重要ですか？"
  },
  {
    "title": "19. Spring Outdoor Fun",
    "content": "🌿 I am walking in the park with my dog now.\n私は今公園で犬と散歩しています.\n\n🌸 The cherry blossoms are blooming beautifully everywhere.\n桜はどこにでも美しく咲いています.\n\n🦋 Butterflies are flying around the flowers now.\n蝶が今花の周りを飛んでいます.\n\n🧢 My friend is wearing a new hat today.\n友達は今日新しい帽子をかぶっています.\n\n🥾 We are hiking up the small hill this morning.\n私たちは今朝小さな丘をハイキングしています.\n\n☀️ The sun is shining brightly in the blue sky.\n太陽が青い空で明るく輝いています.\n\n📱 I am taking photos of the lovely scenery.\n私は愛らしい景色の写真を撮っています.\n\n🎵 Birds are singing sweet songs in the trees.\n鳥が木の中で甘い歌を歌っています.\n\n🌱 New plants are growing fast in the garden.\n庭で新しい植物が急速に育っています.\n\n😄 We are enjoying the lovely spring day outdoors.\n私たちは屋外で愛らしい春の日を楽しんでいます.\n\n❓ What are you doing outdoors this spring weekend？\n今春の週末屋外で何をしていますか？\n\n🌸 What flowers are blooming in your area now？\nあなたの地域で今どのような花が咲いていますか？\n\n🦋 Where are the butterflies flying around？\n蝶はどこを飛び回っていますか？\n\n🥾 What are you and your friends doing this morning？\n今朝あなたと友達は何をしていますか？\n\n☀️ What is the weather like outside today？\n今日の外の天気はどのようですか？\n\n📱 Why are you taking photos with your phone？\nなぜスマホで写真を撮っていますか？\n\n🌱 How are plants changing in the spring season？\n春の季節に植物はどのように変化していますか？\n\n😄 Why are you smiling in this photo？\nなぜこの写真の中で笑っていますか？\n\n🎵 What animals are making sounds in nature？\n自然の中でどの動物が音を立てていますか？\n\n🌿 What outdoor activities are popular in spring？\n春にどのような屋外活動が人気がありますか？"
  },
  {
    "title": "20. May Family Time",
    "content": "👨‍👩‍👧 My family is spending time together this afternoon.\n私の家族は今午後一緒に時間を過ごしています.\n\n🍳 My mother is cooking dinner in the kitchen now.\n母は今台所で夕食を料理しています.\n\n📚 My younger brother is reading a book in his room.\n弟は自分の部屋で本を読んでいます.\n\n📺 My father is watching a football match on television.\n父はテレビでサッカーの試合を見ています.\n\n🐕 Our dog is sleeping peacefully in the living room.\n私たちの犬はリビングで平和に眠っています.\n\n🧘 I am doing my homework at the desk now.\n私は今机宿題をしています.\n\n📞 My grandmother is talking on the phone happily.\n祖母は電話で幸せに話しています.\n\n🎵 My sister is listening to music in her bedroom.\n姉は自分の寝室で音楽を聴いています.\n\n🌸 We are looking at the garden through the window.\n私たちは窓越しに庭を見ています.\n\n🏡 Our home is feeling very warm and peaceful today.\n私たちの家は今日とても温かく平和な気配です.\n\n❓ What is your family doing together this weekend？\n今週末あなたの家族は一緒に何をしていますか？\n\n🍳 What is your mother cooking in the kitchen now？\nあなたの母は今台所で何を料理していますか？\n\n📺 What is your father watching on television？\nあなたの父はテレビで何を見ていますか？\n\n📚 What is your brother reading in his room？\nあなたの弟は部屋で何を読んでいますか？\n\n🐕 Where is your pet sleeping now？\nあなたのペットは今どこで眠っていますか？\n\n📞 Who is talking on the phone in your house？\nあなたの家で誰が電話で話していますか？\n\n🧘 Why are you studying at your desk now？\nなぜ今机で勉強していますか？\n\n🎵 What kind of music is your sister listening to？\nあなたの姉はどのような種類の音楽を聴いていますか？\n\n🌸 What are you looking at through the window？\n窓越しに何を見ていますか？\n\n🏡 How is your family spending quality time together？\nあなたの家族はどのように一緒に質の高い時間を過ごしていますか？"
  },
  {
    "title": "21. Rainy Day Inside",
    "content": "🌧️ It is raining heavily outside my window today.\n今日私の窓の外では激しく雨が降っています.\n\n☔ I am staying inside my house because of the rain.\n雨のために私は家の中にいます.\n\n📺 My brother is watching an interesting film on television.\n弟はテレビで面白い映画を見ています.\n\n🧸 My little sister is playing with her toys in the bedroom.\n妹は寝室でおもちゃで遊んでいます.\n\n🍜 My mother is making a warm noodle soup for lunch.\n母は昼食のために温かい麺料理を作っています.\n\n☕ I am drinking a cup of hot tea right now.\n私は今熱いお茶を一杯飲んでいます.\n\n📖 I am reading a story book about rainy days.\n私は雨の日についての物語の本を読んでいます.\n\n🎶 My father is listening to jazz music in the living room.\n父はリビングでジャズ音楽を聴いています.\n\n🌙 The rain is making the evening peaceful and quiet.\n雨は夕暮れを平和で静かにしています.\n\n😊 I am feeling very relaxed and happy at home.\n家でとてもリラックスして幸せな気分です.\n\n❓ What is the weather like outside your home today？\n今日あなたの家の外の天気はどうですか？\n\n🌧️ Why are you staying inside instead of going out？\nなぜ外に出る代わりに中に留まっているのですか？\n\n📺 What is your family watching on television today？\nあなたの家族は今日テレビで何を見ていますか？\n\n📖 What book are you reading during the rainy day？\n雨の日にどのような本を読んでいますか？\n\n🍜 What food is your mother cooking in the kitchen？\nあなたの母は台所で何を料理していますか？\n\n☕ What hot drink are you drinking right now？\n今どのような熱い飲み物を飲んでいますか？\n\n🎶 What music is your father listening to now？\nあなたの父は今どのような音楽を聴いていますか？\n\n🌙 How is the weather making you feel today？\n天気は今日あなたをどのように感じさせていますか？\n\n😊 Why are you feeling relaxed at home today？\nなぜ今日家でリラックスしているのですか？\n\n🧸 What indoor activities do children enjoy on rainy days？\n雨の日に子供たちはどのような屋内活動を楽しんでいますか？"
  },
  {
    "title": "22. Indoor Hobbies",
    "content": "🎨 I am painting a picture of a rainy afternoon.\n私は雨の午後の絵を描いています.\n\n🧩 My cousin is doing a jigsaw puzzle on the table.\n従兄弟はテーブルでジグソーパズルをしています.\n\n👩‍💻 My friend is learning how to use computer software.\n友達はコンピュータソフトウェアの使い方を学んでいる.\n\n🎭 My sister is practising a drama script now.\n姉は今ドラマの台本を練習しています.\n\n📱 I am using a new app for English learning practice.\n私は英語学習の練習のために新しいアプリを使っている.\n\n🥁 My brother is playing the drums in his room.\n弟は自分の部屋でドラムを演奏している.\n\n🧵 My grandmother is teaching me how to sew.\n祖母は私に縫い方を教えている.\n\n🎵 I am listening to English songs for fun.\n楽しみのために英語の曲を聴いている.\n\n✍️ My friend is writing a story about her summer vacation.\n友達は彼女の夏休みについての物語を書いている.\n\n🎉 We are enjoying our indoor hobbies very much.\n私たちは自分たちの屋内の趣味をとても楽しんでいる.\n\n❓ What hobby are you practising today？\n今日どのような趣味を練習していますか？\n\n🎨 Why are you painting pictures of the rainy weather？\nなぜ雨の天気の絵を描いているのですか？\n\n🧩 What puzzle is your cousin doing on the table？\nあなたの従兄弟はテーブルでどのパズルをしていますか？\n\n🥁 Who is playing music in your house？\nあなたの家で誰が音楽を演奏していますか？\n\n🧵 What is your grandmother teaching you now？\n祖母は今あなたに何を教えていますか？\n\n📱 What app are you using for your studies？\n 学習のためにどのアプリを使用していますか？\n\n✍️ What story is your friend writing now？\nあなたの友達は今どのような物語を書いていますか？\n\n🎵 Why are you listening to music right now？\nなぜ今音楽を聴いているのですか？\n\n🎉 What are you enjoying most about your hobbies？\nあなたの趣味の最も楽しんでいることは何ですか？\n\n🎭 What indoor activities do you like on rainy days？\n雨の日にどのような屋内活動が好きですか？"
  },
  {
    "title": "23. Shopping Indoors",
    "content": "🛍️ I am shopping at a big shopping mall today.\n私は今日大きなショッピングモールで買い物をしています.\n\n👗 My sister is looking at summer dresses in the shop.\n姉は店で夏のワンピースを見ています.\n\n👟 I am trying on new trainers for sports.\n私はスポーツのために新しいスニーカーを試着しています.\n\n👜 My friend is buying a new school bag now.\n友達は今新しい学校のバッグを買っています.\n\n👓 My father is choosing reading glasses at the store.\n父は店で読書用の眼鏡を選んでいます.\n\n💳 I am paying for my purchases with a credit card.\n私はクレジットカードで購入品を支払っています.\n\n🍦 We are eating ice cream at the food court.\n私たちはフードコートでアイスクリームを食べています.\n\n👥 Many people are shopping because of the rain.\n多くの人々が雨のために買い物をしています.\n\n🌂 The mall is full of people with umbrellas.\nモールは傘を持った人々でいっぱいです.\n\n😌 I am feeling happy about my new purchases.\n私は新しい購入品について幸せな気分です.\n\n❓ Where are you shopping this afternoon？\n今午後どこで買い物をしていますか？\n\n👗 What is your sister looking at in the shop？\nあなたの姉は店で何を見ていますか？\n\n👟 What are you trying on at the shoe shop？\n靴店で何を試着していますか？\n\n💳 How are you paying for your shopping？\n買い物をどのように支払っていますか？\n\n🍦 What are you eating at the food court？\nフードコートで何を食べていますか？\n\n🌂 Why are there so many umbrellas today？\nなぜ今日そんなに多くの傘がありますか？\n\n👥 Why are many people shopping indoors today？\nなぜ今日多くの人々が屋内で買い物をしていますか？\n\n😄 Why are you feeling happy about your shopping？\nなぜ買い物について幸せな気分ですか？\n\n👜 Who is shopping with you today？\n今日あなたと一緒に買い物をしているのは誰ですか？\n\n🛍️ What do you like about shopping in malls？\nモールでの買い物の何が好きですか？"
  },
  {
    "title": "24. Summer Preparation",
    "content": "☀️ I am preparing for the summer season now.\n私は今夏のシーズンの準備をしています.\n\n🏊 I am practising swimming every week this month.\n今月毎週水泳の練習をしています.\n\n👕 I am buying some new clothes for hot weather.\n暑い天気のために新しい服をいくつか買っています.\n\n🌴 I am dreaming about a beach holiday vacation.\n私はビーチの休暇の休暇について夢見ています.\n\n🎫 I am planning a trip with my school friends.\n私は学校の友達と旅行の計画を立てています.\n\n🍉 I am eating delicious summer fruits every day.\n毎日美味しい夏果物を食べています.\n\n🌺 My mother is planting flowers in the garden.\n母は庭に花を植えています.\n\n🏕️ My family is planning a camping trip soon.\n私の家族はまもなくキャンプ旅行を計画しています.\n\n🎆 I am looking forward to summer fireworks festivals.\n私は夏の花火大会を楽しみにしています.\n\n✨ I am feeling very excited about the coming summer.\n来る夏についてとても興奮しています.\n\n❓ What are you doing to prepare for summer？\n夏のために何をしていますか？\n\n🏊 How often are you practising swimming？\nどのくらい頻繁に水泳の練習をしていますか？\n\n👕 What clothes are you buying for the hot weather？\n暑い天気のためにどのような服を買っていますか？\n\n🌴 Where are you planning to go for summer vacation？\n夏の休暇のためにどこへ行く計画を立てていますか？\n\n🎫 What are you planning with your friends for summer？\n友達と夏に何を計画していますか？\n\n🍉 What summer fruit are you eating this week？\n今週どのような夏果物を食べていますか？\n\n🌺 What is your mother planting in the garden？\nあなたの母は庭に何を植えていますか？\n\n🏕️ What is your family planning for the summer？\nあなたの家族は夏のために何を計画していますか？\n\n🎆 What summer event are you looking forward to most？\n夏のイベントで最も楽しみにしているのは何ですか？\n\n✨ Why are you feeling excited about the coming summer？\nなぜ来る夏について興奮していますか？"
  },
  {
    "title": "25. Summer Holiday (Present Continuous / Wh-Questions)",
    "content": "🌅 We are planning a holiday for this summer.\n私たちは今年の夏の休暇を計画しています.\n✈️ Where are you going for your vacation？\nあなたは休暇にどこへ行きますか？\n🏨 I am looking for a hotel near the beach.\n私はビーチの近くのホテルを探しています.\n🌴 Are you swimming in the sea this year？\nあなたは今年海で泳ぎますか？\n📸 My sister is taking photos of the beautiful ocean.\n私の妹は美しい海の写真を撮っています.\n🍦 What are you doing on the beach？\nビーチで何をしていますか？\n🎫 We are buying tickets for the boat tour.\n私たちはボートツアーのチケットを買っています.\n🥾 Who is hiking on the mountain with us？\n誰と私たちと一緒に山を登っていますか？\n🗺️ I am reading a map of the island.\n私は島の地図を読んでいます.\n😊 Are you enjoying your summer holiday？\nあなたは夏休みを楽しんでいますか？\n🌅 When is your holiday starting？\nあなたの休暇はいつ始まりますか？\n✈️ How long are you staying there？\nあなたはそこにどのくらい滞在しますか？\n🏨 Is your hotel big or small？\nあなたのホテルは大きいですか、それとも小さいですか？\n🌴 Who are you going with？\nあなたは誰と一緒に行きますか？\n📸 What camera are you using？\n何のカメラを使っていますか？\n🍦 Are you eating ice cream now？\n今アイスクリームを食べていますか？\n🎫 How much are the tickets？\nチケットはいくらですか？\n🥾 Why are you wearing boots？\nなぜブーツを履いているのですか？\n🗺️ Where is the hotel located？\nホテルはどこに位置していますか？\n😊 Are you happy about your holiday plans？\nあなたの休暇計画について満足していますか？"
  },
  {
    "title": "26. Beach Day (Present Continuous / Be-Verb)",
    "content": "🌊 We are walking on the sand at the beach.\n私たちはビーチの砂の上を歩いています.\n🏖️ The sun is shining brightly today.\n今日は太陽が明るく輝いています.\n☀️ I am watching the children playing in the water.\n私は水の中で遊んでいる子供たちを見ています.\n🏊 My brother is swimming in the sea.\n私の兄は海で泳いでいます.\n🍦 Are you hungry and eating ice cream？\nあなたはお腹が空いていてアイスクリームを食べていますか？\n🚗 Many people are driving to the beach today.\n今日、多くの人々が車でビーチに来ています.\n⛱️ We are sitting under a big umbrella.\n私たちは大きな傘の下に座っています.\n🥪 What are you eating for lunch？\n昼食に何を食べていますか？\n🏩 The restaurant is serving fresh fish.\nレストランは新鮮な魚を出しています.\n🌅 The sun is setting in the west.\n太陽は西に沈んでいます.\n🌊 What are you doing at the beach？\nビーチで何をしていますか？\n🏖️ Is it hot or cold today？\n今日は暑いですか、それとも寒いですか？\n☀️ Where are your friends playing？\nあなたの友人たちはどこで遊んでいますか？\n🏊 Who is swimming with you？\n誰とあなたと一緒に泳いでいますか？\n🍦 What flavour ice cream do you like？\nどんなフレーバーのアイスクリームが好きですか？\n🚗 How is the traffic today？\n今日の交通はどうですか？\n⛱️ Why are you sitting in the shade？\nなぜ日陰で座っているのですか？\n🥪 Is the food delicious？\n食べ物は美味しいですか？\n🏩 Where is the restaurant？\nレストランはどこですか？\n🌅 Are you tired after the beach day？\nビーチの日の後、疲れていますか？"
  },
  {
    "title": "27. Mountain Hiking (Present Continuous / Wh-Questions)",
    "content": "🏔️ We are climbing the mountain today.\n私たちは今日山を登っています.\n🥾 I am wearing comfortable hiking shoes.\n私は快適なハイキング靴を履いています.\n🗺️ My friend is looking at the map.\n私の友人は地図を見ています.\n⛈️ Is it raining on the mountain？\n山で雨が降っていますか？\n🏕️ We are walking on the mountain path.\n私たちは山道を歩いています.\n🌲 What animals are you seeing in the forest？\n森でどんな動物を見ていますか？\n🎒 My backpack is heavy with snacks and water.\nスナックと水で私のリュックは重い.\n🥶 Are you cold at the top of the mountain？\n山の頂上で寒いですか？\n🌲 The birds are singing in the trees.\n鳥たちは木々の中でさえずっています.\n🌟 The view from the top is beautiful.\n山頂からの景色は美しい.\n🏔️ Where are you hiking today？\nあなたは今日どこをハイキングしていますか？\n🥾 What are you wearing on your feet？\n足に何を履いていますか？\n🗺️ Who is reading the map？\n誰が地図を読んでいますか？\n⛈️ How is the weather on the mountain？\n山の天気はどうですか？\n🏕️ What is in your backpack？\nあなたのリュックの中には何がありますか？\n🌲 Are the trees tall or short？\n木々は背高いですか、それとも低いですか？\n🎒 Is your bag heavy or light？\nあなたのバッグは重いですか、それとも軽いですか？\n🥶 Why are you putting on a jacket？\nなぜジャケットを着ているのですか？\n🌟 What can you see from the mountain top？\n山頂から何を見ることができますか？\n🌟 Are you enjoying the hike？\nあなたはハイキングを楽しんでいますか？"
  },
  {
    "title": "28. Summer Festival (Present Continuous / Be-Verb)",
    "content": "🎏 Our town is having a summer festival.\n私たちの町は夏祭りを開催しています.\n🍜 People are eating delicious food at the stalls.\n人々は屋台で美味しい食べ物を食べています.\n🎶 The band is playing traditional music.\n楽団は伝統的な音楽を演奏しています.\n🎎 My sister is dancing in the festival show.\n私の妹は祭りのショーで踊っています.\n🏮 The lanterns are hanging in the streets.\n灯籠は通りに掛かっています.\n🎉 Everyone is enjoying the festival atmosphere.\n全員が祭りの雰囲気を楽しんでいます.\n🎫 Is the entrance ticket expensive？\n入場チケットは高いですか？\n🚮 Where are you putting your rubbish？\nあなたのゴミをどこに置いていますか？\n🎇 The fireworks are starting now.\n花火が今始まっています.\n📸 I am taking photos of the festival.\n私は祭りの写真を撮っています.\n🎏 What is happening in your town？\nあなたの町で何が起きていますか？\n🍜 Where are the food stalls？\n食品屋台はどこですか？\n🎶 Who is playing the music？\n誰が音楽を演奏していますか？\n🎎 Are you dancing or watching？\nあなたは踊っていますか、それとも見ていますか？\n🏮 Are the lanterns beautiful？\n灯籠は美しいですか？\n🎉 Are you happy at the festival？\nあなたは祭りで幸せですか？\n🎫 How much money are you spending？\nいくら使っていますか？\n🚮 What are you doing with your rubbish？\nあなたはあなたのゴミで何をしていますか？\n🎇 What color are the fireworks？\n花火は何色ですか？\n📸 Are you taking many photos？\nあなたは多くの写真を撮っていますか？"
  },
  {
    "title": "29. Obon Holiday (Present Continuous / Wh-Questions)",
    "content": "👻 Our family is celebrating Obon this week.\n私の家族は今週盆を祝っています.\n🕯️ I am lighting a lantern for our ancestors.\n私は先祖のために灯籠をともしています.\n🎶 The music is playing in the temple.\nお寺で音楽が流れています.\n🍚 My mother is cooking special food.\n私の母は特別な食べ物を料理しています.\n🚢 We are watching the lanterns on the river.\n私たちは川の灯籠を見ています.\n🎭 Children are dancing the traditional dance.\n子供たちは伝統的なダンスを踊っています.\n🏮 Where are the lanterns hanging？\n灯籠はどこに掛かっていますか？\n🌙 It is getting dark in the evening.\n夜に暗くなってきています.\n✨ The fireworks are starting now.\n花火が今始まりました.\n💖 I am thinking about my family.\n私は私の家族について考えています.\n👻 What are you doing for Obon？\nあなたは盆のために何をしていますか？\n🕯️ Who is cooking the food？\n誰が食べ物を料理していますか？\n🎶 Where is the music coming from？\n音楽はどこから来ていますか？\n🍚 What are you eating for Obon？\nあなたは盆のために何を食べていますか？\n🚢 Are the lanterns beautiful？\n灯籠は美しいですか？\n🎭 Is the dance easy or difficult？\nダンスは簡単ですか、それとも難しいですか？\n🏮 What color are the lanterns？\n灯籠は何色ですか？\n🌙 Is it night or daytime？\n夜ですか、それとも昼ですか？\n✨ Are you watching the fireworks？\nあなたは花火を見ていますか？\n💖 Are you happy with your family？\nあなたは家族と一緒に幸せですか？"
  },
  {
    "title": "30. Summer Fireworks (Present Continuous / Wh-Questions)",
    "content": "🎆 We are waiting for the fireworks to start.\n私たちは花火が始まるのを待っています.\n💥 The noise is very loud today.\n今日はノイズがとても大きい.\n👶 Children are looking at the sky.\n子供たちは空を見ています.\n🌃 Many people are standing in the park.\n多くの人々が公園に立っています.\n💔 My dog is hiding in the house.\n私の犬は家に隠れています.\n🎇 What color are the fireworks？\n花火は何色ですか？\n🎉 The show is ending now.\nショーが今終わっている.\n🏙️ The city is bright with fireworks.\n都市は花火で明るい.\n✨ Everyone is clapping their hands.\n全員が手を叩いています.\n🎆 Are you excited about the fireworks？\nあなたは花火について興奮していますか？\n💥 Where are you standing？\nあなたはどこに立っていますか？\n👶 Who are you with？\nあなたは誰と一緒ですか？\n🌃 Is the park crowded？\n公園は混雑していますか？\n💔 Is your dog scared？\nあなたの犬は怖がっていますか？\n🎇 What are you looking at？\nあなたは何を見ていますか？\n🎉 Is the show long or short？\nショーは長いですか、それとも短いですか？\n🏙️ What can you see in the sky？\n空に何が見えますか？\n✨ Are you enjoying the fireworks？\nあなたは花火を楽しんでいますか？\n🎆 When is the next show？\n次のショーはいつですか？"
  },
  {
    "title": "31. Late Summer Heat (Present Continuous / Be-Verb)",
    "content": "🌡️ It is very hot this week.\n今週はとても暑い.\n☀️ The sun is shining all day.\n太陽は一日中中輝いている.\n🏙️ People are walking in the heat.\n人々は暑さの中で歩いている.\n💧 I am drinking cold water.\n私は冷たい水を飲んでいます.\n🌲 Trees are giving us shade.\n木々が私たちに日陰を与えています.\n💷 My family is using the air conditioner.\n私の家族はエアコンを使っています.\n🚿 I am taking a cool shower.\n私は涼しいシャワーを浴びています.\n🌅 The day is long in summer.\n夏は日が長い.\n🍶 Everyone is eating ice cream.\n全員がアイスクリームを食べている.\n🌡️ How is the weather today？\n今日の天気はどうですか？\n☀️ Is it hot or cold？\n暑いですか、それとも寒いですか？\n🏙️ Where are you walking now？\n今どこを歩いていますか？\n💧 What are you drinking？\n何を飲んでいますか？\n🌲 Are the trees tall？\n木々は背高いですか？\n💷 Is the air conditioner on？\nエアコンはついていますか？\n🚿 Are you taking a shower？\nあなたはシャワーを浴びていますか？\n🌅 Why is the sunset late？\nなぜ日没は遅いのですか？\n🍶 What flavour ice cream do you like？\nどんなフレーバーのアイスクリームが好きですか？\n🌡️ Are you hot today？\nあなたは今日暑いですか？"
  },
  {
    "title": "32. Back to School (Present Continuous / Wh-Questions)",
    "content": "📚 I am preparing for school today.\n私は今日学校の準備をしています.\n🎒 My mother is buying a new bag for me.\n私の母は私のために新しいバッグを買っています.\n📏 The teacher is writing on the blackboard.\n先生は黒板に書いています.\n🚌 The bus is coming to our stop.\nバスが私たちのバス停に来ています.\n📖 I am reading a new book.\n私は新しい本を読んでいます.\n🌟 My friends are waiting at school.\n私の友人たちは学校で待っています.\n📝 I am doing my homework now.\n私は今宿題をしています.\n🏫 The school building is very big.\n学校の建物はとても大きい.\n😊 We are meeting new friends.\n私たちは新しい友人たちに会っています.\n🎨 We are painting pictures in art class.\n美術のクラスで絵を描いています.\n📚 What are you studying at school？\nあなたは学校で何を勉強していますか？\n🎒 Is your school bag new？\nあなたのスクールバッグは新しいですか？\n📏 Who is your teacher？\nあなたの先生は誰ですか？\n🚌 Are you taking the bus？\nあなたはバスに乗っていますか？\n📖 What book are you reading？\nあなたは何の本を読んでいますか？\n🌟 Where are your friends？\nあなたの友人たちはどこですか？\n📝 Is homework easy or difficult？\n宿題は簡単ですか、それとも難しいですか？\n🏫 Is your school big or small？\nあなたの学校は大きいですか、それとも小さいですか？\n😊 Are you happy at school？\nあなたは学校で幸せですか？\n🎨 What are you drawing？\nあなたは何を描いていますか？"
  },
  {
    "title": "33. Autumn Begins (Present continuous, wh-questions, be-verb)",
    "content": "🎒 I am walking in the beautiful park now.\\n今、美しい公園を歩いています。\\n📖 The leaves on the trees are changing color.\\n木の葉は色を変えています。\\n✏️ The weather is getting cooler every day.\\n天気は毎日涼しくなっています。\\n🏠 My family is preparing for autumn.\\n私の家族は秋の準備をしています。\\n💡 I am feeling very happy today.\\n今日とても幸せに感じています。\\n🎒 What are you doing this afternoon?\\n今日の午後は何をしていますか？\\n📖 Why are the leaves changing color?\\nなぜ葉は色を変えているのですか？\\n✏️ How is the weather today?\\n今日の天気はどうですか？\\n🏠 Where are your friends playing?\\n友達はどこで遊んでいますか？\\n💡 Are you feeling well today?\\n今日気分はいいですか？"
  },
  {
    "title": "34. Typhoon Season (Present continuous, wh-questions, be-verb)",
    "content": "🎒 It is raining heavily outside right now.\\n外では激しく雨が降っています。\\n📖 The wind is blowing very strongly.\\n風がとても強く吹いています。\\n✏️ I am staying inside my house.\\n家の中にいます。\\n🏠 You should be careful today.\\n今日は注意すべきです。\\n💡 We are watching the news.\\nニュースを見ています。\\n🎒 What is happening outside?\\n外で何が起きていますか？\\n📖 Why is the wind so strong?\\nなぜ風はそんなに強いのですか？\\n✏️ Where are you staying?\\nどこにいますか？\\n🏠 Is it safe to go out?\\n外出するのは安全ですか？\\n💡 What should we do?\\n私たちは何をすべきですか？"
  },
  {
    "title": "35. Back to School (Present continuous, wh-questions, be-verb)",
    "content": "🎒 I am going to school every morning.\\n毎朝学校に行っています。\\n📖 My teacher is teaching English now.\\n先生は今英語を教えています。\\n✏️ My classmates are studying hard.\\nクラスメートたちは一生懸命勉強しています。\\n🏠 School is starting in September.\\n学校は9月に始まります。\\n💡 I am feeling excited today.\\n今日興奮しています。\\n🎒 Where are you going now?\\n今どこに行っていますか？\\n📖 Who is your new teacher?\\n新しい先生は誰ですか？\\n✏️ What are you studying in class?\\nクラスで何を勉強していますか？\\n🏠 When does school start?\\n学校はいつ始まりますか？\\n💡 Are you feeling happy?\\n幸せを感じていますか？"
  },
  {
    "title": "36. Harvest Festivals (Present continuous, wh-questions, be-verb)",
    "content": "🎒 People are celebrating autumn festivals.\\n人々は秋の祭りを祝っています。\\n📖 Farmers are harvesting their crops.\\n農家は作物を収作物を収穫しています。\\n✏️ We are eating traditional food together.\\n一緒に伝統的な食べ物を食べています。\\n🏠 Everyone is singing and dancing.\\nみんな歌って踊っています。\\n💡 The festival is very enjoyable.\\n祭りはとても楽しいです。\\n🎒 What are people eating?\\n人々は何を食べていますか？\\n📖 Who is singing at the festival?\\n祭りで誰が歌っていますか？\\n✏️ Where is the harvest celebration?\\n収穫祭はどこにありますか？\\n🏠 Are you enjoying the festival?\\n祭りを楽しんでいますか？\\n💡 What time is the festival starting?\\n祭りは何時に始まりますか？"
  },
  {
    "title": "37. Halloween (Present continuous, wh-questions, be-verb)",
    "content": "🎒 Children are wearing funny costumes.\\n子供たちは面白い衣装を着ています。\\n📖 They are visiting many houses.\\n多くの家を訪問しています。\\n✏️ They are saying trick or treat.\\nトリックオアトリートと言っています。\\n🏠 Everyone is eating sweet candy.\\nみんな甘いお菓子を食べています。\\n💡 Halloween is exciting today.\\n今日のハロウィンはエキサイティングです。\\n🎒 What are you wearing for Halloween?\\nハロウィンで何を着ていますか？\\n📖 Where are the children going?\\n子供たちはどこへ行っていますか？\\n✏️ What are they saying?\\n彼らは何と言っていますか？\\n🏠 What are you eating?\\n何を食べていますか？\\n💡 Are you feeling happy?\\n幸せに感じていますか？"
  },
  {
    "title": "38. Autumn Leaves (Koyo) (Present continuous, wh-questions, be-verb)",
    "content": "🎒 The leaves are turning red and yellow.\\n葉は赤と黄色に変わっています。\\n📖 Tourists are visiting the mountains.\\n観光客は山を訪問しています。\\n✏️ I am taking many beautiful photos.\\n美しい写真をたくさん撮っています。\\n🏠 The colors are very pretty.\\n色はとてもきれいです。\\n💡 Autumn is beautiful this year.\\n今年の秋は美しいです。\\n🎒 What colors are the leaves?\\n葉は何色ですか？\\n📖 Where are tourists going today?\\n観光客は今日どこへ行っていますか？\\n✏️ What are photographing?\\n何を写真に撮っていますか？\\n🏠 Are the leaves beautiful?\\n葉は美しいですか？\\n💡 Where is the best view?\\n最高の景色はどこにありますか？"
  },
  {
    "title": "39. Moon Viewing (Present continuous, wh-questions, be-verb)",
    "content": "🎒 We are looking at the full moon.\\n私たちは満月を見ています。\\n📖 The moon is shining very brightly.\\n月はとても明るく輝いています。\\n✏️ Families are sitting outside together.\\n家族は外に一緒に座っています。\\n🏠 We are eating special moon cakes.\\n特別な月餅を食べています。\\n💡 The night feels very peaceful.\\n夜はとても平和に感じます。\\n🎒 Where do we watch the moon?\\nどこで月を見ますか？\\n📖 What is the moon doing?\\n月は何をしていますか？\\n✏️ What are we eating?\\n何を食べていますか？\\n🏠 Where are you sitting?\\nどこに座っていますか？\\n💡 How do you feel tonight?\\n今夜はどう感じていますか？"
  },
  {
    "title": "40. Cooler Temperatures (Present continuous, wh-questions, be-verb)",
    "content": "🎒 I am wearing my warm coat.\\n暖かいコートを着ています。\\n📖 The wind is blowing cold air.\\n風は冷たい空気を吹かせています。\\n✏️ People are buying warmer clothes.\\n人々は暖かい服を買っています。\\n🏠 Winter is coming soon very soon.\\n冬はもうすぐ来ます。\\n💡 I am feeling cold today.\\n今日寒く感じています。\\n🎒 What are you wearing?\\n何を着ていますか？\\n📖 How is the weather?\\n天気はどうですか？\\n✏️ Why are people buying coats?\\nなぜ人々はコートを買っているのですか？\\n🏠 Is winter coming soon?\\n冬はすぐに来ますか？\\n💡 How do you feel?\\nどう感じていますか？"
  },
  {
    "title": "41. Fall Weather (Present Continuous + BE)",
    "content": "🍊 Where is that orange leaf falling?\nあのオレンジ色の葉はどこに落ちていますか？\n🌧️ It is raining and we are staying inside today.\n雨が降っていて、私たちは今日家にいます.\n🍁 I am looking at the colorful autumn trees.\n私は色とりどりの秋の木を見ています.\n🌬️ The wind is blowing the leaves around.\n風が葉を吹き回しています.\n🌡️ Is it getting colder in your town?\nあなたの町は寒くなっていますか？\n🧥 We are wearing warm sweaters and coats.\n私たちは暖かいセーターとコートを着ています.\n🍂 Where are the leaves falling?\nどこに葉が落ちていますか？\n☁️ The sky is becoming cloudy and gray.\n空は曇って灰色になりつつあります.\n❄️ It is not snowing yet, but it is cold.\nまだ雪は降っていませんが、寒いです.\n🏠 Where are you going on this windy day?\nこの風の強い日はどこに行きますか？\n🍁 Do you like the colors of autumn or spring colors more？\n秋の色と春の色のどちらが好きですか？\n🌧️ Is it raining or snowing in your area now？\nあなたの地域では今雨が降っていますか、それとも雪が降っていますか？\n🌡️ What are you wearing today for the weather？\n今日は天気のために何を着ていますか？\n🌬️ Where are the birds flying to in autumn？\n秋に鳥はどこへ飛んでいますか？\n🍂 Why are the leaves falling from the trees？\nなぜ木から葉が落ちているのですか？\n🏠 Are you staying inside or going out today？\n今日は家にいますか、それとも出かけますか？\n☁️ Is the weather nice for outdoor activities today？\n今日は屋外活動のために天気は良いですか？\n🧥 What are you eating in the autumn？\n秋に何を食べていますか？\n❄️ Are you happy with the November weather？\n11月の天気に満足していますか？\n🌟 Why is autumn a special season for you？\nなぜ秋はあなたにとって特別な季節ですか？"
  },
  {
    "title": "42. School in November (Present Continuous + BE)",
    "content": "📚 We are studying English in class now.\n私たちは今、授業で英語を勉強しています.\n👩‍🏫 The teacher is writing on the blackboard.\n先生は黒板に書き込んでいます.\n✏️ I am writing in my notebook today.\n私は今日ノートに書いています.\n🔤 Who is sitting next to you？\n誰が隣に座っていますか？\n👩‍🎓 We are learning about autumn vocabulary.\n私たちは秋のボキャブラリーについて学んでいます.\n📖 Where are you putting your backpack？\nあなたはバックパックをどこに置いていますか？\n🎒 The students are working hard today.\n生徒たちは今日一生懸命働いています.\n🤔 Are you understanding the lesson？\n授業は理解していますか？\n📝 Where is your homework assignment？\nあなたの宿題の課題はどこにありますか？\n🎨 The art class is drawing pictures of leaves.\n美術のクラスは葉の絵を描いています.\n📚 What are you learning in English class？\n英語の授業で何を学んでいますか？\n👩‍🏫 Is your teacher teaching or explaining today？\nあなたの先生は今日教えていますか、それとも説明していますか？\n✏️ Why are you writing notes today？\n今日ノートを取っていますか？\n🔤 Where are your classmates sitting now？\nあなたの同級生たちは今どこに座っていますか？\n👩‍🎓 Are you enjoying school in November？\n11月は学校を楽しんでいますか？\n📖 What is your favorite subject this month？\n今月のお気に入りの科目は何ですか？\n🎒 Is your backpack heavy or light？\nあなたのバックパックは重いですか、それとも軽いですか？\n🤔 Are you listening carefully to the teacher？\n先生の話を注意深く聞いていますか？\n📝 What are you drawing today？\n今日は何を描いていますか？\n🎨 Is the art class painting or drawing？\n美術のクラスは絵を描いていますか、それとも描いていますか？"
  },
  {
    "title": "43. November Activities (Present Continuous + BE)",
    "content": "🍎 Where is that apple coming from？ あのリンゴはどこから来ていますか？\n🥧 My mother is making apple pie now. 母は今アップルパイを作っています.\n🍽️ What are you eating for breakfast？ 朝食に何を食べていますか？\n👨‍👩‍👧‍👦 My family is cooking dinner together. 私の家族は一緒に夕食を料理しています.\n🌽 Who is picking vegetables in the garden？ 庭で野菜を摘んでいるのは誰ですか？\n🥕 The farmers are harvesting autumn crops. 農家たちは秋の作物を収穫しています.\n🍯 We are buying honey at the market. 私たちは市場で蜂蜜を買っています.\n🍎 Why are you choosing that apple？ なぜそのリンゴを選んでいるのですか？\n🥣 What is in the soup？ スープには何が入っていますか？\n🍂 Where is the wind blowing the leaves？ 風は葉をどこに吹いていますか？\n🍎 Is the apple sweet or sour？ リンゴは甘いですか、それとも酸っぱいですか？\n🥧 Who is cooking the best dishes？ 最高の料理を料理しているのは誰ですか？\n🍽️ Are you hungry or thirsty？ 空腹ですか、それとも喉が渇いていますか？\n👨‍👩‍👧‍👦 Is your family eating together tonight？ 今夜、家族は一緒に食事をしていますか？\n🌽 What vegetables are eating in fall？ 秋にどんな野菜を食べていますか？\n🥕 Are farmers working in the fields now？ 農家たちは今畑で働いていますか？\n🍯 Where are you going grocery shopping？ 食料品の買い物にどこに行っていますか？\n🍂 Why is the weather changing？ 天気はなぜ変化していますか？\n🥣 Are you a good cook？ あなたは良い料理人ですか？\n🌟 What is your favorite fall food？ お気に入りの秋の食べ物は何ですか？"
  },
  {
    "title": "44. Fall Time (Present Continuous + BE)",
    "content": "📅 What month is it now？ 今は何月ですか？\n⏰ The clock is ticking quickly. 時計は早く進んでいます.\n🍂 Why are the leaves changing colors？ 葉はなぜ色が変わっていますか？\n🌇 Where is the sun going down now？ 太陽は今どこに沈んでいますか？\n🌙 The moon is rising in the sky. 月は空に昇っています.\n⏰ It is getting dark earlier now. 今は早く暗くなっています.\n☕ What are you drinking in the evening？ 夜に何を飲んでいますか？\n📚 We are going to school by bus. 私たちはバスで学校に行っています.\n🚌 Where is the bus stopping？ バスはどこに停まっていますか？\n🌟 I am feeling happy today. 私は今日幸せです.\n📅 What is the date today？ 今日は何日ですか？\n🌇 Is the sun hot or warm today？ 今日の太陽は熱いですか、それとも暖かいですか？\n🌙 Where are you going after school？ 学校の後どこに行っていますか？\n⏰ What time is it now？ 今は何時ですか？\n📚 Are you looking forward to winter？ 冬を楽しみにしていますか？\n☕ Why are you drinking hot drinks？ なぜ熱いドリンクを飲んでいるのですか？\n🚌 Is the bus coming or going？ バスは来ていますか、それとも行っていますか？\n🌟 Are you tired or energetic tonight？ 今夜は疲れていますか、それとも元気ですか？\n🌇 Why are the days getting shorter？ なぜ日々が短くなっていますか？\n🌙 What is your favorite time of year？ 一年で最も好きな時間はいつですか？\n📖 Are you reading a good book now？ 今良い本を読んでいますか？"
  },
  {
    "title": "45. Winter Fun (Present Continuous + BE)",
    "content": "❄️ Is snow falling or rain falling now？\n今、雪が降っていますか、それとも雨が降っていますか？\n☕ We are drinking hot chocolate with family.\n私たちは家族とホットチョコレートを飲んでいます.\n🧣 Who is wearing a warm red scarf？\n暖かい赤いマフラーを着ているのは誰ですか？\n🎄 The family is decorating the Christmas tree.\n家族はクリスマスツリーを飾っています.\n🎶 We are singing holiday songs together.\n私たちは一緒に祝日の歌を歌っています.\n🎁 What are you wrapping in that paper？\nその紙で何を包んでいますか？\n🏠 Where is your family celebrating this year？\n今年はどこで家族が祝っていますか？\n🎉 We are having a party tonight.\n私たちは今夜パーティーをしています.\n🎨 Is the gift red or green？\nプレゼントは赤いですか、それとも緑ですか？\n🥶 Is the winter cold or pleasant？\n冬は寒いですか、それとも快適ですか？\n❄️ Are you happy about snow falling soon？\n雪がすぐに降ることに幸せですか？\n☕ Where are you sitting and drinking？\nどこに座って飲んでいますか？\n🧣 What color is your favorite winter scarf？\nお気に入りの冬のマフラーは何色ですか？\n🎄 Who is putting the star on the tree？\nツリーに星を置いているのは誰ですか？\n🎶 Are you learning holiday songs this year？\n今年は祝日の歌を学んでいますか？\n🎁 Is wrapping gifts fun or difficult？\nギフトを包むことは楽しいですか、それとも難しいですか？\n🏠 Who is visiting your house this week？\n今週誰があなたの家を訪ねていますか？\n🎉 Are you going to any New Year parties？\n新年のパーティーに行きますか？\n🎨 What decorations are you putting up？\nどんな装飾を設けていますか？\n🥶 Why are you wearing winter clothes？\nなぜ冬服を着ていますか？"
  },
  {
    "title": "46. Winter Clothing (Present Continuous + BE)",
    "content": "🧥 Who is wearing a coat today？\n今日、コートを着ているのは誰ですか？\n👢 I am wearing my new boots now.\n私は今新しいブーツを履いています.\n🧤 My hands are cold and I need gloves.\n私の手は寒くて手袋が必要です.\n🧣 The scarf is very soft and warm.\nマフラーはとても柔らかくて暖かい.\n🧢 Is the hat too big or too small？\n帽子は大きすぎますか、それとも小さすぎますか？\n👕 What is warm enough for winter？\n何が冬に十分暖かいですか？\n🧦 Are you wearing thick socks or thin socks？\n厚い靴下を履いていますか、それとも薄い靴下を履いていますか？\n👖 Are jeans comfortable for winter？\nジーンズは冬に快適ですか？\n🧥 Why is winter clothing expensive？\nなぜ冬の服は高いのですか？\n☔ Is the jacket waterproof or not？\nジャケットは防水ですか、それともそうではありませんか？\n👢 What type of shoes are you wearing？\nどんなタイプの靴を履いていますか？\n🧤 Are your hands cold or warm？\nあなたの手は寒いですか、それとも暖かいですか？\n🧣 Is wool better than cotton？\nウールはコットンより良いですか？\n🧢 What is your favorite winter hat？\nお気に入りの冬の帽子は何ですか？\n🧦 Are your feet cold in winter？\n冬は足が寒いですか？\n👕 What clothes are you buying this year？\n今年はどんな服を買っていますか？\n👖 Who is paying for winter clothes？\n冬の服の費用を払っているのは誰ですか？\n🧥 Is your new winter coat thick or thin？\n新しい冬のコートは厚いですか、それとも薄いですか？\n☔ Where are you keeping your winter clothes？\n冬の服をどこに保管していますか？"
  },
  {
    "title": "47. December Weather (Present Continuous + BE)",
    "content": "❄️ What is the weather like today？\n今日は天気はどうですか？\n🌡️ The temperature is dropping today.\n気温は今日低下しています.\n💨 The wind is blowing strongly now.\n風は今強く吹いています.\n☁️ The day is getting cloudier.\n日はより曇りつつあります.\n🌨️ Where is snow forecast to fall？\n雪が降ると予報されているのはどこですか？\n❄️ The ground is becoming white.\n地面は白くなりつつあります.\n🌦️ Is it snowing or raining？\n雪が降っていますか、それとも雨が降っていますか？\n💧 Are puddles freezing or melting？\n水たまりは凍っていますか、それとも溶けていますか？\n🌤️ The sun is coming out now.\n太陽が出てきています.\n🔥 The fireplace is burning nicely.\n暖炉はよく燃えています.\n❄️ Do you love or hate snow？\n雪が好きですか、それとも嫌いですか？\n🌡️ Is the winter getting colder or staying the same？\n冬はより寒くなっていますか、それとも同じままですか？\n💨 Is the wind strong or weak？\n風は強いですか、それとも弱いですか？\n🌨️ When is the snow stopping？\n雪はいつ止みますか？\n☁️ Why are the clouds dark today？\nなぜ今日は雲が暗いのですか？\n🌦️ Are you happy about winter weather？\n冬の天気について幸せですか？\n💧 The ice is melting on the ground.\n氷は地面で溶けています.\n🌤️ Is the sun shining today？\n今日は太陽が輝いていますか？\n🔥 Where is the fire in the fireplace？\n暖炉の火はどこにありますか？\n🌟 What is your favorite winter weather？\nお気に入りの冬の天気は何ですか？"
  },
  {
    "title": "48. December Celebration (Present Continuous + BE)",
    "content": "🎉 Where is the party tonight？\n今夜パーティーはどこですか？\n🎵 Are you dancing at the party？\nパーティーで踊っていますか？\n🥤 What are you drinking tonight？\n今夜何を飲んでいますか？\n🍽️ We are eating special holiday food.\n私たちは特別な祝日の食べ物を食べています.\n🎊 Everyone is having fun, aren't they？\nみんな楽しんでいますよね？\n👫 Who is talking to your friend？\nあなたの友達と話しているのは誰ですか？\n🎁 The gifts are in beautiful boxes.\nプレゼントは美しい箱に入っています.\n🤝 Are people meeting new friends？\n人々は新しい友達と会っていますか？\n🎇 What is making the night bright？\n夜を明るくしているのは何ですか？\n💃 Are you enjoying the celebration？\n祝いを楽しんでいますか？\n🎉 Why are parties exciting？\nなぜパーティーは興奮するのですか？\n🎵 Who is singing Christmas songs？\nクリスマスの歌を歌っているのは誰ですか？\n🥤 Are you drinking anything special？\n特別なものを飲んでいますか？\n🍽️ Who is cooking the main dish？\n主菜を料理しているのは誰ですか？\n🎊 Is the music loud or quiet？\n音楽は大きいですか、それとも静かですか？\n👫 Where are your friends sitting？\nあなたの友達はどこに座っていますか？\n🎁 Is the gift for you or someone else？\nプレゼントはあなたのものですか、それとも誰かのものですか？\n🤝 Who is introducing you today？\n今日あなたを紹介しているのは誰ですか？\n🎇 What are you celebrating？\n何を祝っていますか？\n💃 Are you staying up late tonight？\n今夜遅く起きていますか？"
  }
];
