var eiken6story = [
  {
    "title": "1. First Day at School",
    "content": "🏫 I go to school in the morning.\n私は朝に学校に行きます。\n\n📚 My school is big and nice.\n私の学校は大きくて素敵です。\n\n👨‍🏫 I have a new teacher.\n新しい先生がいます。\n\n👦 I sit with my friend.\n友達と一緒に座ります。\n\n📖 We learn English and math.\n私たちは英語と数学を学びます。\n\n✏️ I have a pencil and book.\n鉛筆とノートを持っています。\n\n😊 School is fun for me.\n学校は楽しいです。\n\n❤️ I like my school very much.\n学校がとても好きです。\n\n🌟 I have many friends there.\nたくさんの友達がいます。\n\n🎒 My bag is on my desk.\nかばんは机の上にあります。\n\n🎓 What is yourfavorite subject?\n好きな教科は何ですか？\n\n👩‍🏫 Do you like your teacher?\n先生は好きですか？\n\n📚 Is your school big or small?\n学校は大きいですか、小さいですか？\n\n👦 Who is your best friend?\n一番の友達は誰ですか？\n\n🏫 Where is your classroom?\n教室はどこですか？\n\n✏️ Do you have many books?\n本はたくさんありますか？\n\n📖 What do you learn?\n何を学びますか？\n\n😊 Is school fun for you?\n学校は楽しいですか？\n\n❤️ Do you love your school?\n学校は大好きですか？\n\n🌟 Where do you play after school?\n放課後どこで遊びますか？"
  },
  {
    "title": "2. My Classroom",
    "content": "🏫 I study in my classroom.\n教室で勉強します。\n\n🖼️ The board is on the wall.\n黒板は壁にあります。\n\n📺 We have a TV in class.\n教室にテレビがあります。\n\n💡 The lights are very bright.\n照明はとても明るいです。\n\n🪟 The window is big and clean.\n窓は大きくてきれいです。\n\n🪑 I sit on my chair.\n椅子に座ります。\n\n📚 My desk is next to your desk.\n机はあなたの机の隣です。\n\n📖 I put my book on the desk.\n本を机に置きます。\n\n👜 My bag is under the chair.\nかばんは椅子の下にあります。\n\n🎨 We have pictures on the wall.\n壁に絵があります。\n\n🏫 Is your classroom big?\n教室は大きいですか？\n\n📺 Do you have a TV?\nテレビはありますか？\n\n🪟 Is the window open?\n窓は開いていますか？\n\n🪑 Where do you sit?\nどこに座りますか？\n\n📚 What is on your desk?\n机の上に何がありますか？\n\n👜 Is your bag on the floor?\nかばんは床にありますか？\n\n🎨 Do you like art class?\n美術の授業は好きですか？\n\n🖼️ What do you see on the wall?\n壁に何が見えますか？\n\n💡 Is your classroom bright?\n教室は明るいですか？\n\n📖 Do you have many books?\n本はたくさんありますか？"
  },
  {
    "title": "3. School Subjects",
    "content": "📚 I learn many subjects at school.\n学校でたくさんの教科を学びます。\n\n🔤 We study English every day.\n毎日英語を勉強します。\n\n🔢 Math is myfavorite subject.\n算数が一番好きな教科です。\n\n🧬 We have science on Tuesday.\n火曜日に理科があります。\n\n🎨 Art class is very fun.\n美術の授業はとても楽しいです。\n\n🎵 We sing songs in music class.\n音楽の授業で歌を歌います。\n\n🏃 PE is on Friday.\n金曜日に体育があります。\n\n📝 We write in Japanese class.\n国語の授業で書きます。\n\n⏰ All classes are forty minutes.\nすべての授業は40分です。\n\n🎓 I like school very much.\n学校がとても好きです。\n\n🔤 Do you like English?\n英語は好きですか？\n\n🔢 What is yourfavorite subject?\n一番好きな教科は何ですか？\n\n🧬 Is science fun for you?\n理科は楽しいですか？\n\n🎨 Do you like art class?\n美術の授業は好きですか？\n\n🎵 Do you like music class?\n音楽の授業は好きですか？\n\n🏃 Do you like PE?\n体育は好きですか？\n\n📝 What do you write?\n何を書きますか？\n\n⏰ Is your class long?\n授業は長いですか？\n\n🎓 Is school fun for you?\n学校は楽しいですか？\n\n📚 Do you have many subjects?\n教科はたくさんありますか？"
  },
  {
    "title": "4. School Friends",
    "content": "👦 I have many friends at school.\n学校にたくさんの友達がいます。\n\n👧 My best friend is a girl.\n親友は女の子です。\n\n🎒 We play together at lunch time.\n昼休みに一緒に遊びます。\n\n⚽ We play football in the playground.\n校庭でサッカーをします。\n\n😊 My friends are very kind.\n友達はとても優しいです。\n\n📖 We read books in the library.\n図書室で本を読みます。\n\n🍱 We eat lunch together.\n一緒に昼食を食べます。\n\n🗣️ We talk about many things.\nたくさんのことについて話します。\n\n🤝 We help each other.\n互いに助け合います。\n\n❤️ I love my friends very much.\n友達がとても大好きです。\n\n👦 Who is your best friend?\n親友は誰ですか？\n\n🎒 Do you play at lunch time?\n昼休みに遊びますか？\n\n⚽ What do you play?\n何で遊びますか？\n\n📖 Where do you read books?\nどこで本を読みますか？\n\n🍱 Do you eat with friends?\n友達と一緒に食べますか？\n\n🗣️ What do you talk about?\n何について話しますか？\n\n🤝 Do you help your friends?\n友達を手伝いますか？\n\n😊 Are your friends kind?\n友達は優しいですか？\n\n❤️ Do you love your friends?\n友達は大好きですか？\n\n👧 Is your friend a boy or a girl?\n友達は男の子ですか、女の子ですか？"
  },
  {
    "title": "5. Myfavorite Sport",
    "content": "🏈 Ken plays football at the park on Saturday afternoon.\nケンは土曜日の午後に公園でサッカーをします.\n\n⚽ He runs very fast with the ball happily.\n彼はボールを持って幸せにとても速く走ります.\n\n👦 Tom tries to catch Ken near the big tree.\nトムは大きな木の近くでケンを捕まえようとします.\n\n👧 Yuki watches the game from the bench safely.\nユキはベンチから試合を安全に見ます.\n\n😊 Ken loves playing football with his friends very much.\nケンは友達とサッカーをするのがとても大好きです.\n\n⚽ He scores a goal for his team proudly.\n彼は自分のチームのためにゴールを誇らしく決めます.\n\n🏈 Football is a great sport for everyone truly.\nサッカーは本当にみんなにとって最高のスポーツです.\n\n👦 Tom also likes playing football very much.\nトムもサッカーをするのがとても大好きです.\n\n👧 Yuki likes watching football games happily.\nユキはサッカーの試合を見るのが幸せに好きです.\n\n😊 Everyone enjoys playing sports together.\nみんな一緒にスポーツをするのを楽しんでいます.\n\n🏈 Do you like playing sports a lot?\nあなたはスポーツをすることが好きですか？\n\n⚽ What is yourfavorite sport and why?\nあなたのお気に入りのスポーツは何で、それはなぜですか？\n\n👦 Do you like watching sports on TV sometimes?\n時々テレビでスポーツを見るのは好きですか？\n\n👧 Who do you play sports with often?\n頻繁に誰とスポーツをしますか？\n\n😊 Are you good at running very fast?\n速く走るのは得意ですか？\n\n⚽ Which sport do you want to learn soon?\nどのスポーツをすぐに学びたいですか？\n\n🏈 Do you exercise every day happily?\n毎日幸せに運動しますか？\n\n👦 Is sport important for your health?\nスポーツはあなたの健康にとって重要ですか？\n\n👧 What games do you play sometimes?\n時々どのようなゲームをしますか？"
  },
  {
    "title": "6. My Weekend Hobby",
    "content": "👨 Yuki draws pictures at home on Sunday morning.\nユキは日曜の朝、家で絵を描きます.\n\n🎨 He uses colored pencils for his drawing kindly.\n彼は絵を描くのに親切に色鉛筆を使います.\n\n🖍️ He draws a big house in his book carefully.\n彼は注意深く本に大きな家を描きます.\n\n😊 Yuki likes drawing pictures very much indeed.\nユキは本当に絵を描くのがとても好きです.\n\n👩 Mother looks at the picture and smiles happily.\n母は絵を見て幸せに微笑みます.\n\n🎨 The picture is very beautiful indeed.\nその絵は本当にとても美しいです.\n\n👨 Drawing is a great hobby for everyone.\n絵を描くことはみんなにとって最高の趣味です.\n\n🖍️ He shows his picture to his father proudly.\n彼は誇らしく父に絵を見せます.\n\n😊 Yuki draws pictures every weekend happily.\nユキは幸せに毎週末絵を描きます.\n\n👨 Do you have a hobby that you love?\n愛している趣味がありますか？\n\n🎨 What do you like to draw in pictures?\n絵には何を描くのが好きですか？\n\n🖍️ Do you like using pencils or paints?\n鉛筆と絵の具、どっちが好きですか？\n\n😊 What did you draw last week happily?\n幸せに先週は何を描きましたか？\n\n👩 Does your family like your drawings sometimes?\n時々あなたの家族はあなたの絵を好きですか？\n\n🎨 What is yourfavorite color for drawing?\nお絵を描く一番好きな色は何ですか？\n\n👨 Do you share your pictures with friends regularly?\n定期的に友達と絵を共有しますか？\n\n😊 Is drawing a fun hobby for you?\n絵を描くことはあなたにとって楽しい趣味ですか？\n\n🖍️ What would you like to draw next?\n次に何を描きたいですか？"
  },
  {
    "title": "7. Playing with Friends",
    "content": "👧 Tom plays catch with Aiko at the playground.\nトムは遊び場でアイコとキャッチボールをします.\n\n⚽ The ball goes back and forth many times.\nボールは何度も前後に行き来します.\n\n😊 Aiko runs fast to catch the ball well.\nアイコはボールを捕まえるために速く走ります.\n\n👧 Tom throws the ball very far sometimes.\nトムは時々ボールをとても遠くに投げます.\n\n🏃 Lisa joins the game too suddenly.\nリサも突然ゲームに参加します.\n\n😊 Everyone laughs and plays together happily.\nみんな笑って一緒に幸せに遊びます.\n\n👧 Lisa is a very good player clearly.\nリサは明らかにとても良い選手です.\n\n🏃 Running is fun for children generally.\n走ることは子供たちにとって一般的に楽しいです.\n\n😊 Tom loves playing with his friends greatly.\nトムは友達と遊ぶのがとても大好きです.\n\n👧 Do you play catch with your friends?\n友達とキャッチボールをしますか？\n\n⚽ Can you catch a ball easily?\nボールを簡単に捕まえられますか？\n\n😊 Do you like running around in parks?\n公園で走り回るのは好きですか？\n\n👧 Who do you like playing with most?\n誰と遊ぶのが一番好きですか？\n\n🏃 Are you good at sports really?\n本当にスポーツは得意ですか？\n\n😊 What games do you play after school?\n学校の後にはどんなゲームをしますか？\n\n👧 Do you like playing indoors or outdoors more?\n屋内で遊ぶのと屋外で遊ぶのとではどっちが好きですか？\n\n🏃 Is running good for your health?\n走ることはあなたの健康に良いですか？\n\n😊 What do you and your friends do together?\nあなたと友達は一緒に何をしますか？"
  },
  {
    "title": "8. After School Activities",
    "content": "🎹 Aiko has piano practice at school on Tuesday.\nアイコは火曜日に学校でピアノの練習をします.\n\n👨‍🏫 Ms Tanaka teaches Aiko the piano kindly.\n田中先生は親切にアイコにピアノを教えます.\n\n🎹 Aiko plays a song very well today.\n今日、アイコは曲をとても上手に弾きます.\n\n😊 She enjoys playing the piano greatly.\n彼女はピアノを演奏するのを楽しんでいます.\n\n📚 After piano, she studies English at home.\nピアノの後、彼女は家で英語を勉強します.\n\n📖 English is an important subject at school.\n英語は学校で重要な科目です.\n\n😊 Aiko likes learning English very much.\nアイコは英語を学ぶのがとても好きです.\n\n🎹 She practises the piano every week.\n彼女は毎週ピアノを練習します.\n\n😊 Aiko loves after school activities.\nアイコは放課後のアクティビティを愛しています.\n\n🎹 Do you play a musical instrument?\n楽器を演奏しますか？\n\n👨‍🏫 What instrument do you play or learn?\n何の楽器を演奏したり学習したりしていますか？\n\n📚 What do you do after school often?\n放課後には頻繁に何をしますか？\n\n📖 What is yourfavorite school subject?\n一番好きな学校の科目は何ですか？\n\n😊 Do you like learning languages a lot?\n言語を学習するのは好きですか？\n\n🎹 Is music important in your life?\n音楽はあなたの人生で重要ですか？\n\n📚 How do you study English at home?\n家ではどのように英語を勉強しますか？\n\n😊 Do you have many hobbies or few?\n趣味はたくさんありますか、それとも少ないですか？\n\n🎹 Would you like to learn a musical instrument?\n楽器を学びたいですか？"
  },
  {
    "title": "9. My Family",
    "content": "I have a happy family.\n私は幸せな家族がいます。\n\nI live with my mum and dad.\n私は母と父と一緒に住んでいます。\n\nI have one little brother.\n私は一人の弟がいます。\n\nMy mum is kind.\n母は優しいです。\n\nMy dad is funny.\n父は面白いです。\n\nMy brother is small.\n弟は小さいです。\n\nWe eat dinner together.\n私たちは夕食を一緒に食べます。\n\nWe watch TV together.\n私たちは一緒にテレビを見ます。\n\nI love my family.\n私は私の家族を愛しています。\n\nFamily is important.\n家族は大切です。\n\nDo you have a family？\nあなたは家族がいますか？\n\nHow many people are in your family？\nあなたの家族は何人ですか？\n\nDo you live with your parents？\n両親と一緒に住んでいますか？\n\nIs your family big or small？\nあなたの家族は大きいですか、それとも小さいですか？\n\nWho is yourfavorite person？\n一番好きな人は誰ですか？\n\nDo you love your family？\nあなたの家族を愛していますか？\n\nWhat does your mum do？\nあなたの母は何をしていますか？\n\nWhat does your dad do？\nあなたの父は何をしていますか？\n\nDo you have brothers or sisters？\n兄弟や姉妹がいますか？\n\nAre you happy with your family？\nあなたは家族と幸せですか？\n"
  },
  {
    "title": "10. My School",
    "content": "I go to school every day.\n私は毎日学校に行きます。\n\nI walk to school.\n私は学校に歩いていきます。\n\nMy school is big.\n私の学校は大きいです。\n\nI have many friends at school.\n学校に多くの友達がいます。\n\nMy teacher is nice.\n先生はいい人です。\n\nWe study English.\n私たちは英語を勉強します。\n\nWe read books.\n私たちは本を読みます。\n\nWe play games.\n私たちはゲームをします。\n\nI like school.\n私は学校が好きです。\n\nSchool is fun.\n学校は楽しいです。\n\nDo you like school？\n学校は好きですか？\n\nIs your school big or small？\nあなたの学校は大きいですか、それとも小さいですか？\n\nHow do you go to school？\nどのように学校に行きますか？\n\nDo you walk to school？\n学校に歩いていきますか？\n\nWho is yourfavorite teacher？\n一番好きな先生は誰ですか？\n\nWhat do you study at school？\n学校で何を勉強しますか？\n\nDo you read books at school？\n学校で本を読みますか？\n\nWho are your friends at school？\n学校での友達は誰ですか？\n\nIs school fun for you？\nあなたにとって学校は楽しいですか？\n\nWhat time do you go to school？\n何時に学校に行きますか？\n"
  },
  {
    "title": "11. Spring Day",
    "content": "Today is a warm day.\n今日は暖かい日です。\n\nThe sun is shining.\n太陽が輝いています。\n\nI am happy today.\n私は今日幸せです。\n\nI see flowers.\n私は花を見ます。\n\nI see birds.\n私は鳥を見ます。\n\nThe sky is blue.\n空は青いです。\n\nI play outside.\n私は外で遊びます。\n\nI run in the park.\n私は公園で走ります。\n\nI feel good.\n私は気分が良いです。\n\nSpring is here.\n春が来ています。\n\nDo you like spring days？\n春の日は好きですか？\n\nIs the sun shining today？\n今日は太陽が輝いていますか？\n\nDo you see flowers today？\n今日は花を見ますか？\n\nWhat do you see in the sky？\n空に何が見えますか？\n\nDo you like playing outside？\n外で遊ぶのは好きですか？\n\nDo you run in the park？\n公園で走りますか？\n\nIs the sky blue today？\n今日は空は青いですか？\n\nWhat do you do in spring？\n春に何をしますか？\n\nDo you feel happy today？\n今日は幸せな気持ちですか？\n\nWhat color is the sky？\n空は何色ですか？\n"
  },
  {
    "title": "12. My Friends",
    "content": "I have good friends.\n私は良い友達がいます。\n\nMy friends are nice.\n私の友達はいい人たちです。\n\nWe play together.\n私たちは一緒に遊びます。\n\nWe talk together.\n私たちは一緒に話します。\n\nWe eat lunch together.\n私たちは一緒に昼食を食べます.\n\nWe share food.\n私たちは食べ物を分け合います。\n\nWe help each other.\n私たちは互いに助け合います。\n\nMy friends are kind.\n私の友達は優しいです。\n\nI like my friends.\n私は友達が好きです.\n\nFriends are important.\n友達は大切です.\n\nDo you have friends at school？\n学校に友達がいますか？\n\nWhat do you do with friends？\n友達と何をしますか？\n\nDo you play together？\n一緒に遊びますか？\n\nAre your friends nice？\nあなたの友達はいい人たちですか？\n\nWho is your best friend？\n一番の友達は誰ですか？\n\nDo you share food with friends？\n友達と食べ物を分け合いますか？\n\nDo you help your friends？\n友達を助けますか？\n\nAre you a good friend？\nあなたは良い友達ですか？\n\nWhat games do you play together？\n一緒に何のゲームをしますか？\n\nDo you love your friends？\nあなたの友達を愛していますか？\n"
  },
  {
    "title": "13. Spring Weather",
    "content": "☀️ Spring is warm.\n春は暖かいです。\n\n🌞 The sun is warm.\n太陽は暖かいです。\n\n☀️ It is sunny today.\n今日は晴れです.\n\n😊 I like sunny days.\n晴れの日が好きです。\n\n🌌 The sky is blue today.\n今日は空は青いです。\n\n☁️ Clouds are white.\n雲は白いです。\n\n🌸 It is not cold today.\n今日は寒くないです。\n\n😊 The weather is nice today.\n今日は天気がいいです。\n\n🌳 Spring weather is good for playing outside.\n春の天気は外で遊ぶのにいいです.\n\n😊 I feel happy in spring.\n私は春に幸せを感じます。\n\nWhat is the weather today?\n今日は何の天気ですか？\n\nIs it warm today?\n今日は暖かいですか？\n\nWhat color is the sky today?\n今日の空の色は何ですか？\n\nAre clouds white?\n雲は白いですか？\n\nDo you like sunny days?\n晴れの日が好きですか？\n\nIs spring warm?\n春は暖かいですか？\n\nHow do you feel in spring?\n春でどんな気持ちですか？\n\nIs the weather good?\n天気はいいですか？\n\nWhat is spring like?\n春はどんな感じですか？\n\nDo you like spring weather?\n春の天気が好きですか？\n"
  },
  {
    "title": "14. Park Fun",
    "content": "🌳 I go to the park.\n私は公園に行きます.\n\n🏟️ The park is big.\n公園は大きいです。\n\n🌲 There are many trees.\nたくさんの木があります.\n\n🌸 I play on the grass.\n芝生の上で遊びます。\n\n👫 My friends are at the park.\n友達も公園にいます。\n\n🏃‍♂️ We play tag together.\n一緒に鬼ごっこをします.\n\n😊 The park is fun.\n公園は楽しいです。\n\n🌸 I see many flowers.\nたくさんの花を見ます.\n\n🕊️ Birds are flying.\n鳥が飛んでいます。\n\n😊 We are happy at the park.\n公園で私たちは幸せです。\n\nWhere do you go to play?\nどこで遊びに行きますか？\n\nIs your park big?\nあなたの公園は大きいですか？\n\nWhat is in the park?\n公園には何がありますか？\n\nDo you see flowers?\n花を見ますか？\n\nAre birds in the park?\n公園に鳥はいますか？\n\nWho do you play with?\n誰と遊びますか？\n\nWhat game do you play?\n何を遊びますか？\n\nIs the park fun?\n公園は楽しいですか？\n\nHow do you feel at the park?\n公園でどんな気持ちですか？\n\nDo you like the park?\n公園が好きですか？\n"
  },
  {
    "title": "15. Outside Play",
    "content": "🌞 I play outside every day.\n私は毎日外で遊びます.\n\n☀️ The sun is shining.\n太陽が輝いています。\n\n🏃‍♂️ I run in the park.\n公園で走ります。\n\n👫 My friend is with me.\n友達が一緒にいます.\n\n⚽️ We play ball.\nボールで遊びます。\n\n🌌 The sky is blue.\n空は青いです。\n\n🌲 I see green trees.\n緑の木を見ます.\n\n😊 We are happy.\n私たちは幸せです。\n\n🏠 My mother calls me home.\n母が帰宅を呼びます.\n\n🚶 I go home now.\n今帰宅します。\n\nDo you play outside every day?\n毎日外で遊びますか？\n\nWhat do you do outside?\n外で何をしますか？\n\nIs the sun shining today?\n今日は太陽が輝いていますか？\n\nWhere do you run?\nどこで走りますか？\n\nWho plays with you?\n誰と遊びますか？\n\nWhat color is the sky?\n空の色は何ですか？\n\nDo you see green trees?\n緑の木を見ますか？\n\nAre you happy outside?\n外で幸せですか？\n\nWhat time do you go home?\n何時に帰宅しますか？\n\nDoes your mother call you?\n母が呼びますか？\n"
  },
  {
    "title": "16. Flowers and Nature",
    "content": "🌺 I see flowers.\n私は花を見ます。\n\n🌸 Flowers are beautiful.\n花は美しいです。\n\n🌸 Spring flowers are pink and white.\n春の花はピンクと白です。\n\n🌸 Cherry blossoms are pink.\n桜はピンクです。\n\n😊 I like flowers.\n花が好きです。\n\n🌿 The trees have leaves.\n木には葉があります.\n\n🌲 Leaves are green in spring.\n春の葉は緑です。\n\n🕊️ Birds make nests.\n鳥が巣を作ります。\n\n👀 I see a bird's nest.\n鳥の巣を見ます。\n\n😊 Nature is beautiful.\n自然は美しいです。\n\nWhat color are spring flowers?\n春の花の色は何ですか？\n\nDo you like flowers?\n花が好きですか？\n\nWhat flowers do you see?\n何の花を見ますか？\n\nAre cherry blossoms pink?\n桜はピンクですか？\n\nWhat color are leaves in spring?\n春の葉の色は何ですか？\n\nDo birds make nests?\n鳥は巣を作りますか？\n\nCan you see a bird's nest?\n鳥の巣を見ることができますか？\n\nIs nature beautiful?\n自然は美しいですか？\n\nWhat do you like in nature?\n自然で何が好きですか？\n\nDo you see many flowers?\nたくさんの花を見ますか？\n"
  },
  {
    "title": "17. Golden Week",
    "content": "🌸 It is Golden Week this week.\n今週はゴールデンウィークです.\n\n🏯 I visit a temple in Kyoto.\n私は京都の寺社を訪れます.\n\n📸 I take many photos of flowers.\n私は花の写真をたくさん撮ります.\n\n👨‍👩‍👧 My family enjoys the holiday.\n私の家族は休暇を楽しんでいる.\n\n🚄 We take the bullet train.\n私たちは新幹線を利用する.\n\n🍜 We eat ramen for lunch.\n私たちは昼食にラーメンを食べる.\n\n💰 I buy a nice souvenir.\n私は素敵なお土産を買う.\n\n🌟 The weather is very sunny.\n天気はとても晴れています.\n\n😄 Everyone is happy today.\n今日皆は幸せです.\n\n🎉 We have a wonderful time.\n私たちは素晴らしい時間を持つ.\n\n❓ What do you do in Golden Week？\nあなたはゴールデンウィークに何をしますか？\n\n🏯 Where do you go in spring？\n春にはどこへ行きますか？\n\n📸 What do you take photos of？\n何の写真を撮りますか？\n\n🍜 What do you eat for lunch？\n昼食には何を食べますか？\n\n💰 What do you buy at the shop？\n店で何を買いますか？\n\n🌟 Is the weather good this week？\n今週の天気は良いですか？\n\n😄 Are you happy on holiday？\n休暇に幸せですか？\n\n🚄 Do you like trains？\nあなたは列車が好きですか？\n\n👨‍👩‍👧 Who is with you today？\n今日誰と一緒ですか？\n\n🎉 What time is it now？\n今は何時ですか？"
  },
  {
    "title": "18. Spring School",
    "content": "📚 I study English at school.\n私は学校で英語を勉強する.\n\n📝 I write in my notebook.\n私はノートに書く.\n\n👥 My classmates read a book.\n私のクラスメートたちは本を読む.\n\n✏️ I use a pencil for writing.\n私は書くために鉛筆を使う.\n\n📖 We learn new words every day.\n私たちは毎日新しい単語を学ぶ.\n\n💻 I use a computer for homework.\n私は宿題のためにコンピュータを使う.\n\n🗣️ I speak English in class.\n私はクラスで英語を話す.\n\n✨ My teacher is very kind.\n私の先生はとても親切です.\n\n🎯 I practice grammar every week.\n私は毎週文法を練習する.\n\n📅 I study hard for exams.\n私は試験のために一生懸命勉強する.\n\n❓ What do you study at school？\n学校で何を勉強しますか？\n\n📝 What do you write with？\n何で書きますか？\n\n👥 Who is your classmate？\nあなたのクラスメートは誰ですか？\n\n💻 Do you use a computer？\nあなたはコンピュータを使いますか？\n\n📖 What do you learn every day？\n毎日何を学びますか？\n\n🗣️ What language do you speak in class？\nクラスではどの言語を話しますか？\n\n✨ Is your teacher kind？\nあなたの先生は親切ですか？\n\n🎯 How often do you practice？\nどのくらい頻繁に練習しますか？\n\n📅 When do you study？\nいつ勉強しますか？\n\n✏️ What instrument do you use for writing？\n書くためにどの器具を使いますか？"
  },
  {
    "title": "19. Spring Nature",
    "content": "🌿 I walk in the park today.\n今日私は公園を歩く.\n\n🌸 Flowers bloom in the garden.\n花は庭で咲く.\n\n🦋 A butterfly flies in the sky.\n蝶が空を飛んでいる.\n\n🧢 I wear a blue hat.\n私は青い帽子を被る.\n\n🥾 We walk on the path.\n私たちは小道を歩く.\n\n☀️ The sun shines brightly.\n太陽が明るく輝いている.\n\n📱 I take a nice photo.\n私は素敵な写真を撮る.\n\n🎵 Birds sing in the trees.\n鳥が木の中で歌っている.\n\n🌱 Plants grow very fast.\n植物はとても急速に育つ.\n\n😄 I enjoy the spring day.\n私は春の日を楽しむ.\n\n❓ What do you do in the park？\n公園で何をしますか？\n\n🌸 What do flowers do in spring？\n春に花は何をしますか？\n\n🦋 What flies in the sky？\n何が空を飛んでいますか？\n\n🧢 What do you wear on your head？\n頭には何を被っていますか？\n\n☀️ How is the sun today？\n今日の太陽はどうですか？\n\n📱 What do you take photos of？\n何の写真を撮りますか？\n\n🎵 What do birds do in trees？\n木の中で鳥は何をしますか？\n\n🌱 What happens to plants in spring？\n春に植物に何が起きますか？\n\n🥾 Where do you walk for exercise？\n運動のためにどこを歩きますか？\n\n😄 Do you like spring？\nあなたは春が好きですか？"
  },
  {
    "title": "20. May Family",
    "content": "👨‍👩‍👧 My family is at home.\n私の家族は家にいる.\n\n🍳 My mother cooks in the kitchen.\n母は台所で料理をする.\n\n📚 My brother reads in his room.\n弟は自分の部屋で読む.\n\n📺 My father watches television.\n父はテレビを見る.\n\n🐕 My dog runs in the garden.\n私の犬は庭で走る.\n\n🧘 I do my homework.\n私は宿題をする.\n\n📞 My grandmother talks on the phone.\n祖母は電話で話す.\n\n🎵 My sister listens to music.\n姉は音楽を聴く.\n\n🌸 We look at the flowers.\n私たちは花を見る.\n\n🏡 Our home is very happy.\n私の家はとても幸せである.\n\n❓ Who is in your family？\nあなたの家族には誰がいますか？\n\n🍳 What does your mother do？\nあなたの母は何をしますか？\n\n📺 What does your father watch？\nあなたの父は何を見ますか？\n\n🐕 What does your dog do？\nあなたの犬は何をしますか？\n\n🧘 What do you do at home？\n家で何をしますか？\n\n📞 Who talks on the phone？\n電話で話しているのは誰ですか？\n\n🎵 What does your sister listen to？\nあなたの姉は何を聴きますか？\n\n🌸 Do you look at flowers？\nあなたは花を見ますか？\n\n📚 Where does your brother read？\nあなたの弟はどこで読みますか？\n\n🏡 Is your home happy？\nあなたの家は幸せですか？"
  },
  {
    "title": "21. Rainy Day",
    "content": "🌧️ It rains today.\n今日は雨が降る.\n\n☔ I take an umbrella.\n私は傘を取る.\n\n📺 My sister watches TV.\n私の姉はテレビを見る.\n\n🧸 I play with toys.\n私はおもちゃで遊ぶ.\n\n🍜 My mother makes soup.\n母はスープを作る.\n\n☕ I drink hot tea.\n私は熱いお茶を飲む.\n\n📖 I read a book.\n私は本を読む.\n\n🎶 My father listens to music.\n父は音楽を聴く.\n\n🌙 The evening is quiet.\n夕暮れは静かである.\n\n😊 I feel very happy.\n私はとても幸せな気分.\n\n❓ What is the weather today？\n今日の天気は？\n\n🌧️ Do you like rain？\nあなたは雨が好きですか？\n\n☔ What do you take on rainy days？\n雨の日には何を持ちますか？\n\n📺 What does your sister watch？\nあなたの姉は何を見ますか？\n\n🍜 What does your mother make？\nあなたの母は何を作りますか？\n\n☕ What do you drink when it rains？\n雨のとき何を飲みますか？\n\n📖 What do you read at home？\n家で何を読みますか？\n\n🎶 Who listens to music in your family？\nあなたの家族で誰が音楽を聴きますか？\n\n🌙 Is it quiet in the evening？\n夕暮れは静かですか？\n\n😊 How do you feel today？\n今日どう感じていますか？"
  },
  {
    "title": "22. Indoor Activities",
    "content": "🎨 I paint a picture.\n私は絵を描く.\n\n🧩 My friend does a puzzle.\n私の友達はパズルをする.\n\n👩‍💻 I use a computer.\n私はコンピュータを使う.\n\n🎭 I practice for a play.\n私は劇の練習をする.\n\n📱 I study with an app.\n私はアプリで勉強する.\n\n🥁 My brother plays drums.\n弟はドラムを演奏する.\n\n🧵 My grandmother sews.\n祖母は縫う.\n\n🎵 I listen to songs.\n私は歌を聴く.\n\n✍️ I write a story.\n私は物語を書く.\n\n🎉 We enjoy our hobbies.\n私たちは自分たちの趣味を楽しむ.\n\n❓ What do you do indoors？\n屋内で何をしますか？\n\n🎨 What can you paint？\n何を描くことができますか？\n\n🧩 Who does the puzzle？\nパズルをするのは誰ですか？\n\n🎭 What do you practice in drama？\nドラマでは何を練習しますか？\n\n📱 What app do you use？\nどのアプリを使いますか？\n\n🥁 What does your brother play？\nあなたの弟は何を演奏しますか？\n\n🧵 What does your grandmother teach？\nあなたの祖母は何を教えますか？\n\n✍️ What do you like writing？\n何を書くのが好きですか？\n\n🎵 What music do you listen to？\nどのような音楽を聴きますか？\n\n🎉 Do you have fun indoors？\n屋内で楽しみますか？"
  },
  {
    "title": "23. Shopping",
    "content": "🛍️ I go to a shop.\n私は店へ行く.\n\n👗 I look at a dress.\n私はワンピースを見る.\n\n👟 I try on shoes.\n私は靴を試着する.\n\n👜 I buy a new bag.\n私は新しいバッグを買う.\n\n💳 I pay with a card.\n私はカードで支払う.\n\n🍦 I eat ice cream.\n私はアイスクリームを食べる.\n\n👥 Many people shop in the mall.\n多くの人々がモールで買い物をする.\n\n🌂 People use umbrellas.\n人々は傘を使う.\n\n😌 I feel very happy.\n私はとても幸せな気分.\n\n👕 I like the new clothes.\n私は新しい服が好き.\n\n❓ Where do you go shopping？\n買い物にどこへ行きますか？\n\n👗 What do you look at in shops？\n店で何を見ますか？\n\n👟 What do you try on in shoe shops？\n靴店で何を試着しますか？\n\n👜 What do you buy for school？\n学校のために何を買いますか？\n\n💳 How do you pay for shopping？\n買い物をどのように支払いますか？\n\n🍦 What do you eat at the mall？\nモールで何を食べますか？\n\n👥 Who shops with you？\n誰と一緒に買い物をしますか？\n\n🌂 Why do people use umbrellas？\nなぜ人々は傘を使いますか？\n\n👕 What clothes do you like？\nどのような服が好きですか？\n\n❓ Do you like shopping？\nあなたは買い物が好きですか？"
  },
  {
    "title": "24. Summer",
    "content": "☀️ I like summer.\n私は夏が好きである.\n\n🏊 I swim in the pool.\n私はプールで泳ぐ.\n\n👕 I wear a T-shirt.\n私はTシャツを着る.\n\n🌴 I dream of a beach.\n私はビーチを夢見る.\n\n🎫 I plan a trip.\n私は旅行の計画を立てる.\n\n🍉 I eat fruit every day.\n私は毎日果物を食べる.\n\n🌺 My mother plants flowers.\n母は花を植える.\n\n🏕️ My family camp in summer.\n私の家族は夏にキャンプをする.\n\n🎆 I watch fireworks.\n私は花火を見る.\n\n✨ I feel very excited.\n私はとても興私はとても興奮している.\n\n❓ What season do you like？\nどの季節が好きですか？\n\n☀️ Is summer hot？\n夏は暑いですか？\n\n🏊 Where do you swim？\nどこで泳ぎますか？\n\n👕 What do you wear in summer？\n夏に何を着ますか？\n\n🌴 Where do you go on holiday？\n休暇にはどこへ行きますか？\n\n🎫 What do you plan for summer？\n夏に何を計画しますか？\n\n🍉 What fruit do you eat？\nどの果物を食べますか？\n\n🌺 What flowers bloom in summer？\n夏にどの花が咲きますか？\n\n🎆 What do you like in summer？\n夏に何が好きですか？\n\n✨ How do you feel now？\n今どう感じていますか？"
  },
  {
    "title": "25. Summer Holiday (Present Simple)",
    "content": "🌅 It is summer in Japan.\n日本は夏です.\n✈️ I go to the beach in summer.\n私は夏にビーチに行きます.\n🏨 My family stays at a hotel.\n私の家族はホテルに泊まります.\n🌴 The sun is very hot.\n太陽はとても暑い.\n📸 I take many photos.\n私は多くの写真を撮ります.\n🍦 I eat ice cream every day.\n私は毎日アイスクリームを食べます.\n🎫 We buy tickets for trips.\n私たちは旅行のチケットを買います.\n🥾 I swim in the sea.\n私は海で泳ぎます.\n🗺️ I look at the map.\n私は地図を見ます.\n😊 I like summer holidays.\n私は夏休みが好きです.\n🌅 Do you like summer？\nあなたは夏が好きですか？\n✈️ Where do you go？\nあなたはどこへ行きますか？\n🏨 Do you stay at a hotel？\nあなたはホテルに泊まりますか？\n🌴 Is the sun hot？\n太陽は暑いですか？\n📸 Do you take photos？\nあなたは写真を撮りますか？\n🍦 What do you eat？\nあなたは何を食べますか？\n🎫 Do you buy tickets？\nあなたはチケットを買いますか？\n🥾 Do you swim？\nあなたは泳ぎますか？\n🗺️ Do you use a map？\nあなたは地図を使いますか？\n😊 Are you happy？\nあなたは幸せですか？"
  },
  {
    "title": "26. Beach Day (Present Simple / Be-Verb)",
    "content": "🌊 I go to the beach with my family.\n私は家族とビーチに行きます.\n🏖️ The beach is near my house.\nビーチは私の家の近くです.\n☀️ The sun is bright.\n太陽は明るい.\n🏊 I swim in the ocean.\n私は海で泳ぎます.\n🍦 I eat cold ice cream.\n私は冷たいアイスクリームを食べます.\n🚗 We drive to the beach.\n私たちは車でビーチに行きます.\n⛱️ The umbrella is big.\n傘は大きい.\n🥪 I eat lunch at noon.\n私はお昼に昼食を食べます.\n🏩 The restaurant is good.\nレストランは良い.\n🌅 I go home at night.\n私は夜に家に帰ります.\n🌊 Do you go to the beach？\nあなたはビーチに行きますか？\n🏖️ Is the beach far？\nビーチは遠いですか？\n☀️ Is the sun bright？\n太陽は明るいですか？\n🏊 Can you swim？\nあなたは泳ぐことができますか？\n🍦 Do you like ice cream？\nあなたはアイスクリームが好きですか？\n🚗 Do you have a car？\nあなたは車を持っていますか？\n⛱️ Is this umbrella big？\nこの傘は大きいですか？\n🥪 What do you eat？\nあなたは何を食べますか？\n🏩 Where is the restaurant？\nレストランはどこですか？\n🌅 When do you go home？\nあなたはいつ家に帰りますか？"
  },
  {
    "title": "27. Mountain Hiking (Present Simple / Wh-Questions)",
    "content": "🏔️ I go to the mountain.\n私は山に行きます.\n🥾 I wear hiking shoes.\n私はハイキング靴を履きます.\n🗺️ I look at a map.\n私は地図を見ます.\n⛈️ It is sunny today.\n今日は晴れです.\n🏕️ We walk on the path.\n私たちは道を歩きます.\n🌲 I see many trees.\n私は多くの木を見ます.\n🎒 My bag is heavy.\n私のバッグは重い.\n🥶 It is cool at the top.\n頂上は涼しい.\n🦅 I see a bird.\n私は鳥を見ます.\n🌟 The view is beautiful.\n景色は美しい.\n🏔️ Where do you go？\nあなたはどこへ行きますか？\n🥾 What do you wear？\nあなたは何を履いていますか？\n🗺️ Do you see the map？\nあなたは地圖を見ていますか？\n⛈️ Is it sunny？\n晴れていますか？\n🏕️ Do you walk？\nあなたは歩きますか？\n🌲 How many trees？\nどのくらいの木？\n🎒 Is your bag heavy？\nあなたのバッグは重いですか？\n🥶 Is it cold？\n寒いですか？\n🦅 What do you see？\nあなたは何を見ますか？\n🌟 Is the view beautiful？\n景色は美しいですか？"
  },
  {
    "title": "28. Summer Festival (Present Simple / Be-Verb)",
    "content": "🎏 My town has a festival.\n私の町には祭りがあります.\n🍜 I eat food at the stalls.\n私は屋台で食べ物を食べます.\n🎶 I listen to music.\n私は音楽を聞きます.\n🎎 I watch the dance.\n私は踊りを見ます.\n🏮 The lanterns are pretty.\n灯籠はきれいです.\n🎉 I am happy at the festival.\n私は祭りで幸せです.\n🎫 I buy a ticket.\n私はチケットを買います.\n🚮 I put rubbish in the bin.\n私はゴミをゴミ箱に入れます.\n🎇 I see fireworks.\n私は花火を見ます.\n📸 I take pictures.\n私は写真を撮ります.\n🎏 Do you have a festival？\nあなたの町には祭りがありますか？\n🍜 What do you eat？\nあなたは何を食べますか？\n🎶 Do you like music？\nあなたは音楽が好きですか？\n🎎 Is the dance fun？\n踊りは楽しいですか？\n🏮 Are the lanterns pretty？\n灯篭はきれいですか？\n🎉 Are you happy？\nあなたは幸せですか？\n🎫 Do you buy tickets？\nあなたはチケットを買いますか？\n🚮 What do you do？\nあなたは何をしますか？\n🎇 Do you like fireworks？\nあなたは花火が好きですか？\n📸 Do you take photos？\nあなたは写真を撮りますか？"
  },
  {
    "title": "29. Obon Holiday (Present Simple / Be-Verb)",
    "content": "👻 I see my family.\n私は家族を見ます.\n🕯️ I light a lantern.\n私は灯籠をともします.\n🎶 I listen to music.\n私は音楽を聞きます.\n🍚 I eat special food.\n私は特別な食べ物を食べます.\n🚢 I see the river.\n私は川を見ます.\n🎭 I watch the dance.\n私は踊りを見ます.\n🏮 The lantern is red.\n灯籠は赤です.\n🌙 It is dark at night.\n夜は暗い.\n✨ I see fireworks.\n私は花火を見ます.\n💖 I love my family.\n私は私の家族を愛しています.\n👻 Do you see your family？\nあなたは家族を見ますか？\n🕯️ Is the lantern bright？\n灯籠は明るいですか？\n🎶 Do you like music？\nあなたは音楽が好きですか？\n🍚 What do you eat？\nあなたは何を食べますか？\n🚢 Do you go to the river？\nあなたは川に行きますか？\n🎭 Is the dance good？\n踊りは良いですか？\n🏮 Is it red？\nそれは赤いですか？\n🌙 Is it night？\n夜ですか？\n✨ What do you see？\nあなたは何を見ますか？\n💖 Do you love your family？\nあなたは家族を愛していますか？"
  },
  {
    "title": "30. Summer Fireworks (Present Simple / Wh-Questions)",
    "content": "🎆 I see fireworks.\n私は花火を見ます.\n💥 It makes a big noise.\nそれは大きな音を立てます.\n👶 I see children.\n私は子供たちを見ます.\n🌃 We go to the park.\n私たちは公園に行きます.\n💔 My dog runs away.\n私の犬は走り去ります.\n🎇 They are red and blue.\nそれらは赤と青です.\n🎉 It is beautiful.\nそれは美しい.\n🏙️ I see the city.\n私は都市を見ます.\n✨ I look up.\n私は見上げます.\n🎆 I like fireworks.\n私は花火が好きです.\n🎆 What do you see？\nあなたは何を見ますか？\n💥 Is it loud？\nそれはうるさいですか？\n👶 Do you see children？\nあなたは子供たちを見ますか？\n🌃 Where do you go？\nあなたはどこへ行きますか？\n💔 Is your dog scared？\nあなたの犬は怖がっていますか？\n🎇 What color is it？\nそれは何色ですか？\n🎉 Is it beautiful？\nそれは美しいですか？\n🏙️ Do you see the city？\nあなたは都市を見ますか？\n✨ Where do you look？\nあなたはどこを見ますか？\n🎆 Do you like fireworks？\nあなたは花火が好きですか？"
  },
  {
    "title": "31. Late Summer Heat (Present Simple / Be-Verb)",
    "content": "🌡️ It is hot.\n暑い.\n☀️ The sun shines.\n太陽は輝く.\n🏙️ I walk outside.\n私は外を歩きます.\n💧 I drink water.\n私は水を飲みます.\n🌲 I see trees.\n私は木を見ます.\n💷 I use air conditioning.\n私はエアコンを使います.\n🚿 I take a shower.\n私はシャワーを浴びる.\n🌅 I see the sunset.\n私は日没を見る.\n🍶 I eat ice cream.\n私はアイスクリームを食べる.\n🌡️ Is it hot today？\n今日は暑いですか？\n☀️ Is the sun bright？\n太陽は明るいですか？\n🏙️ Do you walk outside？\nあなたは外を歩きますか？\n💧 Do you drink water？\nあなたは水を飲みますか？\n🌲 Are the trees green？\n木々は緑ですか？\n💷 Is it cool？\nそれは涼しいですか？\n🚿 Do you take a shower？\nあなたはシャワーを浴びますか？\n🌅 Is it evening？\n夕方ですか？\n🍶 What do you eat？\nあなたは何を食べますか？\n🌡️ Do you like summer？\nあなたは夏が好きですか？"
  },
  {
    "title": "32. Back to School (Present Simple / Wh-Questions)",
    "content": "📚 I go to school.\n私は学校に行きます.\n🎒 I have a bag.\n私はバッグを持っています.\n📏 I use a ruler.\n私は定規を使います.\n🚌 I take the bus.\n私はバスに乗ります.\n📖 I read a book.\n私は本を読みます.\n🌟 I see my friends.\n私は友人を見ます.\n📝 I write in my notebook.\n私はノートに書きます.\n🏫 The school is big.\n学校は大きい.\n😊 I am happy.\n私は幸せ.\n🎨 I draw a picture.\n私は絵を描く.\n📚 Do you go to school？\nあなたは学校に行きますか？\n🎒 What do you have？\nあなたは何を持っていますか？\n📏 Do you use a ruler？\nあなたは定規を使いますか？\n🚌 Do you take the bus？\nあなたはバスに乗りますか？\n📖 What do you read？\nあなたは何を読みますか？\n🌟 Who do you see？\nあなたは誰を見ますか？\n📝 Do you write？\nあなたは書きますか？\n🏫 Is your school big？\nあなたの学校は大きいですか？\n😊 Are you happy？\nあなたは幸せですか？\n🎨 What do you draw？\nあなたは何を描きますか？"
  },
  {
    "title": "33. Autumn Begins (Basic present patterns)",
    "content": "🍂 I like autumn very much.\\n秋がとても好きです。\\n🍂 The leaves change color now.\\n葉は今色を変えています。\\n🍂 The weather gets cooler.\\n天気は涼しくなります。\\n🍂 I see many red trees.\\n多くの赤い木が見えます。\\n🍂 Fall comes every year.\\n秋は毎年来ます。\\n🍂 Do you like autumn?\\n秋が好きですか？\\n🍂 What color are the leaves?\\n葉は何色ですか？\\n🍂 Is the weather cool today?\\n今日は涼しいですか？\\n🍂 How do you feel in autumn?\\n秋にどう感じますか？\\n🍂 Do you see red leaves?\\n赤い葉が見えますか？"
  },
  {
    "title": "34. Typhoon Season (Basic present patterns)",
    "content": "🌀 The typhoon comes in September.\\n台風は9月に来ます。\\n🌀 The rain falls very hard.\\n雨はとても激しく降ります。\\n🌀 I stay at home with my family.\\n家族と家にいます。\\n🌀 Typhoons bring strong winds.\\n台風は強風をもたらします。\\n🌀 I listen to the weather report.\\n天気予報を聞きます。\\n🌀 When do typhoons come?\\n台風はいつ来ますか？\\n🌀 Does the rain fall hard?\\n激しく雨が降りますか？\\n🌀 Where do you stay?\\nどこにいますか？\\n🌀 Do typhoons bring wind?\\n台風は風をもたらしますか？\\n🌀 Do you listen to the news?\\nニュースを聞きますか？"
  },
  {
    "title": "35. Back to School (Basic present patterns)",
    "content": "📚 School starts in September.\\n学校は9月に始まります。\\n📚 I have a new teacher.\\n新しい先生がいます。\\n📚 I meet my friends every day.\\n毎日友達に会います。\\n📚 My classroom is big.\\n私の教室は大きいです。\\n📚 I study English every morning.\\n毎朝英語を勉強します。\\n📚 When does school start?\\n学校はいつ始まりますか？\\n📚 Do you have a new teacher?\\n新しい先生がいますか？\\n📚 Where do you meet friends?\\n友達に会うのはどこですか？\\n📚 Is your classroom big?\\nあなたの教室は大きいですか？\\n📚 Do you study every day?\\n毎日勉強しますか？"
  },
  {
    "title": "36. Harvest Festivals (Basic present patterns)",
    "content": "🎃 We have a harvest festival.\\n収穫祭があります。\\n🎃 Farmers grow rice and vegetables.\\n農家は米と野菜を育てます。\\n🎃 We eat traditional food together.\\n一緒に伝統的な食べ物を食べます。\\n🎃 The festival is very fun.\\n祭りはとても楽しいです。\\n🎃 We celebrate with our village.\\n村の人たちと祝います。\\n🎃 Do you have a festival?\\n祭りがありますか？\\n🎃 What do farmers grow?\\n農家は何を育てますか？\\n🎃 What do you eat at festivals?\\n祭りで何を食べますか？\\n🎃 Is the festival fun?\\n祭りは楽しいですか？\\n🎃 Do you celebrate at school?\\n学校で祝いますか？"
  },
  {
    "title": "37. Halloween (Basic present patterns)",
    "content": "👻 Halloween is in October.\\nハロウィンは10月にあります。\\n👻 Children dress up in costumes.\\n子供たちは衣装で仮装します。\\n👻 They visit many houses.\\n多くの家を訪問します。\\n👻 They say trick or treat.\\nトリックオアトリートと言います。\\n👻 They get lots of candy.\\nたくさんのお菓子をもらいます。\\n👻 When is Halloween?\\nハロウィンはいつですか？\\n👻 Do children dress up?\\n子供たちは仮装しますか？\\n👻 Where do they visit?\\nどこを訪問しますか？\\n👻 What do they say?\\n何と言いますか？\\n👻 Do you like candy?\\nお菓子は好きですか？"
  },
  {
    "title": "38. Autumn Leaves (Koyo) (Basic present patterns)",
    "content": "🍁 Autumn leaves are beautiful.\\n秋の葉は美しいです。\\n🍁 They turn red and yellow.\\n赤と黄色に変わります。\\n🍁 Many tourists visit Japan.\\n多くの観光客が日本を訪れます。\\n🍁 We go to the mountains.\\n山に行きます。\\n🍁 I take many photos.\\n多くの写真を撮ります。\\n🍁 Are autumn leaves beautiful?\\n秋の葉は美しいですか？\\n🍁 What colors do you see?\\nどんな色が見えますか？\\n🍁 Do many tourists visit?\\n観光客が多いですか？\\n🍁 Where do you go?\\nどこに行きますか？\\n🍁 Do you take photos?\\n写真を撮りますか？"
  },
  {
    "title": "39. Moon Viewing (Basic present patterns)",
    "content": "🌕 We watch the full moon.\\n満月を見ます。\\n🌕 The moon is very bright.\\n月はとても明るいです。\\n🌕 We eat special rice cakes.\\n特別な餅を食べます。\\n🌕 It happens in October.\\n10月に起こります。\\n🌕 The night is very beautiful.\\n夜はとても美しいです。\\n🌕 When do we watch the moon?\\nいつ月を見ますか？\\n🌕 Is the moon bright?\\n月は明るいですか？\\n🌕 What do you eat at night?\\n夜に何を食べますか？\\n🌕 Does it happen in autumn?\\n秋に起こりますか？\\n🌕 Is the night beautiful?\\n夜は美しいですか？"
  },
  {
    "title": "40. Cooler Temperatures (Basic present patterns)",
    "content": "❄️ The days get shorter.\\n日が短くなります。\\n❄️ The weather gets colder.\\n天気は寒くなります。\\n❄️ I wear warm clothes.\\n暖かい服を着ます。\\n❄️ The wind blows in the evening.\\n夕方に風が吹きます。\\n❄️ Winter is coming soon.\\n冬はすぐに来ます。\\n❄️ Do the days get short?\\n日は短くなりますか？\\n❄️ Does the weather get cold?\\n天気は寒くなりますか？\\n❄️ What do you wear in autumn?\\n秋に何を着ますか？\\n❄️ When does the wind blow?\\nいつ風が吹きますか？\\n❄️ Does winter come soon?\\n冬はすぐに来ますか？"
  },
  {
    "title": "41. Autumn Food",
    "content": "🍎 I eat an apple every day.\n私は毎日リンゴを食べます.\n🧣 I need a warm scarf.\n私は暖かいマフラーが必要です.\n☕ I drink hot tea in the morning.\n私は朝に熱いお茶を飲みます.\n🥧 I like pumpkin pie very much.\n私はとてもカボチャパイが好きです.\n🌾 I see many pumpkins in the fall.\n秋に多くのカボチャを見ます.\n🌽 I cook corn for dinner often.\n私は夕食によくトウモロコシを料理します.\n🍁 I watch the beautiful leaves.\n私は美しい葉を見ます.\n🍂 I walk in the park often.\n私はよく公園を歩きます.\n🥕 I eat fresh vegetables regularly.\n私は定期的に新鮮な野菜を食べます.\n🌿 I feel happy in autumn.\n秋に私は幸せを感じます.\n🍎 Do you like apples？\nリンゴは好きですか？\n🧣 What do you need in winter？\n冬に何が必要ですか？\n☕ What do you drink in the morning？\n朝に何を飲みますか？\n🥧 Do you eat pie often？\nよくパイを食べますか？\n🌾 Where do you see pumpkins？\nどこでカボチャを見ますか？\n🌽 Do you cook vegetables？\n野菜を料理しますか？\n🍁 What do you watch in autumn？\n秋に何を見ますか？\n🍂 Do you walk outside？\n外を歩きますか？\n🥕 What vegetables do you eat？\nどんな野菜を食べますか？\n🌿 How do you feel today？\n今日、気分はどうですか？"
  },
  {
    "title": "42. School in Fall",
    "content": "📚 I study English every day.\n私は毎日英語を勉強します.\n✏️ I write with a pencil.\n私は鉛筆で書きます.\n👩‍🏫 I listen to the teacher.\n先生の話を聞きます.\n📖 I read books at home.\n家で本を読みます.\n🏫 I go to school by bus.\nバスで学校に行きます.\n👫 I talk with my friends.\n友達と話します.\n🎒 I carry my backpack to school.\nバックパックを学校に持ちます.\n🔢 I learn math in class.\n教室で数学を学びます.\n🌟 I get good grades.\n良い成績をとります.\n😊 I like school very much.\n私は学校がとても好きです.\n📚 What do you study？\n何を勉強しますか？\n✏️ What do you write with？\n何で書きますか？\n👩‍🏫 Do you listen well？\nよく聞きますか？\n📖 What books do you read？\nどんな本を読みますか？\n🏫 How do you go to school？\nどうやって学校に行きますか？\n👫 Who do you talk to？\n誰と話しますか？\n🎒 Do you have a backpack？\nバックパックを持っていますか？\n🔢 Is math easy or hard？\n数学は簡単ですか、それとも難しいですか？\n🌟 Do you like your grades？\n成績は好きですか？\n😊 How is school？\n学校はどうですか？"
  },
  {
    "title": "43. November Weather",
    "content": "☁️ It is cloudy today.\n今日は曇りです.\n☔ It rains in November.\n11月には雨が降ります.\n🌡️ It is cold this month.\n今月は寒いです.\n🌬️ The wind blows hard.\n風は強く吹きます.\n🍂 The leaves fall down.\n葉は落ちます.\n❄️ Sometimes it snows a little.\n時々少し雪が降ります.\n🌤️ Sometimes the sun shines.\n時々太陽が輝きます.\n💧 It is wet outside.\n外は濡れています.\n🌅 The sun sets early.\n太陽は早く沈みます.\n🌃 It gets dark early.\n早く暗くなります.\n☁️ Is it cloudy now？\n今は曇りですか？\n☔ Do you like rain？\n雨は好きですか？\n🌡️ Is it cold today？\n今日は寒いですか？\n🌬️ Do you feel the wind？\n風を感じますか？\n🍂 Where do leaves fall？\n葉はどこに落ちますか？\n❄️ Does it snow often？\nよく雪が降りますか？\n🌤️ Do you like sun or clouds？\n太陽と曇りのどちらが好きですか？\n💧 Is the ground wet？\n地面は濡れていますか？\n🌅 When does the sun set？\n太陽はいつ沈みますか？\n🌃 Is it dark outside？\n外は暗いですか？"
  },
  {
    "title": "44. Family and Friends",
    "content": "👩 My mother cooks dinner every evening.\n母は毎晩夕食を料理します.\n👨 My father works at an office.\n父はオフィスで働きます.\n👧 My sister goes to high school.\n姉は高校に行きます.\n👦 My brother plays soccer often.\n兄はよくサッカーをします.\n👴 I visit my grandparents often.\n私はよく祖父母を訪ねます.\n👫 I have many good friends.\n私は多くの良い友達がいます.\n🏠 We eat dinner together.\n私たちは一緒に夕食を食べます.\n❤️ I love my family very much.\n私は家族がとても大好きです.\n🤝 We help each other.\n私たちはお互いを助けます.\n😊 We are happy together.\n私たちは一緒で幸せです.\n👩 Does your mother cook？\nあなたの母は料理しますか？\n👨 Where does your father work？\nあなたの父はどこで働きますか？\n👧 Does your sister study？\nあなたの姉は勉強しますか？\n👦 What does your brother play？\nあなたの兄は何をしますか？\n👴 Do you visit your family？\n家族を訪ねますか？\n👫 Do you have friends？\n友達はいますか？\n🏠 What do you eat for dinner？\n夕食に何を食べますか？\n❤️ Do you love your family？\n家族は大好きですか？\n🤝 Do you help others？\n他の人を助けますか？\n😊 Is your family happy？\nあなたの家族は幸せですか？"
  },
  {
    "title": "45. Winter Fun",
    "content": "❄️ I play in the snow every winter.\n私は毎年冬に雪の中で遊びます.\n☕ I drink hot cocoa when it is cold.\n寒いときにホットココアを飲みます.\n🧤 I wear warm gloves outside.\n外では暖かい手袋を着ます.\n🌨️ I watch the snow fall down.\n私は雪が降るのを見ます.\n🏠 I stay inside when it is very cold.\nとても寒いときは家の中にいます.\n🎄 I like the Christmas tree.\n私はクリスマスツリーが好きです.\n🎁 I give gifts to my family.\n家族にギフトをあげます.\n🎶 I sing holiday songs with friends.\n友達と祝日の歌を歌います.\n🎉 I enjoy December parties a lot.\n12月のパーティーをとても楽しんでいます.\n❄️ Do you like winter？\n冬は好きですか？\n☕ What do you drink when cold？\n寒いとき何を飲みますか？\n🧤 Do you wear gloves？\n手袋を着ますか？\n🌨️ Where do you play in snow？\n雪の中でどこで遊びますか？\n🏠 Do you stay inside often？\nよく家にいますか？\n🎄 Do you have a tree？\n木はありますか？\n🎁 What gifts do you give？\nどんなギフトをあげますか？\n🎶 Do you like music？\n音楽は好きですか？\n🎉 Do you like parties？\nパーティーは好きですか？\n🌟 What is your favorite thing about winter？\n冬について最も好きなことは何ですか？"
  },
  {
    "title": "46. Winter Clothes",
    "content": "🧥 I wear a coat in winter.\n私は冬にコートを着ます.\n🧣 I need a scarf today.\n今日はマフラーが必要です.\n🧢 I put a hat on my head.\n頭に帽子をかぶります.\n👢 I wear boots on my feet.\n足にはブーツを履きます.\n🧤 My hands are cold without gloves.\n手袋をしないと手は寒いです.\n👖 I wear jeans when it is cold.\n寒いときはジーンズを着ます.\n🧦 I need warm socks too.\n暖かい靴下も必要です.\n☕ I stay warm with hot drinks.\n熱いドリンクで暖まります.\n🏠 I stay warm inside my home.\n家の中で暖かくしています.\n❄️ I go outside to play in winter.\n冬は外に出て遊びます.\n🧥 Do you have a winter coat？\n冬のコートは持っていますか？\n🧣 What do you wear on your neck？\n首に何を着ますか？\n🧢 Do you like wearing hats？\n帽子を着るのは好きですか？\n👢 What shoes do you wear in winter？\n冬にどんな靴を履きますか？\n🧤 Are your hands cold？\n手は寒いですか？\n👖 Do you wear jeans？\nジーンズを着ますか？\n🧦 What color are your socks？\n靴下は何色ですか？\n☕ How do you stay warm？\nどうやって暖かくしていますか？\n🏠 Is your home warm？\nあなたの家は暖かいですか？\n❄️ Do you like going outside？\n外に出るのは好きですか？"
  },
  {
    "title": "47. December Celebrations",
    "content": "🎄 I decorate the Christmas tree.\n私たちはクリスマスツリーを飾ります.\n🎁 I wrap many gifts.\n多くのプレゼントを包みます.\n🎂 I have a birthday in December.\n12月に誕生日があります.\n🎵 I listen to Christmas music often.\nよくクリスマス音楽を聴きます.\n🎉 I celebrate with my family.\n家族と祝います.\n🕯️ I light candles at night.\n夜にろうそくを灯します.\n🍪 I eat cookies and drink tea.\nクッキーを食べてお茶を飲みます.\n❤️ I feel happy this month.\n今月は幸せを感じます.\n👨‍👩‍👧‍👦 My family visits my house.\n私の家族が私の家を訪ねます.\n🌟 December is a special month.\n12月は特別な月です.\n🎄 Do you decorate for holidays？\n祝日のために装飾しますか？\n🎁 What do you give as gifts？\nどんなギフトをあげますか？\n🎂 When is your birthday？\n誕生日はいつですか？\n🎵 Do you like holiday music？\n祝日の音楽は好きですか？\n🎉 Who celebrates with you？\n誰と一緒に祝いますか？\n🕯️ Do you like candles？\nろうそくは好きですか？\n🍪 What treats do you eat？\nどんなおやつを食べますか？\n❤️ How do you feel today？\n今日、気分はどうですか？\n👨‍👩‍👧‍👦 Does your family visit often？\n家族はよく訪ねますか？\n🌟 Do you like December？\n12月は好きですか？"
  },
  {
    "title": "48. Winter Days",
    "content": "☀️ The sun comes up late in winter.\n冬は太际が遅く昇ります.\n🌅 The sun goes down early.\n太陽は早く沈みます.\n❄️ Snow covers everything white.\n雪がすべてを白く覆います.\n💧 Ice forms on the water.\n氷が水の上にできます.\n💨 The wind feels very cold.\n風はとても寒い感じがします.\n🌨️ Snow falls from the sky.\n雪が空から降ります.\n🌟 Stars shine bright at night.\n星は夜に明るく輝きます.\n🌙 The moon looks beautiful.\n月は美しく見えます.\n🏠 I spend time inside my home.\n私は家の中で時間を過ごします.\n☕ I enjoy hot drinks in winter.\n私は冬に熱いドリンクを楽しみます.\n☀️ Do you like the winter sun？\n冬の太陽は好きですか？\n🌅 When does the sun set？\n太陽はいつ沈みますか？\n❄️ Do you like snow？\n雪は好きですか？\n💧 Is there ice near you？\n近くに氷はありますか？\n💨 Is the wind strong？\n風は強いですか？\n🌨️ Does it snow in your town？\nあなたの町では雪が降りますか？\n🌟 Do you see many stars？\n多くの星を見ますか？\n🌙 Do you like the moon？\n月は好きですか？\n🏠 What do you do inside？\n家の中で何をしますか？\n☕ What hot drinks do you like？\nどんな熱いドリンクが好きですか？"
  }
];
