var eiken7fun = [
  {
    "title": "13. Week 5 - Baseball Game",
    "content": "⚾ I play baseball today. 今日は野球をします。\n\n🏟️ We go to the field. フィールドに行きます。\n\n👦 My team has good players. 私のチームには良い選手がいます。\n\n⚾ The pitcher throws the ball. ピッチャーがボールを投げます。\n\n💨 I swing the bat! 私はバットを振ります！\n\n😮 I hit the ball! ボールに当たりました！\n\n🚴 The ball goes far! ボールが遠くへ行きました！\n\n🏃 I run bases fast! 私はベースを速く走ります！\n\n🏆 My team wins the game! 私のチームが勝ちました！\n\n😊 We are so happy! 私たちはとても幸せです！\n\nDo you like baseball? 野球は好きですか？\n\nWhat sports do you play? どんなスポーツをしますか？\n\nDo you run fast? 速く走れますか？\n\nDo you win games often? よく試合に勝ちますか？\n\nDoes your team have good players? あなたのチームには良い選手がいますか？\n\nDo you like team sports? チームスポーツは好きですか？\n\nDo you feel happy when you win? 勝つときは幸せですか？\n\nDo you practice sports often? スポーツの練習はよくしますか？\n\nDo you like to run? 走るのは好きですか？\n\nDo you like to try new things? 新しいことに挑戦するのは好きですか？"
  },
  {
    "title": "14. Week 5 - Zoo Visit",
    "content": "🦁 I visit the zoo today. 今日は動物園に行きます。\n\n🐯 I see big tigers. 大きなトラを見ます。\n\n🐘 I see big elephants too. 大きなゾウも見ます。\n\n🦒 The giraffe is very tall. キリンはとても背が高いです。\n\n🦓 The zebra has stripes. シマウマにはしま模様があります。\n\n🐵 Parrots talk to me. オウムが私に話しかけます。\n\n🐧 The penguin cannot fly. ペンギンは飛べません。\n\n🐇 The dolphin swims fast. イルカは速く泳ぎます。\n\n🐤 I like all the animals. すべての動物が好きです。\n\n😊 The zoo is so fun! 動物園はとても楽しい！\n\nDo you like zoos? 動物園は好きですか？\n\nWhat is your favorite animal? 一番好きな動物は何ですか？\n\nHave you seen a tiger? トラを見たことがありますか？\n\nDo you like tall animals? 背の高い動物は好きですか？\n\nDo birds talk to you? 鳥はあなたに話しかけますか？\n\nDo you like swimming? 泳ぐのは好きですか？\n\nDo you like to visit new places? 新しい場所を訪れるのは好きですか？\n\nDo you learn about animals? 動物について学びますか？\n\nHave you seen big animals? 大きな動物を見たことがありますか？\n\nDo you have fun at the zoo? 動物園は楽しいですか？"
  },
  {
    "title": "15. Week 5 - Car Ride",
    "content": "🚗 My dad drives the car. お父さんが車を運転します。\n\n🚙 The car is blue. 車は青いです。\n\n🎵 Music plays in the car. 車で音楽が流れています。\n\n😊 I sing along to the songs. 歌に合わせて歌います。\n\n🏍️ We drive down the street. 道の下を走ります。\n\n🏫 We go to the school. 学校に行きます。\n\n🏠 Then we go back home. それから家に帰ります。\n\n🚙 The car goes fast. 車は速いです。\n\n😄 I like car rides. 車での移動は好きです。\n\n❤️ My dad drives safely. お父さんは安全に運転します。\n\nDo you like cars? 車は好きですか？\n\nDoes your dad drive? お父さんは運転しますか？\n\nWhat color is your car? あなたの車は何色ですか？\n\nDo you like music in the car? 車では音楽が好きですか？\n\nDo you sing when you travel? 旅行のときは歌いますか？\n\nDo you drive slowly or fast? ゆっくり運転しますか、それとも速く？\n\nDo you go to school by car? 車で学校に行きますか？\n\nDo you feel safe in the car? 車の中で安全ですか？\n\nDoes your family travel often? 家族はよく旅行しますか？\n\nDo you go back home often? よく家に帰りますか？"
  },
  {
    "title": "16. Week 5 - Ice Cream Shop",
    "content": "🍦 I go to the ice cream shop. アイスクリーム店に行きます。\n\n🍬 There are many flavors. たくさんの味があります。\n\n🍨 My sister wants chocolate. 妹はチョコレートが欲しいです。\n\n🍋 My friend wants lemon. 友達はレモンが欲しいです。\n\n🍓 I want strawberry! 私はイチゴが欲しい！\n\n🧁 We all get different flavors. みんな違う味を選びます。\n\n😋 The ice cream is cold! アイスクリームは冷たいです！\n\n😛 It tastes sweet! 甘くて美味しいです！\n\n🤤 We eat it all fast! 全部速く食べました！\n\n😊 We want more ice cream! もっとアイスクリームが欲しい！\n\nDo you like ice cream? アイスクリームは好きですか？\n\nWhat flavor do you like best? どんな味が一番好きですか？\n\nDo you like cold food? 冷たい食べ物は好きですか？\n\nDo you like sweet food? 甘い食べ物は好きですか？\n\nDo you eat fast or slowly? 速く食べますか、それともゆっくり？\n\nDoes your sister like chocolate? 妹はチョコレートが好きですか？\n\nDo you have a favorite flavor? 好きな味はありますか？\n\nDo you eat snacks often? おやつはよく食べますか？\n\nWhat do you like to eat? あなたは何が食べたいですか？\n\nDo you want more tasty food? もっと美味しい食べ物が欲しいですか？"
  },
  {
    "title": "17. Week 5 - TV Show",
    "content": "📺 I watch TV. 私はテレビを見ます。\n\n🎬 My favorite show starts. 好きな番組が始まりました。\n\n😂 The show is very funny! 番組はとても面白いです！\n\n🎭 People act in the show. 俳優が出演します。\n\n💃 They dance and sing. 歌とダンスをします。\n\n👩 My mom watches with me. お母さんと一緒に見ます。\n\n👨 My dad sits too. お父さんも座っています。\n\n😄 We all laugh together. みんなで一緒に笑います。\n\n🎉 The show is over soon! 番組はすぐに終わります！\n\n😊 TV is fun to watch! テレビを見るのは楽しい！\n\nDo you watch TV? テレビは見ますか？\n\nDo you like funny shows? 面白い番組は好きですか？\n\nDo you like to laugh? 笑うのは好きですか？\n\nDo you like music? 音楽は好きですか？\n\nDo you sing along sometimes? 時々歌に合わせて歌いますか？\n\nDoes your family watch TV too? 家族もテレビを見ますか？\n\nDo you like to dance? ダンスは好きですか？\n\nDo you sit together with friends? 友達と一緒に座りますか？\n\nDo you like movies or TV better? 映画とテレビ、どちらが好きですか？\n\nDo you like ending stories? 物語の結末は好きですか？"
  },
  {
    "title": "18. Week 5 - Beach Day",
    "content": "🏖️ We go to the beach. 海に行きます。\n\n🌊 The sea is blue. 海は青いです。\n\n☀️ The sun is hot. 太陽は暑いです。\n\n🏖️ The sand is white. 砂は白いです。\n\n👟 We run on the sand. 砂の上を走ります。\n\n🚣 I swim in the water. 私は水で泳ぎます。\n\n💦 The water feels good. 水は気持ちいいです。\n\n⛱️ I sit under an umbrella. 傘の下に座ります。\n\n🐚 I find a seashell. 貝殻を見つけました。\n\n😊 I love the beach! 海が大好きです！\n\nDo you like the beach? 海は好きですか？\n\nDo you like swimming? 泳ぐのは好きですか？\n\nDo you like sunny days? 晴れた日は好きですか？\n\nDo you like sand? 砂は好きですか？\n\nDo you run on the beach? 海で走りますか？\n\nDo you feel hot in summer? 夏は暑いと感じますか？\n\nDo you like umbrellas? 傘は好きですか？\n\nHave you found seashells? 貝殻を見つけたことがありますか？\n\nDo you like to find things? 探検するのは好きですか？\n\nDo you like the sea? 海は好きですか？\n\nDo you have fun outside? 外では楽しいですか？"
  },
  {
    "title": "19. Week 6 - Park Play",
    "content": "🌳 I go to the park. 公園に行きます。\n\n🌸 There are many flowers. たくさんの花があります。\n\n🐦 A bird sings on a tree. 木の上で鳥が歌っています。\n\n🪑 I sit on a bench. ベンチに座ります。\n\n🚶 A dog runs by. 犬が走っていきます。\n\n🚶 My friend walks over. 友達が歩いてきました。\n\n⚽ We play soccer together. サッカーを一緒にします。\n\n😆 We run a lot! 私たちはたくさん走ります！\n\n💧 We drink water. 私たちは水を飲みます。\n\n😌 The park is nice! 公園はいいところです！\n\nDo you go to the park? 公園に行きますか？\n\nDo you like flowers? 花は好きですか？\n\nDo you like trees? 木は好きですか？\n\nDo birds sing where you live? あなたの住んでいる場所で鳥は歌いますか？\n\nDo you like dogs? 犬は好きですか？\n\nDo you have a bench near you? あなたのそばにベンチはありますか？\n\nDo you like to run? 走るのは好きですか？\n\nDo you drink water often? よく水を飲みますか？\n\nDo you feel hot sometimes? 時々暑いと感じますか？\n\nDo you play with friends often? 友達とよく遊びますか？\n\nDo you like nice places? いい場所は好きですか？"
  },
  {
    "title": "20. Week 6 - Music Lesson",
    "content": "🎹 I have piano lessons. ピアノのレッスンがあります。\n\n🎵 The teacher is nice. 先生は優しいです。\n\n🎶 She teaches me a song. 先生は私に歌を教室してくれます。\n\n🎹 I play the piano. 私はピアノを演奏します。\n\n👏 My family listens. 家族が聞いています。\n\n🎵 The song is beautiful. 歌はきれいです。\n\n😊 I feel happy! 幸せを感じます！\n\n🎸 Tomorrow I play guitar. 明日はギターを演奏します。\n\n🎤 I can sing too! 歌うこともできます！\n\n😊 Music makes me happy! 音楽は私を幸せにします！\n\nDo you play an instrument? 楽器を演奏しますか？\n\nDo you like piano? ピアノは好きですか？\n\nDo music teachers help you? 音楽の先生はあなたを助けてくれますか？\n\nDo you learn new songs? 新しい歌を学びますか？\n\nDoes your family like music? 家族は音楽が好きですか？\n\nDo you like beautiful songs? きれいな歌は好きですか？\n\nDo you feel happy today? 今日は幸せですか？\n\nDo you like to try new things? 新しいことに挑戦するのは好きですか？\n\nDo you like singing? 歌うのは好きですか？\n\nDo you play other instruments? 他の楽器も演奏しますか？\n\nDoes music make you happy? 音楽はあなたを幸せにしますか？"
  },
  {
    "title": "21. Week 6 - Brother's Birthday",
    "content": "🎂 It is my brother's birthday. 兄のお誕生日です。\n\n🎁 He is six years old. 彼は6歳です。\n\n🎈 We have a small party. 小さなパーティーをします。\n\n👨 Mom and Dad come too. お父さんとお母さんも来ます。\n\n🍰 Mom makes chocolate cake. お母さんがチョコレートケーキを焼きます。\n\n🕯️ We light the candles. ろうそくに火をつけます。\n\n🎶 We sing happy birthday together. 一緒に歌います。\n\n🎁 He opens his gifts. 彼はプレゼントを開けます。\n\n😊 He is very happy! 彼はとても幸せです！\n\n💖 I love my brother! 私は兄が大好きです！\n\nDo you have a brother? 兄はいますか？\n\nHow old is he now? 彼は今何歳ですか？\n\nDo you have parties? パーティーはありますか？\n\nDo your parents come? 親は来ますか？\n\nDoes your mom bake cakes? お母さんはケーキを焼きますか？\n\nDo you sing happy birthday? ハッピーバースデーの歌を歌いますか？\n\nDo you get gifts on your birthday? 誕生日にプレゼントをもらいますか？\n\nDo you like family parties? 家族のパーティーは好きですか？\n\nAre you happy for your brother? 兄のために幸せですか？\n\nDo you love your family? 家族を愛していますか？\n\nDo you have fun together? 一緒に楽しみますか？"
  },
  {
    "title": "22. Week 6 - Bicycle Ride",
    "content": "🚲 I ride my bike. 自転車に乗ります。\n\n🚲 My bike is purple. 自転車は紫です。\n\n⚙️ It has two wheels. 車輪が2つあります。\n\n🚴 I ride fast! 私は速く乗ります！\n\n👟 I wear my helmet. ヘルメットをかぶります。\n\n🛣️ We ride on the path. 道で乗ります。\n\n🏘️ We go around the park. 公園の周りを走ります。\n\n😋 Riding is so fun! 乗るのはとても楽しい！\n\n😌 I feel the wind! 風を感じます！\n\n😊 My bike is great! 自転車は最高です！\n\nDo you have a bike? 自転車を持っていますか？\n\nWhat color is your bike? あなたの自転車は何色ですか？\n\nDo you wear a helmet? ヘルメットをかぶりますか？\n\nDo you ride fast? 速く乗りますか？\n\nDo you have paths near your house? 家のそばに道はありますか？\n\nDo you like parks? 公園は好きですか？\n\nDo you ride in the wind? 風の中で乗りますか？\n\nDo you have fun bikes? 楽しい自転車はありますか？\n\nDo you feel the wind outside? 外で風を感じますか？\n\nDo you like to go fast? 速く行くのは好きですか？\n\nDo you ride with friends? 友達と乗りますか？"
  },
  {
    "title": "23. Week 7 - Library",
    "content": "📚 I go to the library. 図書館に行きます。\n\n🏢 The building is big. 建物は大きいです。\n\n📖 I see many books. たくさんの本を見ます。\n\n🐻 I find a bear book. クマの本を見つけました。\n\n🌈 The pictures are colorful. 挿絵はカラフルです。\n\n📚 I find a butterfly book too. 蝶の本も見つけました。\n\n🪑 I sit and read. 座って読みます。\n\n📖 The story is good. 物語は良いです。\n\n😊 The library is quiet. 図書館は静かです。\n\n😌 I like reading books. 本を読むのが好きです。\n\nDo you go to the library? 図書館に行きますか？\n\nDo you like big buildings? 大きな建物は好きですか？\n\nDo you like to read? 本を読むのは好きですか？\n\nDo you like bears? クマは好きですか？\n\nDo you like butterflies? 蝶は好きですか？\n\nDo you like colorful pictures? カラフルな挿絵は好きですか？\n\nDo you sit when you read? 読むときは座りますか？\n\nDo you like good stories? 良い物語は好きですか？\n\nDo you like quiet places? 静かな場所は好きですか？\n\nDo you read every day? 毎日読みますか？\n\nDo you want more books? もっと本が欲しいですか？"
  },
  {
    "title": "24. Week 7 - Card for Mom",
    "content": "🎁 I make a card for Mom. お母さんにカードを作ります。\n\n📝 I write I love you on it. 「愛してる」と書きます。\n\n💐 I draw flowers too. 花も描きます。\n\n🌺 The flowers are red and pink. 花は赤とピンクです。\n\n💌 Mom opens the card later. お母さんが後でカードを開けます。\n\n💕 She smiles big. 彼女は大きく微笑みます。\n\n🥰 She gives me a hug. 私に抱擁をくれます。\n\n😊 I feel happy forever! 私は永遠に幸せです！\n\n❤️ Love is wonderful! 愛は素晴らしい！\n\nDo you make cards? カードを作りますか？\n\nDo you write messages? メッセージを書きますか？\n\nDo you like drawing pictures? 絵を描くのは好きですか？\n\nDo you like flowers? 花は好きですか？\n\nWhat are your favorite colors? 好きな色は何ですか？\n\nDo you give gifts often? よくプレゼントをあげますか？\n\nDoes your mom smile a lot? お母さんはよく笑いますか？\n\nDo you like hugs? 抱擁は好きですか？\n\nDo you feel happy often? よく幸せですか？\n\nIs your family important to you? 家族はあなたにとって重要ですか？\n\nDo you like to say you love someone? 「愛してる」と言うのは好きですか？"
  }
];
