var eiken7grammar = [
 {
 "title": "Grammar: Eiken 7",
 "content": "BE Verb (am/is/are)\nBE動詞\n\nI am a 👦/👩/🧑‍⚕️.\n私は〜です。（私 です 👦/👩/🧑‍⚕️）\nYou are 😊/💝/📏.\nあなたは〜です。（あなた です 😊/💝/📏）\nHe is 👨/🏃/🧑‍⚕️.\n彼は〜です。（彼 です 📏/💪/👦‍⚕️）\nShe is 👩/🏃/🧑‍⚕️.\n彼女は〜です。（彼女 です 💝/🧠/🌸‍⚕️）\nWe are 👦👧🧒/👫/🎓.\n私たちは〜です。（私たち です 👦👧🧒/👫/🎓）\nThey are 🐱s/🐶s/🐦s.\n彼らは〜です。（彼ら です 🐱s/🐶s/🐦s）\nThis is a 📖/🖊️/🎒.\nこれは〜です。（これ です 一つの 📖/🖊️/🎒）\nThat is a 🏠/🌳/🚗.\nあれは〜です。（あれ です 一つの 🏠/🌳/🚗）\nAre you 😊/✅/😋?\nです あなた 😊/✅/😋？（あなたは〜ですか？）\nIs he 👨/🏃/🧑‍⚕️?\nです 彼 👨/🏃/🧑‍⚕️？（彼は〜ですか？）\nIs she 👩/🏃/👩‍🏫?\nです 彼女 👩/🏃/👩‍🏫？（彼女は〜ですか？）\nAre they 🐱s/🐶s/🐦s?\nです 彼ら 🐱s/🐶s/🐦s？（彼らは〜ですか？）\nI like 🐱/🎵/🍕.\n私は〜が好きです。（私 好き 🐱/🎵/🍕）\nYou like ⚽/🎨/🍦.\nあなたは〜が好きです。（あなた 好き ⚽/🎨/🍦）\nDo you like 🍕/🍦/🎂?\nする あなた 好き 🍕/🍦/🎂？（あなたは〜が好きですか？）\nDoes he like ⚽/🎮/📺?\nする 彼 好き ⚽/🎮/📺？（彼は〜が好きですか？）\nI don't like 🕷️/🐍/🐛.\n私は〜が好きではありません。（私 しない 好き 🕷️/🐍/🐛）\nWh-Questions\n疑問詞\n\nWhat is 🔴/🔵/🟢?\n何 です 🔴/🔵/🟢？（〜は何ですか？）\nWhere is 🏠/🏫/🌳?\nどこ です 🏠/🏫/🌳？（〜はどこですか？）\nIt is 🐘/🐜/❄️.\nそれは〜です。（それ です 😊/😢/🤒）\n"
 }
];

var eiken6grammar = [
 {
 "title": "Grammar: Eiken 6",
 "content": "Present Continuous\n現在進行形\n\nI am 🏃/🏊/📖ing.\n私は〜しています。（私 いる して）\nHe is 🏃/🏊/📖ing.\n彼は〜しています。（彼 いる して）\nShe is 🏃/🏊/📖ing.\n彼女は〜しています。（彼女 いる して）\nThey are 🏃/🏊/📖ing.\n彼らは〜しています。（彼ら いる して）\nAre you 🏃/🏊/📖ing?\nいる あなた して？（あなたは〜していますか？）\nIs he 🏃/🏊/📖ing?\nいる 彼 して？（彼は〜していますか？）\nI was 😊/😢/🤒.\n私は〜だった。（私 だった 😊/😢/🤒）\nHe was 😊/😢/🤒.\n彼は〜だった。（彼 だった 😊/😢/🤒）\nShe was 😊/😢/🤒.\n彼女は〜だった。（彼女 だった 😊/😢/🤒）\nWe were 😊s/😢s/🤒s.\n私たちは〜だった。（私たち だった 🏃/📖/🎵）\nThey were 😊s/😢s/🤒s.\n彼らは〜だった。（彼ら だった 🏃/📖/🎵）\nWas he 😊/😢/🤒?\nだった 彼 🏃/📖/🎵？（彼は〜でしたか？）\nWere you 😊/😢/🤒?\nだった あなた 🏃/📖/🎵？（あなたは〜でしたか？）\nI 🏃/📖/🎵.\n私 動詞。（私は〜する。）\nYou 🏃/📖/🎵.\nあなたは〜する。（あなた 動詞）\nHe 🏃s/📖s/🎵s.\n彼は〜する。（彼 動詞する）\nShe 🏃s/📖s/🎵s.\n彼女は〜する。（彼女 動詞する）\nDo you 🏃/📖/🎵?\nする あなた 🏃/📖/🎵？（あなたは〜しますか？）\nDoes he 🏃/📖/🎵?\nする 彼 🏃/📖/🎵？（彼は〜しますか？）\nDoes she 🏃/📖/🎵?\nする 彼女 🏃/📖/🎵？（彼女は〜しますか？）\nI can 🏃/🏊/🚴.\n私は〜できます。（私 できる 🏃/📖/🎵）\nShe can 🎨/🎹/🎤.\n彼女は〜できます。（彼女 できる 🏃/📖/🎵）\nCan you 🏃/🏊/🚴?\nできる あなた 🏃/📖/🎵？（あなたは〜できますか？）\nI have a 🐱/🐶/🐟.\n私は〜を持っています。（私 持つ 一つの 🏃/📖/🎵）\nShe has a 📱/🐰/🐢.\n彼女は〜を持っています。（彼女 持つ 一つの 🏃/📖/🎵）\nThis is my 🐱/📖/🎨.\nこれは私の〜です。（これ です 私の 🏃/📖/🎵）\nThat is his 🐱/📖/🎨.\nあれは彼の〜です。（あれ です 彼の 🏃/📖/🎵）\nThere is/are\n〜がある\n\nThere is a 🐱/🏠/🌳.\n〜があります。（そこ です 一つの 🏃/📖/🎵）\nThere are 🐱s/🏠s/🌳s.\n〜があります。（そこ です 😊/😢/🤒）\nImperatives\n命令形\n\n📖/✏️/👂 your book.\n本を〜しなさい。（開く あなたの 本）\nPlease 🤝/👋/🙋.\n〜してください。（どうぞ 助ける）\n"
 }
];

var eiken5grammar = [
 {
 "title": "Grammar: Eiken 5",
 "content": "Present Simple\n現在形\n\nI 🍳/📚/🧹 every day.\n私は毎日〜する。（私 動詞 毎日）\nYou 📖/✏️/🗣️ at school.\nあなたは学校で〜する。（あなた 動詞 に 学校）\nWe ⚽/🏀/🎾 on Monday.\n私たちは月曜日に〜する。（私たち 動詞 に 月曜日）\nThey 🏠/🏫/🏢 in Tokyo.\n彼らは東京で〜する。（彼ら 動詞 に 東京）\nHe 🍳s/📚s/🧹s every day.\n彼は毎日〜する。（彼 🏃/📖/🎵s すべての 日）\nShe 📖s/✏️s/🗣️s at school.\n彼女は学校で〜する。（彼女 🏃/📖/🎵s に 学校）\nPresent Continuous\n現在進行形\n\nI am 🏃/🏊/📖ing now.\n私は今〜している。（私 いる して 今）\nShe is 🏃/🏊/📖ing now.\n彼女は今〜している。（彼女 いる して 今）\nThey are 🏃/🏊/📖ing now.\n彼らは今〜している。（彼ら いる して 今）\nDo/Does Questions\nDo/Doesの疑問文\n\nDo you 🏃/📖/🎵 every day?\nする あなた 🏃/📖/🎵 すべての 日？（あなたは毎日〜しますか？）\nDoes he 🏃/📖/🎵 every day?\nする 彼 🏃/📖/🎵 すべての 日？（彼は毎日〜しますか？）\nDoes she 📖/✏️/🎨 at school?\nする 彼女 🏃/📖/🎵 に 学校？（彼女は学校で〜しますか？）\nI don't 🏃/📖/🎵 every day.\n私は毎日〜しない。（私 しない 🏃/📖/🎵 すべての 日）\nHe doesn't 📖/✏️/🎨 at school.\n彼は学校で〜しない。（彼 しない 🏃/📖/🎵 に 学校）\nWh-Questions\n疑問詞\n\nWhat do you 🎨/🍳/📚?\n何 する あなた 🏃/📖/🎵？（あなたは〜何をしますか？）\nWhere do you 🏃/🛒/🍽️?\nどこ する あなた 🏃/📖/🎵？（あなたはどこで〜しますか？）\nWhen do you 🏃/📖/😴?\nいつ する あなた 🏃/📖/🎵？（あなたはいつ〜しますか？）\nWhy do you 📖/🏃/🧹?\nなぜ する あなた 🏃/📖/🎵？（あなたはなぜ〜しますか？）\nHow do you 📖/🍳/🎨?\nどう する あなた 🏃/📖/🎵？（あなたはどう〜しますか？）\nWho 🏃s/📖s/🎨s?\n誰 🏃/📖/🎵s？（誰が〜しますか？）\nWhat is your 🏃/📖/🎵?\n何 です あなたの 🏃/📖/🎵？（あなたの〜は何ですか？）\nWhere is your 🏃/📖/🎵?\nどこ です あなたの 🏃/📖/🎵？（あなたの〜はどこですか？）\nI can 🏃/🏊/🎨 well.\n私は上手に〜できます。（私 できる 🏃/📖/🎵 上手に）\nCan you 🏃/🏊/🚴?\nできる あなた 🏃/📖/🎵？（あなたは〜できますか？）\nYou should 📖/🏃/🧹.\nあなたは〜すべきです。（あなた べき 🏃/📖/🎵）\nPrepositions\n前置詞\n\nI 🍳/🚿/☕ in the morning.\n私は朝〜する。（私 🏃/📖/🎵 に その 朝）\nI 📖/🎨/🎮 at 3 o'clock.\n私は3時に〜する。（私 🏃/📖/🎵 に 3時）\nI ⛪/🏖️/🎮 on Sunday.\n私は日曜日に〜する。（私 🏃/📖/🎵 に 日曜日）\nIt is 🏃/📖/🎵 the box.\nそれは箱の中に〜。（それ です 🏃/📖/🎵 その 箱）\nArticles\n冠詞\n\nI have a 🐱/🐶/🐟.\n私は〜を一つ持っている。（私 持つ 一つの 🏃/📖/🎵）\nI like the 🌸/🌅/🎵.\n私はその〜が好きです。（私 好き その 🏃/📖/🎵）\nShe is an 👩‍🏫/👩‍⚕️/👩‍🎨.\n彼女は〜です。（彼女 です 一つの 🏃/📖/🎵）\nI like 🎨/🎵/📚 him.\n私は彼を〜好きです。（私 好き 🏃/📖/🎵 彼）\nShe helps 🏃/📖/🎨 me.\n彼女は私を〜助ける。（彼女 助ける 🏃/📖/🎵 私）\nI see 🏃/📖/🎨 them.\n私は彼らを〜見る。（私 見る 🏃/📖/🎵 彼ら）\nComparatives\n比較級\n\nThis is 🐘/🦒/🏔️er than that.\nこれはあれより〜です。（これ です 🏃/📖/🎵er より あれ）\nShe is more 😊/🎨/📚 than me.\n彼女は私より〜です。（彼女 です もっと 🏃/📖/🎵 より 私）\nI am 🐘/🦒/🏔️er than you.\n私はあなたより〜です。（私 です 🏃/📖/🎵er より あなた）\nPossessives ('s)\n所有格\n\nThis is 👨/👩/🧑's book.\nこれは〜の本です。（これ です 🏃/📖/🎵の 本）\nThat is my 👨/👩/🧑's car.\nあれは私の〜の車です。（あれ です 私の 🏃/📖/🎵の 車）\nFrequency Adverbs\n頻度副詞\n\nI 🏃/📖/🎵 always.\n私はいつも〜する。（私 🏃/📖/🎵 いつも）\nI 🎮/🛒/🍳 sometimes.\n私は時々〜する。（私 🏃/📖/🎵 時々）\nI 🏊/🚴/⛸️ never.\n私は決して〜しない。（私 🏃/📖/🎵 決して）\n"
 }
];

var eiken4grammar = [
 {
 "title": "Grammar: Eiken 4",
 "content": "Past Simple\n過去形\n\nI 🏃/📖/🎮ed yesterday.\n私は昨日〜した。（私 動詞した 昨日）\nShe 🎨/🍳/📚ed last week.\n彼女は先週〜した。（彼女 動詞した 先週）\nThey 📖/✏️/🎨ed at school.\n彼らは学校で〜した。（彼ら 動詞した に 学校）\nI 🍳/📚/🧹ed in the morning.\n私は朝〜した。（私 動詞した に 朝）\nPast Simple (irregular)\n過去形（不規則変化）\n\nI [went/saw/ate].\n私は〜した。（私 [行った/見た/食べた]）\nShe [went/saw/ate].\n彼女は〜した。（彼女 [行った/見た/食べた]）\nHe [made/took/had].\n彼は〜した。（彼 [作った/取った/持った]）\nShe didn't 🏃/📖/🎮.\n彼女は〜しなかった。（彼女 しない 食べる）\nDid you 🏃/📖/🎮 yesterday?\nした あなた 🏃/📖/🎵 昨日？（あなたは昨日〜しましたか？）\nDid she 🏃/📖/🎮 last week?\nした 彼女 🏃/📖/🎵 先週？（彼女は先週〜しましたか？）\nI will 🏃/📖/🎮 tomorrow.\n私は明日〜するだろう。（私 だろう 🏃/📖/🎵 明日）\nShe will 🎨/🍳/📚 next week.\n彼女は来週〜するだろう。（彼女 だろう 🏃/📖/🎵 来週）\nWill you 🏃/📖/🎮 tomorrow?\nだろう あなた 🏃/📖/🎵 明日？（あなたは明日〜しますか？）\nI won't 🏃/📖/🎵.\n私は〜しないだろう。（私 だろうしない 🏃/📖/🎵）\nGoing to\n〜するつもり\n\nI am going to 🏃/📖/🎮.\n私は〜するつもりです。（私 です 行く に 🏃/📖/🎵）\nShe is going to 🎨/🍳/📚.\n彼女は〜するつもりです。（彼女 です 行く に 🏃/📖/🎵）\nAre you going to 🏃/📖/🎮?\nですか あなた 行く に 🏃/📖/🎵？（あなたは〜するつもりですか？）\nThis is 🐘/🦒/🏔️er than that.\nこれはあれより〜です。（これ は 🏃/📖/🎵er より あれ）\nmore 🏃/📖/🎵 than 🏃/📖/🎵.\n〜より〜です。（もっと 🏃/📖/🎵 より 🏃/📖/🎵）\nthe 🐘/🦒/🏔️est.\n一番〜です。（その [___]est）\nthe most 😊/🎨/📚.\n一番〜です。（その 最も 🏃/📖/🎵）\nCould/Should/Must\nできた/べき/なければならない\n\nI could 🏃/🏊/🚴 when I was young.\n若い時〜できた。（私 できた 🏃/📖/🎵 いつ 私 だった 若い）\nYou should 📖/🏃/🧹 every day.\nあなたは毎日〜すべきです。（あなた べき 🏃/📖/🎵 すべての 日）\nYou must 📖/🏃/🧹 now.\nあなたは今〜しなければならない。（あなた しなければ 🏃/📖/🎵 今）\nI have to 📖/🏃/🧹.\n私は〜しなければならない。（私 持つ に 🏃/📖/🎵）\nDo you have to 📖/🏃/🧹?\nする あなた 持つ に 🏃/📖/🎵？（あなたは〜しなければなりませんか？）\nThere was a 🐱/🏠/🌳.\n〜があった。（そこに だった 一つの 🏃/📖/🎵）\nThere were many 🐱s/🏠s/🌳s.\n〜がたくさんあった。（そこに だった 多くの 🏃/📖/🎵）\nWas there a 🏃/📖/🎵?\nだった そこに 一つの 🏃/📖/🎵？（〜がありましたか？）\nI 🏃/📖/🎮 because 🌧️/😴/🤒.\n私は〜なぜなら〜だから。（私 🏃/📖/🎵 なぜなら 🏃/📖/🎵）\nI 🏃/📖/🎵 so I 🏃/📖/🎵.\n私は〜だから〜する。（私 🏃/📖/🎵 だから 私 🏃/📖/🎵）\nI 🏃/📖/🎮 but 🌧️/🚫/🤒.\n私は〜しかし〜。（私 🏃/📖/🎵 しかし 🏃/📖/🎵）\nWant/Need to\n〜したい/する必要がある\n\nI want to [___].\n私は〜したい。（私 欲しい に 🏃/📖/🎵）\nDo you want to [___]?\nする あなた 欲しい に 🏃/📖/🎵？（あなたは〜したいですか？）\nI need to 📖/🧹/🍳.\n私は〜する必要がある。（私 必要 に 🏃/📖/🎵）\nLike + verb-ing\n〜するのが好き\n\nI like 🏃/🏊/📖ing.\n私 好き する。（私は〜するのが好きです。）\nI like to 🏃/🏊/📖.\n私は〜するのが好きです。（私 好き に 🏃/📖/🎵）\nImperatives (negative)\n命令形（禁止・提案）\n\nDon't 🏃/📖/🎮!\nしない 🏃/📖/🎵！（〜するな！）\nLet's 🏃/📖/🎮!\nしよう 🏃/📖/🎵！（〜しましょう！）\n"
 }
];

var eiken3grammar = [
 {
 "title": "Grammar: Eiken 3",
 "content": "Have/Has auxiliary\n助動詞have/has\n\nI have 🗼/🍣/🎬ed.\n私は〜した。（私 助 動詞した）\nShe has 🗼/🍣/🎬ed.\n彼女は〜した。（彼女 助 動詞した）\nHave you 🗼/🍣/🎬ed?\n助 あなた 動詞した？（あなたは〜しましたか？）\nShe has 🗼/🍣/🎬ed.\n彼女は〜したことがある。（彼女 助 動詞した）\nHave you 🗼/🍣/🎬ed?\n助 あなた 動詞した？（あなたは〜したことがありますか？）\nI haven't 🗼/🍣/🎬ed.\n私は〜したことがない。（私 持たない 🏃/📖/🎵ed）\nHe has never 🗼/🍣/🎬ed.\n彼は決して〜したことがない。（彼 持つ 決して 🏃/📖/🎵ed）\nI have 📚/🏠/💼ed for ⏰/📅/🌙.\n私は〜の間〜している。（私 助 動詞した の間 🏃/📖/🎵）\nI have 📚/🏠/💼ed since 📅/🌅/🎄.\n私は〜以来〜している。（私 助 動詞した 以来 🏃/📖/🎵）\nI have just 🏃/📖/🎮ed.\n私はちょうど〜したところだ。（私 持つ ちょうど 🏃/📖/🎵ed）\nShe has already 🏃/📖/🎮ed.\n彼女はもう〜した。（彼女 持つ 既に 🏃/📖/🎵ed）\nHave you 🏃/📖/🎮ed yet?\n助 あなた 動詞した まだ？（あなたはもう〜しましたか？）\nI 🏃/📖/🎮ed in 2020.\n私は2020年に〜した。（私 🏃/📖/🎵ed に 2020年[2020]）\nI have 🏃/📖/🎮ed today.\n私は今日〜した。（私 助 動詞した 今日）\nFirst Conditional\n第一条件文\n\nIf I 📚/🏃/🧹, I will 😊/✅/🎉.\nもし〜なら、〜だろう。（もし 私 🏃/📖/🎵、私 だろう 🏃/📖/🎵）\nIf she 📚s/🏃s/🧹s, she will 😊/✅/🎉.\nもし彼女が〜なら、〜だろう。（もし 彼女 🏃/📖/🎵s、彼女 だろう 🏃/📖/🎵）\nIf you 🏃/📖/🎮, will you 😊/🎮/😴?\nもし あなた 🏃/📖/🎵、だろう あなた 🏃/📖/🎵？（もし〜なら、〜しますか？）\nI have some 🍎/📚/✏️.\n私はいくつかの〜を持っている。（私 持つ いくつかの 🏃/📖/🎵）\nDo you have any 🍎/📚/✏️?\nする あなた 持つ どんな 🏃/📖/🎵？（〜を持っていますか？）\nI don't have any 🍎/📚/✏️.\n私は〜を全く持っていない。（私 しない 持つ どんな 🏃/📖/🎵）\nThere is no 🍎/📚/✏️.\n〜はない。（そこに です ない 🏃/📖/🎵）\nToo/Enough\nあまりに/十分に\n\nIt is too 🐘/🏔️/⚡.\nそれはあまりに〜です。（それ です あまりに 🏃/📖/🎵）\nIt is 😊/📚/💪 enough.\nそれは十分に〜です。（それ です 🏃/📖/🎵 十分に）\nIt is too 🐘/🏔️/⚡ to 🏃/📖/🎨.\n〜すぎて〜できない。（それ です あまりに 🏃/📖/🎵 に 🏃/📖/🎵）\nI 🏃/📖/🎮 to 📖/🎨/🍳.\n私は〜するために〜する。（私 🏃/📖/🎵 に 🏃/📖/🎵）\nShe 🏃s/📖s/🎮s to 📖/🎨/🍳.\n彼女は〜するために〜する。（彼女 🏃/📖/🎵s に 🏃/📖/🎵）\nGerunds\n動名詞\n\n🏃/🏊/📖ing is fun.\n〜することは楽しい。（🏃/🏊/📖こと です 楽しい）\nI like 🏃/🏊/📖ing.\n私 好き する。（私は〜するのが好きです。）\nI am good at 🏃/🏊/📖ing.\n私 です 上手に する。（私は〜するのが上手です。）\nQuestion Tags\n付加疑問\n\nYou 🏃/📖/🎮, don't you?\nあなた 🏃/📖/🎵、しない あなた？（〜ですね？）\nShe 🏃s/📖s/🎮s, doesn't she?\n彼女 🏃/📖/🎵s、しない 彼女？（彼女は〜ですね？）\nYou can 🏃/🏊/🎨, can't you?\nあなた できる 🏃/📖/🎵、できない あなた？（〜できますよね？）\nThe person who 🏃s/📖s/🎨s.\n〜する人。（その 人 誰 🏃/📖/🎵s）\nThe thing that 📖s/📚s/✏️s.\n〜するもの。（その 物 それ 🏃/📖/🎵s）\nThe place where I 🏃/📖/🎵.\n私が〜する場所。（その 場所 どこ 私 🏃/📖/🎵）\nPrepositions of Movement\n移動の前置詞\n\nI go 🏃/🚶/🚴 the park.\n私は公園に〜行く。（私 行く 🏃/📖/🎵 その 公園）\nI walk 🏃/🚶/🚴 the school.\n私は学校を〜歩く。（私 歩く 🏃/📖/🎵 その 学校）\n"
 }
];

var eikenpre2grammar = [
 {
 "title": "Grammar: Pre-2",
 "content": "Modals (may/might/must)\n助動詞（かもしれない/なければならない）\nI may [___] tomorrow.\n私は明日〜かもしれない。\nShe might [___].\n彼女は〜かもしれない。\nI must [___] now.\n私は今〜しなければならない。\nYou should [___] more.\nあなたはもっと〜すべきです。\nCould you [___]?\nできた あなた [___]？（〜していただけますか？）\nWould you [___]?\nだろう あなた [___]？（〜していただけますか？）\nI was [___]ing.\n私は〜していた。\nShe was [___]ing.\n彼女は〜していた。\nThey were [___]ing.\n彼らは〜していた。\nWas he [___]ing?\nいた 彼 して？（彼は〜していましたか？）\nI was [___]ing when [___].\n〜していた時、〜した。\nPassive Voice\n受身形\nIt is [___]ed by [___].\nそれは〜によって〜される。\nIt was [___]ed by [___].\nそれは〜によって〜された。\nEnglish is [___]ed here.\n英語はここで〜される。\nUsed to\n昔〜したものだ\nI used to [___].\n私は昔〜したものだ。\nShe used to [___].\n彼女は昔〜したものだ。\nDid you use to [___]?\nした あなた 使う に [___]？（あなたは昔〜しましたか？）\nIf I [___]ed, I would [___].\nもし〜なら、〜だろう。\nIf she [___]ed, she would [___].\nもし彼女が〜なら、〜だろう。\nIf I were [___], I would [___].\nもし私なら〜だろう。\nGerund vs Infinitive\n動名詞vs不定詞\nI want to [___].\n私は〜したい。\nI enjoy [___]ing.\n私 楽しむ する。\nI stopped [___]ing.\n私 止めた する。\nI decided to [___].\n私は〜することに決めた。\nI finished [___]ing.\n私 終えた する。\nRelative Clauses\n関係代名詞\nThe man who [___]s.\n〜する男。\nThe book that [___]s.\n〜する本。\nThe dog which [___]s.\n〜する犬。\nComparisons\n比較\nas [___] as [___].\n〜と同じくらい〜。\nnot as [___] as [___].\n〜ほど〜ではない。\nSo/Such\nとても/そんな\nIt is so [___] that [___].\nとても〜なので〜。\nIt is such a [___] that [___].\nとても〜なので〜。\nQuantifiers\n数量詞\nI have much [___].\n私はたくさんの〜を持っている。\nI have many [___].\n私はたくさんの〜を持っている。\nI have a few [___].\n私は少しの〜を持っている。\nI have a little [___].\n私は少しの〜を持っている。\nWish\n願望\nI wish I [___]ed.\n〜だったらなあ。\nI wish I were [___].\n〜だったらなあ。\n"
 }
];

var eikenpre2plusgrammar = [
 {
 "title": "Grammar: Pre-2 Plus",
 "content": "Past Perfect\n過去完了形\nI had [___]ed before [___].\n〜の前に〜していた。\nShe had [___]ed by the time [___].\n〜した時にはもう〜していた。\nHad you [___]ed before [___]?\n持った あなた [___]ed 前に [___]？（〜前に〜しましたか？）\nIf I had [___]ed, I would have [___]ed.\nもし〜していたら、〜していただろう。\nIf she had [___]ed, she would have [___]ed.\nもし彼女が〜していたら、〜していただろう。\nI wish I had [___]ed.\n〜していればなあ。\nI wish I had been [___].\n〜だったらなあ。\nIt can be [___]ed.\nそれは〜できる。\nIt should be [___]ed.\nそれは〜されるべきだ。\nIt must be [___]ed.\nそれは〜されなければならない。\nIt might be [___]ed.\nそれは〜かもしれない。\nReported Speech\n間接話法\nHe said that he [___]ed.\n彼は〜したと言った。\nShe said that she would [___].\n彼女は〜するだろうと言った。\nHe told me that he [___]ed.\n彼は私に〜したと言った。\nCausative\n使役\nI had my hair [___]ed.\n髪を〜してもらった。\nI got someone to [___].\n誰かに〜してもらった。\nMixed Conditionals\n混合条件文\nIf I had [___]ed, I would [___] now.\nもし〜していたら、今〜だろうに。\nIf I were [___], I would have [___]ed.\nもし〜なら、〜していただろう。\nWalking, I [___].\n〜しながら、私は〜する。\nHaving [___]ed, I [___].\n〜した後、私は〜する。\nNarrative Tenses\n物語の時制\nI was [___]ing when I [___]ed.\n〜していた時、〜した。\nAfter I had [___]ed, I [___]ed.\n〜した後、〜した。\nEmphasis (cleft)\n強調構文\nIt was [___] who [___]ed.\n〜したのは〜だ。\nWhat I [___]ed was [___].\n私が〜したのは〜だ。\n"
 }
];

var eiken2grammar = [
 {
 "title": "Grammar: Eiken 2",
 "content": "Present Perfect Continuous\n現在完了進行形\nI have been [___]ing.\n私は〜し続けてきた。\nShe has been [___]ing for [___].\n彼女は〜の間〜し続けてきた。\nHow long have you been [___]ing?\nどのくらい 持つ あなた いた して？（どのくらい〜し続けていますか？）\nIt is being [___]ed now.\nそれは今〜されている。\nIt has been [___]ed.\nそれは〜された。\nIt will be [___]ed.\nそれは〜されるだろう。\nIt had been [___]ed before [___].\n〜の前に〜されていた。\nThird Conditional\n第三条件文\nIf they had [___]ed, they would have [___]ed.\nもし彼らが〜していたら、〜していただろう。\nReported Speech (questions)\n間接疑問文\nHe asked if I [___]ed.\n彼は〜かどうか聞いた。\nShe asked what I [___]ed.\n彼女は私が何を〜したか聞いた。\nHe told me to [___].\n彼は私に〜するように言った。\nRelative Clauses\n関係代名詞\nThe book that I [___]ed.\n私が〜した本。\nThe person whose [___].\n〜の〜を持つ人。\nGerunds & Infinitives\n動名詞・不定詞\nI look forward to [___]ing.\n私 見る ことに する。\nI am used to [___]ing.\n私 です 慣れている する。\nI would rather [___].\nむしろ〜したい。\nI had better [___].\n〜した方がいい。\nConjunctions\n接続詞\nDespite Walking, I [___].\nにもかかわらず in〜にもかかわらず、〜する。\nAlthough [___], I [___].\n〜だけれども、〜する。\nI [___] whereas [___].\n〜である一方、〜。\nQuantifiers\n数量詞\nAll of the [___].\n〜のすべて。\nMost of the [___].\n〜のほとんど。\nNeither of the [___].\n〜のどちらも〜ない。\nTag Questions\n付加疑問\nHe has [___]ed, hasn't he?\n彼 持つ [___]ed、持たない 彼？（彼は〜しましたよね？）\nShe will [___], won't she?\n彼女 だろう [___]、だろうない 彼女？（彼女は〜するでしょう？）\nNot only [___] but also [___].\n〜だけでなく〜も。\n"
 }
];

var eikenpre1grammar = [
 {
 "title": "Grammar: Pre-1",
 "content": "Inverted Conditionals\n倒置条件文\nHad I [___]ed, I would have [___]ed.\nもし〜していたら、〜していただろうに。\nShould you [___], please [___].\n万一〜するなら、〜してください。\nWere I [___], I would [___].\nもし私なら〜だろう。\nCleft Sentences\n強調構文\nIt is [___] that [___]s.\n〜するのは〜だ。\nWhat I need is [___].\n私が必要なのは〜だ。\nMixed Conditionals\n混合条件文\nIf I had [___]ed, I would be [___] now.\nもし〜していたら、今〜だろうに。\nI suggest that he [___].\n彼が〜することを提案する。\nIt is important that she [___].\n彼女が〜することは重要だ。\nPassive Reporting\n受身（伝達）\nIt is believed that [___].\n〜だと信じられている。\nIt is said that [___].\n〜だと言われている。\nIt has been shown that [___].\n〜であることが示されている。\nNominalization\n名詞化\nThe [___] of [___] is [___].\n〜の〜は〜だ。\nThe discovery of [___].\n〜の発見。\nDiscourse Markers\n談話マーカー\nFurthermore, [___].\nさらに、〜。\nNevertheless, [___].\nそれにもかかわらず、〜。\nAccordingly, [___].\nそれに応じて、〜。\nConsequently, [___].\nその結果、〜。\nHedging\n婉曲表現\nIt appears that [___].\n〜のように見える。\nThere seems to be [___].\n〜があるようだ。\nIt tends to [___].\n〜する傾向がある。\nInversion (emphasis)\n倒置（強調）\nNever have I [___]ed.\n私は決して〜したことがない。\nOnly when [___] did I [___].\n〜して初めて〜した。\nNot until [___] did I [___].\n〜して初めて〜した。\n"
 }
];

var eiken1grammar = [
 {
 "title": "Grammar: Eiken 1",
 "content": "Academic Passive\n学術的受身\nIt has been argued that [___].\n〜であると議論されている。\nIt has been demonstrated that [___].\n〜であることが実証されている。\nIt should be noted that [___].\n〜であることに注意すべきだ。\nIt is assumed that [___].\n〜と仮定されている。\nHedging & Stance\n婉曲・立場\nApparently, [___].\nどうやら、〜のようだ。\nSeemingly, [___].\nどうやら、〜のようだ。\nArguably, [___].\n議論の余地はあるが、〜。\nReportedly, [___].\n報道によると、〜。\nNominalization\n名詞化\nThe implementation of [___] resulted in [___].\n〜の実施は〜をもたらした。\nThe failure to [___] led to [___].\n〜しないことは〜につながった。\nAdvanced Inversion\n高度な倒置\nUnder no circumstances should [___].\nいかなる状況でも〜すべきではない。\nLittle did [___] know that [___].\n〜は〜だとは知らなかった。\nNot only did [___] but [___].\n〜だけでなく〜も〜した。\nSubjunctive (formal)\n仮定法（形式）\nIf I were to [___], I would [___].\nもし〜するとしたら、〜だろう。\nBe that as it may, [___].\nそうかもしれないが、〜。\nEllipsis\n省略\nI can [___] and so can [___].\n私は〜できるし、〜もできる。\nShe [___]s more than [___].\n彼女は〜より多く〜する。\nCollocations\n連語\npose a [___]\n〜をもたらす。\nmake a [___]\n〜を行う。\ndraw a [___]\n〜を引き出す。\n"
 }
];

