var eiken7grammar = [
 {
 "title": "Grammar: Eiken 7",
 "content": "<b>BE Verb (am/is/are)</b>\n<b>BE動詞</b>\n\nI am a 👦/👧/🎓.\n私 です 👦/👧/🎓。（私は〜です。）\nYou are 😊/😄/🤗.\nあなた です 😊/😄/🤗。（あなたは〜です。）\nHe is 👨/🏃/🧑‍⚕️.\n彼 です 👨/🏃/🧑‍⚕️。（彼は〜です。）\nShe is 👩/🏃/🧑‍⚕️.\n彼女 です 👩/🏃/🧑‍⚕️。（彼女は〜です。）\nWe are 👦👧🧒/👫/🎓.\n私たち です 👦👧🧒/👫/🎓。（私たちは〜です。）\nThey are 🐱s/🐶s/🐦s.\n彼ら です 🐱s/🐶s/🐦s。（彼らは〜です。）\nThis is a 📖/🖊️/🎒.\nこれ です 一つの 📖/🖊️/🎒。（これは〜です。）\nThat is a 🏠/🌳/🚗.\nあれ です 一つの 🏠/🌳/🚗。（あれは〜です。）\nAre you 😊/👶/🎓?\nです あなた 😊/👶/🎓？（あなたは〜ですか？）\nIs he 👨/🏃/🧑‍⚕️?\nです 彼 👨/🏃/🧑‍⚕️？（彼は〜ですか？）\nIs she 👩/🏃/👩‍🏫?\nです 彼女 👩/🏃/👩‍🏫？（彼女は〜ですか？）\nAre they 🐱s/🐶s/🐦s?\nです 彼ら 🐱s/🐶s/🐦s？（彼らは〜ですか？）\nI like 🐱/🎵/🍕.\n私 好き 🐱/🎵/🍕。（私は〜が好きです。）\nYou like ⚽/🎨/🍦.\nあなた 好き ⚽/🎨/🍦。（あなたは〜が好きです。）\nDo you like 🍕/🍦/🎮?\nする あなた 好き 🍕/🍦/🎮？（あなたは〜が好きですか？）\nDoes he like ⚽/🎮/📺?\nする 彼 好き ⚽/🎮/📺？（彼は〜が好きですか？）\nI don't like 🕷️/🐍/🐛.\n私 しない 好き 🕷️/🐍/🐛。（私は〜が好きではありません。）\n<b>Wh-Questions</b>\n<b>疑問詞</b>\n\nWhat is 🔴/🔵/🟢?\n何 です 🔴/🔵/🟢？（〜は何ですか？）\nWhere is 🏠/🏫/🌳?\nどこ です 🏠/🏫/🌳？（〜はどこですか？）\nIt is 😊/🏠/✈️.\nそれ です 😊/😢/🤒。（それは〜です。）\n"
 }
];

var eiken6grammar = [
 {
 "title": "Grammar: Eiken 6",
 "content": "<b>Present Continuous</b>\n<b>現在進行形</b>\n\nI am 🏃/🏊/📖ing.\n私 いる してして。（私は〜しています。）\nHe is 🏃/🏊/📖ing.\n彼 いる してして。（彼は〜しています。）\nShe is 🏃/🏊/📖ing.\n彼女 いる してして。（彼女は〜しています。）\nThey are 🏃/🏊/📖ing.\n彼ら いる してして。（彼らは〜しています。）\nAre you 🏃/🏊/📖ing?\nいる あなた してして？（あなたは〜していますか？）\nIs he 🏃/🏊/📖ing?\nいる 彼 してして？（彼は〜していますか？）\nI was 😊/😢/🤒.\n私 だった 😊/😢/🤒。（私は〜だった。）\nHe was 😊/😢/🤒.\n彼 だった 😊/😢/🤒。（彼は〜だった。）\nShe was 😊/😢/🤒.\n彼女 だった 😊/😢/🤒。（彼女は〜だった。）\nWe were 😊s/😢s/🤒s.\n私たち だった 🏃/📖/🎵。（私たちは〜だった。）\nThey were 😊s/😢s/🤒s.\n彼ら だった 🏃/📖/🎵。（彼らは〜だった。）\nWas he 😊/😢/🤒?\nだった 彼 🏃/📖/🎵？（彼は〜でしたか？）\nWere you 😊/😢/🤒?\nだった あなた 🏃/📖/🎵？（あなたは〜でしたか？）\nI 🏃/📖/🎵.\n私 動詞。（私は〜する。）\nYou 🏃/📖/🎵.\nあなた 動詞。（あなたは〜する。）\nHe 🏃s/📖s/🎵s.\n彼 動詞する。（彼は〜する。）\nShe 🏃s/📖s/🎵s.\n彼女 動詞する。（彼女は〜する。）\nDo you 🏃/📖/🎵?\nする あなた 🏃/📖/🎵？（あなたは〜しますか？）\nDoes he 🏃/📖/🎵?\nする 彼 🏃/📖/🎵？（彼は〜しますか？）\nDoes she 🏃/📖/🎵?\nする 彼女 🏃/📖/🎵？（彼女は〜しますか？）\nI can 🏃/🏊/🎨.\n私 できる 🏃/📖/🎵。（私は〜できます。）\nShe can 🏃/🏊/🎨.\n彼女 できる 🏃/📖/🎵。（彼女は〜できます。）\nCan you 🏃/🏊/🎨?\nできる あなた 🏃/📖/🎵？（あなたは〜できますか？）\nI have a 🐱/🏠/📱.\n私 持つ 一つの 🏃/📖/🎵。（私は〜を持っています。）\nShe has a 🐱/🏠/📱.\n彼女 持つ 一つの 🏃/📖/🎵。（彼女は〜を持っています。）\nThis is my 🐱/📖/🎨.\nこれ です 私の 🏃/📖/🎵。（これは私の〜です。）\nThat is his 🐱/📖/🎨.\nあれ です 彼の 🏃/📖/🎵。（あれは彼の〜です。）\n<b>There is/are</b>\n<b>〜がある</b>\n\nThere is a 🐱/🏠/🌳.\nそこ です 一つの 🏃/📖/🎵。（〜があります。）\nThere are 🐱s/🏠s/🌳s.\nそこ です 😊/😢/🤒。（〜があります。）\n<b>Imperatives</b>\n<b>命令形</b>\n\n📖/✏️/📝 your book.\n開く あなたの 本。（本を〜しなさい。）\nPlease 🤝/👋/🙋.\nどうぞ 助ける。（〜してください。）\n"
 }
];

var eiken5grammar = [
 {
 "title": "Grammar: Eiken 5",
 "content": "<b>Present Simple</b>\n<b>現在形</b>\n\nI 🏃/📖/🎵 every day.\n私 🏃/📖/🎵 すべての 日。（私は毎日〜する。）\nYou 📖/✏️/🎨 at school.\nあなた 🏃/📖/🎵 に 学校。（あなたは学校で〜する。）\nWe 🏃/⚽/🏊 on Monday.\n私たち 🏃/📖/🎵 に 月曜日。（私たちは月曜日に〜する。）\nThey 🏠/🏫/🏢 in Tokyo.\n彼ら 🏃/📖/🎵 に 東京。（彼らは東京で〜する。）\nHe 🏃s/📖s/🎵s every day.\n彼 🏃/📖/🎵s すべての 日。（彼は毎日〜する。）\nShe 📖s/✏️s/🎨s at school.\n彼女 🏃/📖/🎵s に 学校。（彼女は学校で〜する。）\n<b>Present Continuous</b>\n<b>現在進行形</b>\n\nI am 🏃/🏊/📖ing now.\n私 いる してして 今。（私は今〜している。）\nShe is 🏃/🏊/📖ing now.\n彼女 いる してして 今。（彼女は今〜している。）\nThey are 🏃/🏊/📖ing now.\n彼ら いる してして 今。（彼らは今〜している。）\n<b>Do/Does Questions</b>\n<b>Do/Doesの疑問文</b>\n\nDo you 🏃/📖/🎵 every day?\nする あなた 🏃/📖/🎵 すべての 日？（あなたは毎日〜しますか？）\nDoes he 🏃/📖/🎵 every day?\nする 彼 🏃/📖/🎵 すべての 日？（彼は毎日〜しますか？）\nDoes she 📖/✏️/🎨 at school?\nする 彼女 🏃/📖/🎵 に 学校？（彼女は学校で〜しますか？）\nI don't 🏃/📖/🎵 every day.\n私 しない 🏃/📖/🎵 すべての 日。（私は毎日〜しない。）\nHe doesn't 📖/✏️/🎨 at school.\n彼 しない 🏃/📖/🎵 に 学校。（彼は学校で〜しない。）\n<b>Wh-Questions</b>\n<b>疑問詞</b>\n\nWhat do you 📖/🎵/🎨?\n何 する あなた 🏃/📖/🎵？（あなたは〜何をしますか？）\nWhere do you 🏃/📖/🎮?\nどこ する あなた 🏃/📖/🎵？（あなたはどこで〜しますか？）\nWhen do you 🏃/📖/🎮?\nいつ する あなた 🏃/📖/🎵？（あなたはいつ〜しますか？）\nWhy do you 📖/🏃/🎮?\nなぜ する あなた 🏃/📖/🎵？（あなたはなぜ〜しますか？）\nHow do you 📖/🏃/🎮?\nどう する あなた 🏃/📖/🎵？（あなたはどう〜しますか？）\nWho 🏃s/📖s/🎨s?\n誰 🏃/📖/🎵s？（誰が〜しますか？）\nWhat is your 🏃/📖/🎵?\n何 です あなたの 🏃/📖/🎵？（あなたの〜は何ですか？）\nWhere is your 🏃/📖/🎵?\nどこ です あなたの 🏃/📖/🎵？（あなたの〜はどこですか？）\nI can 🏃/🏊/🎨 well.\n私 できる 🏃/📖/🎵 上手に。（私は上手に〜できます。）\nCan you 🏃/🏊/🎨?\nできる あなた 🏃/📖/🎵？（あなたは〜できますか？）\nYou should 📖/🏃/🧹.\nあなた べき 🏃/📖/🎵。（あなたは〜すべきです。）\n<b>Prepositions</b>\n<b>前置詞</b>\n\nI 🏃/📖/🍳 in the morning.\n私 🏃/📖/🎵 に その 朝。（私は朝〜する。）\nI 🏃/📖/🎮 at 3 o'clock.\n私 🏃/📖/🎵 に 3時[3 o'clock]。（私は3時に〜する。）\nI 🏃/📖/🎮 on Sunday.\n私 🏃/📖/🎵 に 日曜日。（私は日曜日に〜する。）\nIt is 🏃/📖/🎵 the box.\nそれ です 🏃/📖/🎵 その 箱。（それは箱の中に〜。）\n<b>Articles</b>\n<b>冠詞</b>\n\nI have a 🐱/🏠/📱.\n私 持つ 一つの 🏃/📖/🎵。（私は〜を一つ持っている。）\nI like the 🌸/🌅/🎵.\n私 好き その 🏃/📖/🎵。（私はその〜が好きです。）\nShe is an 👩‍🏫/👩‍⚕️/👩‍🎨.\n彼女 です 一つの 🏃/📖/🎵。（彼女は〜です。）\nI like 🏃/📖/🎨 him.\n私 好き 🏃/📖/🎵 彼。（私は彼を〜好きです。）\nShe helps 🏃/📖/🎨 me.\n彼女 助ける 🏃/📖/🎵 私。（彼女は私を〜助ける。）\nI see 🏃/📖/🎨 them.\n私 見る 🏃/📖/🎵 彼ら。（私は彼らを〜見る。）\n<b>Comparatives</b>\n<b>比較級</b>\n\nThis is 🐘/🦒/🏔️er than that.\nこれ です 🏃/📖/🎵er より あれ。（これはあれより〜です。）\nShe is more 😊/🎨/📚 than me.\n彼女 です もっと 🏃/📖/🎵 より 私。（彼女は私より〜です。）\nI am 🐘/🦒/🏔️er than you.\n私 です 🏃/📖/🎵er より あなた。（私はあなたより〜です。）\n<b>Possessives ('s)</b>\n<b>所有格</b>\n\nThis is 👨/👩/🧑's book.\nこれ です 🏃/📖/🎵の 本。（これは〜の本です。）\nThat is my 👨/👩/🧑's car.\nあれ です 私の 🏃/📖/🎵の 車。（あれは私の〜の車です。）\n<b>Frequency Adverbs</b>\n<b>頻度副詞</b>\n\nI 🏃/📖/🎵 always.\n私 🏃/📖/🎵 いつも。（私はいつも〜する。）\nI 🏃/📖/🎵 sometimes.\n私 🏃/📖/🎵 時々。（私は時々〜する。）\nI 🏃/📖/🎵 never.\n私 🏃/📖/🎵 決して。（私は決して〜しない。）\n"
 }
];

var eiken4grammar = [
 {
 "title": "Grammar: Eiken 4",
 "content": "<b>Past Simple</b>\n<b>過去形</b>\n\nI 🏃/📖/🎮ed yesterday.\n私 🏃/📖/🎵ed 昨日。（私は昨日〜した。）\nShe 🏃/📖/🎮ed last week.\n彼女 🏃/📖/🎵ed 先週。（彼女は先週〜した。）\nThey 🏃/📖/🎮ed at school.\n彼ら 🏃/📖/🎵ed に 学校。（彼らは学校で〜した。）\nI 🏃/📖/🎮ed in the morning.\n私 🏃/📖/🎵ed に その 朝。（私は朝〜した。）\n<b>Past Simple (irregular)</b>\n<b>過去形（不規則変化）</b>\n\nI [went/saw/ate].\n私 [行った/見た/食べた]。（私は〜した。）\nShe [went/saw/ate].\n彼女 [行った/見た/食べた]。（彼女は〜した。）\nHe [made/took/had].\n彼 [作った/取った/持った]。（彼は〜した。）\nShe didn't 🏃/📖/🎮.\n彼女 しない 食べる。（彼女は〜しなかった。）\nDid you 🏃/📖/🎮 yesterday?\nした あなた 🏃/📖/🎵 昨日？（あなたは昨日〜しましたか？）\nDid she 🏃/📖/🎮 last week?\nした 彼女 🏃/📖/🎵 先週？（彼女は先週〜しましたか？）\nI will 🏃/📖/🎮 tomorrow.\n私 だろう 🏃/📖/🎵 明日。（私は明日〜するだろう。）\nShe will 🏃/📖/🎮 next week.\n彼女 だろう 🏃/📖/🎵 来週。（彼女は来週〜するだろう。）\nWill you 🏃/📖/🎮 tomorrow?\nだろう あなた 🏃/📖/🎵 明日？（あなたは明日〜しますか？）\nI won't 🏃/📖/🎵.\n私 だろうしない 🏃/📖/🎵。（私は〜しないだろう。）\n<b>Going to</b>\n<b>〜するつもり</b>\n\nI am going to 🏃/📖/🎮.\n私 です 行く に 🏃/📖/🎵。（私は〜するつもりです。）\nShe is going to 🏃/📖/🎮.\n彼女 です 行く に 🏃/📖/🎵。（彼女は〜するつもりです。）\nAre you going to 🏃/📖/🎮?\nですか あなた 行く に 🏃/📖/🎵？（あなたは〜するつもりですか？）\nThis is 🐘/🦒/🏔️er than that.\nこれ は 🏃/📖/🎵er より あれ。（これはあれより〜です。）\nmore 🏃/📖/🎵 than 🏃/📖/🎵.\nもっと 🏃/📖/🎵 より 🏃/📖/🎵。（〜より〜です。）\nthe 🐘/🦒/🏔️est.\nその 🏃/📖/🎵est。（一番〜です。）\nthe most 😊/🎨/📚.\nその 最も 🏃/📖/🎵。（一番〜です。）\n<b>Could/Should/Must</b>\n<b>できた/べき/なければならない</b>\n\nI could 🏃/🏊/🎨 when I was young.\n私 できた 🏃/📖/🎵 いつ 私 だった 若い。（若い時〜できた。）\nYou should 📖/🏃/🧹 every day.\nあなた べき 🏃/📖/🎵 すべての 日。（あなたは毎日〜すべきです。）\nYou must 📖/🏃/🧹 now.\nあなた しなければ 🏃/📖/🎵 今。（あなたは今〜しなければならない。）\nI have to 📖/🏃/🧹.\n私 持つ に 🏃/📖/🎵。（私は〜しなければならない。）\nDo you have to 📖/🏃/🧹?\nする あなた 持つ に 🏃/📖/🎵？（あなたは〜しなければなりませんか？）\nThere was a 🐱/🏠/🌳.\nそこに だった 一つの 🏃/📖/🎵。（〜があった。）\nThere were many 🐱s/🏠s/🌳s.\nそこに だった 多くの 🏃/📖/🎵。（〜がたくさんあった。）\nWas there a 🏃/📖/🎵?\nだった そこに 一つの 🏃/📖/🎵？（〜がありましたか？）\nI 🏃/📖/🎮 because 🌧️/⏰/🤒.\n私 🏃/📖/🎵 なぜなら 🏃/📖/🎵。（私は〜なぜなら〜だから。）\nI 🏃/📖/🎵 so I 🏃/📖/🎵.\n私 🏃/📖/🎵 だから 私 🏃/📖/🎵。（私は〜だから〜する。）\nI 📖/🏃/🎮 but 🌧️/⏰/🤒.\n私 🏃/📖/🎵 しかし 🏃/📖/🎵。（私は〜しかし〜。）\n<b>Want/Need to</b>\n<b>〜したい/する必要がある</b>\n\nI want to 🏃/📖/🎨.\n私 欲しい に 🏃/📖/🎵。（私は〜したい。）\nDo you want to 🏃/📖/🎨?\nする あなた 欲しい に 🏃/📖/🎵？（あなたは〜したいですか？）\nI need to 📖/🧹/🍳.\n私 必要 に 🏃/📖/🎵。（私は〜する必要がある。）\n<b>Like + verb-ing</b>\n<b>〜するのが好き</b>\n\nI like 🏃/🏊/📖ing.\n私 好き ing。（私は〜するのが好きです。）\nI like to 🏃/🏊/📖.\n私 好き に 🏃/📖/🎵。（私は〜するのが好きです。）\n<b>Imperatives (negative)</b>\n<b>命令形（禁止・提案）</b>\n\nDon't 🏃/📖/🎮!\nしない 🏃/📖/🎵！（〜するな！）\nLet's 🏃/📖/🎮!\nしよう 🏃/📖/🎵！（〜しましょう！）\n"
 }
];

var eiken3grammar = [
 {
 "title": "Grammar: Eiken 3",
 "content": "<b>Have/Has auxiliary</b>\n<b>助動詞have/has</b>\n\nI have 🏃/📖/🎮ed.\n私 持つ 🏃/📖/🎵ed。（私は〜した。）\nShe has 🏃/📖/🎮ed.\n彼女 持つ 🏃/📖/🎵ed。（彼女は〜した。）\nHave you 🏃/📖/🎮ed?\n持つ あなた 🏃/📖/🎵ed？（あなたは〜しましたか？）\nShe has 🏃/📖/🎮ed.\n彼女 持つ 🏃/📖/🎵ed。（彼女は〜したことがある。）\nHave you 🏃/📖/🎮ed?\n持つ あなた 🏃/📖/🎵ed？（あなたは〜したことがありますか？）\nI haven't 🏃/📖/🎮ed.\n私 持たない 🏃/📖/🎵ed。（私は〜したことがない。）\nHe has never 🏃/📖/🎮ed.\n彼 持つ 決して 🏃/📖/🎵ed。（彼は決して〜したことがない。）\nI have 🏃/📖/🎮ed for ⏰/📅/🌙.\n私 持つ 🏃/📖/🎵ed の間 🏃/📖/🎵。（私は〜の間〜している。）\nI have 🏃/📖/🎮ed since 📅/🌅/🎄.\n私 持つ 🏃/📖/🎵ed 以来 🏃/📖/🎵。（私は〜以来〜している。）\nI have just 🏃/📖/🎮ed.\n私 持つ ちょうど 🏃/📖/🎵ed。（私はちょうど〜したところだ。）\nShe has already 🏃/📖/🎮ed.\n彼女 持つ 既に 🏃/📖/🎵ed。（彼女はもう〜した。）\nHave you 🏃/📖/🎮ed yet?\n持つ あなた 🏃/📖/🎵ed まだ？（あなたはもう〜しましたか？）\nI 🏃/📖/🎮ed in 2020.\n私 🏃/📖/🎵ed に 2020年[2020]。（私は2020年に〜した。）\nI have 🏃/📖/🎮ed today.\n私 持つ 🏃/📖/🎵ed 今日。（私は今日〜した。）\n<b>First Conditional</b>\n<b>第一条件文</b>\n\nIf I 🏃/📖/🎮, I will 😊/🎮/😴.\nもし 私 🏃/📖/🎵、私 だろう 🏃/📖/🎵。（もし〜なら、〜だろう。）\nIf she 🏃s/📖s/🎮s, she will 😊/🎮/😴.\nもし 彼女 🏃/📖/🎵s、彼女 だろう 🏃/📖/🎵。（もし彼女が〜なら、〜だろう。）\nIf you 🏃/📖/🎮, will you 😊/🎮/😴?\nもし あなた 🏃/📖/🎵、だろう あなた 🏃/📖/🎵？（もし〜なら、〜しますか？）\nI have some 🍎/📚/✏️.\n私 持つ いくつかの 🏃/📖/🎵。（私はいくつかの〜を持っている。）\nDo you have any 🍎/📚/✏️?\nする あなた 持つ どんな 🏃/📖/🎵？（〜を持っていますか？）\nI don't have any 🍎/📚/✏️.\n私 しない 持つ どんな 🏃/📖/🎵。（私は〜を全く持っていない。）\nThere is no 🍎/📚/✏️.\nそこに です ない 🏃/📖/🎵。（〜はない。）\n<b>Too/Enough</b>\n<b>あまりに/十分に</b>\n\nIt is too 🐘/🏔️/🌊.\nそれ です あまりに 🏃/📖/🎵。（それはあまりに〜です。）\nIt is 😊/📚/💪 enough.\nそれ です 🏃/📖/🎵 十分に。（それは十分に〜です。）\nIt is too 🐘/🏔️/🌊 to 🏃/📖/🎨.\nそれ です あまりに 🏃/📖/🎵 に 🏃/📖/🎵。（〜すぎて〜できない。）\nI 🏃/📖/🎮 to 📖/🎨/🍳.\n私 🏃/📖/🎵 に 🏃/📖/🎵。（私は〜するために〜する。）\nShe 🏃s/📖s/🎮s to 📖/🎨/🍳.\n彼女 🏃/📖/🎵s に 🏃/📖/🎵。（彼女は〜するために〜する。）\n<b>Gerunds</b>\n<b>動名詞</b>\n\n🏃/🏊/📖ing is fun.\n🏃/🏊/📖こと です 楽しい。（〜することは楽しい。）\nI like 🏃/🏊/📖ing.\n私 好き ing。（私は〜するのが好きです。）\nI am good at 🏃/🏊/📖ing.\n私 です 上手 に ing。（私は〜するのが上手です。）\n<b>Question Tags</b>\n<b>付加疑問</b>\n\nYou 🏃/📖/🎮, don't you?\nあなた 🏃/📖/🎵、しない あなた？（〜ですね？）\nShe 🏃s/📖s/🎮s, doesn't she?\n彼女 🏃/📖/🎵s、しない 彼女？（彼女は〜ですね？）\nYou can 🏃/🏊/🎨, can't you?\nあなた できる 🏃/📖/🎵、できない あなた？（〜できますよね？）\nThe person who 🏃s/📖s/🎨s.\nその 人 誰 🏃/📖/🎵s。（〜する人。）\nThe thing that 🏃s/📖s/🎨s.\nその 物 それ 🏃/📖/🎵s。（〜するもの。）\nThe place where I 🏃/📖/🎵.\nその 場所 どこ 私 🏃/📖/🎵。（私が〜する場所。）\n<b>Prepositions of Movement</b>\n<b>移動の前置詞</b>\n\nI go 🏃/🚶/🚴 the park.\n私 行く 🏃/📖/🎵 その 公園。（私は公園に〜行く。）\nI walk 🏃/🚶/🚴 the school.\n私 歩く 🏃/📖/🎵 その 学校。（私は学校を〜歩く。）\n"
 }
];

var eikenpre2grammar = [
 {
 "title": "Grammar: Pre-2",
 "content": "<b>Modals (may/might/must)</b>\n<b>助動詞（かもしれない/なければならない）</b>\nI may 🏃/📖/🎮 tomorrow.\n私 かもしれない 🏃/📖/🎵 明日。（私は明日〜かもしれない。）\nShe might 🏃/📖/🎮.\n彼女 かもしれない 🏃/📖/🎵。（彼女は〜かもしれない。）\nI must 📖/🏃/🧹 now.\n私 しなければ 🏃/📖/🎵 今。（私は今〜しなければならない。）\nYou should 📖/🏃/🧹 more.\nあなた べき 🏃/📖/🎵 もっと。（あなたはもっと〜すべきです。）\nCould you 🤝/📖/🧹?\nできた あなた 🏃/📖/🎵？（〜していただけますか？）\nWould you 🤝/📖/🧹?\nだろう あなた 🏃/📖/🎵？（〜していただけますか？）\nI was 🏃/🏊/📖ing.\n私 いた して。（私は〜していた。）\nShe was 🏃/🏊/📖ing.\n彼女 いた して。（彼女は〜していた。）\nThey were 🏃/🏊/📖ing.\n彼ら いた して。（彼らは〜していた。）\nWas he 🏃/🏊/📖ing?\nいた 彼 して？（彼は〜していましたか？）\nI was 🏃/🏊/📖ing when ⏰/🌧️/🔔.\n私 いた して いつ 🏃/📖/🎵。（〜していた時、〜した。）\n<b>Passive Voice</b>\n<b>受身形</b>\nIt is 📖/🎨/🔧ed by 👨/👩/🤖.\nそれ です 🏃/📖/🎵ed によって 🏃/📖/🎵。（それは〜によって〜される。）\nIt was 📖/🎨/🔧ed by 👨/👩/🤖.\nそれ だった 🏃/📖/🎵ed によって 🏃/📖/🎵。（それは〜によって〜された。）\nEnglish is 📖/🎨/🔧ed here.\n英語 です 🏃/📖/🎵ed ここ。（英語はここで〜される。）\n<b>Used to</b>\n<b>昔〜したものだ</b>\nI used to 🏃/📖/🎮.\n私 使った に 🏃/📖/🎵。（私は昔〜したものだ。）\nShe used to 🏃/📖/🎮.\n彼女 使った に 🏃/📖/🎵。（彼女は昔〜したものだ。）\nDid you use to 🏃/📖/🎮?\nした あなた 使う に 🏃/📖/🎵？（あなたは昔〜しましたか？）\nIf I 🏃/📖/🎮ed, I would 😊/🏠/✈️.\nもし 私 🏃/📖/🎵ed、私 だろう 🏃/📖/🎵。（もし〜なら、〜だろう。）\nIf she 🏃/📖/🎮ed, she would 😊/🏠/✈️.\nもし 彼女 🏃/📖/🎵ed、彼女 だろう 🏃/📖/🎵。（もし彼女が〜なら、〜だろう。）\nIf I were 👨/🐦/🌊, I would 🏃/📖/🎮.\nもし 私 だった 🏃/📖/🎵、私 だろう 🏃/📖/🎵。（もし私なら〜だろう。）\n<b>Gerund vs Infinitive</b>\n<b>動名詞vs不定詞</b>\nI want to 🏃/📖/🎨.\n私 欲しい に 🏃/📖/🎵。（私は〜したい。）\nI enjoy 🏃/🏊/📖ing.\n私 楽しむ ing。（私は〜するのを楽しむ。）\nI stopped 🏃/🏊/📖ing.\n私 止めた ing。（私は〜するのをやめた。）\nI decided to 🏃/📖/🎨.\n私 決めた に 🏃/📖/🎵。（私は〜することに決めた。）\nI finished 🏃/🏊/📖ing.\n私 終えた ing。（私は〜し終えた。）\n<b>Relative Clauses</b>\n<b>関係代名詞</b>\nThe man who 🏃s/📖s/🎨s.\nその 男 誰 🏃/📖/🎵s。（〜する男。）\nThe book that 📖s/📚s/✏️s.\nその 本 それ 🏃/📖/🎵s。（〜する本。）\nThe dog which 🏃s/📖s/🎨s.\nその 犬 それ 🏃/📖/🎵s。（〜する犬。）\n<b>Comparisons</b>\n<b>比較</b>\nas 🐘/🏔️/🌊 as 🐘/🏔️/🌊.\n同じ 🏃/📖/🎵 同じ 🏃/📖/🎵。（〜と同じくらい〜。）\nnot as 🐘/🏔️/🌊 as 🐘/🏔️/🌊.\nない 同じ 🏃/📖/🎵 同じ 🏃/📖/🎵。（〜ほど〜ではない。）\n<b>So/Such</b>\n<b>とても/そんな</b>\nIt is so 🐘/🏔️/🌊 that 🏃/📖/🎮.\nそれ です とても 🏃/📖/🎵 それ 🏃/📖/🎵。（とても〜なので〜。）\nIt is such a 🐘/🏔️/🌊 that 🏃/📖/🎮.\nそれ です そんな 一つの 🏃/📖/🎵 それ 🏃/📖/🎵。（とても〜なので〜。）\n<b>Quantifiers</b>\n<b>数量詞</b>\nI have much 📚/🍎/✏️.\n私 持つ 多くの 🏃/📖/🎵。（私はたくさんの〜を持っている。）\nI have many 📚s/🍎s/✏️s.\n私 持つ 多くの 🏃/📖/🎵。（私はたくさんの〜を持っている。）\nI have a few 📚s/🍎s/✏️s.\n私 持つ 少しの 🏃/📖/🎵。（私は少しの〜を持っている。）\nI have a little 📚/🍎/✏️.\n私 持つ 少しの 🏃/📖/🎵。（私は少しの〜を持っている。）\n<b>Wish</b>\n<b>願望</b>\nI wish I 🏃/📖/🎮ed.\n私 願う 私 🏃/📖/🎵ed。（〜だったらなあ。）\nI wish I were 👨/🐦/🌊.\n私 願う 私 だった 🏃/📖/🎵。（〜だったらなあ。）\n"
 }
];

var eikenpre2plusgrammar = [
 {
 "title": "Grammar: Pre-2 Plus",
 "content": "<b>Past Perfect</b>\n<b>過去完了形</b>\nI had 🏃/📖/🎮ed before ⏰/🔔/📅.\n私 持った 🏃/📖/🎵ed 前に 🏃/📖/🎵。（〜の前に〜していた。）\nShe had 🏃/📖/🎮ed by the time ⏰/🔔/📅.\n彼女 持った 🏃/📖/🎵ed までに 🏃/📖/🎵。（〜した時にはもう〜していた。）\nHad you 🏃/📖/🎮ed before ⏰/🔔/📅?\n持った あなた 🏃/📖/🎵ed 前に 🏃/📖/🎵？（〜前に〜しましたか？）\nIf I had 🏃/📖/🎮ed, I would have 😊/🏠/✈️ed.\nもし 私 持った 🏃/📖/🎵ed、私 だろう 持った 🏃/📖/🎵ed。（もし〜していたら、〜していただろう。）\nIf she had 🏃/📖/🎮ed, she would have 😊/🏠/✈️ed.\nもし 彼女 持った 🏃/📖/🎵ed、彼女 だろう 持った 🏃/📖/🎵ed。（もし彼女が〜していたら、〜していただろう。）\nI wish I had 🏃/📖/🎮ed.\n私 願う 私 持った 🏃/📖/🎵ed。（〜していればなあ。）\nI wish I had been 👨/🐦/🌊.\n私 願う 私 持った だった 🏃/📖/🎵。（〜だったらなあ。）\nIt can be 📖/🎨/🔧ed.\nそれ できる である 🏃/📖/🎵ed。（それは〜できる。）\nIt should be 📖/🎨/🔧ed.\nそれ べき である 🏃/📖/🎵ed。（それは〜されるべきだ。）\nIt must be 📖/🎨/🔧ed.\nそれ しなければ である 🏃/📖/🎵ed。（それは〜されなければならない。）\nIt might be 📖/🎨/🔧ed.\nそれ かもしれない である 🏃/📖/🎵ed。（それは〜かもしれない。）\n<b>Reported Speech</b>\n<b>間接話法</b>\nHe said that he 🏃/📖/🎮ed.\n彼 言った それ 彼 🏃/📖/🎵ed。（彼は〜したと言った。）\nShe said that she would 🏃/📖/🎮.\n彼女 言った それ 彼女 だろう 🏃/📖/🎵。（彼女は〜するだろうと言った。）\nHe told me that he 🏃/📖/🎮ed.\n彼 告げた 私 それ 彼 🏃/📖/🎵ed。（彼は私に〜したと言った。）\n<b>Causative</b>\n<b>使役</b>\nI had my hair ✂️/🎨/💇ed.\n私 持った 私の 髪 🏃/📖/🎵ed。（髪を〜してもらった。）\nI got someone to 🏃/📖/🔧.\n私 得た 誰か に 🏃/📖/🎵。（誰かに〜してもらった。）\n<b>Mixed Conditionals</b>\n<b>混合条件文</b>\nIf I had 🏃/📖/🎮ed, I would 😊/🏠/✈️ now.\nもし 私 持った 🏃/📖/🎵ed、私 だろう 🏃/📖/🎵 今。（もし〜していたら、今〜だろうに。）\nIf I were 👨/🐦/🌊, I would have 🏃/📖/🎮ed.\nもし 私 だった 🏃/📖/🎵、私 だろう 持った 🏃/📖/🎵ed。（もし〜なら、〜していただろう。）\nWalking, I 🏃/📖/🎵.\n歩きながら、私 😊/🏠/✈️。（〜しながら、私は〜する。）\nHaving 🏃/📖/🎵ed, I 🏃/📖/🎵.\n持っている 🏃/📖/🎵ed、私 🏃/📖/🎵。（〜した後、私は〜する。）\n<b>Narrative Tenses</b>\n<b>物語の時制</b>\nI was 🏃/🏊/📖ing when I 🔔/👀/⏰ed.\n私 いた して いつ 私 🏃/📖/🎵ed。（〜していた時、〜した。）\nAfter I had 🏃/📖/🎮ed, I 😊/🏠/✈️ed.\n後 私 持った 🏃/📖/🎵ed、私 🏃/📖/🎵ed。（〜した後、〜した。）\n<b>Emphasis (cleft)</b>\n<b>強調構文</b>\nIt was 👨/👩/🧑 who 🏃/📖/🎮ed.\nそれ だった 🏃/📖/🎵 誰 🏃/📖/🎵ed。（〜したのは〜だ。）\nWhat I 🏃/📖/🎮ed was 😊/🏠/✈️.\n何 私 🏃/📖/🎵ed だった 🏃/📖/🎵。（私が〜したのは〜だ。）\n"
 }
];

var eiken2grammar = [
 {
 "title": "Grammar: Eiken 2",
 "content": "<b>Present Perfect Continuous</b>\n<b>現在完了進行形</b>\nI have been 🏃/🏊/📖ing.\n私 持つ いた して。（私は〜し続けてきた。）\nShe has been 🏃/🏊/📖ing for ⏰/📅/🌙.\n彼女 持つ いた して の間 🏃/📖/🎵。（彼女は〜の間〜し続けてきた。）\nHow long have you been 🏃/🏊/📖ing?\nどのくらい 持つ あなた いた して？（どのくらい〜し続けていますか？）\nIt is being 📖/🎨/🔧ed now.\nそれ です である 🏃/📖/🎵ed 今。（それは今〜されている。）\nIt has been 📖/🎨/🔧ed.\nそれ 持つ だった 🏃/📖/🎵ed。（それは〜された。）\nIt will be 📖/🎨/🔧ed.\nそれ だろう である 🏃/📖/🎵ed。（それは〜されるだろう。）\nIt had been 📖/🎨/🔧ed before ⏰/🔔/📅.\nそれ 持った だった 🏃/📖/🎵ed 前に 🏃/📖/🎵。（〜の前に〜されていた。）\n<b>Third Conditional</b>\n<b>第三条件文</b>\nIf they had 🏃/📖/🎮ed, they would have 😊/🏠/✈️ed.\nもし 彼ら 持った 🏃/📖/🎵ed、彼ら だろう 持った 🏃/📖/🎵ed。（もし彼らが〜していたら、〜していただろう。）\n<b>Reported Speech (questions)</b>\n<b>間接疑問文</b>\nHe asked if I 🏃/📖/🎮ed.\n彼 聞いた もし 私 🏃/📖/🎵ed。（彼は〜かどうか聞いた。）\nShe asked what I 🏃/📖/🎮ed.\n彼女 聞いた 何 私 🏃/📖/🎵ed。（彼女は私が何を〜したか聞いた。）\nHe told me to 🏃/📖/🎮.\n彼 告げた 私 に 🏃/📖/🎵。（彼は私に〜するように言った。）\n<b>Relative Clauses</b>\n<b>関係代名詞</b>\nThe book that I 🏃/📖/🎮ed.\nその 本 それ 私 🏃/📖/🎵ed。（私が〜した本。）\nThe person whose 🐱/🏠/📱.\nその 人 その 🏃/📖/🎵。（〜の〜を持つ人。）\n<b>Gerunds & Infinitives</b>\n<b>動名詞・不定詞</b>\nI look forward to 🏃/📖/🎮ing.\n私 見る 前に に ing。（〜するのを楽しみにしている。）\nI am used to 🏃/📖/🎮ing.\n私 です 使った に ing。（〜することに慣れている。）\nI would rather 🏃/📖/🎮.\n私 だろう むしろ 🏃/📖/🎵。（むしろ〜したい。）\nI had better 🏃/📖/🎮.\n私 持った より 🏃/📖/🎵。（〜した方がいい。）\n<b>Conjunctions</b>\n<b>接続詞</b>\nDespite Walking, I 🏃/📖/🎵.\nにもかかわらず ing、私 🏃/📖/🎵。（〜にもかかわらず、〜する。）\nAlthough 🏃/📖/🎵, I 🏃/📖/🎵.\nalthough[Although] 🏃/📖/🎵、私 🏃/📖/🎵。（〜だけれども、〜する。）\nI 🏃/📖/🎮 whereas 🛋️/😴/🎮.\n私 🏃/📖/🎵 一方 🏃/📖/🎵。（〜である一方、〜。）\n<b>Quantifiers</b>\n<b>数量詞</b>\nAll of the 📚s/🍎s/✏️s.\nすべて の その 🏃/📖/🎵。（〜のすべて。）\nMost of the 📚s/🍎s/✏️s.\nほとんど の その 🏃/📖/🎵。（〜のほとんど。）\nNeither of the 📚s/🍎s/✏️s.\nどちらも の その 🏃/📖/🎵。（〜のどちらも〜ない。）\n<b>Tag Questions</b>\n<b>付加疑問</b>\nHe has 🏃/📖/🎮ed, hasn't he?\n彼 持つ 🏃/📖/🎵ed、持たない 彼？（彼は〜しましたよね？）\nShe will 🏃/📖/🎮, won't she?\n彼女 だろう 🏃/📖/🎵、だろうない 彼女？（彼女は〜するでしょう？）\nNot only 🏃/📖/🎮 but also 😊/🏠/✈️.\nない のみ 🏃/📖/🎵 しかし また 🏃/📖/🎵。（〜だけでなく〜も。）\n"
 }
];

var eikenpre1grammar = [
 {
 "title": "Grammar: Pre-1",
 "content": "<b>Inverted Conditionals</b>\n<b>倒置条件文</b>\nHad I 🏃/📖/🎮ed, I would have 😊/🏠/✈️ed.\n持った 私 🏃/📖/🎵ed、私 だろう 持った 🏃/📖/🎵ed。（もし〜していたら、〜していただろうに。）\nShould you 🏃/📖/🎮, please 📞/📧/🙋.\nべき あなた 🏃/📖/🎵、どうぞ 🏃/📖/🎵。（万一〜するなら、〜してください。）\nWere I 👨/🐦/🌊, I would 🏃/📖/🎮.\nだった 私 🏃/📖/🎵、私 だろう 🏃/📖/🎵。（もし私なら〜だろう。）\n<b>Cleft Sentences</b>\n<b>強調構文</b>\nIt is 👨/👩/🧑 that 🏃s/📖s/🎨s.\nそれ です 🏃/📖/🎵 それ 🏃/📖/🎵s。（〜するのは〜だ。）\nWhat I need is 📚/🍎/✏️.\n何 私 必要 です 😊/😢/🤒。（私が必要なのは〜だ。）\n<b>Mixed Conditionals</b>\n<b>混合条件文</b>\nIf I had 🏃/📖/🎮ed, I would be 😊/🏠/✈️ now.\nもし 私 持った 🏃/📖/🎵ed、私 だろう です 🏃/📖/🎵 今。（もし〜していたら、今〜だろうに。）\nI suggest that he 🏃/📖/🎮.\n私 示唆 それ 彼 🏃/📖/🎵。（彼が〜することを提案する。）\nIt is important that she 🏃/📖/🎮.\nそれ です 重要な それ 彼女 🏃/📖/🎵。（彼女が〜することは重要だ。）\n<b>Passive Reporting</b>\n<b>受身（伝達）</b>\nIt is believed that 🌍/📚/🔬.\nそれ です 信じられた それ 🏃/📖/🎵。（〜だと信じられている。）\nIt is said that 🌍/📚/🔬.\nそれ です 言われた それ 🏃/📖/🎵。（〜だと言われている。）\nIt has been shown that 🌍/📚/🔬.\nそれ 持つ だった 示された それ 🏃/📖/🎵。（〜であることが示されている。）\n<b>Nominalization</b>\n<b>名詞化</b>\nThe 📚/🔬/🎨 of 🌍/📚/🔬 is 😊/🏠/✈️.\nその 🏃/📖/🎵 の 🏃/📖/🎵 です 😊/😢/🤒。（〜の〜は〜だ。）\nThe discovery of 🌍/📚/🔬.\nその 発見 の 🏃/📖/🎵。（〜の発見。）\n<b>Discourse Markers</b>\n<b>談話マーカー</b>\nFurthermore, 🌍/📚/🔬.\nさらに、🏃/📖/🎵。（さらに、〜。）\nNevertheless, 🌍/📚/🔬.\nそれにもかかわらず、🏃/📖/🎵。（それにもかかわらず、〜。）\nAccordingly, 🌍/📚/🔬.\nそれに応じて、🏃/📖/🎵。（それに応じて、〜。）\nConsequently, 🌍/📚/🔬.\nその結果、🏃/📖/🎵。（その結果、〜。）\n<b>Hedging</b>\n<b>婉曲表現</b>\nIt appears that 🌍/📚/🔬.\nそれ 現れる それ 🏃/📖/🎵。（〜のように見える。）\nThere seems to be 📚/🍎/✏️.\nそこに 思われる である 🏃/📖/🎵。（〜があるようだ。）\nIt tends to 🏃/📖/🎮.\nそれ 傾向 に 🏃/📖/🎵。（〜する傾向がある。）\n<b>Inversion (emphasis)</b>\n<b>倒置（強調）</b>\nNever have I 🏃/📖/🎮ed.\n決して 持つ 私 🏃/📖/🎵ed。（私は決して〜したことがない。）\nOnly when 🏃/📖/🎵 did I 🏃/📖/🎵.\nのみ いつ 🏃/📖/🎵 した 私 🏃/📖/🎵。（〜して初めて〜した。）\nNot until 🏃/📖/🎵 did I 🏃/📖/🎵.\nない まで 🏃/📖/🎵 した 私 🏃/📖/🎵。（〜して初めて〜した。）\n"
 }
];

var eiken1grammar = [
 {
 "title": "Grammar: Eiken 1",
 "content": "<b>Academic Passive</b>\n<b>学術的受身</b>\nIt has been argued that 🌍/📚/🔬.\nそれ 持つ だった 議論された それ 🏃/📖/🎵。（〜であると議論されている。）\nIt has been demonstrated that 🌍/📚/🔬.\nそれ 持つ だった 実証された それ 🏃/📖/🎵。（〜であることが実証されている。）\nIt should be noted that 🌍/📚/🔬.\nそれ べき である 注意された それ 🏃/📖/🎵。（〜であることに注意すべきだ。）\nIt is assumed that 🌍/📚/🔬.\nそれ です 仮定された それ 🏃/📖/🎵。（〜と仮定されている。）\n<b>Hedging & Stance</b>\n<b>婉曲・立場</b>\nApparently, 🌍/📚/🔬.\nどうやら、🏃/📖/🎵。（どうやら、〜のようだ。）\nSeemingly, 🌍/📚/🔬.\nどうやら、🏃/📖/🎵。（どうやら、〜のようだ。）\nArguably, 🌍/📚/🔬.\n議論の余地は、🏃/📖/🎵。（議論の余地はあるが、〜。）\nReportedly, 🌍/📚/🔬.\n報道によると、🏃/📖/🎵。（報道によると、〜。）\n<b>Nominalization</b>\n<b>名詞化</b>\nThe implementation of 📚/🔬/🎨 resulted in 😊/🏠/✈️.\nその 実施 の 🏃/📖/🎵 結果 に 🏃/📖/🎵。（〜の実施は〜をもたらした。）\nThe failure to 🏃/📖/🎮 led to 😊/🏠/✈️.\nその 失敗 に 🏃/📖/🎵 導いた に 🏃/📖/🎵。（〜しないことは〜につながった。）\n<b>Advanced Inversion</b>\n<b>高度な倒置</b>\nUnder no circumstances should 🏃/📖/🎮.\n下 ない 状況 べき 🏃/📖/🎵。（いかなる状況でも〜すべきではない。）\nLittle did 👨/👩/🧑 know that 🌍/📚/🔬.\n少し した 🏃/📖/🎵 知る それ 🏃/📖/🎵。（〜は〜だとは知らなかった。）\nNot only did 🏃/📖/🎮 but 😊/🏠/✈️.\nない のみ した 🏃/📖/🎵 しかし 🏃/📖/🎵。（〜だけでなく〜も〜した。）\n<b>Subjunctive (formal)</b>\n<b>仮定法（形式）</b>\nIf I were to 🏃/📖/🎮, I would 😊/🏠/✈️.\nもし 私 だった に 🏃/📖/🎵、私 だろう 🏃/📖/🎵。（もし〜するとしたら、〜だろう。）\nBe that as it may, 🌍/📚/🔬.\nである それ として それ かもしれない、🏃/📖/🎵。（そうかもしれないが、〜。）\n<b>Ellipsis</b>\n<b>省略</b>\nI can 🏃/🏊/🎨 and so can 👨/👩/🧑.\n私 できる 🏃/📖/🎵 そして できる 🏃/📖/🎵。（私は〜できるし、〜もできる。）\nShe 🏃s/📖s/🎨s more than 👨/👩/🧑.\n彼女 🏃/📖/🎵s もっと より 🏃/📖/🎵。（彼女は〜より多く〜する。）\n<b>Collocations</b>\n<b>連語</b>\npose a ⚠️/❓/🎯\n提示する 一つの 🏃/📖/🎵。（〜をもたらす。）\nmake a 📋/💬/🎨\n作る 一つの 🏃/📖/🎵。（〜を行う。）\ndraw a 📊/🎨/✏️\n引く 一つの 🏃/📖/🎵。（〜を引き出す。）\n"
 }
];

