var eiken7grammar = [
 {
 "title": "Grammar: Eiken 7",
 "content": "<b>BE Verb (am/is/are)</b>\n<b>BE動詞</b>\nI am a [___].\n私 です 一つの [___]。（私は〜です。）\nYou are [___].\nあなた です [___]。（あなたは〜です。）\nHe is [___].\n彼 です [___]。（彼は〜です。）\nShe is [___].\n彼女 です [___]。（彼女は〜です。）\nWe are [___].\n私たち です [___]。（私たちは〜です。）\nThey are [___].\n彼ら です [___]。（彼らは〜です。）\nThis is a [___].\nこれ です 一つの [___]。（これは〜です。）\nThat is a [___].\nあれ です 一つの [___]。（あれは〜です。）\nAre you [___]?\nです あなた [___]？（あなたは〜ですか？）\nIs he [___]?\nです 彼 [___]？（彼は〜ですか？）\nIs she [___]?\nです 彼女 [___]？（彼女は〜ですか？）\nAre they [___]?\nです 彼ら [___]？（彼らは〜ですか？）\nI like [___].\n私 好き [___]。（私は〜が好きです。）\nYou like [___].\nあなた 好き [___]。（あなたは〜が好きです。）\nDo you like [___]?\nする あなた 好き [___]？（あなたは〜が好きですか？）\nDoes he like [___]?\nする 彼 好き [___]？（彼は〜が好きですか？）\nI don't like [___].\n私 しない 好き [___]。（私は〜が好きではありません。）\n<b>Wh-Questions</b>\n<b>疑問詞</b>\nWhat is [___]?\n何 です [___]？（〜は何ですか？）\nWhere is [___]?\nどこ です [___]？（〜はどこですか？）\nIt is [___].\nそれ です [___]。（それは〜です。）\n"
 }
];

var eiken6grammar = [
 {
 "title": "Grammar: Eiken 6",
 "content": "<b>Present Continuous</b>\n<b>現在進行形</b>\nI am [___]ing.\n私 いる [___]して[___ing]。（私は〜しています。）\nHe is [___]ing.\n彼 いる [___]して[___ing]。（彼は〜しています。）\nShe is [___]ing.\n彼女 いる [___]して[___ing]。（彼女は〜しています。）\nThey are [___]ing.\n彼ら いる [___]して[___ing]。（彼らは〜しています。）\nAre you [___]ing?\nいる あなた [___]して[___ing]？（あなたは〜していますか？）\nIs he [___]ing?\nいる 彼 [___]して[___ing]？（彼は〜していますか？）\nI was [___].\n私 だった [___]。（私は〜だった。）\nHe was [___].\n彼 だった [___]。（彼は〜だった。）\nShe was [___].\n彼女 だった [___]。（彼女は〜だった。）\nWe were [___].\n私たち だった [___]。（私たちは〜だった。）\nThey were [___].\n彼ら だった [___]。（彼らは〜だった。）\nWas he [___]?\nだった 彼 [___]？（彼は〜でしたか？）\nWere you [___]?\nだった あなた [___]？（あなたは〜でしたか？）\nI verb.\n私 動詞。（私は〜する。）\nYou verb.\nあなた 動詞。（あなたは〜する。）\nHe verbs.\n彼 動詞s[verbs]。（彼は〜する。）\nShe verbs.\n彼女 動詞s[verbs]。（彼女は〜する。）\nDo you [___]?\nする あなた [___]？（あなたは〜しますか？）\nDoes he [___]?\nする 彼 [___]？（彼は〜しますか？）\nDoes she [___]?\nする 彼女 [___]？（彼女は〜しますか？）\nI can [___].\n私 できる [___]。（私は〜できます。）\nShe can [___].\n彼女 できる [___]。（彼女は〜できます。）\nCan you [___]?\nできる あなた [___]？（あなたは〜できますか？）\nI have a [___].\n私 持つ 一つの [___]。（私は〜を持っています。）\nShe has a [___].\n彼女 持つ 一つの [___]。（彼女は〜を持っています。）\nThis is my [___].\nこれ です 私の [___]。（これは私の〜です。）\nThat is his [___].\nあれ です 彼の [___]。（あれは彼の〜です。）\n<b>There is/are</b>\n<b>〜がある</b>\nThere is a [___].\nそこ です 一つの [___]。（〜があります。）\nThere are [___].\nそこ です [___]。（〜があります。）\n<b>Imperatives</b>\n<b>命令形</b>\nOpen your book.\n開く あなたの 本。（本を〜しなさい。）\nPlease help.\nどうぞ 助ける。（〜してください。）\n"
 }
];

var eiken5grammar = [
 {
 "title": "Grammar: Eiken 5",
 "content": "<b>Present Simple</b>\n<b>現在形</b>\nI [___] every day.\n私 [___] すべての 日。（私は毎日〜する。）\nYou [___] at school.\nあなた [___] に 学校。（あなたは学校で〜する。）\nWe [___] on Monday.\n私たち [___] に 月曜日。（私たちは月曜日に〜する。）\nThey [___] in Tokyo.\n彼ら [___] に 東京。（彼らは東京で〜する。）\nHe [___]s every day.\n彼 [___]s すべての 日。（彼は毎日〜する。）\nShe [___]s at school.\n彼女 [___]s に 学校。（彼女は学校で〜する。）\n<b>Present Continuous</b>\n<b>現在進行形</b>\nI am [___]ing now.\n私 いる [___]して[___ing] 今。（私は今〜している。）\nShe is [___]ing now.\n彼女 いる [___]して[___ing] 今。（彼女は今〜している。）\nThey are [___]ing now.\n彼ら いる [___]して[___ing] 今。（彼らは今〜している。）\n<b>Do/Does Questions</b>\n<b>Do/Doesの疑問文</b>\nDo you [___] every day?\nする あなた [___] すべての 日？（あなたは毎日〜しますか？）\nDoes he [___] every day?\nする 彼 [___] すべての 日？（彼は毎日〜しますか？）\nDoes she [___] at school?\nする 彼女 [___] に 学校？（彼女は学校で〜しますか？）\nI don't [___] every day.\n私 しない [___] すべての 日。（私は毎日〜しない。）\nHe doesn't [___] at school.\n彼 しない [___] に 学校。（彼は学校で〜しない。）\n<b>Wh-Questions</b>\n<b>疑問詞</b>\nWhat do you [___]?\n何 する あなた [___]？（あなたは〜何をしますか？）\nWhere do you [___]?\nどこ する あなた [___]？（あなたはどこで〜しますか？）\nWhen do you [___]?\nいつ する あなた [___]？（あなたはいつ〜しますか？）\nWhy do you [___]?\nなぜ する あなた [___]？（あなたはなぜ〜しますか？）\nHow do you [___]?\nどう する あなた [___]？（あなたはどう〜しますか？）\nWho [___]s?\n誰 [___]s？（誰が〜しますか？）\nWhat is your [___]?\n何 です あなたの [___]？（あなたの〜は何ですか？）\nWhere is your [___]?\nどこ です あなたの [___]？（あなたの〜はどこですか？）\nI can [___] well.\n私 できる [___] 上手に。（私は上手に〜できます。）\nCan you [___]?\nできる あなた [___]？（あなたは〜できますか？）\nYou should [___].\nあなた べき [___]。（あなたは〜すべきです。）\n<b>Prepositions</b>\n<b>前置詞</b>\nI [___] in the morning.\n私 [___] に その 朝。（私は朝〜する。）\nI [___] at 3 o'clock.\n私 [___] に 3時[3 o'clock]。（私は3時に〜する。）\nI [___] on Sunday.\n私 [___] に 日曜日。（私は日曜日に〜する。）\nIt is [___] the box.\nそれ です [___] その 箱。（それは箱の中に〜。）\n<b>Articles</b>\n<b>冠詞</b>\nI have a [___].\n私 持つ 一つの [___]。（私は〜を一つ持っている。）\nI like the [___].\n私 好き その [___]。（私はその〜が好きです。）\nShe is an [___].\n彼女 です 一つの [___]。（彼女は〜です。）\nI like [___] him.\n私 好き [___] 彼。（私は彼を〜好きです。）\nShe helps [___] me.\n彼女 助ける [___] 私。（彼女は私を〜助ける。）\nI see [___] them.\n私 見る [___] 彼ら。（私は彼らを〜見る。）\n<b>Comparatives</b>\n<b>比較級</b>\nThis is [___]er than that.\nこれ です [___]er より あれ。（これはあれより〜です。）\nShe is more [___] than me.\n彼女 です もっと [___] より 私。（彼女は私より〜です。）\nI am [___]er than you.\n私 です [___]er より あなた。（私はあなたより〜です。）\n<b>Possessives ('s)</b>\n<b>所有格</b>\nThis is [___]'s book.\nこれ です [___]の 本。（これは〜の本です。）\nThat is my [___]'s car.\nあれ です 私の [___]の 車。（あれは私の〜の車です。）\n<b>Frequency Adverbs</b>\n<b>頻度副詞</b>\nI [___] always.\n私 [___] いつも。（私はいつも〜する。）\nI [___] sometimes.\n私 [___] 時々[sometimes]。（私は時々〜する。）\nI [___] never.\n私 [___] 決して。（私は決して〜しない。）\n"
 }
];

var eiken4grammar = [
 {
 "title": "Grammar: Eiken 4",
 "content": "<b>Past Simple</b>\n<b>過去形</b>\nI [___]ed yesterday.\n私 [___]ed 昨日。（私は昨日〜した。）\nShe [___]ed last week.\n彼女 [___]ed 先週。（彼女は先週〜した。）\nThey [___]ed at school.\n彼ら [___]ed に 学校。（彼らは学校で〜した。）\nI [___]ed in the morning.\n私 [___]ed に その 朝。（私は朝〜した。）\n<b>Past Simple (irregular)</b>\n<b>過去形（不規則変化）</b>\nI [went/saw/ate].\n私 [行った/見た/食べた]。（私は〜した。）\nShe [went/saw/ate].\n彼女 [行った/見た/食べた]。（彼女は〜した。）\nHe [made/took/had].\n彼 [作った/取った/持った]。（彼は〜した。）\nShe didn't [___].\n彼女 しない 食べる。（彼女は〜しなかった。）\nDid you [___] yesterday?\nした あなた [___] 昨日？（あなたは昨日〜しましたか？）\nDid she [___] last week?\nした 彼女 [___] 先週？（彼女は先週〜しましたか？）\nI will [___] tomorrow.\n私 だろう [___] 明日。（私は明日〜するだろう。）\nShe will [___] next week.\n彼女 だろう [___] 来週。（彼女は来週〜するだろう。）\nWill you [___] tomorrow?\nだろう あなた [___] 明日？（あなたは明日〜しますか？）\nI won't [___].\n私 だろうしない [___]。（私は〜しないだろう。）\n<b>Going to</b>\n<b>〜するつもり</b>\nI am going to [___].\n私 です 行く に [___]。（私は〜するつもりです。）\nShe is going to [___].\n彼女 です 行く に [___]。（彼女は〜するつもりです。）\nAre you going to [___]?\nですか あなた 行く に [___]？（あなたは〜するつもりですか？）\n[___]er than [___].\n[___]er より [___]。（〜より〜です。）\nmore [___] than [___].\nもっと [___] より [___]。（〜より〜です。）\nthe [___]est.\nその [___]est。（一番〜です。）\nthe most [___].\nその 最も [___]。（一番〜です。）\n<b>Could/Should/Must</b>\n<b>できた/べき/なければならない</b>\nI could [___] when I was young.\n私 できた [___] いつ 私 だった 若い。（若い時〜できた。）\nYou should [___] every day.\nあなた べき [___] すべての 日。（あなたは毎日〜すべきです。）\nYou must [___] now.\nあなた しなければ [___] 今。（あなたは今〜しなければならない。）\nI have to [___].\n私 持つ に [___]。（私は〜しなければならない。）\nDo you have to [___]?\nする あなた 持つ に [___]？（あなたは〜しなければなりませんか？）\nThere was a [___].\nそこに だった 一つの [___]。（〜があった。）\nThere were many [___].\nそこに だった 多くの [___]。（〜がたくさんあった。）\nWas there a [___]?\nだった そこに 一つの [___]？（〜がありましたか？）\nI [___] because [___].\n私 [___] なぜなら [___]。（私は〜なぜなら〜だから。）\nI [___] so I verb.\n私 [___] だから 私 [___]。（私は〜だから〜する。）\nI [___] but [___].\n私 [___] しかし [___]。（私は〜しかし〜。）\n<b>Want/Need to</b>\n<b>〜したい/する必要がある</b>\nI want to [___].\n私 欲しい に [___]。（私は〜したい。）\nDo you want to [___]?\nする あなた 欲しい に [___]？（あなたは〜したいですか？）\nI need to [___].\n私 必要 に [___]。（私は〜する必要がある。）\n<b>Like + verb-ing</b>\n<b>〜するのが好き</b>\nI like [___]ing.\n私 好き [___]ing。（私は〜するのが好きです。）\nI like to [___].\n私 好き に [___]。（私は〜するのが好きです。）\n<b>Imperatives (negative)</b>\n<b>命令形（禁止・提案）</b>\nDon't [___]!\nしない [___]！（〜するな！）\nLet's [___]!\nしよう [___]！（〜しましょう！）\n"
 }
];

var eiken3grammar = [
 {
 "title": "Grammar: Eiken 3",
 "content": "<b>Have/Has auxiliary</b>\n<b>助動詞have/has</b>\nI have [___]ed.\n私 持つ [___]ed。（私は〜した。）\nShe has [___]ed.\n彼女 持つ [___]ed。（彼女は〜した。）\nHave you [___]ed?\n持つ あなた [___]ed？（あなたは〜しましたか？）\nShe has [___]ed.\n彼女 持つ [___]ed。（彼女は〜したことがある。）\nHave you [___]ed?\n持つ あなた [___]ed？（あなたは〜したことがありますか？）\nI haven't [___]ed.\n私 持たない [___]ed。（私は〜したことがない。）\nHe has never [___]ed.\n彼 持つ 決して [___]ed。（彼は決して〜したことがない。）\nI have [___]ed for [___].\n私 持つ [___]ed の間 [___]。（私は〜の間〜している。）\nI have [___]ed since [___].\n私 持つ [___]ed 以来 [___]。（私は〜以来〜している。）\nI have just [___]ed.\n私 持つ ちょうど [___]ed。（私はちょうど〜したところだ。）\nShe has already [___]ed.\n彼女 持つ 既に [___]ed。（彼女はもう〜した。）\nHave you [___]ed yet?\n持つ あなた [___]ed まだ？（あなたはもう〜しましたか？）\nI [___]ed in 2020.\n私 [___]ed に 2020年[2020]。（私は2020年に〜した。）\nI have [___]ed today.\n私 持つ [___]ed 今日。（私は今日〜した。）\n<b>First Conditional</b>\n<b>第一条件文</b>\nIf I [___], I will [___].\nもし 私 [___]、私 だろう [___]。（もし〜なら、〜だろう。）\nIf she [___]s, she will [___].\nもし 彼女 [___]s、彼女 だろう [___]。（もし彼女が〜なら、〜だろう。）\nIf you [___], will you [___]?\nもし あなた [___]、だろう あなた [___]？（もし〜なら、〜しますか？）\nI have some [___].\n私 持つ いくつかの [___]。（私はいくつかの〜を持っている。）\nDo you have any [___]?\nする あなた 持つ どんな [___]？（〜を持っていますか？）\nI don't have any [___].\n私 しない 持つ どんな [___]。（私は〜を全く持っていない。）\nThere is no [___].\nそこに です ない [___]。（〜はない。）\n<b>Too/Enough</b>\n<b>あまりに/十分に</b>\nIt is too [___].\nそれ です あまりに [___]。（それはあまりに〜です。）\nIt is [___] enough.\nそれ です [___] 十分に。（それは十分に〜です。）\nIt is too [___] to [___].\nそれ です あまりに [___] に [___]。（〜すぎて〜できない。）\nI [___] to [___].\n私 [___] に [___]。（私は〜するために〜する。）\nShe [___]s to [___].\n彼女 [___]s に [___]。（彼女は〜するために〜する。）\n<b>Gerunds</b>\n<b>動名詞</b>\n[___]ing is fun.\n[___]ing です 楽しい。（〜することは楽しい。）\nI like [___]ing.\n私 好き [___]ing。（私は〜するのが好きです。）\nI am good at [___]ing.\n私 です 上手 に [___]ing。（私は〜するのが上手です。）\n<b>Question Tags</b>\n<b>付加疑問</b>\nYou [___], don't you?\nあなた [___]、しない あなた？（〜ですね？）\nShe [___]s, doesn't she?\n彼女 [___]s、しない 彼女？（彼女は〜ですね？）\nYou can [___], can't you?\nあなた できる [___]、できない あなた？（〜できますよね？）\nThe person who [___]s.\nその 人 誰 [___]s。（〜する人。）\nThe thing that [___]s.\nその 物 それ [___]s。（〜するもの。）\nThe place where I verb.\nその 場所 どこ 私 [___]。（私が〜する場所。）\n<b>Prepositions of Movement</b>\n<b>移動の前置詞</b>\nI go [___] the park.\n私 行く [___] その 公園。（私は公園に〜行く。）\nI walk [___] the school.\n私 歩く [___] その 学校。（私は学校を〜歩く。）\n"
 }
];

var eikenpre2grammar = [
 {
 "title": "Grammar: Pre-2",
 "content": "I may [___] tomorrow.\n私 かもしれない [___] 明日。（私は明日〜かもしれない。）\nShe might [___].\n彼女 かもしれない [___]。（彼女は〜かもしれない。）\nI must [___] now.\n私 しなければ [___] 今。（私は今〜しなければならない。）\nYou should [___] more.\nあなた べき [___] もっと。（あなたはもっと〜すべきです。）\nCould you [___]?\nできた あなた [___]？（〜していただけますか？）\nWould you [___]?\nだろう あなた [___]？（〜していただけますか？）\nI was [___]ing.\n私 いた [___]して。（私は〜していた。）\nShe was [___]ing.\n彼女 いた [___]して。（彼女は〜していた。）\nThey were [___]ing.\n彼ら いた [___]して。（彼らは〜していた。）\nWas he [___]ing?\nいた 彼 [___]して？（彼は〜していましたか？）\nI was [___]ing when [___].\n私 いた [___]して いつ [___]。（〜していた時、〜した。）\nIt is [___]ed by [___].\nそれ です [___]ed によって [___]。（それは〜によって〜される。）\nIt was [___]ed by [___].\nそれ だった [___]ed によって [___]。（それは〜によって〜された。）\nEnglish is [___]ed here.\n英語 です [___]ed ここ。（英語はここで〜される。）\nI used to [___].\n私 使った に [___]。（私は昔〜したものだ。）\nShe used to [___].\n彼女 使った に [___]。（彼女は昔〜したものだ。）\nDid you use to [___]?\nした あなた 使う に [___]？（あなたは昔〜しましたか？）\nIf I [___]ed, I would [___].\nもし 私 [___]ed、私 だろう [___]。（もし〜なら、〜だろう。）\nIf she [___]ed, she would [___].\nもし 彼女 [___]ed、彼女 だろう [___]。（もし彼女が〜なら、〜だろう。）\nIf I were [___], I would [___].\nもし 私 だった [___]、私 だろう [___]。（もし私なら〜だろう。）\nI want to [___].\n私 欲しい に [___]。（私は〜したい。）\nI enjoy [___]ing.\n私 楽しむ [___]ing。（私は〜するのを楽しむ。）\nI stopped [___]ing.\n私 止めた [___]ing。（私は〜するのをやめた。）\nI decided to [___].\n私 決めた に [___]。（私は〜することに決めた。）\nI finished [___]ing.\n私 終えた [___]ing。（私は〜し終えた。）\nThe man who [___]s.\nその 男 誰 [___]s。（〜する男。）\nThe book that [___]s.\nその 本 それ [___]s。（〜する本。）\nThe dog which [___]s.\nその 犬 それ [___]s。（〜する犬。）\nas [___] as [___].\n同じ [___] 同じ [___]。（〜と同じくらい〜。）\nnot as [___] as [___].\nない 同じ [___] 同じ [___]。（〜ほど〜ではない。）\nIt is so [___] that [___].\nそれ です とても [___] それ [___]。（とても〜なので〜。）\nIt is such a [___] that [___].\nそれ です そんな 一つの [___] それ [___]。（とても〜なので〜。）\nI have much [___].\n私 持つ 多くの [___]。（私はたくさんの〜を持っている。）\nI have many [___].\n私 持つ 多くの [___]。（私はたくさんの〜を持っている。）\nI have a few [___].\n私 持つ 少しの [___]。（私は少しの〜を持っている。）\nI have a little [___].\n私 持つ 少しの [___]。（私は少しの〜を持っている。）\nI wish I [___]ed.\n私 願う 私 [___]ed。（〜だったらなあ。）\nI wish I were [___].\n私 願う 私 だった [___]。（〜だったらなあ。）\n"
 }
];

var eikenpre2plusgrammar = [
 {
 "title": "Grammar: Pre-2 Plus",
 "content": "I had [___]ed before [___].\n私 持った [___]ed 前に [___]。（〜の前に〜していた。）\nShe had [___]ed by the time [___].\n彼女 持った [___]ed までに [___]。（〜した時にはもう〜していた。）\nHad you [___]ed before [___]?\n持った あなた [___]ed 前に [___]？（〜前に〜しましたか？）\nIf I had [___]ed, I would have [___]ed.\nもし 私 持った [___]ed、私 だろう 持った [___]ed。（もし〜していたら、〜していただろう。）\nIf she had [___]ed, she would have [___]ed.\nもし 彼女 持った [___]ed、彼女 だろう 持った [___]ed。（もし彼女が〜していたら、〜していただろう。）\nI wish I had [___]ed.\n私 願う 私 持った [___]ed。（〜していればなあ。）\nI wish I had been [___].\n私 願う 私 持った だった [___]。（〜だったらなあ。）\nIt can be [___]ed.\nそれ できる である [___]ed。（それは〜できる。）\nIt should be [___]ed.\nそれ べき である [___]ed。（それは〜されるべきだ。）\nIt must be [___]ed.\nそれ しなければ である [___]ed。（それは〜されなければならない。）\nIt might be [___]ed.\nそれ かもしれない である [___]ed。（それは〜かもしれない。）\nHe said that he [___]ed.\n彼 言った それ 彼 [___]ed。（彼は〜したと言った。）\nShe said that she would [___].\n彼女 言った それ 彼女 だろう [___]。（彼女は〜するだろうと言った。）\nHe told me that he [___]ed.\n彼 告げた 私 それ 彼 [___]ed。（彼は私に〜したと言った。）\nI had my hair [___]ed.\n私 持った 私の 髪 [___]ed。（髪を〜してもらった。）\nI got someone to [___].\n私 得た 誰か に [___]。（誰かに〜してもらった。）\nIf I had [___]ed, I would [___] now.\nもし 私 持った [___]ed、私 だろう [___] 今。（もし〜していたら、今〜だろうに。）\nIf I were [___], I would have [___]ed.\nもし 私 だった [___]、私 だろう 持った [___]ed。（もし〜なら、〜していただろう。）\n[___]ing, I verb.\n[___]ing、私 [___]。（〜しながら、私は〜する。）\nHaving [___]ed, I verb.\n持っている [___]ed、私 [___]。（〜した後、私は〜する。）\nI was [___]ing when I [___]ed.\n私 いた [___]して いつ 私 [___]ed。（〜していた時、〜した。）\nAfter I had [___]ed, I [___]ed.\n後 私 持った [___]ed、私 [___]ed。（〜した後、〜した。）\nIt was [___] who [___]ed.\nそれ だった [___] 誰 [___]ed。（〜したのは〜だ。）\nWhat I [___]ed was [___].\n何 私 [___]ed だった [___]。（私が〜したのは〜だ。）\n"
 }
];

var eiken2grammar = [
 {
 "title": "Grammar: Eiken 2",
 "content": "I have been [___]ing.\n私 持つ いた [___]して。（私は〜し続けてきた。）\nShe has been [___]ing for [___].\n彼女 持つ いた [___]して の間 [___]。（彼女は〜の間〜し続けてきた。）\nHow long have you been [___]ing?\nどのくらい 持つ あなた いた [___]して？（どのくらい〜し続けていますか？）\nIt is being [___]ed now.\nそれ です である [___]ed 今。（それは今〜されている。）\nIt has been [___]ed.\nそれ 持つ だった [___]ed。（それは〜された。）\nIt will be [___]ed.\nそれ だろう である [___]ed。（それは〜されるだろう。）\nIt had been [___]ed before [___].\nそれ 持った だった [___]ed 前に [___]。（〜の前に〜されていた。）\nIf they had [___]ed, they would have [___]ed.\nもし 彼ら 持った [___]ed、彼ら だろう 持った [___]ed。（もし彼らが〜していたら、〜していただろう。）\nHe asked if I [___]ed.\n彼 聞いた もし 私 [___]ed。（彼は〜かどうか聞いた。）\nShe asked what I [___]ed.\n彼女 聞いた 何 私 [___]ed。（彼女は私が何を〜したか聞いた。）\nHe told me to [___].\n彼 告げた 私 に [___]。（彼は私に〜するように言った。）\nThe book that I [___]ed.\nその 本 それ 私 [___]ed。（私が〜した本。）\nThe person whose [___].\nその 人 その [___]。（〜の〜を持つ人。）\nI look forward to [___]ing.\n私 見る 前に に [___]ing。（〜するのを楽しみにしている。）\nI am used to [___]ing.\n私 です 使った に [___]ing。（〜することに慣れている。）\nI would rather [___].\n私 だろう むしろ [___]。（むしろ〜したい。）\nI had better [___].\n私 持った より [___]。（〜した方がいい。）\nDespite [___]ing, I verb.\nにもかかわらず [___]ing、私 [___]。（〜にもかかわらず、〜する。）\nAlthough [___], I verb.\nalthough[Although] [___]、私 [___]。（〜だけれども、〜する。）\nI [___] whereas [___].\n私 [___] 一方 [___]。（〜である一方、〜。）\nAll of the [___].\nすべて の その [___]。（〜のすべて。）\nMost of the [___].\nほとんど の その [___]。（〜のほとんど。）\nNeither of the [___].\nどちらも の その [___]。（〜のどちらも〜ない。）\nHe has [___]ed, hasn't he?\n彼 持つ [___]ed、持たない 彼？（彼は〜しましたよね？）\nShe will [___], won't she?\n彼女 だろう [___]、だろうない 彼女？（彼女は〜するでしょう？）\nNot only [___] but also [___].\nない のみ [___] しかし また [___]。（〜だけでなく〜も。）\n"
 }
];

var eikenpre1grammar = [
 {
 "title": "Grammar: Pre-1",
 "content": "Had I [___]ed, I would have [___]ed.\n持った 私 [___]ed、私 だろう 持った [___]ed。（もし〜していたら、〜していただろうに。）\nShould you [___], please [___].\nべき あなた [___]、どうぞ [___]。（万一〜するなら、〜してください。）\nWere I [___], I would [___].\nだった 私 [___]、私 だろう [___]。（もし私なら〜だろう。）\nIt is [___] that [___]s.\nそれ です [___] それ [___]s。（〜するのは〜だ。）\nWhat I need is [___].\n何 私 必要 です [___]。（私が必要なのは〜だ。）\nIf I had [___]ed, I would be [___] now.\nもし 私 持った [___]ed、私 だろう です [___] 今。（もし〜していたら、今〜だろうに。）\nI suggest that he [___].\n私 示唆 それ 彼 [___]。（彼が〜することを提案する。）\nIt is important that she [___].\nそれ です 重要な それ 彼女 [___]。（彼女が〜することは重要だ。）\nIt is believed that [___].\nそれ です 信じられた それ [___]。（〜だと信じられている。）\nIt is said that [___].\nそれ です 言われた それ [___]。（〜だと言われている。）\nIt has been shown that [___].\nそれ 持つ だった 示された それ [___]。（〜であることが示されている。）\nThe [___] of [___] is [___].\nその [___] の [___] です [___]。（〜の〜は〜だ。）\nThe discovery of [___].\nその 発見 の [___]。（〜の発見。）\nFurthermore, [___].\nさらに、[___]。（さらに、〜。）\nNevertheless, [___].\nそれにもかかわらず、[___]。（それにもかかわらず、〜。）\nAccordingly, [___].\nそれに応じて、[___]。（それに応じて、〜。）\nConsequently, [___].\nその結果、[___]。（その結果、〜。）\nIt appears that [___].\nそれ 現れる それ [___]。（〜のように見える。）\nThere seems to be [___].\nそこに 思われる である [___]。（〜があるようだ。）\nIt tends to [___].\nそれ 傾向 に [___]。（〜する傾向がある。）\nNever have I [___]ed.\n決して 持つ 私 [___]ed。（私は決して〜したことがない。）\nOnly when [___] did I verb.\nのみ いつ [___] した 私 [___]。（〜して初めて〜した。）\nNot until [___] did I verb.\nない まで [___] した 私 [___]。（〜して初めて〜した。）\n"
 }
];

var eiken1grammar = [
 {
 "title": "Grammar: Eiken 1",
 "content": "It has been argued that [___].\nそれ 持つ だった 議論された それ [___]。（〜であると議論されている。）\nIt has been demonstrated that [___].\nそれ 持つ だった 実証された それ [___]。（〜であることが実証されている。）\nIt should be noted that [___].\nそれ べき である 注意された それ [___]。（〜であることに注意すべきだ。）\nIt is assumed that [___].\nそれ です 仮定された それ [___]。（〜と仮定されている。）\nApparently, [___].\nどうやら、[___]。（どうやら、〜のようだ。）\nSeemingly, [___].\nどうやら、[___]。（どうやら、〜のようだ。）\nArguably, [___].\n議論の余地は、[___]。（議論の余地はあるが、〜。）\nReportedly, [___].\n報道によると、[___]。（報道によると、〜。）\nThe implementation of [___] resulted in [___].\nその 実施 の [___] 結果 に [___]。（〜の実施は〜をもたらした。）\nThe failure to [___] led to [___].\nその 失敗 に [___] 導いた に [___]。（〜しないことは〜につながった。）\nUnder no circumstances should [___].\n下 ない 状況 べき [___]。（いかなる状況でも〜すべきではない。）\nLittle did [___] know that [___].\n少し した [___] 知る それ [___]。（〜は〜だとは知らなかった。）\nNot only did [___] but [___].\nない のみ した [___] しかし [___]。（〜だけでなく〜も〜した。）\nIf I were to [___], I would [___].\nもし 私 だった に [___]、私 だろう [___]。（もし〜するとしたら、〜だろう。）\nBe that as it may, [___].\nである それ として それ かもしれない、[___]。（そうかもしれないが、〜。）\nI can [___] and so can [___].\n私 できる [___] そして できる [___]。（私は〜できるし、〜もできる。）\nShe [___]s more than [___].\n彼女 [___]s もっと より [___]。（彼女は〜より多く〜する。）\npose a [___]\n提示する 一つの [___]。（〜をもたらす。）\nmake a [___]\n作る 一つの [___]。（〜を行う。）\ndraw a [___]\n引く 一つの [___]。（〜を引き出す。）\n"
 }
];

