var vocab = [
  // CONCRETE WORDS (Nouns, Verbs, Adjectives, Adverbs)

  // 1. NOUNS
  { "emoji": "🐶", "word": "dog", "type": "noun", "japanese": "いぬ", "category": "concrete" },
  { "emoji": "🐱", "word": "cat", "type": "noun", "japanese": "ねこ", "category": "concrete" },
  { "emoji": "✋", "word": "hand", "type": "noun", "japanese": "て", "category": "concrete" },
  { "emoji": "👁️", "word": "eye", "type": "noun", "japanese": "め", "category": "concrete" },
  { "emoji": "🏠", "word": "house", "type": "noun", "japanese": "いえ", "category": "concrete" },
  { "emoji": "🌳", "word": "tree", "type": "noun", "japanese": "き", "category": "concrete" },
  { "emoji": "🚗", "word": "car", "type": "noun", "japanese": "くるま", "category": "concrete" },
  { "emoji": "📚", "word": "book", "type": "noun", "japanese": "ほん", "category": "concrete" },
  { "emoji": "🌊", "word": "water", "type": "noun", "japanese": "みず", "category": "concrete" },
  { "emoji": "☀️", "word": "sun", "type": "noun", "japanese": "たいよう", "category": "concrete" },
  { "emoji": "🌙", "word": "moon", "type": "noun", "japanese": "つき", "category": "concrete" },
  { "emoji": "🍎", "word": "apple", "type": "noun", "japanese": "りんご", "category": "concrete" },
  { "emoji": "🪑", "word": "chair", "type": "noun", "japanese": "いす", "category": "concrete" },
  { "emoji": "🛏️", "word": "bed", "type": "noun", "japanese": "ベッド", "category": "concrete" },
  { "emoji": "🚪", "word": "door", "type": "noun", "japanese": "ドア", "category": "concrete" },
  { "emoji": "🪟", "word": "window", "type": "noun", "japanese": "まど", "category": "concrete" },
  { "emoji": "🏙️", "word": "city", "type": "noun", "japanese": "とし", "category": "concrete" },
  { "emoji": "🌍", "word": "world", "type": "noun", "japanese": "せかい", "category": "concrete" },
  { "emoji": "👨", "word": "man", "type": "noun", "japanese": "おとこ", "category": "concrete" },
  { "emoji": "👩", "word": "woman", "type": "noun", "japanese": "おんな", "category": "concrete" },
  { "emoji": "👶", "word": "child", "type": "noun", "japanese": "こども", "category": "concrete" },
  { "emoji": "👪", "word": "family", "type": "noun", "japanese": "かぞく", "category": "concrete" },
  { "emoji": "👫", "word": "friend", "type": "noun", "japanese": "ともだち", "category": "concrete" },
  { "emoji": "🍴", "word": "food", "type": "noun", "japanese": "たべもの", "category": "concrete" },
  { "emoji": "🥤", "word": "drink", "type": "noun", "japanese": "のみもの", "category": "concrete" },
  { "emoji": "💰", "word": "money", "type": "noun", "japanese": "おかね", "category": "concrete" },
  { "emoji": "⏰", "word": "time", "type": "noun", "japanese": "じかん", "category": "concrete" },
  { "emoji": "📍", "word": "place", "type": "noun", "japanese": "ばしょ", "category": "concrete" },
  { "emoji": "🌞", "word": "day", "type": "noun", "japanese": "ひ", "category": "concrete" },
  { "emoji": "🌙", "word": "night", "type": "noun", "japanese": "よる", "category": "concrete" },
  { "emoji": "🐦", "word": "bird", "type": "noun", "japanese": "とり", "category": "concrete" },
  { "emoji": "🐟", "word": "fish", "type": "noun", "japanese": "さかな", "category": "concrete" },
  { "emoji": "🌸", "word": "flower", "type": "noun", "japanese": "はな", "category": "concrete" },
  { "emoji": "🍊", "word": "orange", "type": "noun", "japanese": "オレンジ", "category": "concrete" },
  { "emoji": "🍔", "word": "hamburger", "type": "noun", "japanese": "ハンバーガー", "category": "concrete" },
  { "emoji": "🍕", "word": "pizza", "type": "noun", "japanese": "ピザ", "category": "concrete" },
  { "emoji": "🍦", "word": "ice cream", "type": "noun", "japanese": "アイスクリーム", "category": "concrete" },
  { "emoji": "🍫", "word": "chocolate", "type": "noun", "japanese": "チョコレート", "category": "concrete" },
  { "emoji": "🍞", "word": "bread", "type": "noun", "japanese": "パン", "category": "concrete" },
  { "emoji": "🍎", "word": "fruit", "type": "noun", "japanese": "くだもの", "category": "concrete" },
  { "emoji": "🥕", "word": "vegetable", "type": "noun", "japanese": "やさい", "category": "concrete" },
  { "emoji": "🥛", "word": "milk", "type": "noun", "japanese": "ミルク", "category": "concrete" },
  { "emoji": "☕", "word": "coffee", "type": "noun", "japanese": "コーヒー", "category": "concrete" },
  { "emoji": "🍵", "word": "tea", "type": "noun", "japanese": "おちゃ", "category": "concrete" },
  { "emoji": "🍽️", "word": "plate", "type": "noun", "japanese": "さら", "category": "concrete" },
  { "emoji": "🥄", "word": "spoon", "type": "noun", "japanese": "スプーン", "category": "concrete" },
  { "emoji": "🍴", "word": "fork", "type": "noun", "japanese": "フォーク", "category": "concrete" },
  { "emoji": "🔪", "word": "knife", "type": "noun", "japanese": "ナイフ", "category": "concrete" },
  { "emoji": "🧣", "word": "scarf", "type": "noun", "japanese": "マフラー", "category": "concrete" },
  { "emoji": "👕", "word": "shirt", "type": "noun", "japanese": "シャツ", "category": "concrete" },
  { "emoji": "👖", "word": "pants", "type": "noun", "japanese": "ズボン", "category": "concrete" },
  { "emoji": "👟", "word": "shoes", "type": "noun", "japanese": "くつ", "category": "concrete" },
  { "emoji": "🧦", "word": "socks", "type": "noun", "japanese": "くつした", "category": "concrete" },
  { "emoji": "🧢", "word": "hat", "type": "noun", "japanese": "ぼうし", "category": "concrete" },
  { "emoji": "🧤", "word": "gloves", "type": "noun", "japanese": "てぶくろ", "category": "concrete" },
  { "emoji": "🧳", "word": "bag", "type": "noun", "japanese": "かばん", "category": "concrete" },
  { "emoji": "📱", "word": "phone", "type": "noun", "japanese": "でんわ", "category": "concrete" },
  { "emoji": "💻", "word": "computer", "type": "noun", "japanese": "コンピュータ", "category": "concrete" },
  { "emoji": "📺", "word": "television", "type": "noun", "japanese": "テレビ", "category": "concrete" },
  { "emoji": "🖼️", "word": "picture", "type": "noun", "japanese": "え", "category": "concrete" },
  { "emoji": "🖌️", "word": "pen", "type": "noun", "japanese": "ペン", "category": "concrete" },
  { "emoji": "✏️", "word": "pencil", "type": "noun", "japanese": "えんぴつ", "category": "concrete" },
  { "emoji": "📜", "word": "paper", "type": "noun", "japanese": "かみ", "category": "concrete" },
  { "emoji": "🛒", "word": "cart", "type": "noun", "japanese": "カート", "category": "concrete" },
  { "emoji": "🛍️", "word": "store", "type": "noun", "japanese": "みせ", "category": "concrete" },
  { "emoji": "🏫", "word": "school", "type": "noun", "japanese": "がっこう", "category": "concrete" },
  { "emoji": "🏥", "word": "hospital", "type": "noun", "japanese": "びょういん", "category": "concrete" },
  { "emoji": "🚒", "word": "fire truck", "type": "noun", "japanese": "しょうぼうしゃ", "category": "concrete" },
  { "emoji": "🚓", "word": "police car", "type": "noun", "japanese": "パトカー", "category": "concrete" },
  { "emoji": "🚲", "word": "bicycle", "type": "noun", "japanese": "じてんしゃ", "category": "concrete" },
  { "emoji": "✈️", "word": "airplane", "type": "noun", "japanese": "ひこうき", "category": "concrete" },
  { "emoji": "🚂", "word": "train", "type": "noun", "japanese": "でんしゃ", "category": "concrete" },
  { "emoji": "🛥️", "word": "boat", "type": "noun", "japanese": "ボート", "category": "concrete" },
  { "emoji": "🛣️", "word": "road", "type": "noun", "japanese": "みち", "category": "concrete" },
  { "emoji": "🏞️", "word": "park", "type": "noun", "japanese": "こうえん", "category": "concrete" },
  { "emoji": "🏖️", "word": "beach", "type": "noun", "japanese": "ビーチ", "category": "concrete" },
  { "emoji": "⛰️", "word": "mountain", "type": "noun", "japanese": "やま", "category": "concrete" },
  { "emoji": "🌄", "word": "sky", "type": "noun", "japanese": "そら", "category": "concrete" },
  { "emoji": "⭐", "word": "star", "type": "noun", "japanese": "ほし", "category": "concrete" },
  { "emoji": "☁️", "word": "cloud", "type": "noun", "japanese": "くも", "category": "concrete" },
  { "emoji": "🌧️", "word": "rain", "type": "noun", "japanese": "あめ", "category": "concrete" },
  { "emoji": "❄️", "word": "snow", "type": "noun", "japanese": "ゆき", "category": "concrete" },
  { "emoji": "🌬️", "word": "wind", "type": "noun", "japanese": "かぜ", "category": "concrete" },
  { "emoji": "🔥", "word": "fire", "type": "noun", "japanese": "ひ", "category": "concrete" },
  { "emoji": "🕰️", "word": "clock", "type": "noun", "japanese": "とけい", "category": "concrete" },
  { "emoji": "🗓️", "word": "calendar", "type": "noun", "japanese": "カレンダー", "category": "concrete" },
  { "emoji": "🎁", "word": "gift", "type": "noun", "japanese": "プレゼント", "category": "concrete" },
  { "emoji": "🎉", "word": "party", "type": "noun", "japanese": "パーティー", "category": "concrete" },
  { "emoji": "🎂", "word": "cake", "type": "noun", "japanese": "ケーキ", "category": "concrete" },
  { "emoji": "🎈", "word": "balloon", "type": "noun", "japanese": "ふうせん", "category": "concrete" },
  { "emoji": "🎸", "word": "guitar", "type": "noun", "japanese": "ギター", "category": "concrete" },
  { "emoji": "🎹", "word": "piano", "type": "noun", "japanese": "ピアノ", "category": "concrete" },
  { "emoji": "⚽", "word": "soccer ball", "type": "noun", "japanese": "サッカーボール", "category": "concrete" },
  { "emoji": "🏀", "word": "basketball", "type": "noun", "japanese": "バスケットボール", "category": "concrete" },
  { "emoji": "🎾", "word": "tennis ball", "type": "noun", "japanese": "テニスボール", "category": "concrete" },
  { "emoji": "🏊", "word": "pool", "type": "noun", "japanese": "プール", "category": "concrete" },
  { "emoji": "🛠️", "word": "tool", "type": "noun", "japanese": "どうぐ", "category": "concrete" },
  { "emoji": "🔧", "word": "wrench", "type": "noun", "japanese": "レンチ", "category": "concrete" },
  { "emoji": "🔨", "word": "hammer", "type": "noun", "japanese": "ハンマー", "category": "concrete" },
  { "emoji": "🪚", "word": "saw", "type": "noun", "japanese": "のこぎり", "category": "concrete" },
  { "emoji": "🖥️", "word": "monitor", "type": "noun", "japanese": "モニター", "category": "concrete" },
  { "emoji": "⌨️", "word": "keyboard", "type": "noun", "japanese": "キーボード", "category": "concrete" },
  { "emoji": "🖱️", "word": "mouse", "type": "noun", "japanese": "マウス", "category": "concrete" },
  { "emoji": "🎤", "word": "microphone", "type": "noun", "japanese": "マイク", "category": "concrete" },
  { "emoji": "🎧", "word": "headphones", "type": "noun", "japanese": "ヘッドフォン", "category": "concrete" },
  { "emoji": "📷", "word": "camera", "type": "noun", "japanese": "カメラ", "category": "concrete" },
  { "emoji": "🖨️", "word": "printer", "type": "noun", "japanese": "プリンター", "category": "concrete" },
  { "emoji": "📡", "word": "radio", "type": "noun", "japanese": "ラジオ", "category": "concrete" },
  { "emoji": "🛋️", "word": "sofa", "type": "noun", "japanese": "ソファ", "category": "concrete" },
  { "emoji": "🛁", "word": "bathtub", "type": "noun", "japanese": "ふろ", "category": "concrete" },
  { "emoji": "🚿", "word": "shower", "type": "noun", "japanese": "シャワー", "category": "concrete" },
  { "emoji": "🧼", "word": "soap", "type": "noun", "japanese": "せっけん", "category": "concrete" },
  { "emoji": "🪥", "word": "toothbrush", "type": "noun", "japanese": "はぶらし", "category": "concrete" },
  { "emoji": "🧴", "word": "shampoo", "type": "noun", "japanese": "シャンプー", "category": "concrete" },
  { "emoji": "🧻", "word": "toilet paper", 'type': "noun", "japanese": "トイレットペーパー", "category": "concrete" },
  { "emoji": "🪞", "word": "mirror", "type": "noun", "japanese": "かがみ", "category": "concrete" },
  { "emoji": "🧹", "word": "broom", "type": "noun", "japanese": "ほうき", "category": "concrete" },
  { "emoji": "🗑️", "word": "trash can", "type": "noun", "japanese": "ごみばこ", "category": "concrete" },
  { "emoji": "🧺", "word": "basket", "type": "noun", "japanese": "かご", "category": "concrete" },
  { "emoji": "🧽", "word": "sponge", "type": "noun", "japanese": "スポンジ", "category": "concrete" },
  { "emoji": "🧸", "word": "teddy bear", "type": "noun", "japanese": "テディベア", "category": "concrete" },
  { "emoji": "🎮", "word": "video game", "type": "noun", "japanese": "ビデオゲーム", "category": "concrete" },
  { "emoji": "🧩", "word": "puzzle", "type": "noun", "japanese": "パズル", "category": "concrete" },
  { "emoji": "🛹", "word": "skateboard", "type": "noun", "japanese": "スケートボード", "category": "concrete" },
  { "emoji": "🪁", "word": "kite", "type": "noun", "japanese": "たこ", "category": "concrete" },
  { "emoji": "🎠", "word": "carousel", "type": "noun", "japanese": "メリーゴーランド", "category": "concrete" },
  { "emoji": "🎡", "word": "ferris wheel", "type": "noun", "japanese": "かんらんしゃ", "category": "concrete" },
  { "emoji": "🏰", "word": "castle", "type": "noun", "japanese": "しろ", "category": "concrete" },
  { "emoji": "🏯", "word": "temple", "type": "noun", "japanese": "てら", "category": "concrete" },
  { "emoji": "🕍", "word": "shrine", "type": "noun", "japanese": "じんじゃ", "category": "concrete" },
  { "emoji": "🦒", "word": "giraffe", "type": "noun", "japanese": "キリン", "category": "concrete" },
  { "emoji": "🦁", "word": "lion", "type": "noun", "japanese": "ライオン", "category": "concrete" },
  { "emoji": "🐘", "word": "elephant", "type": "noun", "japanese": "ぞう", "category": "concrete" },
  { "emoji": "🦓", "word": "zebra", "type": "noun", "japanese": "シマウマ", "category": "concrete" },
  { "emoji": "🐻", "word": "bear", "type": "noun", "japanese": "くま", "category": "concrete" },
  { "emoji": "🐰", "word": "rabbit", "type": "noun", "japanese": "うさぎ", "category": "concrete" },
  { "emoji": "🦊", "word": "fox", "type": "noun", "japanese": "きつね", "category": "concrete" },
  { "emoji": "🐺", "word": "wolf", "type": "noun", "japanese": "おおかみ", "category": "concrete" },
  { "emoji": "🐴", "word": "horse", "type": "noun", "japanese": "うま", "category": "concrete" },
  { "emoji": "🐮", "word": "cow", "type": "noun", "japanese": "うし", "category": "concrete" },
  { "emoji": "🐷", "word": "pig", "type": "noun", "japanese": "ぶた", "category": "concrete" },
  { "emoji": "🐑", "word": "sheep", "type": "noun", "japanese": "ひつじ", "category": "concrete" },
  { "emoji": "🐐", "word": "goat", "type": "noun", "japanese": "やぎ", "category": "concrete" },
  { "emoji": "🐔", "word": "chicken", "type": "noun", "japanese": "にわとり", "category": "concrete" },
  { "emoji": "🦆", "word": "duck", "type": "noun", "japanese": "あひる", "category": "concrete" },
  { "emoji": "🦢", "word": "swan", "type": "noun", "japanese": "はくちょう", "category": "concrete" },
  { "emoji": "🦜", "word": "parrot", "type": "noun", "japanese": "おうむ", "category": "concrete" },
  { "emoji": "🦋", "word": "butterfly", "type": "noun", "japanese": "ちょう", "category": "concrete" },
  { "emoji": "🐝", "word": "bee", "type": "noun", "japanese": "はち", "category": "concrete" },
  { "emoji": "🐞", "word": "ladybug", "type": "noun", "japanese": "てんとうむし", "category": "concrete" },
  { "emoji": "🕷️", "word": "spider", "type": "noun", "japanese": "くも", "category": "concrete" },
  { "emoji": "🐍", "word": "snake", "type": "noun", "japanese": "へび", "category": "concrete" },
  { "emoji": "🐢", "word": "turtle", "type": "noun", "japanese": "かめ", "category": "concrete" },
  { "emoji": "🐙", "word": "octopus", "type": "noun", "japanese": "たこ", "category": "concrete" },
  { "emoji": "🦑", "word": "squid", "type": "noun", "japanese": "いか", "category": "concrete" },
  { "emoji": "🦐", "word": "shrimp", "type": "noun", "japanese": "えび", "category": "concrete" },
  { "emoji": "🦞", "word": "lobster", "type": "noun", "japanese": "ロブスター", "category": "concrete" },
  { "emoji": "🦀", "word": "crab", "type": "noun", "japanese": "かに", "category": "concrete" },
  { "emoji": "🐬", "word": "dolphin", "type": "noun", "japanese": "イルカ", "category": "concrete" },
  { "emoji": "🐳", "word": "whale", "type": "noun", "japanese": "くじら", "category": "concrete" },
  { "emoji": "🦈", "word": "shark", "type": "noun", "japanese": "さめ", "category": "concrete" },
  { "emoji": "🐠", "word": "tropical fish", "type": "noun", "japanese": "ねったいぎょ", "category": "concrete" },
  { "emoji": "🍇", "word": "grape", "type": "noun", "japanese": "ぶどう", "category": "concrete" },
  { "emoji": "🍉", "word": "watermelon", "type": "noun", "japanese": "すいか", "category": "concrete" },
  { "emoji": "🍈", "word": "melon", "type": "noun", "japanese": "メロン", "category": "concrete" },
  { "emoji": "🍓", "word": "strawberry", "type": "noun", "japanese": "いちご", "category": "concrete" },
  { "emoji": "🍑", "word": "peach", "type": "noun", "japanese": "もも", "category": "concrete" },
  { "emoji": "🍍", "word": "pineapple", "type": "noun", "japanese": "パイナップル", "category": "concrete" },
  { "emoji": "🥭", "word": "mango", "type": "noun", "japanese": "マンゴー", "category": "concrete" },
  { "emoji": "🍋", "word": "lemon", "type": "noun", "japanese": "レモン", "category": "concrete" },
  { "emoji": "🍌", "word": "banana", "type": "noun", "japanese": "バナナ", "category": "concrete" },
  { "emoji": "🥝", "word": "kiwi", "type": "noun", "japanese": "キウイ", "category": "concrete" },
  { "emoji": "🥥", "word": "coconut", "type": "noun", "japanese": "ココナッツ", "category": "concrete" },
  { "emoji": "🍅", "word": "tomato", "type": "noun", "japanese": "トマト", "category": "concrete" },
  { "emoji": "🥔", "word": "potato", "type": "noun", "japanese": "じゃがいも", "category": "concrete" },
  { "emoji": "🥕", "word": "carrot", "type": "noun", "japanese": "にんじん", "category": "concrete" },
  { "emoji": "🌽", "word": "corn", "type": "noun", "japanese": "とうもろこし", "category": "concrete" },
  { "emoji": "🥦", "word": "broccoli", "type": "noun", "japanese": "ブロッコリー", "category": "concrete" },
  { "emoji": "🥬", "word": "lettuce", "type": "noun", "japanese": "レタス", "category": "concrete" },
  { "emoji": "🥒", "word": "cucumber", "type": "noun", "japanese": "きゅうり", "category": "concrete" },
  { "emoji": "🍄", "word": "mushroom", "type": "noun", "japanese": "きのこ", "category": "concrete" },
  { "emoji": "🥜", "word": "peanut", "type": "noun", "japanese": "ピーナッツ", "category": "concrete" },
  { "emoji": "🌰", "word": "chestnut", "type": "noun", "japanese": "くり", "category": "concrete" },
  { "emoji": "🍙", "word": "rice ball", "type": "noun", "japanese": "おにぎり", "category": "concrete" },
  { "emoji": "🍚", "word": "rice", "type": "noun", "japanese": "ごはん", "category": "concrete" },
  { "emoji": "🍜", "word": "noodles", "type": "noun", "japanese": "めん", "category": "concrete" },
  { "emoji": "🍣", "word": "sushi", "type": "noun", "japanese": "すし", "category": "concrete" },
  { "emoji": "🍤", "word": "tempura", "type": "noun", "japanese": "てんぷら", "category": "concrete" },
  { "emoji": "🥟", "word": "dumpling", "type": "noun", "japanese": "ぎょうざ", "category": "concrete" },
  { "emoji": "🥠", "word": "fortune cookie", "type": "noun", "japanese": "フォーチュンクッキー", "category": "concrete" },
  { "emoji": "🥮", "word": "mooncake", "type": "noun", "japanese": "月餅", "category": "concrete" },
  { "emoji": "🧀", "word": "cheese", "type": "noun", "japanese": "チーズ", "category": "concrete" },
  { "emoji": "🥚", "word": "egg", "type": "noun", "japanese": "たまご", "category": "concrete" },
  { "emoji": "🥓", "word": "bacon", "type": "noun", "japanese": "ベーコン", "category": "concrete" },
  { "emoji": "🥩", "word": "meat", "type": "noun", "japanese": "にく", "category": "concrete" },
  { "emoji": "🍗", "word": "chicken leg", "type": "noun", "japanese": "チキンレッグ", "category": "concrete" },
  { "emoji": "🥐", "word": "croissant", "type": "noun", "japanese": "クロワッサン", "category": "concrete" },
  { "emoji": "🥖", "word": "baguette", "type": "noun", "japanese": "バゲット", "category": "concrete" },
  { "emoji": "🥨", "word": "pretzel", "type": "noun", "japanese": "プレッツェル", "category": "concrete" },
  { "emoji": "🥯", "word": "bagel", "type": "noun", "japanese": "ベーグル", "category": "concrete" },
  { "emoji": "🥞", "word": "pancake", "type": "noun", "japanese": "パンケーキ", "category": "concrete" },
  { "emoji": "🧇", "word": "waffle", "type": "noun", "japanese": "ワッフル", "category": "concrete" },
  { "emoji": "🥤", "word": "soda", "type": "noun", "japanese": "ソーダ", "category": "concrete" },
  { "emoji": "🧃", "word": "juice", "type": "noun", "japanese": "ジュース", "category": "concrete" },
  { "emoji": "🍺", "word": "beer", "type": "noun", "japanese": "ビール", "category": "concrete" },
  { "emoji": "🍷", "word": "wine", "type": "noun", "japanese": "ワイン", "category": "concrete" },
  { "emoji": "🥃", "word": "whiskey", "type": "noun", "japanese": "ウイスキー", "category": "concrete" },
  { "emoji": "🍸", "word": "cocktail", "type": "noun", "japanese": "カクテル", "category": "concrete" },
  { "emoji": "🥂", "word": "champagne", "type": "noun", "japanese": "シャンパン", "category": "concrete" },

  // 2. VERBS
  { "emoji": "🏃", "word": "run", "type": "verb", "japanese": "はしる", "category": "concrete" },
  { "emoji": "🍽️", "word": "eat", "type": "verb", "japanese": "たべる", "category": "concrete" },
  { "emoji": "🚶", "word": "walk", "type": "verb", "japanese": "あるく", "category": "concrete" },
  { "emoji": "💤", "word": "sleep", "type": "verb", "japanese": "ねる", "category": "concrete" },
  { "emoji": "📝", "word": "write", "type": "verb", "japanese": "かく", "category": "concrete" },
  { "emoji": "📖", "word": "read", "type": "verb", "japanese": "よむ", "category": "concrete" },
  { "emoji": "🗣️", "word": "speak", "type": "verb", "japanese": "はなす", "category": "concrete" },
  { "emoji": "🚶‍♂️", "word": "go", "type": "verb", "japanese": "いく", "category": "concrete" },
  { "emoji": "🏠", "word": "come", "type": "verb", "japanese": "くる", "category": "concrete" },
  { "emoji": "👀", "word": "see", "type": "verb", "japanese": "みる", "category": "concrete" },
  { "emoji": "👂", "word": "hear", "type": "verb", "japanese": "きく", "category": "concrete" },
  { "emoji": "🧠", "word": "think", "type": "verb", "japanese": "かんがえる", "category": "concrete" },
  { "emoji": "💭", "word": "know", "type": "verb", "japanese": "しる", "category": "concrete" },
  { "emoji": "❤️", "word": "want", "type": "verb", "japanese": "ほしい", "category": "concrete" },
  { "emoji": "👍", "word": "like", "type": "verb", "japanese": "すき", "category": "concrete" },
  { "emoji": "🗣️", "word": "say", "type": "verb", "japanese": "いう", "category": "concrete" },
  { "emoji": "🛠️", "word": "make", "type": "verb", "japanese": "つくる", "category": "concrete" },
  { "emoji": "🤲", "word": "take", "type": "verb", "japanese": "とる", "category": "concrete" },
  { "emoji": "🎁", "word": "give", "type": "verb", "japanese": "あげる", "category": "concrete" },
  { "emoji": "📦", "word": "use", "type": "verb", "japanese": "つかう", "category": "concrete" },
  { "emoji": "🔍", "word": "find", "type": "verb", "japanese": "みつける", "category": "concrete" },
  { "emoji": "📢", "word": "tell", "type": "verb", "japanese": "いう", "category": "concrete" },
  { "emoji": "🙋", "word": "ask", "type": "verb", "japanese": "きく", "category": "concrete" },
  { "emoji": "👷", "word": "work", "type": "verb", "japanese": "はたらく", "category": "concrete" },
  { "emoji": "🧘", "word": "feel", "type": "verb", "japanese": "かんじる", "category": "concrete" },
  { "emoji": "🧗", "word": "try", "type": "verb", "japanese": "こころみる", "category": "concrete" },
  { "emoji": "🚶", "word": "leave", "type": "verb", "japanese": "さる", "category": "concrete" },
  { "emoji": "📞", "word": "call", "type": "verb", "japanese": "でんわする", "category": "concrete" },
  { "emoji": "🏊", "word": "swim", "type": "verb", "japanese": "およぐ", "category": "concrete" },
  { "emoji": "🚴", "word": "ride", "type": "verb", "japanese": "のる", "category": "concrete" },
  { "emoji": "🖌️", "word": "paint", "type": "verb", "japanese": "えがく", "category": "concrete" },
  { "emoji": "🎶", "word": "sing", "type": "verb", "japanese": "うたう", "category": "concrete" },
  { "emoji": "💃", "word": "dance", "type": "verb", "japanese": "おどる", "category": "concrete" },
  { "emoji": "📸", "word": "photograph", "type": "verb", "japanese": "しゃしんをとる", "category": "concrete" },
  { "emoji": "🎬", "word": "film", "type": "verb", "japanese": "えいがをとる", "category": "concrete" },
  { "emoji": "🎮", "word": "play", "type": "verb", "japanese": "あそぶ", "category": "concrete" },
  { "emoji": "🧹", "word": "clean", "type": "verb", "japanese": "そうじする", "category": "concrete" },
  { "emoji": "🧼", "word": "wash", "type": "verb", "japanese": "あらう", "category": "concrete" },
  { "emoji": "🍳", "word": "cook", "type": "verb", "japanese": "りょうりする", "category": "concrete" },
  { "emoji": "✂️", "word": "cut", "type": "verb", "japanese": "きる", "category": "concrete" },
  { "emoji": "🪡", "word": "sew", "type": "verb", "japanese": "ぬう", "category": "concrete" },
  { "emoji": "🛠️", "word": "build", "type": "verb", "japanese": "たてる", "category": "concrete" },
  { "emoji": "🔨", "word": "hammer", "type": "verb", "japanese": "くぎをうつ", "category": "concrete" },
  { "emoji": "🚿", "word": "shower", "type": "verb", "japanese": "シャワーをあびる", "category": "concrete" },
  { "emoji": "🛁", "word": "bathe", "type": "verb", "japanese": "ふろにはいる", "category": "concrete" },
  { "emoji": "🪥", "word": "brush", "type": "verb", "japanese": "みがく", "category": "concrete" },
  { "emoji": "🚪", "word": "open", "type": "verb", "japanese": "あける", "category": "concrete" },
  { "emoji": "🔒", "word": "close", "type": "verb", "japanese": "しめる", "category": "concrete" },
  { "emoji": "🔓", "word": "unlock", "type": "verb", "japanese": "かぎをあける", "category": "concrete" },
  { "emoji": "🔐", "word": "lock", "type": "verb", "japanese": "かぎをかける", "category": "concrete" },
  { "emoji": "🛒", "word": "shop", "type": "verb", "japanese": "かいものする", "category": "concrete" },
  { "emoji": "💸", "word": "buy", "type": "verb", "japanese": "かう", "category": "concrete" },
  { "emoji": "💵", "word": "sell", "type": "verb", "japanese": "うる", "category": "concrete" },
  { "emoji": "🎁", "word": "wrap", "type": "verb", "japanese": "つつむ", "category": "concrete" },
  { "emoji": "📬", "word": "mail", "type": "verb", "japanese": "ゆうびんをおくる", "category": "concrete" },
  { "emoji": "📩", "word": "send", "type": "verb", "japanese": "おくる", "category": "concrete" },
  { "emoji": "📥", "word": "receive", "type": "verb", "japanese": "うけとる", "category": "concrete" },
  { "emoji": "📦", "word": "pack", "type": "verb", "japanese": "つめる", "category": "concrete" },
  { "emoji": "📤", "word": "unpack", "type": "verb", "japanese": "ほどく", "category": "concrete" },
  { "emoji": "🛌", "word": "lie", "type": "verb", "japanese": "ねる", "category": "concrete" },
  { "emoji": "🪑", "word": "sit", "type": "verb", "japanese": "すわる", "category": "concrete" },
  { "emoji": "🧍", "word": "stand", "type": "verb", "japanese": "たつ", "category": "concrete" },
  { "emoji": "🤸", "word": "jump", "type": "verb", "japanese": "とぶ", "category": "concrete" },
  { "emoji": "🤝", "word": "shake", "type": "verb", "japanese": "あくしゅする", "category": "concrete" },
  { "emoji": "👏", "word": "clap", "type": "verb", "japanese": "はくしゅする", "category": "concrete" },
  { "emoji": "🙌", "word": "raise", "type": "verb", "japanese": "あげる", "category": "concrete" },
  { "emoji": "👈", "word": "point", "type": "verb", "japanese": "ゆびさす", "category": "concrete" },
  { "emoji": "✍️", "word": "draw", "type": "verb", "japanese": "かく", "category": "concrete" },
  { "emoji": "🔎", "word": "search", "type": "verb", "japanese": "さがす", "category": "concrete" },
  { "emoji": "📴", "word": "turn off", "type": "verb", "japanese": "けす", "category": "concrete" },
  { "emoji": "💡", "word": "turn on", "type": "verb", "japanese": "つける", "category": "concrete" },
  { "emoji": "🚶‍♀️", "word": "arrive", "type": "verb", "japanese": "つく", "category": "concrete" },
  { "emoji": "🛫", "word": "depart", "type": "verb", "japanese": "しゅっぱつする", "category": "concrete" },

  // 3. ADJECTIVES
  { "emoji": "🔴", "word": "red", "type": "adjective", "japanese": "あかい", "category": "concrete" },
  { "emoji": "🔵", "word": "blue", "type": "adjective", "japanese": "あおい", "category": "concrete" },
  { "emoji": "📏", "word": "big", "type": "adjective", "japanese": "おおきい", "category": "concrete" },
  { "emoji": "🔍", "word": "small", "type": "adjective", "japanese": "ちいさい", "category": "concrete" },
  { "emoji": "🗻", "word": "tall", "type": "adjective", "japanese": "たかい", "category": "concrete" },
  { "emoji": "📐", "word": "short", "type": "adjective", "japanese": "みじかい", "category": "concrete" },
  { "emoji": "🌞", "word": "hot", "type": "adjective", "japanese": "あつい", "category": "concrete" },
  { "emoji": "❄️", "word": "cold", "type": "adjective", "japanese": "さむい", "category": "concrete" },
  { "emoji": "🟢", "word": "new", "type": "adjective", "japanese": "あたらしい", "category": "concrete" },
  { "emoji": "🟤", "word": "old", "type": "adjective", "japanese": "ふるい", "category": "concrete" },
  { "emoji": "👶", "word": "young", "type": "adjective", "japanese": "わかい", "category": "concrete" },
  { "emoji": "🧓", "word": "old (person)", "type": "adjective", "japanese": "としをとった", "category": "concrete" },
  { "emoji": "👍", "word": "good", "type": "adjective", "japanese": "いい", "category": "concrete" },
  { "emoji": "👎", "word": "bad", "type": "adjective", "japanese": "わるい", "category": "concrete" },
  { "emoji": "💨", "word": "fast", "type": "adjective", "japanese": "はやい", "category": "concrete" },
  { "emoji": "🐌", "word": "slow", "type": "adjective", "japanese": "おそい", "category": "concrete" },
  { "emoji": "😊", "word": "happy", "type": "adjective", "japanese": "しあわせ", "category": "concrete" },
  { "emoji": "😢", "word": "sad", "type": "adjective", "japanese": "かなしい", "category": "concrete" },
  { "emoji": "😡", "word": "angry", "type": "adjective", "japanese": "おこった", "category": "concrete" },
  { "emoji": "😴", "word": "tired", "type": "adjective", "japanese": "つかれた", "category": "concrete" },
  { "emoji": "🍽️", "word": "hungry", "type": "adjective", "japanese": "おなかがすいた", "category": "concrete" },
  { "emoji": "🥤", "word": "thirsty", "type": "adjective", "japanese": "のどがかわいた", "category": "concrete" },
  { "emoji": "🟡", "word": "yellow", "type": "adjective", "japanese": "きいろい", "category": "concrete" },
  { "emoji": "🟢", "word": "green", "type": "adjective", "japanese": "みどり", "category": "concrete" },
  { "emoji": "⚫", "word": "black", "type": "adjective", "japanese": "くろい", "category": "concrete" },
  { "emoji": "⚪", "word": "white", "type": "adjective", "japanese": "しろい", "category": "concrete" },
  { "emoji": "🟣", "word": "purple", "type": "adjective", "japanese": "むらさき", "category": "concrete" },
  { "emoji": "🟤", "word": "brown", "type": "adjective", "japanese": "ちゃいろい", "category": "concrete" },
  { "emoji": "🟠", "word": "orange", "type": "adjective", "japanese": "オレンジいろ", "category": "concrete" },
  { "emoji": "🌸", "word": "pink", "type": "adjective", "japanese": "ピンク", "category": "concrete" },
  { "emoji": "☁️", "word": "cloudy", "type": "adjective", "japanese": "くもり", "category": "concrete" },
  { "emoji": "🌧️", "word": "rainy", "type": "adjective", "japanese": "あめ", "category": "concrete" },
  { "emoji": "❄️", "word": "snowy", "type": "adjective", "japanese": "ゆき", "category": "concrete" },
  { "emoji": "🌞", "word": "sunny", "type": "adjective", "japanese": "はれ", "category": "concrete" },
  { "emoji": "🌬️", "word": "windy", "type": "adjective", "japanese": "かぜ", "category": "concrete" },
  { "emoji": "🧼", "word": "clean", "type": "adjective", "japanese": "きれい", "category": "concrete" },
  { "emoji": "🧹", "word": "dirty", "type": "adjective", "japanese": "きたない", "category": "concrete" },
  { "emoji": "💪", "word": "strong", "type": "adjective", "japanese": "つよい", "category": "concrete" },
  { "emoji": "🤒", "word": "weak", "type": "adjective", "japanese": "よわい", "category": "concrete" },
  { "emoji": "🧠", "word": "smart", "type": "adjective", "japanese": "かしこい", "category": "concrete" },
  { "emoji": "😊", "word": "kind", "type": "adjective", "japanese": "しんせつ", "category": "concrete" },
  { "emoji": "😈", "word": "mean", "type": "adjective", "japanese": "いや", "category": "concrete" },
  { "emoji": "😄", "word": "funny", "type": "adjective", "japanese": "おもしろい", "category": "concrete" },
  { "emoji": "😑", "word": "boring", "type": "adjective", "japanese": "つまらない", "category": "concrete" },
  { "emoji": "😍", "word": "beautiful", "type": "adjective", "japanese": "うつくしい", "category": "concrete" },
  { "emoji": "😣", "word": "ugly", "type": "adjective", "japanese": "みにくい", "category": "concrete" },
  { "emoji": "🤫", "word": "quiet", "type": "adjective", "japanese": "しずか", "category": "concrete" },
  { "emoji": "🔊", "word": "loud", "type": "adjective", "japanese": "うるさい", "category": "concrete" },
  { "emoji": "🧊", "word": "cool", "type": "adjective", "japanese": "すずしい", "category": "concrete" },
  { "emoji": "🔥", "word": "warm", "type": "adjective", "japanese": "あたたかい", "category": "concrete" },
  { "emoji": "🟥", "word": "square", "type": "adjective", "japanese": "しかく", "category": "concrete" },
  { "emoji": "🟡", "word": "round", "type": "adjective", "japanese": "まるい", "category": "concrete" },
  { "emoji": "🔺", "word": "triangular", "type": "adjective", "japanese": "さんかく", "category": "concrete" },
  { "emoji": "📏", "word": "long", "type": "adjective", "japanese": "ながい", "category": "concrete" },
  { "emoji": "📐", "word": "narrow", "type": "adjective", "japanese": "せまい", "category": "concrete" },
  { "emoji": "📏", "word": "wide", "type": "adjective", "japanese": "ひろい", "category": "concrete" },

  // 4. ADVERBS
  { "emoji": "🚀", "word": "quickly", "type": "adverb", "japanese": "はやく", "category": "concrete" },
  { "emoji": "🐢", "word": "slowly", "type": "adverb", "japanese": "ゆっくり", "category": "concrete" },
  { "emoji": "🔊", "word": "loudly", "type": "adverb", "japanese": "おおきなこえで", "category": "concrete" },
  { "emoji": "🔇", "word": "quietly", "type": "adverb", "japanese": "しずかに", "category": "concrete" },
  { "emoji": "😊", "word": "happily", "type": "adverb", "japanese": "しあわせに", "category": "concrete" },
  { "emoji": "😢", "word": "sadly", "type": "adverb", "japanese": "かなしく", "category": "concrete" },
  { "emoji": "😣", "word": "angrily", "type": "adverb", "japanese": "おこって", "category": "concrete" },
  { "emoji": "🔍", "word": "carefully", "type": "adverb", "japanese": "ていねいに", "category": "concrete" },
  { "emoji": "🏃", "word": "fast", "type": "adverb", "japanese": "はやく", "category": "concrete" },
  { "emoji": "🧘", "word": "calmly", "type": "adverb", "japanese": "おだやかに", "category": "concrete" },
  { "emoji": "🧠", "word": "cleverly", "type": "adverb", "japanese": "かしこく", "category": "concrete" },
  { "emoji": "😄", "word": "cheerfully", "type": "adverb", "japanese": "たのしく", "category": "concrete" },
  { "emoji": "🙏", "word": "politely", "type": "adverb", "japanese": "ていねいに", "category": "concrete" },
  { "emoji": "💪", "word": "strongly", "type": "adverb", "japanese": "つよく", "category": "concrete" },
  { "emoji": "🤒", "word": "weakly", "type": "adverb", "japanese": "よわく", "category": "concrete" },
  { "emoji": "🌞", "word": "brightly", "type": "adverb", "japanese": "あかるく", "category": "concrete" },
  { "emoji": "🌙", "word": "darkly", "type": "adverb", "japanese": "くらやみに", "category": "concrete" },
  { "emoji": "🧼", "word": "cleanly", "type": "adverb", "japanese": "きれいに", "category": "concrete" },
  { "emoji": "🧹", "word": "messily", "type": "adverb", "japanese": "きたなく", "category": "concrete" },

  // ABSTRACT WORDS (Pronouns, Prepositions, Conjunctions, Auxiliary Verbs, Interjections)

  // 5. PRONOUNS
  { "word": "I", "type": "pronoun", "japanese": "わたし", "category": "abstract" },
  { "word": "me", "type": "pronoun", "japanese": "わたしの", "category": "abstract" },
  { "word": "you", "type": "pronoun", "japanese": "あなた", "category": "abstract" },
  { "word": "he", "type": "pronoun", "japanese": "かれ", "category": "abstract" },
  { "word": "she", "type": "pronoun", "japanese": "かのじょ", "category": "abstract" },
  { "word": "we", "type": "pronoun", "japanese": "わたしたち", "category": "abstract" },
{ "word": "they", "type": "pronoun", "japanese": "かれら", "category": "abstract" },
  { "word": "this", "type": "pronoun", "japanese": "これ", "category": "abstract" },
  { "word": "that", "type": "pronoun", "japanese": "それ", "category": "abstract" },
  { "word": "it", "type": "pronoun", "japanese": "それ", "category": "abstract" },
  { "word": "us", "type": "pronoun", "japanese": "わたしたち", "category": "abstract" },
  { "word": "them", "type": "pronoun", "japanese": "かれら", "category": "abstract" },
  { "word": "him", "type": "pronoun", "japanese": "かれ", "category": "abstract" },
  { "word": "her", "type": "pronoun", "japanese": "かのじょ", "category": "abstract" },
  { "word": "my", "type": "pronoun", "japanese": "わたしの", "category": "abstract" },
  { "word": "your", "type": "pronoun", "japanese": "あなたの", "category": "abstract" },
  { "word": "his", "type": "pronoun", "japanese": "かれの", "category": "abstract" },
  { "word": "our", "type": "pronoun", "japanese": "わたしたちの", "category": "abstract" },
  { "word": "their", "type": "pronoun", "japanese": "かれらの", "category": "abstract" },
  { "word": "mine", "type": "pronoun", "japanese": "わたしのもの", "category": "abstract" },
  { "word": "yours", "type": "pronoun", "japanese": "あなたのもの", "category": "abstract" },
  { "word": "hers", "type": "pronoun", "japanese": "かのじょのもの", "category": "abstract" },
  { "word": "ours", "type": "pronoun", "japanese": "わたしたちのもの", "category": "abstract" },
  { "word": "theirs", "type": "pronoun", "japanese": "かれらのもの", "category": "abstract" },
  { "word": "who", "type": "pronoun", "japanese": "だれ", "category": "abstract" },
  { "word": "whom", "type": "pronoun", "japanese": "だれを", "category": "abstract" },
  { "word": "whose", "type": "pronoun", "japanese": "だれの", "category": "abstract" },
  { "word": "what", "type": "pronoun", "japanese": "なに", "category": "abstract" },
  { "word": "which", "type": "pronoun", "japanese": "どれ", "category": "abstract" },
  { "word": "someone", "type": "pronoun", "japanese": "だれか", "category": "abstract" },
  { "word": "somebody", "type": "pronoun", "japanese": "だれか", "category": "abstract" },
  { "word": "something", "type": "pronoun", "japanese": "なにか", "category": "abstract" },
  { "word": "anyone", "type": "pronoun", "japanese": "だれでも", "category": "abstract" },
  { "word": "anybody", "type": "pronoun", "japanese": "だれでも", "category": "abstract" },
  { "word": "anything", "type": "pronoun", "japanese": "なんでも", "category": "abstract" },
  { "word": "everyone", "type": "pronoun", "japanese": "みんなく", "category": "abstract" },
  { "word": "everybody", "type": "pronoun", "japanese": "みんな", "category": "abstract" },
  { "word": "everything", "type": "pronoun", "japanese": "すべて", "category": "abstract" },
  { "word": "nobody", "type": "pronoun", "japanese": "だれも", "category": "abstract" },
  { "word": "nothing", "type": "pronoun", "japanese": "なにも", "category": "abstract" },

  // 6. PREPOSITIONS
  { "word": "in", "type": "preposition", "japanese": "のなかに", "category": "abstract" },
  { "word": "on", "type": "preposition", "japanese": "のうえに", "category": "abstract" },
  { "word": "at", "type": "preposition", "japanese": "で", "category": "abstract" },
  { "word": "to", "type": "preposition", "japanese": "に", "category": "abstract" },
  { "word": "from", "type": "preposition", "japanese": "から", "category": "abstract" },
  { "word": "with", "type": "preposition", "japanese": "と", "category": "abstract" },
  { "word": "by", "type": "preposition", "japanese": "によって", "category": "abstract" },
  { "word": "for", "type": "preposition", "japanese": "のために", "category": "abstract" },
  { "word": "about", "type": "preposition", "japanese": "について", "category": "abstract" },
  { "word": "of", "type": "preposition", "japanese": "の", "category": "abstract" },
  { "word": "over", "type": "preposition", "japanese": "のうえに", "category": "abstract" },
  { "word": "under", "type": "preposition", "japanese": "のしたに", "category": "abstract" },
  { "word": "through", "type": "preposition", "japanese": "をとおして", "category": "abstract" },
  { "word": "into", "type": "preposition", "japanese": "のなかへ", "category": "abstract" },
  { "word": "out", "type": "preposition", "japanese": "そとに", "category": "abstract" },
  { "word": "up", "type": "preposition", "japanese": "うえに", "category": "abstract" },
  { "word": "down", "type": "preposition", "japanese": "したに", "category": "abstract" },
  { "word": "across", "type": "preposition", "japanese": "よこに", "category": "abstract" },
  { "word": "between", "type": "preposition", "japanese": "のあいだに", "category": "abstract" },
  { "word": "among", "type": "preposition", "japanese": "のなかに", "category": "abstract" },
  { "word": "behind", "type": "preposition", "japanese": "うしろに", "category": "abstract" },
  { "word": "in front of", "type": "preposition", "japanese": "まえに", "category": "abstract" },
  { "word": "next to", "type": "preposition", "japanese": "となりに", "category": "abstract" },
  { "word": "beside", "type": "preposition", "japanese": "そばに", "category": "abstract" },
  { "word": "near", "type": "preposition", "japanese": "ちかくに", "category": "abstract" },
  { "word": "far", "type": "preposition", "japanese": "とおく", "category": "abstract" },
  { "word": "above", "type": "preposition", "japanese": "うえに", "category": "abstract" },
  { "word": "below", "type": "preposition", "japanese": "したに", "category": "abstract" },
  { "word": "inside", "type": "preposition", "japanese": "なかに", "category": "abstract" },
  { "word": "outside", "type": "preposition", "japanese": "そとに", "category": "abstract" },

  // 7. CONJUNCTIONS
  { "word": "and", "type": "conjunction", "japanese": "と", "category": "abstract" },
  { "word": "but", "type": "conjunction", "japanese": "しかし", "category": "abstract" },
  { "word": "or", "type": "conjunction", "japanese": "または", "category": "abstract" },
  { "word": "because", "type": "conjunction", "japanese": "なぜなら", "category": "abstract" },
  { "word": "so", "type": "conjunction", "japanese": "だから", "category": "abstract" },
  { "word": "if", "type": "conjunction", "japanese": "もし", "category": "abstract" },
  { "word": "although", "type": "conjunction", "japanese": "であっても", "category": "abstract" },
  { "word": "while", "type": "conjunction", "japanese": "あいだ", "category": "abstract" },
  { "word": "since", "type": "conjunction", "japanese": "から", "category": "abstract" },
  { "word": "until", "type": "conjunction", "japanese": "まで", "category": "abstract" },
  { "word": "unless", "type": "conjunction", "japanese": "でない限り", "category": "abstract" },
  { "word": "as", "type": "conjunction", "japanese": "として", "category": "abstract" },
  { "word": "before", "type": "conjunction", "japanese": "まえに", "category": "abstract" },
  { "word": "after", "type": "conjunction", "japanese": "あとに", "category": "abstract" },
  { "word": "though", "type": "conjunction", "japanese": "けれども", "category": "abstract" },
  { "word": "whereas", "type": "conjunction", "japanese": "一方で", "category": "abstract" },
  { "word": "whenever", "type": "conjunction", "japanese": "いつでも", "category": "abstract" },
  { "word": "wherever", "type": "conjunction", "japanese": "どこでも", "category": "abstract" },

 // 8. AUXILIARY VERBS
  { "word": "be", "type": "auxiliary verb", "japanese": "である", "category": "abstract" },
  { "word": "have", "type": "auxiliary verb", "japanese": "ある", "category": "abstract" },
  { "word": "do", "type": "auxiliary verb", "japanese": "する", "category": "abstract" },
  { "word": "will", "type": "auxiliary verb", "japanese": "だろう", "category": "abstract" },
  { "word": "can", "type": "auxiliary verb", "japanese": "できる", "category": "abstract" },
  { "word": "must", "type": "auxiliary verb", "japanese": "なければならない", "category": "abstract" },
  { "word": "should", "type": "auxiliary verb", "japanese": "べき", "category": "abstract" },
  { "word": "would", "type": "auxiliary verb", "japanese": "だろう", "category": "abstract" },
  { "word": "could", "type": "auxiliary verb", "japanese": "できる", "category": "abstract" },
  { "word": "shall", "type": "auxiliary verb", "japanese": "するだろう", "category": "abstract" },
  { "word": "might", "type": "auxiliary verb", "japanese": "かもしれない", "category": "abstract" },
  { "word": "may", "type": "auxiliary verb", "japanese": "かもしれない", "category": "abstract" },
  { "word": "ought", "type": "auxiliary verb", "japanese": "すべき", "category": "abstract" },

  // 9. INTERJECTIONS
  { "emoji": "❗", "word": "oh!", "type": "interjection", "japanese": "ああ！", "category": "abstract" },
  { "emoji": "😲", "word": "wow!", "type": "interjection", "japanese": "わあ！", "category": "abstract" },
  { "emoji": "👍", "word": "good!", "type": "interjection", "japanese": "いいね！", "category": "abstract" },
  { "emoji": "👋", "word": "hello!", "type": "interjection", "japanese": "こんにちは！", "category": "abstract" },
  { "emoji": "😮", "word": "oops!", "type": "interjection", "japanese": "おっと！", "category": "abstract" },
  { "emoji": "🎉", "word": "yay!", "type": "interjection", "japanese": "やった！", "category": "abstract" },
  { "emoji": "😣", "word": "ouch!", "type": "interjection", "japanese": "いたっ！", "category": "abstract" },
  { "emoji": "😢", "word": "aw!", "type": "interjection", "japanese": "ああ！", "category": "abstract" },
  { "emoji": "🤗", "word": "hurray!", "type": "interjection", "japanese": "万歳！", "category": "abstract" },
  { "emoji": "😬", "word": "ugh!", "type": "interjection", "japanese": "うっ！", "category": "abstract" },
  { "emoji": "🙌", "word": "great!", "type": "interjection", "japanese": "すばらしい！", "category": "abstract" },
  { "emoji": "😳", "word": "oh no!", "type": "interjection", "japanese": "なんてこと！", "category": "abstract" },
  { "emoji": "😁", "word": "cool!", "type": "interjection", "japanese": "かっこいい！", "category": "abstract" },
  { "emoji": "😅", "word": "phew!", "type": "interjection", "japanese": "ふう！", "category": "abstract" },
  { "emoji": "😱", "word": "yikes!", "type": "interjection", "japanese": "ひえ！", "category": "abstract" },
  { "emoji": "🙏", "word": "please!", "type": "interjection", "japanese": "お願い！", "category": "abstract" },
  { "emoji": "👏", "word": "bravo!", "type": "interjection", "japanese": "ブラボー！", "category": "abstract" },
  { "emoji": "😴", "word": "zzz!", "type": "interjection", "japanese": "ぐー！", "category": "abstract" },
  { "emoji": "😕", "word": "huh!", "type": "interjection", "japanese": "はあ？", "category": "abstract" },
  { "emoji": "😎", "word": "nice!", "type": "interjection", "japanese": "ナイス！", "category": "abstract" }
];
