// vocabulary.js
const vocabularyCategories = {
    "People": [
 {english: "friend", japanese: "友達", emoji: "👫"},
                    {english: "member", japanese: "メンバー", emoji: "👥"},
                    {english: "man", japanese: "男性", emoji: "👨"},
                    {english: "woman", japanese: "女性", emoji: "👩"},
                    {english: "lady", japanese: "ご婦人", emoji: "👵"},
                    {english: "adult", japanese: "大人", emoji: "🧑"},
                    {english: "boy", japanese: "少年", emoji: "👦"},
                    {english: "girl", japanese: "少女", emoji: "👧"},
                    {english: "child", japanese: "子ども", emoji: "🧒"},
                    {english: "children", japanese: "child の複数形", emoji: "👶"},
                    {english: "baby", japanese: "赤ちゃん", emoji: "👶"},
                    {english: "people", japanese: "人々", emoji: "👥"},
                    {english: "job", japanese: "仕事", emoji: "💼"},
                    {english: "worker", japanese: "働く人", emoji: "👷"},
                    {english: "doctor", japanese: "医者", emoji: "👨‍⚕️"},
                    {english: "player", japanese: "選手", emoji: "🏃"},
                    {english: "cook", japanese: "コック", emoji: "👨‍🍳"},
                    {english: "driver", japanese: "運転手", emoji: "👨‍✈️"},
                    {english: "officer", japanese: "役人", emoji: "👮"},
                    {english: "singer", japanese: "歌手", emoji: "🎤"},
                    {english: "farmer", japanese: "農場経営者", emoji: "👨‍🌾"},
                    {english: "nurse", japanese: "看護師", emoji: "👩‍⚕️"},
                    {english: "pilot", japanese: "パイロット", emoji: "👨‍✈️"},
                    {english: "waiter", japanese: "ウエーター", emoji: "👨‍🍳"},
                    {english: "police officer", japanese: "警察官", emoji: "👮"},
                    {english: "dancer", japanese: "ダンサー", emoji: "💃"},
                    {english: "pianist", japanese: "ピアニスト", emoji: "🎹"},
                    {english: "firefighter", japanese: "消防士", emoji: "👨‍🚒"}
                ],
                "Numbers": [
                    {english: "one", japanese: "1", emoji: "1️⃣"},
                    {english: "two", japanese: "2", emoji: "2️⃣"},
                    {english: "three", japanese: "3", emoji: "3️⃣"},
                    {english: "four", japanese: "4", emoji: "4️⃣"},
                    {english: "five", japanese: "5", emoji: "5️⃣"},
                    {english: "six", japanese: "6", emoji: "6️⃣"},
                    {english: "seven", japanese: "7", emoji: "7️⃣"},
                    {english: "eight", japanese: "8", emoji: "8️⃣"},
                    {english: "nine", japanese: "9", emoji: "9️⃣"},
                    {english: "ten", japanese: "10", emoji: "🔟"},
                    {english: "eleven", japanese: "11", emoji: "1️⃣1️⃣"},
                    {english: "twelve", japanese: "12", emoji: "1️⃣2️⃣"},
                    {english: "thirteen", japanese: "13", emoji: "1️⃣3️⃣"},
                    {english: "fourteen", japanese: "14", emoji: "1️⃣4️⃣"},
                    {english: "fifteen", japanese: "15", emoji: "1️⃣1️⃣5️⃣"},
                    {english: "sixteen", japanese: "16", emoji: "1️⃣6️⃣"},
                    {english: "seventeen", japanese: "17", emoji: "1️⃣7️⃣"},
                    {english: "eighteen", japanese: "18", emoji: "1️⃣8️⃣"},
                    {english: "nineteen", japanese: "19", emoji: "1️⃣9️⃣"},
                    {english: "twenty", japanese: "20", emoji: "2️⃣0️⃣"},
                    {english: "thirty", japanese: "30", emoji: "3️⃣0️⃣"},
                    {english: "forty", japanese: "40", emoji: "4️⃣0️⃣"},
                    {english: "fifty", japanese: "50", emoji: "5️⃣0️⃣"},
                    {english: "sixty", japanese: "60", emoji: "6️⃣0️⃣"},
                    {english: "seventy", japanese: "70", emoji: "7️⃣0️⃣"},
                    {english: "eighty", japanese: "80", emoji: "8️⃣0️⃣"},
                    {english: "ninety", japanese: "90", emoji: "9️⃣0️⃣"},
                    {english: "hundred", japanese: "100", emoji: "💯"},
                    {english: "thousand", japanese: "1000", emoji: "1000"},
                    {english: "first", japanese: "1 番目の", emoji: "1️⃣"},
                    {english: "second", japanese: "2 番目の", emoji: "2️⃣"},
                    {english: "third", japanese: "3 番目の", emoji: "3️⃣"},
                    {english: "fourth", japanese: "4 番目の", emoji: "4️⃣"},
                    {english: "fifth", japanese: "5 番目の", emoji: "5️⃣"},
                    {english: "sixth", japanese: "6 番目の", emoji: "6️⃣"},
                    {english: "seventh", japanese: "7 番目の", emoji: "7️⃣"},
                    {english: "eighth", japanese: "8 番目の", emoji: "8️⃣"},
                    {english: "ninth", japanese: "9 番目の", emoji: "9️⃣"},
                    {english: "tenth", japanese: "10 番目の", emoji: "🔟"},
                    {english: "eleventh", japanese: "11 番目の", emoji: "1️⃣1️⃣"},
                    {english: "twelfth", japanese: "12 番目の", emoji: "1️⃣2️⃣"},
                    {english: "twice", japanese: "２回", emoji: "2️⃣"}
                ],
                "Time & Dates": [
                    {english: "today", japanese: "今日", emoji: "📅"},
                    {english: "tomorrow", japanese: "明日", emoji: "📅"},
                    {english: "yesterday", japanese: "きのう", emoji: "📅"},
                    {english: "day", japanese: "日", emoji: "📅"},
                    {english: "date", japanese: "日付", emoji: "📅"},
                    {english: "time", japanese: "時刻", emoji: "⏰"},
                    {english: "hour", japanese: "１時間", emoji: "⏰"},
                    {english: "minute", japanese: "分", emoji: "⏰"},
                    {english: "morning", japanese: "朝、午前", emoji: "🌅"},
                    {english: "noon", japanese: "正午", emoji: "☀️"},
                    {english: "afternoon", japanese: "午後", emoji: "🌇"},
                    {english: "evening", japanese: "夕方、晩", emoji: "🌆"},
                    {english: "night", japanese: "夜", emoji: "🌙"},
                    {english: "week", japanese: "週", emoji: "📅"},
                    {english: "weekend", japanese: "週末", emoji: "🎉"},
                    {english: "year", japanese: "年", emoji: "📅"},
                    {english: "month", japanese: "月、１ヶ月", emoji: "📅"},
                    {english: "January", japanese: "１月", emoji: "1️⃣"},
                    {english: "February", japanese: "２月", emoji: "2️⃣"},
                    {english: "March", japanese: "３月", emoji: "3️⃣"},
                    {english: "April", japanese: "４月", emoji: "4️⃣"},
                    {english: "May", japanese: "５月", emoji: "5️⃣"},
                    {english: "June", japanese: "６月", emoji: "6️⃣"},
                    {english: "July", japanese: "７月", emoji: "7️⃣"},
                    {english: "August", japanese: "８月", emoji: "8️⃣"},
                    {english: "September", japanese: "９月", emoji: "9️⃣"},
                    {english: "October", japanese: "１０月", emoji: "🔟"},
                    {english: "November", japanese: "１１月", emoji: "1️⃣1️⃣"},
                    {english: "December", japanese: "１２月", emoji: "1️⃣2️⃣"}
                ],
                "Home & Objects": [
                    {english: "house", japanese: "家", emoji: "🏠"},
                    {english: "room", japanese: "部屋", emoji: "🚪"},
                    {english: "home", japanese: "家庭", emoji: "🏠"},
                    {english: "table", japanese: "テーブル", emoji: "🪑"},
                    {english: "bed", japanese: "ベッド", emoji: "🛏️"},
                    {english: "door", japanese: "ドア", emoji: "🚪"},
                    {english: "book", japanese: "本", emoji: "📖"},
                    {english: "picture", japanese: "絵", emoji: "🖼️"},
                    {english: "computer", japanese: "コンピューター", emoji: "💻"},
                    {english: "box", japanese: "箱", emoji: "📦"},
                    {english: "TV", japanese: "テレビ", emoji: "📺"},
                    {english: "cap", japanese: "縁のない帽子", emoji: "🧢"},
                    {english: "bag", japanese: "かばん", emoji: "👜"},
                    {english: "letter", japanese: "手紙", emoji: "✉️"},
                    {english: "camera", japanese: "カメラ", emoji: "📷"},
                    {english: "pet", japanese: "ペット", emoji: "🐶"},
                    {english: "T-shirt", japanese: "Ｔシャツ", emoji: "👕"},
                    {english: "window", japanese: "窓", emoji: "🪟"},
                    {english: "e-mail", japanese: "Eメール", emoji: "📧"},
                    {english: "bath", japanese: "入浴", emoji: "🛁"},
                    {english: "watch", japanese: "腕時計", emoji: "⌚"},
                    {english: "comic book", japanese: "マンガ本", emoji: "📖"},
                    {english: "umbrella", japanese: "傘", emoji: "☂️"},
                    {english: "chair", japanese: "いす", emoji: "💺"},
                    {english: "magazine", japanese: "雑誌", emoji: "📰"},
                    {english: "phone", japanese: "電話", emoji: "📱"},
                    {english: "bathroom", japanese: "浴室", emoji: "🚽"},
                    {english: "hat", japanese: "ふちのある帽子", emoji: "👒"},
                    {english: "cup", japanese: "カップ", emoji: "☕"},
                    {english: "kitchen", japanese: "キッチン", emoji: "🍳"},
                    {english: "desk", japanese: "机", emoji: "🪑"},
                    {english: "basket", japanese: "かご", emoji: "🧺"},
                    {english: "garden", japanese: "庭", emoji: "🌻"},
                    {english: "bedroom", japanese: "寝室", emoji: "🛏️"},
                    {english: "newspaper", japanese: "新聞", emoji: "📰"},
                    {english: "shirt", japanese: "シャツ", emoji: "👕"},
                    {english: "DVD", japanese: "ＤＵＤ", emoji: "📀"},
                    {english: "floor", japanese: "床", emoji: "🧹"},
                    {english: "glove", japanese: "手袋", emoji: "🧤"},
                    {english: "living room", japanese: "居間", emoji: "🛋️"},
                    {english: "shoe", japanese: "くつ", emoji: "👞"},
                    {english: "jacket", japanese: "ジャケット", emoji: "🧥"},
                    {english: "postcard", japanese: "はがき", emoji: "📮"},
                    {english: "shower", japanese: "シャワー", emoji: "🚿"},
                    {english: "sofa", japanese: "ソファー", emoji: "🛋️"},
                    {english: "album", japanese: "アルバム", emoji: "📒"},
                    {english: "card", japanese: "カード", emoji: "🎴"},
                    {english: "curtain", japanese: "カーテン", emoji: "🪟"},
                    {english: "diary", japanese: "日記", emoji: "📔"},
                    {english: "dining room", japanese: "食堂", emoji: "🍽️"},
                    {english: "radio", japanese: "ラジオ", emoji: "📻"},
                    {english: "towel", japanese: "タオル", emoji: "🧻"},
                    {english: "backpack", japanese: "バックパック", emoji: "🎒"},
                    {english: "calendar", japanese: "カレンダー", emoji: "📅"},
                    {english: "coat", japanese: "コート", emoji: "🧥"},
                    {english: "pocket", japanese: "ポケット", emoji: "👖"},
                    {english: "skirt", japanese: "スカート", emoji: "👗"},
                    {english: "toy", japanese: "おもちゃ", emoji: "🧸"},
                    {english: "wall", japanese: "壁", emoji: "🧱"},
                    {english: "clock", japanese: "置き時計", emoji: "🕰️"},
                    {english: "coin", japanese: "硬貨", emoji: "🪙"},
                    {english: "doghouse", japanese: "犬小屋", emoji: "🐶"},
                    {english: "living", japanese: "暮らし", emoji: "🏠"},
                    {english: "package", japanese: "荷物", emoji: "📦"},
                    {english: "poster", japanese: "ポスター", emoji: "📰"},
                    {english: "shoes", japanese: "くつ", emoji: "👟"},
                    {english: "soap", japanese: "せっけん", emoji: "🧼"},
                    {english: "telephone", japanese: "電話", emoji: "📞"},
                    {english: "case", japanese: "箱", emoji: "📦"},
                    {english: "life", japanese: "生活", emoji: "🌱"},
                    {english: "light", japanese: "明かり", emoji: "💡"},
                    {english: "video", japanese: "ビデオ", emoji: "📹"},
                    {english: "dream", japanese: "夢", emoji: "💭"},
                    {english: "exercise", japanese: "運動", emoji: "🏃"},
                    {english: "glasses", japanese: "めがね", emoji: "👓"},
                    {english: "hobby", japanese: "趣味", emoji: "🎨"}
                ],
                "Places": [
                    {english: "park", japanese: "公園", emoji: "🏞️"},
                    {english: "train", japanese: "列車", emoji: "🚆"},
                    {english: "bus", japanese: "バス", emoji: "🚌"},
                    {english: "library", japanese: "図書館", emoji: "📚"},
                    {english: "car", japanese: "車", emoji: "🚗"},
                    {english: "movie", japanese: "映画", emoji: "🎬"},
                    {english: "restaurant", japanese: "レストラン", emoji: "🍽️"},
                    {english: "station", japanese: "駅", emoji: "🚉"},
                    {english: "shop", japanese: "店", emoji: "🛒"},
                    {english: "zoo", japanese: "動物園", emoji: "🐯"},
                    {english: "city", japanese: "都市", emoji: "🏙️"},
                    {english: "museum", japanese: "博物館", emoji: "🏛️"},
                    {english: "hospital", japanese: "病院", emoji: "🏥"},
                    {english: "street", japanese: "通り", emoji: "🛣️"},
                    {english: "store", japanese: "店", emoji: "🏪"},
                    {english: "supermarket", japanese: "スーパーマーケット", emoji: "🛒"},
                    {english: "office", japanese: "会社", emoji: "🏢"},
                    {english: "department store", japanese: "デパート", emoji: "🏬"},
                    {english: "ship", japanese: "船", emoji: "🚢"},
                    {english: "ticket", japanese: "チケット", emoji: "🎫"},
                    {english: "airport", japanese: "空港", emoji: "✈️"},
                    {english: "bookstore", japanese: "書店", emoji: "📚"},
                    {english: "bridge", japanese: "橋", emoji: "🌉"},
                    {english: "building", japanese: "建物", emoji: "🏢"},
                    {english: "tower", japanese: "塔", emoji: "🗼"},
                    {english: "bank", japanese: "銀行", emoji: "🏦"},
                    {english: "bus stop", japanese: "バス停", emoji: "🚏"},
                    {english: "gas station", japanese: "ガソリンスタンド", emoji: "⛽"},
                    {english: "hotel", japanese: "ホテル", emoji: "🏨"},
                    {english: "plane", japanese: "飛行機", emoji: "✈️"},
                    {english: "post office", japanese: "郵便局", emoji: "🏣"},
                    {english: "police station", japanese: "警察署", emoji: "👮"},
                    {english: "taxi", japanese: "タクシー", emoji: "🚕"},
                    {english: "shopping", japanese: "買物", emoji: "🛒"},
                    {english: "place", japanese: "場所", emoji: "📍"},
                    {english: "theater", japanese: "劇場", emoji: "🎭"},
                    {english: "post", japanese: "郵便", emoji: "📮"},
                    {english: "police", japanese: "警察", emoji: "👮"},
                    {english: "bench", japanese: "ベンチ", emoji: "🪑"},
                    {english: "City Hall", japanese: "市役所", emoji: "🏛️"},
                    {english: "movie theater", japanese: "映画館", emoji: "🎬"},
                    {english: "town", japanese: "町", emoji: "🏘️"},
                    {english: "village", japanese: "村", emoji: "🏡"},
                    {english: "money", japanese: "お金", emoji: "💰"},
                    {english: "musical", japanese: "ミュージカル", emoji: "🎵"},
                    {english: "trip", japanese: "旅行", emoji: "✈️"},
                    {english: "turn", japanese: "順番", emoji: "🔄"}
                ],
                "School": [
                    {english: "school", japanese: "学校", emoji: "🏫"},
                    {english: "textbook", japanese: "教科書", emoji: "📚"},
                    {english: "class", japanese: "クラス", emoji: "👨‍🏫"},
                    {english: "pen", japanese: "ペン", emoji: "🖊️"},
                    {english: "homework", japanese: "宿題", emoji: "📝"},
                    {english: "name", japanese: "名前", emoji: "📛"},
                    {english: "math", japanese: "数学", emoji: "➗"},
                    {english: "student", japanese: "生徒", emoji: "👨‍🎓"},
                    {english: "teacher", japanese: "先生", emoji: "👩‍🏫"},
                    {english: "pencil", japanese: "鉛筆", emoji: "✏️"},
                    {english: "club", japanese: "クラブ", emoji: "♣️"},
                    {english: "eraser", japanese: "消しゴム", emoji: "🧼"},
                    {english: "dictionary", japanese: "辞書", emoji: "📖"},
                    {english: "gym", japanese: "体育館", emoji: "🏃"},
                    {english: "science", japanese: "理科", emoji: "🔬"},
                    {english: "classroom", japanese: "教室", emoji: "🏫"},
                    {english: "notebook", japanese: "ノート", emoji: "📓"},
                    {english: "art", japanese: "美術", emoji: "🎨"},
                    {english: "classmate", japanese: "同級生", emoji: "👨‍🎓"},
                    {english: "number", japanese: "番号", emoji: "🔢"},
                    {english: "subject", japanese: "科目", emoji: "📚"},
                    {english: "story", japanese: "物語", emoji: "📖"},
                    {english: "pencil case", japanese: "筆箱", emoji: "📏"},
                    {english: "lesson", japanese: "レッスン", emoji: "📚"},
                    {english: "page", japanese: "ページ", emoji: "📄"},
                    {english: "pool", japanese: "プール", emoji: "🏊"},
                    {english: "cafeteria", japanese: "カフェテリア", emoji: "🍽️"},
                    {english: "test", japanese: "テスト", emoji: "📝"},
                    {english: "P.E.", japanese: "体育", emoji: "🏃"},
                    {english: "ruler", japanese: "定規", emoji: "📏"},
                    {english: "blackboard", japanese: "黒板", emoji: "🏫"},
                    {english: "ground", japanese: "グラウンド", emoji: "⚽"},
                    {english: "history", japanese: "歴史", emoji: "📜"},
                    {english: "idea", japanese: "考え", emoji: "💡"},
                    {english: "chalk", japanese: "チョーク", emoji: "🖍️"},
                    {english: "exam", japanese: "試験", emoji: "📝"},
                    {english: "map", japanese: "地図", emoji: "🗺️"},
                    {english: "plan", japanese: "計画", emoji: "📋"},
                    {english: "question", japanese: "質問", emoji: "❓"}
                ],
                "Music & Arts": [
                    {english: "music", japanese: "音楽", emoji: "🎵"},
                    {english: "show", japanese: "番組、ショー", emoji: "📺"},
                    {english: "song", japanese: "歌", emoji: "🎵"},
                    {english: "CD", japanese: "ＣＤ", emoji: "💿"},
                    {english: "band", japanese: "バンド", emoji: "🎸"},
                    {english: "concert", japanese: "コンサート", emoji: "🎤"},
                    {english: "guitar", japanese: "ギター", emoji: "🎸"},
                    {english: "piano", japanese: "ピアノ", emoji: "🎹"},
                    {english: "violin", japanese: "バイオリン", emoji: "🎻"},
                    {english: "flute", japanese: "フルート", emoji: "🎶"},
                    {english: "drum", japanese: "太鼓", emoji: "🥁"},
                    {english: "harmonica", japanese: "ハーモニカ", emoji: "🎵"}
                ],
                "Languages & Countries": [
                    {english: "Mr.", japanese: "～さん（男性に対する敬称）", emoji: "👨"},
                    {english: "Ms.", japanese: "～さん（女性に対する敬称）", emoji: "👩"},
                    {english: "Mrs.", japanese: "～さん（既婚女性に対する敬称）", emoji: "👰"},
                    {english: "English", japanese: "英語", emoji: "🇬🇧"},
                    {english: "Japanese", japanese: "日本語", emoji: "🇯🇵"},
                    {english: "French", japanese: "フランス語", emoji: "🇫🇷"},
                    {english: "world", japanese: "世界", emoji: "🌎"},
                    {english: "country", japanese: "国", emoji: "🇺🇳"},
                    {english: "Japan", japanese: "日本", emoji: "🇯🇵"},
                    {english: "England", japanese: "イギリス", emoji: "🇬🇧"},
                    {english: "France", japanese: "フランス", emoji: "🇫🇷"},
                    {english: "Germany", japanese: "ドイツ", emoji: "🇩🇪"},
                    {english: "Australia", japanese: "オーストラリア", emoji: "🇦🇺"},
                    {english: "China", japanese: "中国", emoji: "🇨🇳"},
                    {english: "India", japanese: "インド", emoji: "🇮🇳"},
                    {english: "Italy", japanese: "イタリア", emoji: "🇮🇹"},
                    {english: "Canada", japanese: "カナダ", emoji: "🇨🇦"},
                    {english: "Singapore", japanese: "シンガポール", emoji: "🇸🇬"},
                    {english: "American", japanese: "アメリカ人", emoji: "🇺🇸"},
                    {english: "Spanish", japanese: "スペイン人", emoji: "🇪🇸"}
                ],
                "Body Parts": [
                    {english: "hand", japanese: "手", emoji: "✋"},
                    {english: "eye", japanese: "目", emoji: "👁️"},
                    {english: "hair", japanese: "髪の毛", emoji: "💇"},
                    {english: "leg", japanese: "脚", emoji: "🦵"},
                    {english: "face", japanese: "顔", emoji: "😀"},
                    {english: "head", japanese: "頭", emoji: "🧠"},
                    {english: "mouth", japanese: "口", emoji: "👄"},
                    {english: "finger", japanese: "手の指", emoji: "👆"},
                    {english: "teeth", japanese: "歯の複数形", emoji: "🦷"},
                    {english: "foot", japanese: "足", emoji: "🦶"},
                    {english: "ear", japanese: "耳", emoji: "👂"},
                    {english: "shoulder", japanese: "肩", emoji: "💪"},
                    {english: "neck", japanese: "首", emoji: "👔"}
                ],
                "Animals": [
                    {english: "animal", japanese: "動物", emoji: "🐾"},
                    {english: "dog", japanese: "犬", emoji: "🐶"},
                    {english: "bird", japanese: "鳥", emoji: "🐦"},
                    {english: "cat", japanese: "猫", emoji: "🐱"},
                    {english: "fish", japanese: "魚", emoji: "🐟"},
                    {english: "sheep", japanese: "羊", emoji: "🐑"},
                    {english: "rabbit", japanese: "ウサギ", emoji: "🐰"},
                    {english: "dolphin", japanese: "イルカ", emoji: "🐬"},
                    {english: "elephant", japanese: "象", emoji: "🐘"},
                    {english: "butterfly", japanese: "蝶", emoji: "🦋"},
                    {english: "monkey", japanese: "猿", emoji: "🐒"},
                    {english: "hamster", japanese: "ハ姆スター", emoji: "🐹"}
                ],
                "Nature": [
                    {english: "tree", japanese: "木", emoji: "🌳"},
                    {english: "rose", japanese: "バラ", emoji: "🌹"},
                    {english: "wood", japanese: "木", emoji: "🪵"},
                    {english: "flower", japanese: "花", emoji: "🌸"},
                    {english: "water", japanese: "水", emoji: "💧"},
                    {english: "sea", japanese: "海", emoji: "🌊"},
                    {english: "river", japanese: "川", emoji: "🌊"},
                    {english: "sun", japanese: "太陽", emoji: "☀️"},
                    {english: "star", japanese: "星", emoji: "⭐"},
                    {english: "rock", japanese: "岩", emoji: "🪨"},
                    {english: "wind", japanese: "風", emoji: "💨"},
                    {english: "mountain", japanese: "山", emoji: "⛰️"},
                    {english: "weather", japanese: "天気", emoji: "🌤️"},
                    {english: "sky", japanese: "空", emoji: "🌌"},
                    {english: "lake", japanese: "湖", emoji: "🌊"},
                    {english: "beach", japanese: "海辺", emoji: "🏖️"},
                    {english: "cloud", japanese: "雲", emoji: "☁️"},
                    {english: "snow", japanese: "雪", emoji: "❄️"},
                    {english: "moon", japanese: "月", emoji: "🌙"},
                    {english: "spring", japanese: "春", emoji: "🌷"},
                    {english: "summer", japanese: "夏", emoji: "🌞"},
                    {english: "fall", japanese: "秋", emoji: "🍂"},
                    {english: "autumn", japanese: "秋", emoji: "🍁"},
                    {english: "winter", japanese: "冬", emoji: "⛄"}
                ],
                "Events & Celebrations": [
                    {english: "party", japanese: "パーティー", emoji: "🎉"},
                    {english: "present", japanese: "プレゼント", emoji: "🎁"},
                    {english: "holiday", japanese: "休日", emoji: "🎉"},
                    {english: "festival", japanese: "祭り", emoji: "🎎"},
                    {english: "birthday", japanese: "誕生日", emoji: "🎂"}
                ],
                "Family": [
                    {english: "brother", japanese: "兄、弟", emoji: "👦"},
                    {english: "sister", japanese: "姉、妹", emoji: "👧"},
                    {english: "father", japanese: "父", emoji: "👨"},
                    {english: "mother", japanese: "母", emoji: "👩"},
                    {english: "family", japanese: "家族", emoji: "👪"},
                    {english: "uncle", japanese: "おじ", emoji: "👨"},
                    {english: "aunt", japanese: "おば", emoji: "👩"},
                    {english: "son", japanese: "息子", emoji: "👦"},
                    {english: "daughter", japanese: "娘", emoji: "👧"},
                    {english: "grandfather", japanese: "祖父", emoji: "👴"},
                    {english: "grandmother", japanese: "祖母", emoji: "👵"}
                ],
                "Colors": [
                    {english: "color", japanese: "色", emoji: "🎨"},
                    {english: "black", japanese: "黒", emoji: "⚫"},
                    {english: "white", japanese: "白", emoji: "⚪"},
                    {english: "green", japanese: "緑色", emoji: "🟢"},
                    {english: "red", japanese: "赤", emoji: "🔴"},
                    {english: "blue", japanese: "青", emoji: "🔵"},
                    {english: "brown", japanese: "茶色", emoji: "🟤"},
                    {english: "yellow", japanese: "黄色", emoji: "🟡"},
                    {english: "pink", japanese: "ピンク色", emoji: "🌸"},
                    {english: "purple", japanese: "紫色", emoji: "🟣"}
                ],
                "Sports": [
                    {english: "team", japanese: "チーム", emoji: "👥"},
                    {english: "game", japanese: "試合", emoji: "🎮"},
                    {english: "sport", japanese: "スポーツ", emoji: "⚽"},
                    {english: "score", japanese: "得点", emoji: "📊"},
                    {english: "ball", japanese: "ボール", emoji: "⚽"},
                    {english: "softball", japanese: "ソフトボール", emoji: "🥎"},
                    {english: "football", japanese: "フットボール", emoji: "🏈"},
                    {english: "tennis", japanese: "テニス", emoji: "🎾"},
                    {english: "bike", japanese: "自転車", emoji: "🚲"},
                    {english: "soccer", japanese: "サッカー", emoji: "⚽"},
                    {english: "bicycle", japanese: "自転車", emoji: "🚲"},
                    {english: "racket", japanese: "ラケット", emoji: "🎾"},
                    {english: "baseball", japanese: "野球", emoji: "⚾"},
                    {english: "badminton", japanese: "バドミントン", emoji: "🏸"},
                    {english: "basketball", japanese: "バスケットボール", emoji: "🏀"},
                    {english: "volleyball", japanese: "バレーボール", emoji: "🏐"}
                ],
                "Food & Drinks": [
                    {english: "breakfast", japanese: "朝食", emoji: "🍳"},
                    {english: "lunch", japanese: "昼食", emoji: "🍱"},
                    {english: "lunchtime", japanese: "昼食時間", emoji: "🕛"},
                    {english: "dinner", japanese: "夕食", emoji: "🍽️"},
                    {english: "glass", japanese: "コップ", emoji: "🥛"},
                    {english: "tea", japanese: "茶", emoji: "🍵"},
                    {english: "coffee", japanese: "コーヒー", emoji: "☕"},
                    {english: "plate", japanese: "浅い皿", emoji: "🍽️"},
                    {english: "knife", japanese: "ナイフ", emoji: "🔪"},
                    {english: "fork", japanese: "フォーク", emoji: "🍴"},
                    {english: "dish", japanese: "皿", emoji: "🍽️"},
                    {english: "spoon", japanese: "スプーン", emoji: "🥄"},
                    {english: "lunchbox", japanese: "弁当箱", emoji: "🍱"},
                    {english: "chopstick", japanese: "はし", emoji: "🥢"},
                    {english: "food", japanese: "食べ物", emoji: "🍎"},
                    {english: "egg", japanese: "卵", emoji: "🥚"},
                    {english: "milk", japanese: "牛乳", emoji: "🥛"},
                    {english: "fruit", japanese: "果物", emoji: "🍎"},
                    {english: "ice", japanese: "氷", emoji: "🧊"},
                    {english: "sugar", japanese: "砂糖", emoji: "🍬"},
                    {english: "cake", japanese: "ケーキ", emoji: "🍰"},
                    {english: "bread", japanese: "パン", emoji: "🍞"},
                    {english: "meat", japanese: "肉", emoji: "🍖"},
                    {english: "salt", japanese: "塩", emoji: "🧂"},
                    {english: "cream", japanese: "クリーム", emoji: "🍦"},
                    {english: "apple", japanese: "リンゴ", emoji: "🍎"},
                    {english: "orange", japanese: "オレンジ", emoji: "🍊"},
                    {english: "vegetable", japanese: "野菜", emoji: "🥦"},
                    {english: "potato", japanese: "じゃがいも", emoji: "🥔"},
                    {english: "chocolate", japanese: "チョコレート", emoji: "🍫"},
                    {english: "sandwich", japanese: "サンドイッチ", emoji: "🥪"},
                    {english: "juice", japanese: "ジュース", emoji: "🧃"},
                    {english: "jam", japanese: "ジャム", emoji: "🍓"},
                    {english: "rice", japanese: "米", emoji: "🍚"},
                    {english: "pie", japanese: "パイ", emoji: "🥧"},
                    {english: "ham", japanese: "ハム", emoji: "🍖"},
                    {english: "tomato", japanese: "トマト", emoji: "🍅"},
                    {english: "soup", japanese: "スープ", emoji: "🍲"},
                    {english: "salad", japanese: "サラダ", emoji: "🥗"},
                    {english: "onion", japanese: "玉ねぎ", emoji: "🧅"},
                    {english: "banana", japanese: "バナナ", emoji: "🍌"},
                    {english: "sausage", japanese: "ソーセージ", emoji: "🌭"},
                    {english: "carrot", japanese: "にんじん", emoji: "🥕"},
                    {english: "grape", japanese: "ぶどう", emoji: "🍇"},
                    {english: "peach", japanese: "もモ", emoji: "🍑"},
                    {english: "strawberry", japanese: "いちご", emoji: "🍓"},
                    {english: "pizza", japanese: "ピザ", emoji: "🍕"},
                    {english: "curry", japanese: "カレー", emoji: "🍛"},
                    {english: "dessert", japanese: "デザート", emoji: "🍰"},
                    {english: "burger", japanese: "ハンバーガー", emoji: "🍔"},
                    {english: "pineapple", japanese: "パイナップル", emoji: "🍍"},
                    {english: "ice cream", japanese: "アイスクリーム", emoji: "🍦"},
                    {english: "yogurt", japanese: "ヨーグルト", emoji: "🥛"},
                    {english: "spaghetti", japanese: "スパゲティー", emoji: "🍝"},
                    {english: "cucumber", japanese: "きゅうり", emoji: "🥒"},
                    {english: "hamburger", japanese: "ハンバーガー", emoji: "🍔"},
                    {english: "pumpkin", japanese: "かぼちゃ", emoji: "🎃"},
                    {english: "cookie", japanese: "クッキー", emoji: "🍪"},
                    {english: "sushi", japanese: "寿司", emoji: "🍣"}
                ],
                "Days of Week": [
                    {english: "Sunday", japanese: "日曜日", emoji: "📅"},
                    {english: "Monday", japanese: "月曜日", emoji: "📅"},
                    {english: "Tuesday", japanese: "火曜日", emoji: "📅"},
                    {english: "Wednesday", japanese: "水曜日", emoji: "📅"},
                    {english: "Thursday", japanese: "木曜日", emoji: "📅"},
                    {english: "Friday", japanese: "金曜日", emoji: "📅"},
                    {english: "Saturday", japanese: "土曜日", emoji: "📅"}
                ],
                "Measurements & Currency": [
                    {english: "meter", japanese: "メートル", emoji: "📏"},
                    {english: "centimeter", japanese: "センチメートル", emoji: "📏"},
                    {english: "dollar", japanese: "ドル", emoji: "💵"},
                    {english: "cent", japanese: "セント", emoji: "💰"},
                    {english: "yen", japanese: "円", emoji: "💴"},
                    {english: "kilogram", japanese: "キログラム", emoji: "⚖️"},
                    {english: "a.m.", japanese: "午前", emoji: "🌅"}
                ],
                "Pronouns": [
                    {english: "this", japanese: "これ", emoji: "👉"},
                    {english: "that", japanese: "あれ", emoji: "👈"},
                    {english: "these", japanese: "これら", emoji: "👈"},
                    {english: "those", japanese: "あれら", emoji: "👉"},
                    {english: "I", japanese: "私は", emoji: "🙋"},
                    {english: "my", japanese: "私の", emoji: "🙋"},
                    {english: "me", japanese: "私を", emoji: "🙋"},
                    {english: "mine", japanese: "私のもの", emoji: "🙋"},
                    {english: "you", japanese: "あなたは", emoji: "👉"},
                    {english: "your", japanese: "あなたの", emoji: "👉"},
                    {english: "yours", japanese: "あなたのもの", emoji: "👉"},
                    {english: "he", japanese: "彼は", emoji: "👨"},
                    {english: "his", japanese: "彼の", emoji: "👨"},
                    {english: "him", japanese: "彼を", emoji: "👨"},
                    {english: "she", japanese: "彼女は", emoji: "👩"},
                    {english: "her", japanese: "彼女の", emoji: "👩"},
                    {english: "hers", japanese: "彼女のもの", emoji: "👩"},
                    {english: "it", japanese: "それは", emoji: "🐶"},
                    {english: "its", japanese: "それの", emoji: "🐶"},
                    {english: "we", japanese: "私たちは", emoji: "👥"},
                    {english: "our", japanese: "私たちの", emoji: "👥"},
                    {english: "us", japanese: "私たちに", emoji: "👥"},
                    {english: "ours", japanese: "私たちのもの", emoji: "👥"},
                    {english: "they", japanese: "彼らは", emoji: "👥"},
                    {english: "their", japanese: "彼らの", emoji: "👥"},
                    {english: "them", japanese: "彼らを", emoji: "👥"},
                    {english: "theirs", japanese: "彼らのもの", emoji: "👥"},
                    {english: "one", japanese: "1 つ", emoji: "1️⃣"},
                    {english: "all", japanese: "すべての", emoji: "👥"},
                    {english: "some", japanese: "いくつかの", emoji: "🔢"},
                    {english: "any", japanese: "いくつかの", emoji: "🔢"},
                    {english: "many", japanese: "たくさんの", emoji: "🔢"},
                    {english: "every", japanese: "毎～", emoji: "🔄"},
                    {english: "everything", japanese: "全てのもの", emoji: "🌎"},
                    {english: "everyone", japanese: "みんな", emoji: "👥"}
                ],
                "Verbs": [
                    {english: "am", japanese: "～である", emoji: "✅"},
                    {english: "are", japanese: "～である", emoji: "✅"},
                    {english: "is", japanese: "～である", emoji: "✅"},
                    {english: "do", japanese: "～をする", emoji: "🔨"},
                    {english: "does", japanese: "～をする", emoji: "🔨"},
                    {english: "like", japanese: "～が好きである", emoji: "❤️"},
                    {english: "have", japanese: "～を持っている", emoji: "👜"},
                    {english: "go", japanese: "行く", emoji: "🚶"},
                    {english: "come", japanese: "来る", emoji: "👋"},
                    {english: "play", japanese: "遊ぶ", emoji: "🎮"},
                    {english: "want", japanese: "～が欲しい", emoji: "🤲"},
                    {english: "make", japanese: "～を作る", emoji: "🔨"},
                    {english: "open", japanese: "～を開く", emoji: "🚪"},
                    {english: "close", japanese: "～を閉じる", emoji: "🚪"},
                    {english: "see", japanese: "～を見る", emoji: "👀"},
                    {english: "eat", japanese: "～を食べる", emoji: "🍎"},
                    {english: "read", japanese: "～を読む", emoji: "📖"},
                    {english: "look", japanese: "注意して見る", emoji: "👀"},
                    {english: "watch", japanese: "～をじっと見る", emoji: "📺"},
                    {english: "know", japanese: "～を知っている", emoji: "🧠"},
                    {english: "speak", japanese: "～を話す", emoji: "🗣️"},
                    {english: "use", japanese: "～を使う", emoji: "🔨"},
                    {english: "wash", japanese: "～を洗う", emoji: "🧼"},
                    {english: "run", japanese: "走る", emoji: "🏃"},
                    {english: "write", japanese: "～を書る", emoji: "✏️"},
                    {english: "take", japanese: "乗り物に乗る", emoji: "🚗"},
                    {english: "live", japanese: "住む", emoji: "🏠"},
                    {english: "sing", japanese: "～を歌う", emoji: "🎤"},
                    {english: "get", japanese: "～を得る", emoji: "🎁"},
                    {english: "study", japanese: "～を勉強する", emoji: "📚"},
                    {english: "walk", japanese: "歩く", emoji: "🚶"},
                    {english: "listen", japanese: "聴く", emoji: "👂"},
                    {english: "drink", japanese: "～を飲む", emoji: "🥛"},
                    {english: "swim", japanese: "泳ぐ", emoji: "🏊"},
                    {english: "meet", japanese: "～に会う", emoji: "👥"},
                    {english: "cook", japanese: "～を料理する", emoji: "👨‍🍳"},
                    {english: "start", japanese: "始まる", emoji: "🚀"},
                    {english: "talk", japanese: "話す", emoji: "🗣️"},
                    {english: "teach", japanese: "教える", emoji: "👨‍🏫"},
                    {english: "clean", japanese: "～を掃除する", emoji: "🧹"},
                    {english: "help", japanese: "～を助ける", emoji: "🤝"},
                    {english: "love", japanese: "～を愛する", emoji: "❤️"},
                    {english: "sit", japanese: "座る", emoji: "💺"},
                    {english: "stand", japanese: "立つ", emoji: "🧍"},
                    {english: "work", japanese: "働く", emoji: "💼"},
                    {english: "jump", japanese: "跳ぶ", emoji: "🦘"},
                    {english: "brush", japanese: "をみがく", emoji: "🪥"},
                    {english: "dance", japanese: "踊る", emoji: "💃"},
                    {english: "fly", japanese: "飛ぶ", emoji: "✈️"},
                    {english: "skate", japanese: "スケートをする", emoji: "⛸️"},
                    {english: "stop", japanese: "～を止める", emoji: "🛑"},
                    {english: "enjoy", japanese: "～を楽しむ", emoji: "😊"},
                    {english: "practice", japanese: "～を練習する", emoji: "📚"},
                    {english: "put", japanese: "～を置く", emoji: "📥"},
                    {english: "buy", japanese: "～を買う", emoji: "🛒"},
                    {english: "cut", japanese: "～を切る", emoji: "✂️"},
                    {english: "sleep", japanese: "眠る", emoji: "😴"},
                    {english: "need", japanese: "～を必要とする", emoji: "❗"},
                    {english: "paint", japanese: "絵の具で～を書く", emoji: "🎨"},
                    {english: "rain", japanese: "雨が降る", emoji: "🌧️"},
                    {english: "call", japanese: "～に電話をかける", emoji: "📞"},
                    {english: "camp", japanese: "キャンプをする", emoji: "🏕️"},
                    {english: "find", japanese: "～を見つける", emoji: "🔍"},
                    {english: "ski", japanese: "スキーをする", emoji: "⛷️"},
                    {english: "think", japanese: "～と思う", emoji: "🤔"},
                    {english: "smile", japanese: "ほほえむ", emoji: "😊"},
                    {english: "begin", japanese: "～を始める", emoji: "🚀"},
                    {english: "give", japanese: "～を与える", emoji: "🎁"},
                    {english: "learn", japanese: "～を習う", emoji: "📚"},
                    {english: "wait", japanese: "待つ", emoji: "⏳"},
                    {english: "hike", japanese: "ハイキングをする", emoji: "🥾"},
                    {english: "shut", japanese: "閉める", emoji: "🚪"},
                    {english: "carry", japanese: "運ぶ", emoji: "📦"},
                    {english: "sell", japanese: "売る", emoji: "💰"},
                    {english: "stay", japanese: "滞在", emoji: "🏨"},
                    {english: "try", japanese: "やってみる", emoji: "🔨"},
                    {english: "win", japanese: "勝つ", emoji: "🏆"}
                ],
                "Adjectives": [
                    {english: "good", japanese: "良い", emoji: "👍"},
                    {english: "old", japanese: "古い", emoji: "👴"},
                    {english: "new", japanese: "新しい", emoji: "🆕"},
                    {english: "fine", japanese: "元気で", emoji: "😊"},
                    {english: "nice", japanese: "すてきな", emoji: "👍"},
                    {english: "right", japanese: "正しい", emoji: "✅"},
                    {english: "big", japanese: "大きい", emoji: "🔍"},
                    {english: "small", japanese: "小さい", emoji: "🔍"},
                    {english: "little", japanese: "小さい", emoji: "🔍"},
                    {english: "long", japanese: "極度に", emoji: "📏"},
                    {english: "short", japanese: "短い", emoji: "📏"},
                    {english: "high", japanese: "高い", emoji: "📈"},
                    {english: "cute", japanese: "かわいい", emoji: "🐶"},
                    {english: "next", japanese: "次の", emoji: "➡️"},
                    {english: "great", japanese: "すばらしい", emoji: "👍"},
                    {english: "hungry", japanese: "空腹の", emoji: "🍎"},
                    {english: "cold", japanese: "寒い", emoji: "🥶"},
                    {english: "hot", japanese: "暑い", emoji: "🥵"},
                    {english: "favorite", japanese: "お気に入りの", emoji: "⭐"},
                    {english: "ready", japanese: "用意ができて", emoji: "✅"},
                    {english: "beautiful", japanese: "美しい", emoji: "🌸"},
                    {english: "Chinese", japanese: "中国の", emoji: "🇨🇳"},
                    {english: "last", japanese: "最後の", emoji: "🔚"},
                    {english: "wonderful", japanese: "極度に", emoji: "👍"},
                    {english: "tall", japanese: "背の高い", emoji: "📏"},
                    {english: "easy", japanese: "簡単な", emoji: "😊"},
                    {english: "happy", japanese: "幸せな", emoji: "😊"},
                    {english: "pretty", japanese: "きれいな", emoji: "🌸"},
                    {english: "sunny", japanese: "晴れている", emoji: "☀️"},
                    {english: "cloudy", japanese: "曇った", emoji: "☁️"},
                    {english: "rainy", japanese: "雨の", emoji: "🌧️"},
                    {english: "windy", japanese: "風が強い", emoji: "💨"},
                    {english: "snowy", japanese: "雪の降る", emoji: "❄️"},
                    {english: "young", japanese: "若い", emoji: "👦"},
                    {english: "large", japanese: "大きい", emoji: "🔍"},
                    {english: "slow", japanese: "遅い", emoji: "🐢"},
                    {english: "fast", japanese: "速い", emoji: "🐇"},
                    {english: "busy", japanese: "忙しい", emoji: "💼"},
                    {english: "soft", japanese: "柔らかい", emoji: "🛏️"},
                    {english: "sweet", japanese: "甘い", emoji: "🍬"},
                    {english: "warm", japanese: "暖かい", emoji: "🌞"},
                    {english: "sleepy", japanese: "眠い", emoji: "😴"},
                    {english: "Italian", japanese: "イタリアの", emoji: "🇮🇹"},
                    {english: "kind", japanese: "親切な", emoji: "🤝"},
                    {english: "much", japanese: "たくさんの", emoji: "🔢"},
                    {english: "lot", japanese: "たくさん", emoji: "🔢"},
                    {english: "more", japanese: "もっと多数の", emoji: "➕"},
                    {english: "final", japanese: "最後の", emoji: "🔚"},
                    {english: "main", japanese: "主な", emoji: "⭐"},
                    {english: "angry", japanese: "怒って", emoji: "😠"},
                    {english: "sad", japanese: "悲しい", emoji: "😢"},
                    {english: "bad", japanese: "悪い", emoji: "👎"},
                    {english: "special", japanese: "特別な", emoji: "⭐"}
                ],
                "Adverbs & Other": [
                    {english: "not", japanese: "～でない", emoji: "❌"},
                    {english: "here", japanese: "ここに", emoji: "📍"},
                    {english: "very", japanese: "とても", emoji: "❗"},
                    {english: "too", japanese: "～もまた", emoji: "➕"},
                    {english: "often", japanese: "しばしば", emoji: "🔄"},
                    {english: "now", japanese: "今", emoji: "⏰"},
                    {english: "there", japanese: "そこに", emoji: "📍"},
                    {english: "o’clock", japanese: "～時", emoji: "🕐"},
                    {english: "up", japanese: "上へ", emoji: "⬆️"},
                    {english: "down", japanese: "下へ", emoji: "⬇️"},
                    {english: "into", japanese: "～の中へ", emoji: "➡️"},
                    {english: "then", japanese: "それから", emoji: "➡️"},
                    {english: "out", japanese: "外へ", emoji: "🚪"},
                    {english: "only", japanese: "ただ～だけ", emoji: "1️⃣"},
                    {english: "over", japanese: "上方に", emoji: "⬆️"},
                    {english: "just", japanese: "ちょうど", emoji: "✅"},
                    {english: "also", japanese: "～もまた", emoji: "➕"},
                    {english: "well", japanese: "上手に", emoji: "👍"},
                    {english: "off", japanese: "離れて", emoji: "🚪"},
                    {english: "again", japanese: "再び", emoji: "🔄"},
                    {english: "early", japanese: "早い", emoji: "⏰"},
                    {english: "really", japanese: "極度に", emoji: "❗"},
                    {english: "always", japanese: "いつも", emoji: "🔄"},
                    {english: "around", japanese: "～頃", emoji: "⏰"},
                    {english: "together", japanese: "一緒に", emoji: "👥"},
                    {english: "sure", japanese: "もちろん", emoji: "✅"},
                    {english: "sometimes", japanese: "時々", emoji: "⏰"},
                    {english: "usually", japanese: "普通", emoji: "🔄"},
                    {english: "fast", japanese: "速く", emoji: "🐇"},
                    {english: "the", japanese: "その", emoji: "🔍"},
                    {english: "a", japanese: "ひとつの", emoji: "1️⃣"},
                    {english: "what", japanese: "何", emoji: "❓"},
                    {english: "how", japanese: "どうやって", emoji: "❓"},
                    {english: "where", japanese: "どこに", emoji: "📍"},
                    {english: "when", japanese: "いつ", emoji: "⏰"},
                    {english: "who", japanese: "誰が", emoji: "👤"},
                    {english: "whose", japanese: "誰の", emoji: "👤"},
                    {english: "which", japanese: "どちら", emoji: "🔀"},
                    {english: "why", japanese: "なぜ", emoji: "❓"},
                    {english: "can", japanese: "～することができる", emoji: "✅"},
                    {english: "will", japanese: "～だろう", emoji: "🔮"},
                    {english: "in", japanese: "～の中に", emoji: "📥"},
                    {english: "of", japanese: "～の", emoji: "🔗"},
                    {english: "to", japanese: "～へ", emoji: "➡️"},
                    {english: "for", japanese: "～のために", emoji: "🎁"},
                    {english: "on", japanese: "～の上に", emoji: "⬆️"},
                    {english: "with", japanese: "～と一緒に", emoji: "👥"},
                    {english: "by", japanese: "～で", emoji: "🔨"},
                    {english: "at", japanese: "～に", emoji: "📍"},
                    {english: "from", japanese: "～から", emoji: "⬅️"},
                    {english: "about", japanese: "～についての", emoji: "📝"},
                    {english: "after", japanese: "～の後に", emoji: "➡️"},
                    {english: "before", japanese: "～の前に", emoji: "⬅️"},
                    {english: "under", japanese: "極度に", emoji: "⬇️"},
                    {english: "near", japanese: "～の近くに", emoji: "📍"},
                    {english: "and", japanese: "～と…", emoji: "➕"},
                    {english: "or", japanese: "極度に", emoji: "🔀"},
                    {english: "but", japanese: "けれども", emoji: "🔄"},
                    {english: "so", japanese: "それで", emoji: "➡️"}
                ]
            };

 // Flatten the vocabulary into a single array
        const vocabulary = [];
        for (const category in vocabularyCategories) {
            vocabulary.push(...vocabularyCategories[category]);
        }
